# Using Version control for collaboration {#version_control}

## Overview


## Chapter learning objectives
By the end of the chapter, students will be able to:

- Describe what version control is and why data analysis projects can benefit 
from using it
- Create a remote version control repository on GitHub.com
- Move changes to files from GitHub to JupyterHub, and from JupyterHub to GitHub
- Use best practices for collaboration when using version control to collaborate 
on a project with others

## What is version control and why should I use it?

Good data analysis projects require iteration and revision to move from project
ideation, through proof-of-concept to a finished product that is ready to be 
communicated to the intended audience. Without deliberate and 
conscious effort towards tracking which version of the analysis code led to 
which version of the results, data analysis projects can quickly and easily 
become messy, and the results irreproducible. Additionally,
the iterative nature of data analysis projects means that there are usually 
several times in a project where one would like to go back to an earlier version
of a code file, or back in time to an earlier state of the project to experiment 
or test things. Finally,
data analysis projects are rarely completed by a single person alone, and 
instead teams of people typically collaborate. This means that files need to be 
shared across multiple computers, and multiple people usually end up editing a
single file. In such a situation, determining which version of that file is 
the latest and most up to date can be a challenge - especially when two people 
are working on the same file at once!

Version control helps solve these challenges in analysis projects, particularly 
those that involve code, by tracking changes to code and data over 
the lifespan of a project (including when the changes were made and who made 
them). Version control also provides means to retreive earlier versions of a 
file (or files), or even go back in time to earlier states of the 
project. Finally, it also facilitates the merging changes from different
collaborators working on the project - even when they are working on the same 
file [@wilson2014best]!

You might find yourself saying, but I am not collaborating, so I don't need to 
use or learn version control. However, as this popular data science quote 
aptly points out, future you often has to collaborate with past you.

*You mostly collaborate with yourself, and me-from-two-months-ago never responds to email*

-- Mark T. Holder

## Creating a space to share your code online


## Moving changes from GitHub to JupyterHub


## Bringing changes from JupyterHub to GitHub


## Strategies for collaboration when using version control


