# Regression, continued some more... {#regression3}

## Overview 
This week will introduce the bootstrap, first by visualizing bootstrap samples and their fitted regression lines for cases where there is a response variable of interest and a single explanatory variable. An intuitive case will be made for what the ensemble of slopes represents, Then we work through examples from multiple regression, emphasizing the scientific interpretation and relevance of the mix of negative/positive slopes. We will emphasize that this is a jumping off point for the study of statistical inference.

## Learning objectives 
By the end of the chapter, students will be able to:

* Explain in words or using drawings, how bootstrap samples can be generated from a single sample.
* From a single sample, generate multiple samples through bootstrapping using R.
* In R, overlay the ordinary least squares regression lines from multiple bootstrapped samples on a single plot. 
* Discuss what the collection of these slopes represents.