# How to get started using version control {#How-to-get-started-using-version-control}

## Overview

Now that you have been introduced to the motivations behind using version 
control for collaboration for data science project, this chapter will introduce 
how to actually use the two most common version control tools: Git for local 
version control, and GitHub for remote version control. We will focus on the 
most common version control operations used day-to-day in a standard data 
science project.

## Chapter learning objectives

By the end of the chapter, students will be able to:

- Create a remote version control repository on GitHub
- Communicate with collaborators using GitHub issues
- Give collaborators access to a GitHub repository
- use Jupyter's and RStudio's Git version control tools for project versioning and 
collaboration, specifically to:

  - commit changes to a local version control repository
  - push changes to a remote version control repository
  - pull changes from a remote version control repository
  - resolve merge conflicts
  - checkout a past version of a file from the version control history