# this script was generated by ChatGPT
# and corrected/verified by T. Campbell

from pathlib import Path
import re

DOCS_DIR = Path("docs")

def update_html_file(path: Path):
    filename = path.name  # e.g. "about-us.html"

    # Customize this however you want.
    line = f'<link rel="canonical" href="https://datasciencebook.ca/{filename}" />'

    html = path.read_text(encoding="utf-8")

    # Don't add it twice if the script is run again.
    if line in html:
        print(f"Skipping (already updated): {path}")
        return

    # Find the opening <head> tag, case-insensitively.
    match = re.search(r"<head\b[^>]*>", html, re.IGNORECASE)

    if not match:
        print(f"Skipping (no <head> found): {path}")
        return

    # Insert immediately after <head>.
    insert_at = match.end()
    html = html[:insert_at] + "\n" + line + html[insert_at:]

    path.write_text(html, encoding="utf-8")
    print(f"Updated: {path}")


def main():
    for path in DOCS_DIR.rglob("*.html"):
        update_html_file(path)

if __name__ == "__main__":
    main()
