services:
  book-env:
    image: "ubcdsci/intro-to-ds:v0.6.0-47d5cbf"
    ports:
      - "8787:8787"
    volumes:
      - .:/home/rstudio/introduction-to-datascience
    environment:
      PASSWORD: password
      
