services:
  book-env:
    image: ubcdsci/intro-to-ds:202307130106229dd1c2
    ports:
      - "8787:8787"
    volumes:
      - .:/home/rstudio/introduction-to-datascience
    environment:
      PASSWORD: password
    deploy:
      resources:
        limits:
          memory: 5G
      
