services:
  book-env:
    image: ubcdsci/intro-to-ds:v0.16.0
    ports:
      - "8787:8787"
    volumes:
      - .:/home/rstudio/introduction-to-datascience
    environment:
      PASSWORD: password
    deploy:
      resources:
        limits:
          memory: 4G
      
