<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Introduction to Data Science</title>
  <meta name="description" content="This is an open source textbook for teaching Introductory Data Science.">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Introduction to Data Science" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is an open source textbook for teaching Introductory Data Science." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Introduction to Data Science" />
  
  <meta name="twitter:description" content="This is an open source textbook for teaching Introductory Data Science." />
  

<meta name="author" content="Tiffany-Anne Timbers">
<meta name="author" content="Melissa Lee">
<meta name="author" content="Samuel Hinshaw">


<meta name="date" content="2019-02-12">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="classification.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introduction to Data Science</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction to Data Science</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#chapter-learning-objectives"><i class="fa fa-check"></i><b>1.1</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#jupyter-notebooks"><i class="fa fa-check"></i><b>1.2</b> Jupyter notebooks</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#loading-a-tabular-dataset"><i class="fa fa-check"></i><b>1.3</b> Loading a tabular dataset</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#assigning-value-to-an-object"><i class="fa fa-check"></i><b>1.4</b> Assigning value to an object</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#subsetting-data-frames-with-select-filter"><i class="fa fa-check"></i><b>1.5</b> Subsetting data frames with <code>select</code> &amp; <code>filter</code></a><ul>
<li class="chapter" data-level="1.5.1" data-path="index.html"><a href="index.html#using-select-to-subset-multiple-columns"><i class="fa fa-check"></i><b>1.5.1</b> Using <code>select</code> to subset multiple columns</a></li>
<li class="chapter" data-level="1.5.2" data-path="index.html"><a href="index.html#using-select-to-subset-a-range-of-columns"><i class="fa fa-check"></i><b>1.5.2</b> Using <code>select</code> to subset a range of columns</a></li>
<li class="chapter" data-level="1.5.3" data-path="index.html"><a href="index.html#using-filter-to-subset-a-single-column"><i class="fa fa-check"></i><b>1.5.3</b> Using <code>filter</code> to subset a single column</a></li>
<li class="chapter" data-level="1.5.4" data-path="index.html"><a href="index.html#using-filter-to-get-rows-with-values-above-a-threshold"><i class="fa fa-check"></i><b>1.5.4</b> Using <code>filter</code> to get rows with values above a threshold</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#combining-functions-using-the-pipe-operator"><i class="fa fa-check"></i><b>1.6</b> Combining functions using the pipe operator: %&gt;%</a><ul>
<li class="chapter" data-level="1.6.1" data-path="index.html"><a href="index.html#using-to-combine-filter-and-select"><i class="fa fa-check"></i><b>1.6.1</b> Using %&gt;% to combine <code>filter</code> and <code>select</code></a></li>
<li class="chapter" data-level="1.6.2" data-path="index.html"><a href="index.html#using-with-more-than-two-functions"><i class="fa fa-check"></i><b>1.6.2</b> Using %&gt;% with more than two functions</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#creating-visualizations-in-r"><i class="fa fa-check"></i><b>1.7</b> Creating Visualizations in R</a><ul>
<li class="chapter" data-level="1.7.1" data-path="index.html"><a href="index.html#using-ggplot-to-create-a-scatter-plot"><i class="fa fa-check"></i><b>1.7.1</b> Using <code>ggplot</code> to create a scatter plot</a></li>
<li class="chapter" data-level="1.7.2" data-path="index.html"><a href="index.html#using-ggplot-to-create-a-scatter-plot-1"><i class="fa fa-check"></i><b>1.7.2</b> Using <code>ggplot</code> to create a scatter plot</a></li>
<li class="chapter" data-level="1.7.3" data-path="index.html"><a href="index.html#formatting-ggplot-objects"><i class="fa fa-check"></i><b>1.7.3</b> Formatting ggplot objects</a></li>
<li class="chapter" data-level="1.7.4" data-path="index.html"><a href="index.html#coloring-points-by-group"><i class="fa fa-check"></i><b>1.7.4</b> Coloring points by group</a></li>
<li class="chapter" data-level="1.7.5" data-path="index.html"><a href="index.html#whats-next"><i class="fa fa-check"></i><b>1.7.5</b> What’s next?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="reading.html"><a href="reading.html"><i class="fa fa-check"></i><b>2</b> Reading in data locally and from the web</a><ul>
<li class="chapter" data-level="2.1" data-path="reading.html"><a href="reading.html#overview"><i class="fa fa-check"></i><b>2.1</b> Overview</a></li>
<li class="chapter" data-level="2.2" data-path="reading.html"><a href="reading.html#chapter-learning-objectives-1"><i class="fa fa-check"></i><b>2.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="2.3" data-path="reading.html"><a href="reading.html#absolute-and-relative-file-paths"><i class="fa fa-check"></i><b>2.3</b> Absolute and relative file paths</a></li>
<li class="chapter" data-level="2.4" data-path="reading.html"><a href="reading.html#reading-tabular-data-into-r"><i class="fa fa-check"></i><b>2.4</b> Reading tabular data into R</a><ul>
<li class="chapter" data-level="2.4.1" data-path="reading.html"><a href="reading.html#read_delim-as-a-more-flexible-method-to-get-tabular-data-into-r"><i class="fa fa-check"></i><b>2.4.1</b> <code>read_delim</code> as a more flexible method to get tabular data into R</a></li>
<li class="chapter" data-level="2.4.2" data-path="reading.html"><a href="reading.html#reading-tabular-data-directly-from-a-url"><i class="fa fa-check"></i><b>2.4.2</b> Reading tabular data directly from a URL</a></li>
<li class="chapter" data-level="2.4.3" data-path="reading.html"><a href="reading.html#previewing-a-data-file-before-reading-it-into-r"><i class="fa fa-check"></i><b>2.4.3</b> Previewing a data file before reading it into R</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="reading.html"><a href="reading.html#scraping-data-off-the-web-using-r"><i class="fa fa-check"></i><b>2.5</b> Scraping data off the web using R</a><ul>
<li class="chapter" data-level="2.5.1" data-path="reading.html"><a href="reading.html#html-and-css-selectors"><i class="fa fa-check"></i><b>2.5.1</b> HTML and CSS selectors</a></li>
<li class="chapter" data-level="2.5.2" data-path="reading.html"><a href="reading.html#are-you-allowed-to-scrape-that-website"><i class="fa fa-check"></i><b>2.5.2</b> Are you allowed to scrape that website?</a></li>
<li class="chapter" data-level="2.5.3" data-path="reading.html"><a href="reading.html#using-rvest"><i class="fa fa-check"></i><b>2.5.3</b> Using <code>rvest</code></a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="reading.html"><a href="reading.html#additional-readingsresources"><i class="fa fa-check"></i><b>2.6</b> Additional readings/resources</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="wrangling.html"><a href="wrangling.html"><i class="fa fa-check"></i><b>3</b> Cleaning and wrangling data</a><ul>
<li class="chapter" data-level="3.1" data-path="wrangling.html"><a href="wrangling.html#overview-1"><i class="fa fa-check"></i><b>3.1</b> Overview</a></li>
<li class="chapter" data-level="3.2" data-path="wrangling.html"><a href="wrangling.html#chapter-learning-objectives-2"><i class="fa fa-check"></i><b>3.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="3.3" data-path="wrangling.html"><a href="wrangling.html#vectors-and-data-frames"><i class="fa fa-check"></i><b>3.3</b> Vectors and Data frames</a><ul>
<li class="chapter" data-level="3.3.1" data-path="wrangling.html"><a href="wrangling.html#what-is-a-data-frame"><i class="fa fa-check"></i><b>3.3.1</b> What is a data frame?</a></li>
<li class="chapter" data-level="3.3.2" data-path="wrangling.html"><a href="wrangling.html#what-is-a-vector"><i class="fa fa-check"></i><b>3.3.2</b> What is a vector?</a></li>
<li class="chapter" data-level="3.3.3" data-path="wrangling.html"><a href="wrangling.html#how-are-vectors-different-from-a-list"><i class="fa fa-check"></i><b>3.3.3</b> How are vectors different from a list?</a></li>
<li class="chapter" data-level="3.3.4" data-path="wrangling.html"><a href="wrangling.html#what-does-this-have-to-do-with-data-frames"><i class="fa fa-check"></i><b>3.3.4</b> What does this have to do with data frames?</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="wrangling.html"><a href="wrangling.html#the-dplyr-functions"><i class="fa fa-check"></i><b>3.4</b> The <code>dplyr</code> functions</a></li>
<li class="chapter" data-level="3.5" data-path="wrangling.html"><a href="wrangling.html#tidy-data"><i class="fa fa-check"></i><b>3.5</b> Tidy Data</a><ul>
<li class="chapter" data-level="3.5.1" data-path="wrangling.html"><a href="wrangling.html#what-is-tidy-data"><i class="fa fa-check"></i><b>3.5.1</b> What is tidy data?</a></li>
<li class="chapter" data-level="3.5.2" data-path="wrangling.html"><a href="wrangling.html#why-is-tidy-data-important-in-r"><i class="fa fa-check"></i><b>3.5.2</b> Why is tidy data important in R?</a></li>
<li class="chapter" data-level="3.5.3" data-path="wrangling.html"><a href="wrangling.html#going-from-wide-to-long-or-tidy-using-gather"><i class="fa fa-check"></i><b>3.5.3</b> Going from wide to long (or tidy!) using <code>gather</code></a></li>
<li class="chapter" data-level="3.5.4" data-path="wrangling.html"><a href="wrangling.html#using-separate-to-deal-with-multiple-delimiters"><i class="fa fa-check"></i><b>3.5.4</b> Using separate to deal with multiple delimiters</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="wrangling.html"><a href="wrangling.html#using-purrrs-map-functions-to-iterate"><i class="fa fa-check"></i><b>3.6</b> Using <code>purrr</code>’s <code>map*</code> functions to iterate</a><ul>
<li class="chapter" data-level="3.6.1" data-path="wrangling.html"><a href="wrangling.html#a-bit-more-about-the-map-functions"><i class="fa fa-check"></i><b>3.6.1</b> A bit more about the <code>map*</code> functions</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="wrangling.html"><a href="wrangling.html#additional-readingsresources-1"><i class="fa fa-check"></i><b>3.7</b> Additional readings/resources</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="viz.html"><a href="viz.html"><i class="fa fa-check"></i><b>4</b> Effective data visualization</a><ul>
<li class="chapter" data-level="4.1" data-path="viz.html"><a href="viz.html#overview-2"><i class="fa fa-check"></i><b>4.1</b> Overview</a></li>
<li class="chapter" data-level="4.2" data-path="viz.html"><a href="viz.html#chapter-learning-objectives-3"><i class="fa fa-check"></i><b>4.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="4.3" data-path="viz.html"><a href="viz.html#ggplot2-for-data-visualization-in-r"><i class="fa fa-check"></i><b>4.3</b> <code>ggplot2</code> for data visualization in R</a></li>
<li class="chapter" data-level="4.4" data-path="viz.html"><a href="viz.html#making-effective-vizualizations"><i class="fa fa-check"></i><b>4.4</b> Making effective vizualizations</a><ul>
<li class="chapter" data-level="4.4.1" data-path="viz.html"><a href="viz.html#some-guiding-principles-for-making-effectice-visualizations"><i class="fa fa-check"></i><b>4.4.1</b> Some guiding principles for making effectice visualizations</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="GitHub.html"><a href="GitHub.html"><i class="fa fa-check"></i><b>5</b> Version control with GitHub</a><ul>
<li class="chapter" data-level="5.1" data-path="GitHub.html"><a href="GitHub.html#overview-3"><i class="fa fa-check"></i><b>5.1</b> Overview</a></li>
<li class="chapter" data-level="5.2" data-path="GitHub.html"><a href="GitHub.html#videos-to-learn-about-version-control-with-github-and-git"><i class="fa fa-check"></i><b>5.2</b> Videos to learn about version control with GitHub and Git</a><ul>
<li class="chapter" data-level="5.2.1" data-path="GitHub.html"><a href="GitHub.html#creating-a-github-repository"><i class="fa fa-check"></i><b>5.2.1</b> Creating a GitHub repository</a></li>
<li class="chapter" data-level="5.2.2" data-path="GitHub.html"><a href="GitHub.html#exploring-a-github-repository"><i class="fa fa-check"></i><b>5.2.2</b> Exploring a GitHub repository</a></li>
<li class="chapter" data-level="5.2.3" data-path="GitHub.html"><a href="GitHub.html#directly-editing-files-on-github"><i class="fa fa-check"></i><b>5.2.3</b> Directly editing files on GitHub</a></li>
<li class="chapter" data-level="5.2.4" data-path="GitHub.html"><a href="GitHub.html#logging-changes-and-pushing-them-to-github"><i class="fa fa-check"></i><b>5.2.4</b> Logging changes and pushing them to GitHub</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="GitHub.html"><a href="GitHub.html#git-command-cheatsheet"><i class="fa fa-check"></i><b>5.3</b> Git command cheatsheet</a><ul>
<li class="chapter" data-level="5.3.1" data-path="GitHub.html"><a href="GitHub.html#getting-a-repository-from-github-onto-the-server-for-the-first-time"><i class="fa fa-check"></i><b>5.3.1</b> Getting a repository from GitHub onto the server for the first time</a></li>
<li class="chapter" data-level="5.3.2" data-path="GitHub.html"><a href="GitHub.html#logging-changes"><i class="fa fa-check"></i><b>5.3.2</b> Logging changes</a></li>
<li class="chapter" data-level="5.3.3" data-path="GitHub.html"><a href="GitHub.html#sending-your-changes-back-to-github"><i class="fa fa-check"></i><b>5.3.3</b> Sending your changes back to GitHub</a></li>
<li class="chapter" data-level="5.3.4" data-path="GitHub.html"><a href="GitHub.html#getting-changes"><i class="fa fa-check"></i><b>5.3.4</b> Getting changes</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="GitHub.html"><a href="GitHub.html#terminal-cheatsheet"><i class="fa fa-check"></i><b>5.4</b> Terminal cheatsheet</a><ul>
<li class="chapter" data-level="5.4.1" data-path="GitHub.html"><a href="GitHub.html#see-where-you-are"><i class="fa fa-check"></i><b>5.4.1</b> See where you are:</a></li>
<li class="chapter" data-level="5.4.2" data-path="GitHub.html"><a href="GitHub.html#see-what-is-inside-the-directory-where-you-are"><i class="fa fa-check"></i><b>5.4.2</b> See what is inside the directory where you are:</a></li>
<li class="chapter" data-level="5.4.3" data-path="GitHub.html"><a href="GitHub.html#move-to-a-different-directory"><i class="fa fa-check"></i><b>5.4.3</b> Move to a different directory</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="classification.html"><a href="classification.html"><i class="fa fa-check"></i><b>6</b> Classification</a><ul>
<li class="chapter" data-level="6.1" data-path="classification.html"><a href="classification.html#overview-4"><i class="fa fa-check"></i><b>6.1</b> Overview</a></li>
<li class="chapter" data-level="6.2" data-path="classification.html"><a href="classification.html#learning-objectives"><i class="fa fa-check"></i><b>6.2</b> Learning objectives</a></li>
<li class="chapter" data-level="6.3" data-path="classification.html"><a href="classification.html#classification"><i class="fa fa-check"></i><b>6.3</b> Classification</a></li>
<li class="chapter" data-level="6.4" data-path="classification.html"><a href="classification.html#wisconsin-breast-cancer-example"><i class="fa fa-check"></i><b>6.4</b> Wisconsin Breast Cancer Example:</a><ul>
<li class="chapter" data-level="6.4.1" data-path="classification.html"><a href="classification.html#data-exploration"><i class="fa fa-check"></i><b>6.4.1</b> Data Exploration</a></li>
<li class="chapter" data-level="6.4.2" data-path="classification.html"><a href="classification.html#k-nearest-neighbour-classifier"><i class="fa fa-check"></i><b>6.4.2</b> K-Nearest Neighbour Classifier</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="classification.html"><a href="classification.html#find-the-distance-between-new-point-and-all-others-in-dataset"><i class="fa fa-check"></i><b>6.5</b> Find the distance between new point and all others in dataset</a><ul>
<li class="chapter" data-level="6.5.1" data-path="classification.html"><a href="classification.html#k-nearest-neighbours-in-r"><i class="fa fa-check"></i><b>6.5.1</b> K-Nearest Neighbours in R</a></li>
<li class="chapter" data-level="6.5.2" data-path="classification.html"><a href="classification.html#more-than-two-explanatory-variablespredictors"><i class="fa fa-check"></i><b>6.5.2</b> More than two explanatory variables/predictors</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="classification-continued.html"><a href="classification-continued.html"><i class="fa fa-check"></i><b>7</b> Classification continued</a><ul>
<li class="chapter" data-level="7.1" data-path="classification-continued.html"><a href="classification-continued.html#overview-5"><i class="fa fa-check"></i><b>7.1</b> Overview</a></li>
<li class="chapter" data-level="7.2" data-path="classification-continued.html"><a href="classification-continued.html#learning-objectives-1"><i class="fa fa-check"></i><b>7.2</b> Learning objectives</a></li>
<li class="chapter" data-level="7.3" data-path="classification-continued.html"><a href="classification-continued.html#assessing-how-good-your-classifier-is"><i class="fa fa-check"></i><b>7.3</b> Assessing how good your classifier is</a><ul>
<li class="chapter" data-level="7.3.1" data-path="classification-continued.html"><a href="classification-continued.html#assessing-your-classifier-in-r"><i class="fa fa-check"></i><b>7.3.1</b> Assessing your classifier in R</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Data Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="classification_continued" class="section level1">
<h1><span class="header-section-number">Chapter 7</span> Classification continued</h1>
<div id="overview-5" class="section level2">
<h2><span class="header-section-number">7.1</span> Overview</h2>
<p>Metrics for classification accuracy; cross-validation to choose the number of neighbours; scaling of variables and other practical considerations.</p>
</div>
<div id="learning-objectives-1" class="section level2">
<h2><span class="header-section-number">7.2</span> Learning objectives</h2>
<p>By the end of the chapter, students will be able to:</p>
<ul>
<li>Describe what a validation data set is and how it is used in classification.</li>
<li>Using R, evaluate classification accuracy using a validation data set and appropriate metrics.</li>
<li>Using R, execute cross-validation in R to choose the number of neighbours.</li>
<li>Identify when it is necessary to scale variables before classification and do this using R</li>
<li>In a dataset with &gt; 2 attributes, perform k-nearest neighbour classification in R using caret::train(method = “knn”, …) to predict the class of a test dataset.</li>
<li>Describe advantages and disadvantages of the k-nearest neighbour classification algorithm.</li>
</ul>
</div>
<div id="assessing-how-good-your-classifier-is" class="section level2">
<h2><span class="header-section-number">7.3</span> Assessing how good your classifier is</h2>
<p>Sometimes our classifier might make the wrong prediction. A classifier does not need to be right 100% of the time to be useful, though we don’t want the classifier to make too many wrong predictions. How do we measure how “good” our classifier?</p>
<p>One way to assess our classifier’s performance can be done by splitting our data into a <strong>training</strong> set and a <strong>validation</strong> set. When we split the data, we make the assumption that there is no order to our originally collected data set. However, if we think that there might be some order to the original data set, then we can randomly shuffle the data before splitting it into a training and validation set.</p>
<p><img src="img/training_validation.jpeg" width="600" /></p>
<p>The <strong>training set</strong> is used to build the classifer. Then we can give the observations from the <strong>validation set</strong> (without the labels/classes) to our classifier and predict the labels/classes as if these were new observations that we didn’t have the labels/classes for. Then we can see how well our predictions match the true labels/classes for the observations in the <strong>validation set</strong>. If our predictions match the true labels/classes for the observations in the <strong>validation set</strong> very well then we have some confidence that our classifier might also do a good job of predicting the class labels for new observations that we do not have the class labels for.</p>
<p>How exactly can we assess how well our predictions match the true labels/classes for the observations in the <strong>validation set</strong>? One way we can do this is to calculate the prediction <strong>accuracy</strong>. This is essentially the proportion of time the classifier was correct. To calculate this we divide the number of correct predictions by the number of predictions made. Other measures for how well our classifier did include precision and recall (which will not be discussed here, but are discussed in other more advanced courses on this topic).</p>
<p>We try to illustrate this below:</p>
<p><img src="img/ML-paradigm.png" width="800" /></p>
<div id="assessing-your-classifier-in-r" class="section level3">
<h3><span class="header-section-number">7.3.1</span> Assessing your classifier in R</h3>
<p>We can use the <code>caret</code> package in R to not only perform k-nn classification, but also to assess how well our classification worked. Let’s start by loading the necessary libraries, data (we’ll continue exploring the breast cancer data set from last chapter) and making a quick scatter plot of tumour cell concavity versus perimeter, labelling the points be diagnosis class.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># load libraries</span>
<span class="kw">library</span>(tidyverse)
<span class="kw">library</span>(caret)

<span class="co">#load data</span>
cancer &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/clean-wdbc.data.csv&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Class =</span> <span class="kw">as.factor</span>(Class)) <span class="co"># because we will be doing statistical analysis on a categorical variable</span>

<span class="co"># colour palette</span>
cbPalette &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;#56B4E9&quot;</span>, <span class="st">&quot;#E69F00&quot;</span>,<span class="st">&quot;#009E73&quot;</span>, <span class="st">&quot;#F0E442&quot;</span>, <span class="st">&quot;#0072B2&quot;</span>, <span class="st">&quot;#D55E00&quot;</span>, <span class="st">&quot;#CC79A7&quot;</span>, <span class="st">&quot;#999999&quot;</span>) 

<span class="co"># create scatter plot of tumour cell concavity versus perimeter, </span>
<span class="co"># labelling the points be diagnosis class</span>
perim_concav &lt;-<span class="st"> </span>cancer <span class="op">%&gt;%</span><span class="st">  </span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Perimeter, <span class="dt">y =</span> Concavity, <span class="dt">color =</span> Class)) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">geom_point</span>(<span class="dt">alpha =</span> <span class="fl">0.5</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">labs</span>(<span class="dt">color =</span> <span class="st">&quot;Diagnosis&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">scale_color_manual</span>(<span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Benign&quot;</span>, <span class="st">&quot;Malignant&quot;</span>), <span class="dt">values =</span> cbPalette)
perim_concav</code></pre></div>
<p><img src="bookdown-demo_files/figure-html/precode-1.png" width="480" /></p>
<div id="splitting-into-training-and-validation-sets" class="section level4">
<h4><span class="header-section-number">7.3.1.1</span> Splitting into training and validation sets</h4>
<p>Next, lets split our data into a training and a validation set using <code>caret</code>’s <code>createDataPartition</code> function. When using this function to split a data set into a training and validation set it takes 3 arguments:</p>
<ol style="list-style-type: decimal">
<li><code>y</code> (the class labels, must be a vector),</li>
<li><code>p</code> (the proportion of the data you would like in the training data set), and</li>
<li><code>list = FALSE</code> (says we want the data back as a matrix instead of a list).</li>
</ol>
<p>The <code>createDataPartition</code> function returns the row numbers for the training set.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">1234</span>) <span class="co"># makes the random selection of rows reproducible</span>
set_rows &lt;-<span class="st"> </span>cancer <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(Class) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">unlist</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># converts Class from a tibble to a vector</span>
<span class="st">  </span><span class="kw">createDataPartition</span>(<span class="dt">p =</span> <span class="fl">0.60</span>, <span class="dt">list =</span> <span class="ot">FALSE</span>)
<span class="kw">head</span>(set_rows)</code></pre></div>
<pre><code>##      Resample1
## [1,]         1
## [2,]         3
## [3,]         4
## [4,]         5
## [5,]         7
## [6,]         8</code></pre>
<p><em>You will also see in the code above that we use the <code>set.seed</code> function. This is because <code>createDataPartition</code> uses random sampling to choose which rows will be in the training set, and if we use <code>set.seed</code> to specify where the random number generator starts for this process then we can make our analysis reproducible (always get the same random set of observations in the training set).</em></p>
<p>Now that we have the row numbers for the training set, we can use the <code>slice</code> function to get the rows from the original data set (here <code>cancer</code>) to create the training set and the validation sets.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">training_set &lt;-<span class="st"> </span>cancer <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">slice</span>(set_rows)
validation_set &lt;-<span class="st"> </span>cancer <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">slice</span>(<span class="op">-</span>set_rows)
<span class="kw">glimpse</span>(training_set)</code></pre></div>
<pre><code>## Observations: 343
## Variables: 12
## $ ID                &lt;int&gt; 842302, 84300903, 84348301, 84358402, 844359...
## $ Class             &lt;fct&gt; M, M, M, M, M, M, M, M, M, M, M, M, M, M, M,...
## $ Radius            &lt;dbl&gt; 1.88503100, 1.51054113, -0.28121702, 1.29743...
## $ Texture           &lt;dbl&gt; -1.35809849, -0.02395331, 0.13386631, -1.465...
## $ Perimeter         &lt;dbl&gt; 2.301575480, 1.346290616, -0.249719577, 1.33...
## $ Area              &lt;dbl&gt; 1.99947816, 1.45500430, -0.54953769, 1.21965...
## $ Smoothness        &lt;dbl&gt; 1.3065367, 0.5269438, 3.3912907, 0.2203623, ...
## $ Compactness       &lt;dbl&gt; 2.61436466, 1.08198014, 3.88997467, -0.31311...
## $ Concavity         &lt;dbl&gt; 2.10767182, 0.85422232, 1.98783917, 0.612639...
## $ Concave_points    &lt;dbl&gt; 2.29405760, 1.95328166, 2.17387323, 0.728618...
## $ Symmetry          &lt;dbl&gt; 2.7482041, 1.1512420, 6.0407261, -0.8675896,...
## $ Fractal_dimension &lt;dbl&gt; 1.93531174, 0.20121416, 4.93067187, -0.39675...</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">glimpse</span>(validation_set)</code></pre></div>
<pre><code>## Observations: 226
## Variables: 12
## $ ID                &lt;int&gt; 842517, 843786, 844981, 84501001, 845636, 84...
## $ Class             &lt;fct&gt; M, M, M, M, M, M, M, M, M, B, B, B, M, M, M,...
## $ Radius            &lt;dbl&gt; 1.80433981, -0.16535275, -0.16121474, -0.243...
## $ Texture           &lt;dbl&gt; -0.368878647, -0.313560433, 0.822089979, 2.4...
## $ Perimeter         &lt;dbl&gt; 1.53377643, -0.11490835, -0.03158132, -0.286...
## $ Area              &lt;dbl&gt; 1.888827020, -0.244105421, -0.248145066, -0....
## $ Smoothness        &lt;dbl&gt; -0.375281748, 2.046711944, 1.661295226, 2.31...
## $ Compactness       &lt;dbl&gt; -0.4300658, 1.7201029, 1.8167112, 5.1083824,...
## $ Concavity         &lt;dbl&gt; -0.1466200, 1.2621327, 1.2789092, 3.9919204,...
## $ Concave_points    &lt;dbl&gt; 1.08612862, 0.90509140, 1.39039284, 1.618591...
## $ Symmetry          &lt;dbl&gt; -0.2436753, 1.7525273, 2.3877562, 2.3683599,...
## $ Fractal_dimension &lt;dbl&gt; 0.28094279, 2.23983079, 1.28751667, 6.840836...</code></pre>
<p>We can see from <code>glimpse</code> in the code above that the training set contains 343 observations, while the validation set contains 226 observations. This corresponds to the training set having 60% of the observations from the original data set and the validation set having the other 40% of the observations. We specified this when we set <code>p = 0.60</code> when we called <code>createDataPartition</code>.</p>
</div>
<div id="creating-the-k-nn-classifier" class="section level4">
<h4><span class="header-section-number">7.3.1.2</span> Creating the k-nn classifier</h4>
<p>Now that we have split our original data set into a training and validation set, we can create our k-nn classifier using the training set. We explained how to do this last chapter, so here we just do it! For the time being we will just choose a single <span class="math inline">\(k\)</span> of 3, and use the predictors concavity and perimeter.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">X_train &lt;-<span class="st"> </span>training_set <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(Concavity, Perimeter) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">data.frame</span>()
Y_train &lt;-<span class="st"> </span>training_set <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(Class) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">unlist</span>()
k =<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">k =</span> <span class="dv">3</span>)
model_knn &lt;-<span class="st"> </span><span class="kw">train</span>(<span class="dt">x =</span> X_train, <span class="dt">y =</span> Y_train, <span class="dt">method =</span> <span class="st">&quot;knn&quot;</span>, <span class="dt">tuneGrid =</span> k)
model_knn</code></pre></div>
<pre><code>## k-Nearest Neighbors 
## 
## 343 samples
##   2 predictor
##   2 classes: &#39;B&#39;, &#39;M&#39; 
## 
## No pre-processing
## Resampling: Bootstrapped (25 reps) 
## Summary of sample sizes: 343, 343, 343, 343, 343, 343, ... 
## Resampling results:
## 
##   Accuracy   Kappa    
##   0.9314839  0.8538238
## 
## Tuning parameter &#39;k&#39; was held constant at a value of 3</code></pre>
</div>
<div id="predict-class-labels-for-the-validation-set" class="section level4">
<h4><span class="header-section-number">7.3.1.3</span> Predict class labels for the validation set</h4>
<p>Now that we have a k-nn classifier object, we can use it to predict the class labels for our validation set:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">X_validation &lt;-<span class="st"> </span>validation_set <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(Concavity, Perimeter) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">data.frame</span>()
Y_validation_predicted &lt;-<span class="st"> </span><span class="kw">predict</span>(<span class="dt">object =</span> model_knn, X_validation)
<span class="kw">head</span>(Y_validation_predicted)</code></pre></div>
<pre><code>## [1] M M M M M M
## Levels: B M</code></pre>
</div>
<div id="assessing-our-classifiers-accuracy" class="section level4">
<h4><span class="header-section-number">7.3.1.4</span> Assessing our classifier’s accuracy</h4>
<p>Finally we can assess our classifier’s accuracy. To do this we need to create vector containing the class labels for the validation set. Next we use the function <code>confusionMatrix</code> to get the statistics about the quality of our model, this includes the statistic we are interested: accuracy. <code>confusionMatrix</code> takes two arguments:</p>
<ol style="list-style-type: decimal">
<li><code>data</code> (the predicted class labels for the validation set), and</li>
<li><code>reference</code> (the original/measured class labels for the validation set).</li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Y_validation &lt;-<span class="st"> </span>validation_set <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(Class) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">unlist</span>()

model_quality &lt;-<span class="st"> </span><span class="kw">confusionMatrix</span>(<span class="dt">data =</span> Y_validation_predicted, <span class="dt">reference =</span> Y_validation)
model_quality</code></pre></div>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   B   M
##          B 126   5
##          M  16  79
##                                           
##                Accuracy : 0.9071          
##                  95% CI : (0.8615, 0.9416)
##     No Information Rate : 0.6283          
##     P-Value [Acc &gt; NIR] : &lt;2e-16          
##                                           
##                   Kappa : 0.8062          
##  Mcnemar&#39;s Test P-Value : 0.0291          
##                                           
##             Sensitivity : 0.8873          
##             Specificity : 0.9405          
##          Pos Pred Value : 0.9618          
##          Neg Pred Value : 0.8316          
##              Prevalence : 0.6283          
##          Detection Rate : 0.5575          
##    Detection Prevalence : 0.5796          
##       Balanced Accuracy : 0.9139          
##                                           
##        &#39;Positive&#39; Class : B               
## </code></pre>

</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="classification.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/06-classification_continued.Rmd",
"text": "Edit"
},
"download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
