<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Classification I: training &amp; predicting | Data Science: A First Introduction</title>
  <meta name="description" content="This is a textbook for teaching a first introduction to data science." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Classification I: training &amp; predicting | Data Science: A First Introduction" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a textbook for teaching a first introduction to data science." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Classification I: training &amp; predicting | Data Science: A First Introduction" />
  
  <meta name="twitter:description" content="This is a textbook for teaching a first introduction to data science." />
  

<meta name="author" content="Tiffany-Anne Timbers" />
<meta name="author" content="Trevor Campbell" />
<meta name="author" content="Melissa Lee" />


<meta name="date" content="2021-11-13" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="viz.html"/>
<link rel="next" href="classification2.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.5.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.5.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Data Science: A First Introduction</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="" data-path="acknowledgments.html"><a href="acknowledgments.html"><i class="fa fa-check"></i>Acknowledgments</a></li>
<li class="chapter" data-level="" data-path="about-the-authors.html"><a href="about-the-authors.html"><i class="fa fa-check"></i>About the authors</a></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> R and the tidyverse</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#overview"><i class="fa fa-check"></i><b>1.1</b> Overview</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#chapter-learning-objectives"><i class="fa fa-check"></i><b>1.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#canadian-languages-data-set"><i class="fa fa-check"></i><b>1.3</b> Canadian languages data set</a></li>
<li class="chapter" data-level="1.4" data-path="intro.html"><a href="intro.html#asking-a-question"><i class="fa fa-check"></i><b>1.4</b> Asking a question</a></li>
<li class="chapter" data-level="1.5" data-path="intro.html"><a href="intro.html#loading-a-tabular-data-set"><i class="fa fa-check"></i><b>1.5</b> Loading a tabular data set</a></li>
<li class="chapter" data-level="1.6" data-path="intro.html"><a href="intro.html#naming-things-in-r"><i class="fa fa-check"></i><b>1.6</b> Naming things in R</a></li>
<li class="chapter" data-level="1.7" data-path="intro.html"><a href="intro.html#creating-subsets-of-data-frames-with-filter-select"><i class="fa fa-check"></i><b>1.7</b> Creating subsets of data frames with <code>filter</code> &amp; <code>select</code></a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="intro.html"><a href="intro.html#using-filter-to-extract-rows"><i class="fa fa-check"></i><b>1.7.1</b> Using <code>filter</code> to extract rows</a></li>
<li class="chapter" data-level="1.7.2" data-path="intro.html"><a href="intro.html#using-select-to-extract-columns"><i class="fa fa-check"></i><b>1.7.2</b> Using <code>select</code> to extract columns</a></li>
<li class="chapter" data-level="1.7.3" data-path="intro.html"><a href="intro.html#using-arrange-to-order-and-slice-to-select-rows-by-index-number"><i class="fa fa-check"></i><b>1.7.3</b> Using <code>arrange</code> to order and <code>slice</code> to select rows by index number</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="intro.html"><a href="intro.html#exploring-data-with-visualizations"><i class="fa fa-check"></i><b>1.8</b> Exploring data with visualizations</a>
<ul>
<li class="chapter" data-level="1.8.1" data-path="intro.html"><a href="intro.html#using-ggplot-to-create-a-bar-plot"><i class="fa fa-check"></i><b>1.8.1</b> Using <code>ggplot</code> to create a bar plot</a></li>
<li class="chapter" data-level="1.8.2" data-path="intro.html"><a href="intro.html#formatting-ggplot-objects"><i class="fa fa-check"></i><b>1.8.2</b> Formatting ggplot objects</a></li>
<li class="chapter" data-level="1.8.3" data-path="intro.html"><a href="intro.html#putting-it-all-together"><i class="fa fa-check"></i><b>1.8.3</b> Putting it all together</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="intro.html"><a href="intro.html#accessing-documentation"><i class="fa fa-check"></i><b>1.9</b> Accessing documentation</a></li>
<li class="chapter" data-level="1.10" data-path="intro.html"><a href="intro.html#exercises"><i class="fa fa-check"></i><b>1.10</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="reading.html"><a href="reading.html"><i class="fa fa-check"></i><b>2</b> Reading in data locally and from the web</a>
<ul>
<li class="chapter" data-level="2.1" data-path="reading.html"><a href="reading.html#overview-1"><i class="fa fa-check"></i><b>2.1</b> Overview</a></li>
<li class="chapter" data-level="2.2" data-path="reading.html"><a href="reading.html#chapter-learning-objectives-1"><i class="fa fa-check"></i><b>2.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="2.3" data-path="reading.html"><a href="reading.html#absolute-and-relative-file-paths"><i class="fa fa-check"></i><b>2.3</b> Absolute and relative file paths</a></li>
<li class="chapter" data-level="2.4" data-path="reading.html"><a href="reading.html#reading-tabular-data-from-a-plain-text-file-into-r"><i class="fa fa-check"></i><b>2.4</b> Reading tabular data from a plain text file into R</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="reading.html"><a href="reading.html#readcsv"><i class="fa fa-check"></i><b>2.4.1</b> <code>read_csv</code> to read in comma-separated files</a></li>
<li class="chapter" data-level="2.4.2" data-path="reading.html"><a href="reading.html#skipping-rows-when-reading-in-data"><i class="fa fa-check"></i><b>2.4.2</b> Skipping rows when reading in data</a></li>
<li class="chapter" data-level="2.4.3" data-path="reading.html"><a href="reading.html#read_tsv-to-read-in-tab-separated-files"><i class="fa fa-check"></i><b>2.4.3</b> <code>read_tsv</code> to read in tab-separated files</a></li>
<li class="chapter" data-level="2.4.4" data-path="reading.html"><a href="reading.html#read_delim-as-a-more-flexible-method-to-get-tabular-data-into-r"><i class="fa fa-check"></i><b>2.4.4</b> <code>read_delim</code> as a more flexible method to get tabular data into R</a></li>
<li class="chapter" data-level="2.4.5" data-path="reading.html"><a href="reading.html#reading-tabular-data-directly-from-a-url"><i class="fa fa-check"></i><b>2.4.5</b> Reading tabular data directly from a URL</a></li>
<li class="chapter" data-level="2.4.6" data-path="reading.html"><a href="reading.html#previewing-a-data-file-before-reading-it-into-r"><i class="fa fa-check"></i><b>2.4.6</b> Previewing a data file before reading it into R</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="reading.html"><a href="reading.html#reading-tabular-data-from-a-microsoft-excel-file"><i class="fa fa-check"></i><b>2.5</b> Reading tabular data from a Microsoft Excel file</a></li>
<li class="chapter" data-level="2.6" data-path="reading.html"><a href="reading.html#reading-data-from-a-database"><i class="fa fa-check"></i><b>2.6</b> Reading data from a database</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="reading.html"><a href="reading.html#reading-data-from-a-sqlite-database"><i class="fa fa-check"></i><b>2.6.1</b> Reading data from a SQLite database</a></li>
<li class="chapter" data-level="2.6.2" data-path="reading.html"><a href="reading.html#reading-data-from-a-postgresql-database"><i class="fa fa-check"></i><b>2.6.2</b> Reading data from a PostgreSQL database</a></li>
<li class="chapter" data-level="2.6.3" data-path="reading.html"><a href="reading.html#why-should-we-bother-with-databases-at-all"><i class="fa fa-check"></i><b>2.6.3</b> Why should we bother with databases at all?</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="reading.html"><a href="reading.html#writing-data-from-r-to-a-.csv-file"><i class="fa fa-check"></i><b>2.7</b> Writing data from R to a <code>.csv</code> file</a></li>
<li class="chapter" data-level="2.8" data-path="reading.html"><a href="reading.html#obtaining-data-from-the-web"><i class="fa fa-check"></i><b>2.8</b> Obtaining data from the web</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="reading.html"><a href="reading.html#web-scraping"><i class="fa fa-check"></i><b>2.8.1</b> Web scraping</a></li>
<li class="chapter" data-level="2.8.2" data-path="reading.html"><a href="reading.html#using-an-api"><i class="fa fa-check"></i><b>2.8.2</b> Using an API</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="reading.html"><a href="reading.html#exercises-1"><i class="fa fa-check"></i><b>2.9</b> Exercises</a></li>
<li class="chapter" data-level="2.10" data-path="reading.html"><a href="reading.html#additional-resources"><i class="fa fa-check"></i><b>2.10</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="wrangling.html"><a href="wrangling.html"><i class="fa fa-check"></i><b>3</b> Cleaning and wrangling data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="wrangling.html"><a href="wrangling.html#overview-2"><i class="fa fa-check"></i><b>3.1</b> Overview</a></li>
<li class="chapter" data-level="3.2" data-path="wrangling.html"><a href="wrangling.html#chapter-learning-objectives-2"><i class="fa fa-check"></i><b>3.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="3.3" data-path="wrangling.html"><a href="wrangling.html#data-frames-vectors-and-lists"><i class="fa fa-check"></i><b>3.3</b> Data frames, vectors, and lists</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="wrangling.html"><a href="wrangling.html#what-is-a-data-frame"><i class="fa fa-check"></i><b>3.3.1</b> What is a data frame?</a></li>
<li class="chapter" data-level="3.3.2" data-path="wrangling.html"><a href="wrangling.html#what-is-a-vector"><i class="fa fa-check"></i><b>3.3.2</b> What is a vector?</a></li>
<li class="chapter" data-level="3.3.3" data-path="wrangling.html"><a href="wrangling.html#what-is-a-list"><i class="fa fa-check"></i><b>3.3.3</b> What is a list?</a></li>
<li class="chapter" data-level="3.3.4" data-path="wrangling.html"><a href="wrangling.html#what-does-this-have-to-do-with-data-frames"><i class="fa fa-check"></i><b>3.3.4</b> What does this have to do with data frames?</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="wrangling.html"><a href="wrangling.html#tidy-data"><i class="fa fa-check"></i><b>3.4</b> Tidy data</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="wrangling.html"><a href="wrangling.html#tidying-up-going-from-wide-to-long-using-pivot_longer"><i class="fa fa-check"></i><b>3.4.1</b> Tidying up: going from wide to long using <code>pivot_longer</code></a></li>
<li class="chapter" data-level="3.4.2" data-path="wrangling.html"><a href="wrangling.html#pivot-wider"><i class="fa fa-check"></i><b>3.4.2</b> Tidying up: going from long to wide using <code>pivot_wider</code></a></li>
<li class="chapter" data-level="3.4.3" data-path="wrangling.html"><a href="wrangling.html#separate"><i class="fa fa-check"></i><b>3.4.3</b> Tidying up: using <code>separate</code> to deal with multiple delimiters</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="wrangling.html"><a href="wrangling.html#using-select-to-extract-a-range-of-columns"><i class="fa fa-check"></i><b>3.5</b> Using <code>select</code> to extract a range of columns</a></li>
<li class="chapter" data-level="3.6" data-path="wrangling.html"><a href="wrangling.html#using-filter-to-extract-rows-1"><i class="fa fa-check"></i><b>3.6</b> Using <code>filter</code> to extract rows</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="wrangling.html"><a href="wrangling.html#extracting-rows-that-have-a-certain-value-with"><i class="fa fa-check"></i><b>3.6.1</b> Extracting rows that have a certain value with <code>==</code></a></li>
<li class="chapter" data-level="3.6.2" data-path="wrangling.html"><a href="wrangling.html#extracting-rows-that-do-not-have-a-certain-value-with"><i class="fa fa-check"></i><b>3.6.2</b> Extracting rows that do not have a certain value with <code>!=</code></a></li>
<li class="chapter" data-level="3.6.3" data-path="wrangling.html"><a href="wrangling.html#filter-and"><i class="fa fa-check"></i><b>3.6.3</b> Extracting rows satisfying multiple conditions using <code>,</code> or <code>&amp;</code></a></li>
<li class="chapter" data-level="3.6.4" data-path="wrangling.html"><a href="wrangling.html#extracting-rows-satisfying-at-least-one-condition-using"><i class="fa fa-check"></i><b>3.6.4</b> Extracting rows satisfying at least one condition using <code>|</code></a></li>
<li class="chapter" data-level="3.6.5" data-path="wrangling.html"><a href="wrangling.html#extracting-rows-with-values-in-a-vector-using-in"><i class="fa fa-check"></i><b>3.6.5</b> Extracting rows with values in a vector using <code>%in%</code></a></li>
<li class="chapter" data-level="3.6.6" data-path="wrangling.html"><a href="wrangling.html#extracting-rows-above-or-below-a-threshold-using-and"><i class="fa fa-check"></i><b>3.6.6</b> Extracting rows above or below a threshold using <code>&gt;</code> and <code>&lt;</code></a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="wrangling.html"><a href="wrangling.html#using-mutate-to-modify-or-add-columns"><i class="fa fa-check"></i><b>3.7</b> Using <code>mutate</code> to modify or add columns</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="wrangling.html"><a href="wrangling.html#using-mutate-to-modify-columns"><i class="fa fa-check"></i><b>3.7.1</b> Using <code>mutate</code> to modify columns</a></li>
<li class="chapter" data-level="3.7.2" data-path="wrangling.html"><a href="wrangling.html#using-mutate-to-create-new-columns"><i class="fa fa-check"></i><b>3.7.2</b> Using <code>mutate</code> to create new columns</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="wrangling.html"><a href="wrangling.html#combining-functions-using-the-pipe-operator"><i class="fa fa-check"></i><b>3.8</b> Combining functions using the pipe operator, <code>|&gt;</code></a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="wrangling.html"><a href="wrangling.html#using-to-combine-filter-and-select"><i class="fa fa-check"></i><b>3.8.1</b> Using <code>|&gt;</code> to combine <code>filter</code> and <code>select</code></a></li>
<li class="chapter" data-level="3.8.2" data-path="wrangling.html"><a href="wrangling.html#using-with-more-than-two-functions"><i class="fa fa-check"></i><b>3.8.2</b> Using <code>|&gt;</code> with more than two functions</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="wrangling.html"><a href="wrangling.html#aggregating-data-with-summarize-and-map"><i class="fa fa-check"></i><b>3.9</b> Aggregating data with <code>summarize</code> and <code>map</code></a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="wrangling.html"><a href="wrangling.html#calculating-summary-statistics-on-whole-columns"><i class="fa fa-check"></i><b>3.9.1</b> Calculating summary statistics on whole columns</a></li>
<li class="chapter" data-level="3.9.2" data-path="wrangling.html"><a href="wrangling.html#calculating-summary-statistics-for-groups-of-rows"><i class="fa fa-check"></i><b>3.9.2</b> Calculating summary statistics for groups of rows</a></li>
<li class="chapter" data-level="3.9.3" data-path="wrangling.html"><a href="wrangling.html#calculating-summary-statistics-on-many-columns"><i class="fa fa-check"></i><b>3.9.3</b> Calculating summary statistics on many columns</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="wrangling.html"><a href="wrangling.html#apply-functions-across-many-columns-with-mutate-and-across"><i class="fa fa-check"></i><b>3.10</b> Apply functions across many columns with <code>mutate</code> and <code>across</code></a></li>
<li class="chapter" data-level="3.11" data-path="wrangling.html"><a href="wrangling.html#apply-functions-across-columns-within-one-row-with-rowwise-and-mutate"><i class="fa fa-check"></i><b>3.11</b> Apply functions across columns within one row with <code>rowwise</code> and <code>mutate</code></a></li>
<li class="chapter" data-level="3.12" data-path="wrangling.html"><a href="wrangling.html#summary"><i class="fa fa-check"></i><b>3.12</b> Summary</a></li>
<li class="chapter" data-level="3.13" data-path="wrangling.html"><a href="wrangling.html#exercises-2"><i class="fa fa-check"></i><b>3.13</b> Exercises</a></li>
<li class="chapter" data-level="3.14" data-path="wrangling.html"><a href="wrangling.html#additional-resources-1"><i class="fa fa-check"></i><b>3.14</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="viz.html"><a href="viz.html"><i class="fa fa-check"></i><b>4</b> Effective data visualization</a>
<ul>
<li class="chapter" data-level="4.1" data-path="viz.html"><a href="viz.html#overview-3"><i class="fa fa-check"></i><b>4.1</b> Overview</a></li>
<li class="chapter" data-level="4.2" data-path="viz.html"><a href="viz.html#chapter-learning-objectives-3"><i class="fa fa-check"></i><b>4.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="4.3" data-path="viz.html"><a href="viz.html#choosing-the-visualization"><i class="fa fa-check"></i><b>4.3</b> Choosing the visualization</a></li>
<li class="chapter" data-level="4.4" data-path="viz.html"><a href="viz.html#refining-the-visualization"><i class="fa fa-check"></i><b>4.4</b> Refining the visualization</a></li>
<li class="chapter" data-level="4.5" data-path="viz.html"><a href="viz.html#creating-visualizations-with-ggplot2"><i class="fa fa-check"></i><b>4.5</b> Creating visualizations with <code>ggplot2</code></a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="viz.html"><a href="viz.html#scatter-plots-and-line-plots-the-mauna-loa-co_text2-data-set"><i class="fa fa-check"></i><b>4.5.1</b> Scatter plots and line plots: the Mauna Loa CO<span class="math inline">\(_{\text{2}}\)</span> data set</a></li>
<li class="chapter" data-level="4.5.2" data-path="viz.html"><a href="viz.html#scatter-plots-the-old-faithful-eruption-time-data-set"><i class="fa fa-check"></i><b>4.5.2</b> Scatter plots: the Old Faithful eruption time data set</a></li>
<li class="chapter" data-level="4.5.3" data-path="viz.html"><a href="viz.html#axis-transformation-and-colored-scatter-plots-the-canadian-languages-data-set"><i class="fa fa-check"></i><b>4.5.3</b> Axis transformation and colored scatter plots: the Canadian languages data set</a></li>
<li class="chapter" data-level="4.5.4" data-path="viz.html"><a href="viz.html#bar-plots-the-island-landmass-data-set"><i class="fa fa-check"></i><b>4.5.4</b> Bar plots: the island landmass data set</a></li>
<li class="chapter" data-level="4.5.5" data-path="viz.html"><a href="viz.html#histograms-the-michelson-speed-of-light-data-set"><i class="fa fa-check"></i><b>4.5.5</b> Histograms: the Michelson speed of light data set</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="viz.html"><a href="viz.html#explaining-the-visualization"><i class="fa fa-check"></i><b>4.6</b> Explaining the visualization</a></li>
<li class="chapter" data-level="4.7" data-path="viz.html"><a href="viz.html#saving-the-visualization"><i class="fa fa-check"></i><b>4.7</b> Saving the visualization</a></li>
<li class="chapter" data-level="4.8" data-path="viz.html"><a href="viz.html#exercises-3"><i class="fa fa-check"></i><b>4.8</b> Exercises</a></li>
<li class="chapter" data-level="4.9" data-path="viz.html"><a href="viz.html#additional-resources-2"><i class="fa fa-check"></i><b>4.9</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="classification.html"><a href="classification.html"><i class="fa fa-check"></i><b>5</b> Classification I: training &amp; predicting</a>
<ul>
<li class="chapter" data-level="5.1" data-path="classification.html"><a href="classification.html#overview-4"><i class="fa fa-check"></i><b>5.1</b> Overview</a></li>
<li class="chapter" data-level="5.2" data-path="classification.html"><a href="classification.html#chapter-learning-objectives-4"><i class="fa fa-check"></i><b>5.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="5.3" data-path="classification.html"><a href="classification.html#the-classification-problem"><i class="fa fa-check"></i><b>5.3</b> The classification problem</a></li>
<li class="chapter" data-level="5.4" data-path="classification.html"><a href="classification.html#exploring-a-data-set"><i class="fa fa-check"></i><b>5.4</b> Exploring a data set</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="classification.html"><a href="classification.html#loading-the-cancer-data"><i class="fa fa-check"></i><b>5.4.1</b> Loading the cancer data</a></li>
<li class="chapter" data-level="5.4.2" data-path="classification.html"><a href="classification.html#describing-the-variables-in-the-cancer-data-set"><i class="fa fa-check"></i><b>5.4.2</b> Describing the variables in the cancer data set</a></li>
<li class="chapter" data-level="5.4.3" data-path="classification.html"><a href="classification.html#exploring-the-cancer-data"><i class="fa fa-check"></i><b>5.4.3</b> Exploring the cancer data</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="classification.html"><a href="classification.html#classification-with-k-nearest-neighbors"><i class="fa fa-check"></i><b>5.5</b> Classification with <span class="math inline">\(K\)</span>-nearest neighbors</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="classification.html"><a href="classification.html#distance-between-points"><i class="fa fa-check"></i><b>5.5.1</b> Distance between points</a></li>
<li class="chapter" data-level="5.5.2" data-path="classification.html"><a href="classification.html#more-than-two-explanatory-variables"><i class="fa fa-check"></i><b>5.5.2</b> More than two explanatory variables</a></li>
<li class="chapter" data-level="5.5.3" data-path="classification.html"><a href="classification.html#summary-of-k-nearest-neighbors-algorithm"><i class="fa fa-check"></i><b>5.5.3</b> Summary of <span class="math inline">\(K\)</span>-nearest neighbors algorithm</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="classification.html"><a href="classification.html#k-nearest-neighbors-with-tidymodels"><i class="fa fa-check"></i><b>5.6</b> <span class="math inline">\(K\)</span>-nearest neighbors with <code>tidymodels</code></a></li>
<li class="chapter" data-level="5.7" data-path="classification.html"><a href="classification.html#data-preprocessing-with-tidymodels"><i class="fa fa-check"></i><b>5.7</b> Data preprocessing with <code>tidymodels</code></a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="classification.html"><a href="classification.html#centering-and-scaling"><i class="fa fa-check"></i><b>5.7.1</b> Centering and scaling</a></li>
<li class="chapter" data-level="5.7.2" data-path="classification.html"><a href="classification.html#balancing"><i class="fa fa-check"></i><b>5.7.2</b> Balancing</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="classification.html"><a href="classification.html#puttingittogetherworkflow"><i class="fa fa-check"></i><b>5.8</b> Putting it together in a <code>workflow</code></a></li>
<li class="chapter" data-level="5.9" data-path="classification.html"><a href="classification.html#exercises-4"><i class="fa fa-check"></i><b>5.9</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="classification2.html"><a href="classification2.html"><i class="fa fa-check"></i><b>6</b> Classification II: evaluation &amp; tuning</a>
<ul>
<li class="chapter" data-level="6.1" data-path="classification2.html"><a href="classification2.html#overview-5"><i class="fa fa-check"></i><b>6.1</b> Overview</a></li>
<li class="chapter" data-level="6.2" data-path="classification2.html"><a href="classification2.html#chapter-learning-objectives-5"><i class="fa fa-check"></i><b>6.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="6.3" data-path="classification2.html"><a href="classification2.html#evaluating-accuracy"><i class="fa fa-check"></i><b>6.3</b> Evaluating accuracy</a></li>
<li class="chapter" data-level="6.4" data-path="classification2.html"><a href="classification2.html#randomseeds"><i class="fa fa-check"></i><b>6.4</b> Randomness and seeds</a></li>
<li class="chapter" data-level="6.5" data-path="classification2.html"><a href="classification2.html#evaluating-accuracy-with-tidymodels"><i class="fa fa-check"></i><b>6.5</b> Evaluating accuracy with <code>tidymodels</code></a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="classification2.html"><a href="classification2.html#create-the-train-test-split"><i class="fa fa-check"></i><b>6.5.1</b> Create the train / test split</a></li>
<li class="chapter" data-level="6.5.2" data-path="classification2.html"><a href="classification2.html#preprocess-the-data"><i class="fa fa-check"></i><b>6.5.2</b> Preprocess the data</a></li>
<li class="chapter" data-level="6.5.3" data-path="classification2.html"><a href="classification2.html#train-the-classifier"><i class="fa fa-check"></i><b>6.5.3</b> Train the classifier</a></li>
<li class="chapter" data-level="6.5.4" data-path="classification2.html"><a href="classification2.html#predict-the-labels-in-the-test-set"><i class="fa fa-check"></i><b>6.5.4</b> Predict the labels in the test set</a></li>
<li class="chapter" data-level="6.5.5" data-path="classification2.html"><a href="classification2.html#compute-the-accuracy"><i class="fa fa-check"></i><b>6.5.5</b> Compute the accuracy</a></li>
<li class="chapter" data-level="6.5.6" data-path="classification2.html"><a href="classification2.html#critically-analyze-performance"><i class="fa fa-check"></i><b>6.5.6</b> Critically analyze performance</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="classification2.html"><a href="classification2.html#tuning-the-classifier"><i class="fa fa-check"></i><b>6.6</b> Tuning the classifier</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="classification2.html"><a href="classification2.html#cross-validation"><i class="fa fa-check"></i><b>6.6.1</b> Cross-validation</a></li>
<li class="chapter" data-level="6.6.2" data-path="classification2.html"><a href="classification2.html#parameter-value-selection"><i class="fa fa-check"></i><b>6.6.2</b> Parameter value selection</a></li>
<li class="chapter" data-level="6.6.3" data-path="classification2.html"><a href="classification2.html#underoverfitting"><i class="fa fa-check"></i><b>6.6.3</b> Under/Overfitting</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="classification2.html"><a href="classification2.html#summary-1"><i class="fa fa-check"></i><b>6.7</b> Summary</a></li>
<li class="chapter" data-level="6.8" data-path="classification2.html"><a href="classification2.html#predictor-variable-selection"><i class="fa fa-check"></i><b>6.8</b> Predictor variable selection</a>
<ul>
<li class="chapter" data-level="6.8.1" data-path="classification2.html"><a href="classification2.html#the-effect-of-irrelevant-predictors"><i class="fa fa-check"></i><b>6.8.1</b> The effect of irrelevant predictors</a></li>
<li class="chapter" data-level="6.8.2" data-path="classification2.html"><a href="classification2.html#finding-a-good-subset-of-predictors"><i class="fa fa-check"></i><b>6.8.2</b> Finding a good subset of predictors</a></li>
<li class="chapter" data-level="6.8.3" data-path="classification2.html"><a href="classification2.html#forward-selection-in-r"><i class="fa fa-check"></i><b>6.8.3</b> Forward selection in R</a></li>
</ul></li>
<li class="chapter" data-level="6.9" data-path="classification2.html"><a href="classification2.html#exercises-5"><i class="fa fa-check"></i><b>6.9</b> Exercises</a></li>
<li class="chapter" data-level="6.10" data-path="classification2.html"><a href="classification2.html#additional-resources-3"><i class="fa fa-check"></i><b>6.10</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="regression1.html"><a href="regression1.html"><i class="fa fa-check"></i><b>7</b> Regression I: K-nearest neighbors</a>
<ul>
<li class="chapter" data-level="7.1" data-path="regression1.html"><a href="regression1.html#overview-6"><i class="fa fa-check"></i><b>7.1</b> Overview</a></li>
<li class="chapter" data-level="7.2" data-path="regression1.html"><a href="regression1.html#chapter-learning-objectives-6"><i class="fa fa-check"></i><b>7.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="7.3" data-path="regression1.html"><a href="regression1.html#the-regression-problem"><i class="fa fa-check"></i><b>7.3</b> The regression problem</a></li>
<li class="chapter" data-level="7.4" data-path="regression1.html"><a href="regression1.html#exploring-a-data-set-1"><i class="fa fa-check"></i><b>7.4</b> Exploring a data set</a></li>
<li class="chapter" data-level="7.5" data-path="regression1.html"><a href="regression1.html#k-nearest-neighbors-regression"><i class="fa fa-check"></i><b>7.5</b> K-nearest neighbors regression</a></li>
<li class="chapter" data-level="7.6" data-path="regression1.html"><a href="regression1.html#training-evaluating-and-tuning-the-model"><i class="fa fa-check"></i><b>7.6</b> Training, evaluating, and tuning the model</a></li>
<li class="chapter" data-level="7.7" data-path="regression1.html"><a href="regression1.html#underfitting-and-overfitting"><i class="fa fa-check"></i><b>7.7</b> Underfitting and overfitting</a></li>
<li class="chapter" data-level="7.8" data-path="regression1.html"><a href="regression1.html#evaluating-on-the-test-set"><i class="fa fa-check"></i><b>7.8</b> Evaluating on the test set</a></li>
<li class="chapter" data-level="7.9" data-path="regression1.html"><a href="regression1.html#multivariable-knn-regression"><i class="fa fa-check"></i><b>7.9</b> Multivariable KNN regression</a></li>
<li class="chapter" data-level="7.10" data-path="regression1.html"><a href="regression1.html#strengths-and-limitations-of-knn-regression"><i class="fa fa-check"></i><b>7.10</b> Strengths and limitations of KNN regression</a></li>
<li class="chapter" data-level="7.11" data-path="regression1.html"><a href="regression1.html#exercises-6"><i class="fa fa-check"></i><b>7.11</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="regression2.html"><a href="regression2.html"><i class="fa fa-check"></i><b>8</b> Regression II: linear regression</a>
<ul>
<li class="chapter" data-level="8.1" data-path="regression2.html"><a href="regression2.html#overview-7"><i class="fa fa-check"></i><b>8.1</b> Overview</a></li>
<li class="chapter" data-level="8.2" data-path="regression2.html"><a href="regression2.html#chapter-learning-objectives-7"><i class="fa fa-check"></i><b>8.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="8.3" data-path="regression2.html"><a href="regression2.html#simple-linear-regression"><i class="fa fa-check"></i><b>8.3</b> Simple linear regression</a></li>
<li class="chapter" data-level="8.4" data-path="regression2.html"><a href="regression2.html#linear-regression-in-r"><i class="fa fa-check"></i><b>8.4</b> Linear regression in R</a></li>
<li class="chapter" data-level="8.5" data-path="regression2.html"><a href="regression2.html#comparing-simple-linear-and-knn-regression"><i class="fa fa-check"></i><b>8.5</b> Comparing simple linear and KNN regression</a></li>
<li class="chapter" data-level="8.6" data-path="regression2.html"><a href="regression2.html#multivariable-linear-regression"><i class="fa fa-check"></i><b>8.6</b> Multivariable linear regression</a></li>
<li class="chapter" data-level="8.7" data-path="regression2.html"><a href="regression2.html#multicollinearity-and-outliers"><i class="fa fa-check"></i><b>8.7</b> Multicollinearity and outliers</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="regression2.html"><a href="regression2.html#outliers"><i class="fa fa-check"></i><b>8.7.1</b> Outliers</a></li>
<li class="chapter" data-level="8.7.2" data-path="regression2.html"><a href="regression2.html#multicollinearity"><i class="fa fa-check"></i><b>8.7.2</b> Multicollinearity</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="regression2.html"><a href="regression2.html#designing-new-predictors"><i class="fa fa-check"></i><b>8.8</b> Designing new predictors</a></li>
<li class="chapter" data-level="8.9" data-path="regression2.html"><a href="regression2.html#the-other-sides-of-regression"><i class="fa fa-check"></i><b>8.9</b> The other sides of regression</a></li>
<li class="chapter" data-level="8.10" data-path="regression2.html"><a href="regression2.html#exercises-7"><i class="fa fa-check"></i><b>8.10</b> Exercises</a></li>
<li class="chapter" data-level="8.11" data-path="regression2.html"><a href="regression2.html#additional-resources-4"><i class="fa fa-check"></i><b>8.11</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="clustering.html"><a href="clustering.html"><i class="fa fa-check"></i><b>9</b> Clustering</a>
<ul>
<li class="chapter" data-level="9.1" data-path="clustering.html"><a href="clustering.html#overview-8"><i class="fa fa-check"></i><b>9.1</b> Overview</a></li>
<li class="chapter" data-level="9.2" data-path="clustering.html"><a href="clustering.html#chapter-learning-objectives-8"><i class="fa fa-check"></i><b>9.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="9.3" data-path="clustering.html"><a href="clustering.html#clustering-1"><i class="fa fa-check"></i><b>9.3</b> Clustering</a></li>
<li class="chapter" data-level="9.4" data-path="clustering.html"><a href="clustering.html#k-means"><i class="fa fa-check"></i><b>9.4</b> K-means</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="clustering.html"><a href="clustering.html#measuring-cluster-quality"><i class="fa fa-check"></i><b>9.4.1</b> Measuring cluster quality</a></li>
<li class="chapter" data-level="9.4.2" data-path="clustering.html"><a href="clustering.html#the-clustering-algorithm"><i class="fa fa-check"></i><b>9.4.2</b> The clustering algorithm</a></li>
<li class="chapter" data-level="9.4.3" data-path="clustering.html"><a href="clustering.html#random-restarts"><i class="fa fa-check"></i><b>9.4.3</b> Random restarts</a></li>
<li class="chapter" data-level="9.4.4" data-path="clustering.html"><a href="clustering.html#choosing-k"><i class="fa fa-check"></i><b>9.4.4</b> Choosing K</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="clustering.html"><a href="clustering.html#data-pre-processing-for-k-means"><i class="fa fa-check"></i><b>9.5</b> Data pre-processing for K-means</a></li>
<li class="chapter" data-level="9.6" data-path="clustering.html"><a href="clustering.html#k-means-in-r"><i class="fa fa-check"></i><b>9.6</b> K-means in R</a></li>
<li class="chapter" data-level="9.7" data-path="clustering.html"><a href="clustering.html#exercises-8"><i class="fa fa-check"></i><b>9.7</b> Exercises</a></li>
<li class="chapter" data-level="9.8" data-path="clustering.html"><a href="clustering.html#additional-resources-5"><i class="fa fa-check"></i><b>9.8</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="inference.html"><a href="inference.html"><i class="fa fa-check"></i><b>10</b> Statistical inference</a>
<ul>
<li class="chapter" data-level="10.1" data-path="inference.html"><a href="inference.html#overview-9"><i class="fa fa-check"></i><b>10.1</b> Overview</a></li>
<li class="chapter" data-level="10.2" data-path="inference.html"><a href="inference.html#chapter-learning-objectives-9"><i class="fa fa-check"></i><b>10.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="10.3" data-path="inference.html"><a href="inference.html#why-do-we-need-sampling"><i class="fa fa-check"></i><b>10.3</b> Why do we need sampling?</a></li>
<li class="chapter" data-level="10.4" data-path="inference.html"><a href="inference.html#sampling-distributions"><i class="fa fa-check"></i><b>10.4</b> Sampling distributions</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="inference.html"><a href="inference.html#sampling-distributions-for-proportions"><i class="fa fa-check"></i><b>10.4.1</b> Sampling distributions for proportions</a></li>
<li class="chapter" data-level="10.4.2" data-path="inference.html"><a href="inference.html#sampling-distributions-for-means"><i class="fa fa-check"></i><b>10.4.2</b> Sampling distributions for means</a></li>
<li class="chapter" data-level="10.4.3" data-path="inference.html"><a href="inference.html#summary-2"><i class="fa fa-check"></i><b>10.4.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="inference.html"><a href="inference.html#bootstrapping"><i class="fa fa-check"></i><b>10.5</b> Bootstrapping</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="inference.html"><a href="inference.html#overview-10"><i class="fa fa-check"></i><b>10.5.1</b> Overview</a></li>
<li class="chapter" data-level="10.5.2" data-path="inference.html"><a href="inference.html#bootstrapping-in-r"><i class="fa fa-check"></i><b>10.5.2</b> Bootstrapping in R</a></li>
<li class="chapter" data-level="10.5.3" data-path="inference.html"><a href="inference.html#using-the-bootstrap-to-calculate-a-plausible-range"><i class="fa fa-check"></i><b>10.5.3</b> Using the bootstrap to calculate a plausible range</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="inference.html"><a href="inference.html#exercises-9"><i class="fa fa-check"></i><b>10.6</b> Exercises</a></li>
<li class="chapter" data-level="10.7" data-path="inference.html"><a href="inference.html#additional-resources-6"><i class="fa fa-check"></i><b>10.7</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html"><i class="fa fa-check"></i><b>11</b> Combining code and text with Jupyter</a>
<ul>
<li class="chapter" data-level="11.1" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#overview-11"><i class="fa fa-check"></i><b>11.1</b> Overview</a></li>
<li class="chapter" data-level="11.2" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#chapter-learning-objectives-10"><i class="fa fa-check"></i><b>11.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="11.3" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#jupyter"><i class="fa fa-check"></i><b>11.3</b> Jupyter</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#accessing-jupyter"><i class="fa fa-check"></i><b>11.3.1</b> Accessing Jupyter</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#code-cells"><i class="fa fa-check"></i><b>11.4</b> Code cells</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#executing-code-cells"><i class="fa fa-check"></i><b>11.4.1</b> Executing code cells</a></li>
<li class="chapter" data-level="11.4.2" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#the-kernel"><i class="fa fa-check"></i><b>11.4.2</b> The Kernel</a></li>
<li class="chapter" data-level="11.4.3" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#creating-new-code-cells"><i class="fa fa-check"></i><b>11.4.3</b> Creating new code cells</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#markdown-cells"><i class="fa fa-check"></i><b>11.5</b> Markdown cells</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#editing-markdown-cells"><i class="fa fa-check"></i><b>11.5.1</b> Editing Markdown cells</a></li>
<li class="chapter" data-level="11.5.2" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#creating-new-markdown-cells"><i class="fa fa-check"></i><b>11.5.2</b> Creating new Markdown cells</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#saving-your-work"><i class="fa fa-check"></i><b>11.6</b> Saving your work</a></li>
<li class="chapter" data-level="11.7" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#best-practices-for-running-a-notebook"><i class="fa fa-check"></i><b>11.7</b> Best practices for running a notebook</a>
<ul>
<li class="chapter" data-level="11.7.1" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#best-practices-for-executing-code-cells"><i class="fa fa-check"></i><b>11.7.1</b> Best practices for executing code cells</a></li>
<li class="chapter" data-level="11.7.2" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#best-practices-for-including-r-packages-in-notebooks"><i class="fa fa-check"></i><b>11.7.2</b> Best practices for including R packages in notebooks</a></li>
<li class="chapter" data-level="11.7.3" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#summary-of-best-practices-for-running-a-notebook"><i class="fa fa-check"></i><b>11.7.3</b> Summary of best practices for running a notebook</a></li>
</ul></li>
<li class="chapter" data-level="11.8" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#exploring-data-files"><i class="fa fa-check"></i><b>11.8</b> Exploring data files</a></li>
<li class="chapter" data-level="11.9" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#exporting-to-a-different-file-format"><i class="fa fa-check"></i><b>11.9</b> Exporting to a different file format</a>
<ul>
<li class="chapter" data-level="11.9.1" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#exporting-to-html"><i class="fa fa-check"></i><b>11.9.1</b> Exporting to HTML</a></li>
<li class="chapter" data-level="11.9.2" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#exporting-to-pdf"><i class="fa fa-check"></i><b>11.9.2</b> Exporting to PDF</a></li>
</ul></li>
<li class="chapter" data-level="11.10" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#creating-a-new-jupyter-notebook"><i class="fa fa-check"></i><b>11.10</b> Creating a new Jupyter notebook</a></li>
<li class="chapter" data-level="11.11" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#additional-resources-7"><i class="fa fa-check"></i><b>11.11</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html"><i class="fa fa-check"></i><b>12</b> Collaboration with version control</a>
<ul>
<li class="chapter" data-level="12.1" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#overview-12"><i class="fa fa-check"></i><b>12.1</b> Overview</a></li>
<li class="chapter" data-level="12.2" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#chapter-learning-objectives-11"><i class="fa fa-check"></i><b>12.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="12.3" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#what-is-version-control-and-why-should-i-use-it"><i class="fa fa-check"></i><b>12.3</b> What is version control, and why should I use it?</a></li>
<li class="chapter" data-level="12.4" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#version-control-repositories"><i class="fa fa-check"></i><b>12.4</b> Version control repositories</a></li>
<li class="chapter" data-level="12.5" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#version-control-workflows"><i class="fa fa-check"></i><b>12.5</b> Version control workflows</a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#commit-changes"><i class="fa fa-check"></i><b>12.5.1</b> Committing changes to a local repository</a></li>
<li class="chapter" data-level="12.5.2" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#pushing-changes-to-a-remote-repository"><i class="fa fa-check"></i><b>12.5.2</b> Pushing changes to a remote repository</a></li>
<li class="chapter" data-level="12.5.3" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#pulling-changes-from-a-remote-repository"><i class="fa fa-check"></i><b>12.5.3</b> Pulling changes from a remote repository</a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#working-with-remote-repositories-using-github"><i class="fa fa-check"></i><b>12.6</b> Working with remote repositories using GitHub</a>
<ul>
<li class="chapter" data-level="12.6.1" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#creating-a-remote-repository-on-github"><i class="fa fa-check"></i><b>12.6.1</b> Creating a remote repository on GitHub</a></li>
<li class="chapter" data-level="12.6.2" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#editing-files-on-github-with-the-pen-tool"><i class="fa fa-check"></i><b>12.6.2</b> Editing files on GitHub with the pen tool</a></li>
<li class="chapter" data-level="12.6.3" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#creating-files-on-github-with-the-add-file-menu"><i class="fa fa-check"></i><b>12.6.3</b> Creating files on GitHub with the “Add file” menu</a></li>
</ul></li>
<li class="chapter" data-level="12.7" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#local-repo-jupyter"><i class="fa fa-check"></i><b>12.7</b> Working with local repositories using Jupyter</a>
<ul>
<li class="chapter" data-level="12.7.1" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#generating-a-github-personal-access-token"><i class="fa fa-check"></i><b>12.7.1</b> Generating a GitHub personal access token</a></li>
<li class="chapter" data-level="12.7.2" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#cloning-a-repository-using-jupyter"><i class="fa fa-check"></i><b>12.7.2</b> Cloning a repository using Jupyter</a></li>
<li class="chapter" data-level="12.7.3" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#specifying-files-to-commit"><i class="fa fa-check"></i><b>12.7.3</b> Specifying files to commit</a></li>
<li class="chapter" data-level="12.7.4" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#making-the-commit"><i class="fa fa-check"></i><b>12.7.4</b> Making the commit</a></li>
<li class="chapter" data-level="12.7.5" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#pushing-the-commits-to-github"><i class="fa fa-check"></i><b>12.7.5</b> Pushing the commits to GitHub</a></li>
</ul></li>
<li class="chapter" data-level="12.8" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#collaboration"><i class="fa fa-check"></i><b>12.8</b> Collaboration</a>
<ul>
<li class="chapter" data-level="12.8.1" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#giving-collaborators-access-to-your-project"><i class="fa fa-check"></i><b>12.8.1</b> Giving collaborators access to your project</a></li>
<li class="chapter" data-level="12.8.2" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#pulling-changes-from-github-using-jupyter"><i class="fa fa-check"></i><b>12.8.2</b> Pulling changes from GitHub using Jupyter</a></li>
<li class="chapter" data-level="12.8.3" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#handling-merge-conflicts"><i class="fa fa-check"></i><b>12.8.3</b> Handling merge conflicts</a></li>
<li class="chapter" data-level="12.8.4" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#communicating-using-github-issues"><i class="fa fa-check"></i><b>12.8.4</b> Communicating using GitHub issues</a></li>
</ul></li>
<li class="chapter" data-level="12.9" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#exercises-10"><i class="fa fa-check"></i><b>12.9</b> Exercises</a></li>
<li class="chapter" data-level="12.10" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#vc-add-res"><i class="fa fa-check"></i><b>12.10</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html"><i class="fa fa-check"></i><b>13</b> Setting up your computer</a>
<ul>
<li class="chapter" data-level="13.1" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#overview-13"><i class="fa fa-check"></i><b>13.1</b> Overview</a></li>
<li class="chapter" data-level="13.2" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#chapter-learning-objectives-12"><i class="fa fa-check"></i><b>13.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="13.3" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#installing-software-on-your-own-computer"><i class="fa fa-check"></i><b>13.3</b> Installing software on your own computer</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#git"><i class="fa fa-check"></i><b>13.3.1</b> Git</a></li>
<li class="chapter" data-level="13.3.2" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#miniconda"><i class="fa fa-check"></i><b>13.3.2</b> Miniconda</a></li>
<li class="chapter" data-level="13.3.3" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#jupyterlab"><i class="fa fa-check"></i><b>13.3.3</b> JupyterLab</a></li>
<li class="chapter" data-level="13.3.4" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#r-and-the-irkernel"><i class="fa fa-check"></i><b>13.3.4</b> R and the IRkernel</a></li>
<li class="chapter" data-level="13.3.5" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#r-packages"><i class="fa fa-check"></i><b>13.3.5</b> R packages</a></li>
<li class="chapter" data-level="13.3.6" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#latex"><i class="fa fa-check"></i><b>13.3.6</b> LaTeX</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#finishing-up-installation"><i class="fa fa-check"></i><b>13.4</b> Finishing up installation</a></li>
<li class="chapter" data-level="13.5" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#downloading-the-worksheets-for-this-book"><i class="fa fa-check"></i><b>13.5</b> Downloading the worksheets for this book</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="appendixA.html"><a href="appendixA.html"><i class="fa fa-check"></i><b>A</b> Downloading files from JupyterHub</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Science: A First Introduction</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="classification" class="section level1" number="5">
<h1><span class="header-section-number">Chapter 5</span> Classification I: training &amp; predicting</h1>
<div id="overview-4" class="section level2" number="5.1">
<h2><span class="header-section-number">5.1</span> Overview</h2>
<p>In previous chapters, we focused solely on descriptive and exploratory
data analysis questions.
This chapter and the next together serve as our first
foray into answering <em>predictive</em> questions about data. In particular, we will
focus on <em>classification</em>, i.e., using one or more
variables to predict the value of a categorical variable of interest. This chapter
will cover the basics of classification, how to preprocess data to make it
suitable for use in a classifier, and how to use our observed data to make
predictions. The next chapter will focus on how to evaluate how accurate the
predictions from our classifier are, as well as how to improve our classifier
(where possible) to maximize its accuracy.</p>
</div>
<div id="chapter-learning-objectives-4" class="section level2" number="5.2">
<h2><span class="header-section-number">5.2</span> Chapter learning objectives</h2>
<p>By the end of the chapter, readers will be able to:</p>
<ul>
<li>Recognize situations where a classifier would be appropriate for making predictions</li>
<li>Describe what a training data set is and how it is used in classification</li>
<li>Interpret the output of a classifier</li>
<li>Compute, by hand, the straight-line (Euclidean) distance between points on a graph when there are two predictor variables</li>
<li>Explain the <span class="math inline">\(K\)</span>-nearest neighbor classification algorithm</li>
<li>Perform <span class="math inline">\(K\)</span>-nearest neighbor classification in R using <code>tidymodels</code><br />
</li>
<li>Use a <code>recipe</code> to preprocess data to be centered, scaled, and balanced</li>
<li>Combine preprocessing and model training using a <code>workflow</code></li>
</ul>
</div>
<div id="the-classification-problem" class="section level2" number="5.3">
<h2><span class="header-section-number">5.3</span> The classification problem</h2>
<p>In many situations, we want to make predictions  based on the current situation
as well as past experiences. For instance, a doctor may want to diagnose a
patient as either diseased or healthy based on their symptoms and the doctor’s
past experience with patients; an email provider might want to tag a given
email as “spam” or “not spam” based on the email’s text and past email text data;
or a credit card company may want to predict whether a purchase is fraudulent based
on the current purchase item, amount, and location as well as past purchases.
These tasks are all examples of  <strong>classification</strong>, i.e., predicting a
categorical class (sometimes called a <em>label</em>)  for an observation given its
other variables (sometimes called <em>features</em>). </p>
<p>Generally, a classifier assigns an observation without a known class (e.g., a new patient)
to a class (e.g., diseased or healthy) on the basis of how similar it is to other observations
for which we do know the class (e.g., previous patients with known diseases and
symptoms). These observations with known classes that we use as a basis for
prediction are called a <strong>training set</strong>;  this name comes from the fact that
we use these data to train, or teach, our classifier. Once taught, we can use
the classifier to make predictions on new data for which we do not know the class.</p>
<p>There are many possible methods that we could use to predict
a categorical class/label for an observation. In this book, we will
focus on the widely used <strong><span class="math inline">\(K\)</span>-nearest neighbors</strong>  algorithm.
In your future studies, you might encounter decision trees, support vector machines (SVMs),
logistic regression, neural networks, and more; see the additional resources
section at the end of the next chapter for where to begin learning more about
these other methods. It is also worth mentioning that there are many
variations on the basic classification problem. For example,
we focus on the setting of <strong>binary classification</strong>  where only two
classes are involved (e.g., a diagnosis of either healthy or diseased), but you may
also run into multiclass classification problems with more than two
categories (e.g., a diagnosis of healthy, bronchitis, pneumonia, or a common cold).</p>
</div>
<div id="exploring-a-data-set" class="section level2" number="5.4">
<h2><span class="header-section-number">5.4</span> Exploring a data set</h2>
<p>In this chapter and the next, we will study a data set of
<a href="http://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+%28Diagnostic%29">digitized breast cancer image features</a>,
created by Dr. William H. Wolberg, W. Nick Street, and Olvi L. Mangasarian at
the University of Wisconsin, Madison.  Each row in the data set represents an
image of a tumor sample, including the diagnosis (benign or malignant) and
several other measurements (nucleus texture, perimeter, area, and more).
Diagnosis for each image was conducted by physicians.</p>
<p>As with all data analyses, we first need to formulate a precise question that
we want to answer. Here, the question is <em>predictive</em>:  can
we use the tumor
image measurements available to us to predict whether a future tumor image
(with unknown diagnosis) shows a benign or malignant tumor? Answering this
question is important because traditional, non-data-driven methods for tumor
diagnosis are quite subjective and dependent upon how skilled and experienced
the diagnosing physician is. Furthermore, benign tumors are not normally
dangerous; the cells stay in the same place, and the tumor stops growing before
it gets very large. By contrast, in malignant tumors, the cells invade the
surrounding tissue and spread into nearby organs, where they can cause serious
damage (<span class="citation"><a href="#ref-stanfordhealthcare" role="doc-biblioref">Stanford Health Care</a> (<a href="#ref-stanfordhealthcare" role="doc-biblioref">2021</a>)</span>).
Thus, it is important to quickly and accurately diagnose the tumor type to
guide patient treatment.</p>
<div id="loading-the-cancer-data" class="section level3" number="5.4.1">
<h3><span class="header-section-number">5.4.1</span> Loading the cancer data</h3>
<p>Our first step is to load, wrangle, and explore the data using visualizations
in order to better understand the data we are working with. We start by
loading the <code>tidyverse</code> package needed for our analysis.</p>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb255-1"><a href="classification.html#cb255-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<p>In this case, the file containing the breast cancer data set is a <code>.csv</code>
file with headers. We’ll use the <code>read_csv</code> function with no additional
arguments, and then inspect its contents:</p>
<p></p>
<div class="sourceCode" id="cb256"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb256-1"><a href="classification.html#cb256-1" aria-hidden="true" tabindex="-1"></a>cancer <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/wdbc.csv&quot;</span>)</span>
<span id="cb256-2"><a href="classification.html#cb256-2" aria-hidden="true" tabindex="-1"></a>cancer</span></code></pre></div>
<pre><code>## # A tibble: 569 × 12
##        ID Class Radius Texture Perimeter   Area Smoothness Compactness Concavity
##     &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;       &lt;dbl&gt;     &lt;dbl&gt;
##  1 8.42e5 M      1.10   -2.07     1.27    0.984      1.57       3.28      2.65  
##  2 8.43e5 M      1.83   -0.353    1.68    1.91      -0.826     -0.487    -0.0238
##  3 8.43e7 M      1.58    0.456    1.57    1.56       0.941      1.05      1.36  
##  4 8.43e7 M     -0.768   0.254   -0.592  -0.764      3.28       3.40      1.91  
##  5 8.44e7 M      1.75   -1.15     1.78    1.82       0.280      0.539     1.37  
##  6 8.44e5 M     -0.476  -0.835   -0.387  -0.505      2.24       1.24      0.866 
##  7 8.44e5 M      1.17    0.161    1.14    1.09      -0.123      0.0882    0.300 
##  8 8.45e7 M     -0.118   0.358   -0.0728 -0.219      1.60       1.14      0.0610
##  9 8.45e5 M     -0.320   0.588   -0.184  -0.384      2.20       1.68      1.22  
## 10 8.45e7 M     -0.473   1.10    -0.329  -0.509      1.58       2.56      1.74  
## # … with 559 more rows, and 3 more variables: Concave_Points &lt;dbl&gt;,
## #   Symmetry &lt;dbl&gt;, Fractal_Dimension &lt;dbl&gt;</code></pre>
</div>
<div id="describing-the-variables-in-the-cancer-data-set" class="section level3" number="5.4.2">
<h3><span class="header-section-number">5.4.2</span> Describing the variables in the cancer data set</h3>
<p>Breast tumors can be diagnosed by performing a <em>biopsy</em>, a process where
tissue is removed from the body and examined for the presence of disease.
Traditionally these procedures were quite invasive; modern methods such as fine
needle aspiration, used to collect the present data set, extract only a small
amount of tissue and are less invasive. Based on a digital image of each breast
tissue sample collected for this data set, ten different variables were measured
for each cell nucleus in the image (items 3-12 of the list of variables below), and then the mean
for each variable across the nuclei was recorded. As part of the
data preparation, these values have been <em>standardized (centered and scaled)</em>; we will discuss what this
means and why we do it later in this chapter. Each image additionally was given
a unique ID and a diagnosis by a physician. Therefore, the
total set of variables per image in this data set is:</p>
<ol style="list-style-type: decimal">
<li>ID: identification number</li>
<li>Class: the diagnosis (M = malignant or B = benign)</li>
<li>Radius: the mean of distances from center to points on the perimeter</li>
<li>Texture: the standard deviation of gray-scale values</li>
<li>Perimeter: the length of the surrounding contour</li>
<li>Area: the area inside the contour</li>
<li>Smoothness: the local variation in radius lengths</li>
<li>Compactness: the ratio of squared perimeter and area</li>
<li>Concavity: severity of concave portions of the contour</li>
<li>Concave Points: the number of concave portions of the contour</li>
<li>Symmetry: how similar the nucleus is when mirrored</li>
<li>Fractal Dimension: a measurement of how “rough” the perimeter is</li>
</ol>
<p>Below we use <code>glimpse</code>  to preview the data frame. This function can
make it easier to inspect the data when we have a lot of columns,
as it prints the data such that the columns go down
the page (instead of across).</p>
<div class="sourceCode" id="cb258"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb258-1"><a href="classification.html#cb258-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(cancer)</span></code></pre></div>
<pre><code>## Rows: 569
## Columns: 12
## $ ID                &lt;dbl&gt; 842302, 842517, 84300903, 84348301, 84358402, 843786…
## $ Class             &lt;chr&gt; &quot;M&quot;, &quot;M&quot;, &quot;M&quot;, &quot;M&quot;, &quot;M&quot;, &quot;M&quot;, &quot;M&quot;, &quot;M&quot;, &quot;M&quot;, &quot;M&quot;, &quot;M…
## $ Radius            &lt;dbl&gt; 1.0960995, 1.8282120, 1.5784992, -0.7682333, 1.74875…
## $ Texture           &lt;dbl&gt; -2.0715123, -0.3533215, 0.4557859, 0.2535091, -1.150…
## $ Perimeter         &lt;dbl&gt; 1.26881726, 1.68447255, 1.56512598, -0.59216612, 1.7…
## $ Area              &lt;dbl&gt; 0.98350952, 1.90703027, 1.55751319, -0.76379174, 1.8…
## $ Smoothness        &lt;dbl&gt; 1.56708746, -0.82623545, 0.94138212, 3.28066684, 0.2…
## $ Compactness       &lt;dbl&gt; 3.28062806, -0.48664348, 1.05199990, 3.39991742, 0.5…
## $ Concavity         &lt;dbl&gt; 2.65054179, -0.02382489, 1.36227979, 1.91421287, 1.3…
## $ Concave_Points    &lt;dbl&gt; 2.53024886, 0.54766227, 2.03543978, 1.45043113, 1.42…
## $ Symmetry          &lt;dbl&gt; 2.215565542, 0.001391139, 0.938858720, 2.864862154, …
## $ Fractal_Dimension &lt;dbl&gt; 2.25376381, -0.86788881, -0.39765801, 4.90660199, -0…</code></pre>
<p>From the summary of the data above, we can see that <code>Class</code> is of type character
(denoted by <code>&lt;chr&gt;</code>). Since we will be working with <code>Class</code> as a
categorical statistical variable, we will convert it to a factor using the
function <code>as_factor</code>. </p>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb260-1"><a href="classification.html#cb260-1" aria-hidden="true" tabindex="-1"></a>cancer <span class="ot">&lt;-</span> cancer <span class="sc">|&gt;</span></span>
<span id="cb260-2"><a href="classification.html#cb260-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Class =</span> <span class="fu">as_factor</span>(Class))</span>
<span id="cb260-3"><a href="classification.html#cb260-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(cancer)</span></code></pre></div>
<pre><code>## Rows: 569
## Columns: 12
## $ ID                &lt;dbl&gt; 842302, 842517, 84300903, 84348301, 84358402, 843786…
## $ Class             &lt;fct&gt; M, M, M, M, M, M, M, M, M, M, M, M, M, M, M, M, M, M…
## $ Radius            &lt;dbl&gt; 1.0960995, 1.8282120, 1.5784992, -0.7682333, 1.74875…
## $ Texture           &lt;dbl&gt; -2.0715123, -0.3533215, 0.4557859, 0.2535091, -1.150…
## $ Perimeter         &lt;dbl&gt; 1.26881726, 1.68447255, 1.56512598, -0.59216612, 1.7…
## $ Area              &lt;dbl&gt; 0.98350952, 1.90703027, 1.55751319, -0.76379174, 1.8…
## $ Smoothness        &lt;dbl&gt; 1.56708746, -0.82623545, 0.94138212, 3.28066684, 0.2…
## $ Compactness       &lt;dbl&gt; 3.28062806, -0.48664348, 1.05199990, 3.39991742, 0.5…
## $ Concavity         &lt;dbl&gt; 2.65054179, -0.02382489, 1.36227979, 1.91421287, 1.3…
## $ Concave_Points    &lt;dbl&gt; 2.53024886, 0.54766227, 2.03543978, 1.45043113, 1.42…
## $ Symmetry          &lt;dbl&gt; 2.215565542, 0.001391139, 0.938858720, 2.864862154, …
## $ Fractal_Dimension &lt;dbl&gt; 2.25376381, -0.86788881, -0.39765801, 4.90660199, -0…</code></pre>
<p>Recall factors have what are called “levels,” which you can think of as categories. We
can verify the levels of the <code>Class</code> column by using the <code>levels</code>  function.
This function should return the name of each category in that column. Given
that we only have two different values in our <code>Class</code> column (B for benign and M
for malignant), we only expect to get two names back. Note that the <code>levels</code> function requires a <em>vector</em> argument;
so we use the <code>pull</code> function to extract a single column (<code>Class</code>) and
pass that into the <code>levels</code> function to see the categories
in the <code>Class</code> column.</p>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb262-1"><a href="classification.html#cb262-1" aria-hidden="true" tabindex="-1"></a>cancer <span class="sc">|&gt;</span></span>
<span id="cb262-2"><a href="classification.html#cb262-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(Class) <span class="sc">|&gt;</span></span>
<span id="cb262-3"><a href="classification.html#cb262-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">levels</span>()</span></code></pre></div>
<pre><code>## [1] &quot;M&quot; &quot;B&quot;</code></pre>
</div>
<div id="exploring-the-cancer-data" class="section level3" number="5.4.3">
<h3><span class="header-section-number">5.4.3</span> Exploring the cancer data</h3>
<p>Before we start doing any modeling, let’s explore our data set. Below we use
the <code>group_by</code>, <code>summarize</code> and <code>n</code>  functions to find the number and percentage
of benign and malignant tumor observations in our data set. The <code>n</code> function within
<code>summarize</code> when paired with <code>group_by</code> counts the number of observations in each <code>Class</code> group.
Then we calculate the percentage in each group by dividing by the total number of observations. We have 357 (63%) benign and 212 (37%) malignant tumor observations.</p>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb264-1"><a href="classification.html#cb264-1" aria-hidden="true" tabindex="-1"></a>num_obs <span class="ot">&lt;-</span> <span class="fu">nrow</span>(cancer)</span>
<span id="cb264-2"><a href="classification.html#cb264-2" aria-hidden="true" tabindex="-1"></a>cancer <span class="sc">|&gt;</span></span>
<span id="cb264-3"><a href="classification.html#cb264-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Class) <span class="sc">|&gt;</span></span>
<span id="cb264-4"><a href="classification.html#cb264-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb264-5"><a href="classification.html#cb264-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">count =</span> <span class="fu">n</span>(),</span>
<span id="cb264-6"><a href="classification.html#cb264-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">percentage =</span> <span class="fu">n</span>() <span class="sc">/</span> num_obs <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb264-7"><a href="classification.html#cb264-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 2 × 3
##   Class count percentage
##   &lt;fct&gt; &lt;int&gt;      &lt;dbl&gt;
## 1 M       212       37.3
## 2 B       357       62.7</code></pre>
<p>Next, let’s draw a scatter plot  to visualize the relationship between the
perimeter and concavity variables. Rather than use <code>ggplot's</code> default palette,
we select our own colorblind-friendly colors—<code>"orange2"</code>
for light orange and <code>"steelblue2"</code> for light blue—and
pass them as the <code>values</code> argument to the <code>scale_color_manual</code> function.
We also make the category labels (“B” and “M”) more readable by
changing them to “Benign” and “Malignant” using the <code>labels</code> argument.</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb266-1"><a href="classification.html#cb266-1" aria-hidden="true" tabindex="-1"></a>perim_concav <span class="ot">&lt;-</span> cancer <span class="sc">|&gt;</span></span>
<span id="cb266-2"><a href="classification.html#cb266-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Perimeter, <span class="at">y =</span> Concavity, <span class="at">color =</span> Class)) <span class="sc">+</span></span>
<span id="cb266-3"><a href="classification.html#cb266-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb266-4"><a href="classification.html#cb266-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Perimeter (standardized)&quot;</span>, </span>
<span id="cb266-5"><a href="classification.html#cb266-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Concavity (standardized)&quot;</span>,</span>
<span id="cb266-6"><a href="classification.html#cb266-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">&quot;Diagnosis&quot;</span>) <span class="sc">+</span></span>
<span id="cb266-7"><a href="classification.html#cb266-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Malignant&quot;</span>, <span class="st">&quot;Benign&quot;</span>), </span>
<span id="cb266-8"><a href="classification.html#cb266-8" aria-hidden="true" tabindex="-1"></a>                     <span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;orange2&quot;</span>, <span class="st">&quot;steelblue2&quot;</span>))</span>
<span id="cb266-9"><a href="classification.html#cb266-9" aria-hidden="true" tabindex="-1"></a>perim_concav</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:05-scatter"></span>
<img src="_main_files/figure-html/05-scatter-1.png" alt="Scatter plot of concavity versus perimeter colored by diagnosis label." width="432" />
<p class="caption">
Figure 5.1: Scatter plot of concavity versus perimeter colored by diagnosis label.
</p>
</div>
<p>In Figure <a href="classification.html#fig:05-scatter">5.1</a>, we can see that malignant observations typically fall in
the upper right-hand corner of the plot area. By contrast, benign
observations typically fall in the lower left-hand corner of the plot. In other words,
benign observations tend to have lower concavity and perimeter values, and malignant
ones tend to have larger values. Suppose we
obtain a new observation not in the current data set that has all the variables
measured <em>except</em> the label (i.e., an image without the physician’s diagnosis
for the tumor class). We could compute the standardized perimeter and concavity values,
resulting in values of, say, 1 and 1. Could we use this information to classify
that observation as benign or malignant? Based on the scatter plot, how might
you classify that new observation? If the standardized concavity and perimeter
values are 1 and 1 respectively, the point would lie in the middle of the
orange cloud of malignant points and thus we could probably classify it as
malignant. Based on our visualization, it seems like
the <em>prediction of an unobserved label</em> might be possible.</p>
</div>
</div>
<div id="classification-with-k-nearest-neighbors" class="section level2" number="5.5">
<h2><span class="header-section-number">5.5</span> Classification with <span class="math inline">\(K\)</span>-nearest neighbors</h2>
<p>In order to actually make predictions for new observations in practice, we
will need a classification algorithm.
In this book, we will use the <span class="math inline">\(K\)</span>-nearest neighbors  classification algorithm.
To predict the label of a new observation (here, classify it as either benign
or malignant), the <span class="math inline">\(K\)</span>-nearest neighbors classifier generally finds the <span class="math inline">\(K\)</span>
“nearest” or “most similar” observations in our training set, and then uses
their diagnoses to make a prediction for the new observation’s diagnosis. <span class="math inline">\(K\)</span>
is a number that we must choose in advance; for now, we will assume that someone has chosen
<span class="math inline">\(K\)</span> for us. We will cover how to choose <span class="math inline">\(K\)</span> ourselves in the next chapter.</p>
<p>To illustrate the concept of <span class="math inline">\(K\)</span>-nearest neighbors classification, we
will walk through an example. Suppose we have a
new observation, with standardized perimeter of 2 and standardized concavity of 4, whose
diagnosis “Class” is unknown. This new observation is depicted by the red, diamond point in
Figure <a href="classification.html#fig:05-knn-1">5.2</a>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:05-knn-1"></span>
<img src="_main_files/figure-html/05-knn-1-1.png" alt="Scatter plot of concavity versus perimeter with new observation represented as a red diamond." width="432" />
<p class="caption">
Figure 5.2: Scatter plot of concavity versus perimeter with new observation represented as a red diamond.
</p>
</div>
<p>Figure <a href="classification.html#fig:05-knn-2">5.3</a> shows that the nearest point to this new observation is <strong>malignant</strong> and
located at the coordinates (2.1, 3.6). The idea here is that if a point is close to another in the scatter plot,
then the perimeter and concavity values are similar, and so we may expect that
they would have the same diagnosis.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:05-knn-2"></span>
<img src="_main_files/figure-html/05-knn-2-1.png" alt="Scatter plot of concavity versus perimeter. The new observation is represented as a red diamond with a line to the one nearest neighbor, which has a malignant label." width="432" />
<p class="caption">
Figure 5.3: Scatter plot of concavity versus perimeter. The new observation is represented as a red diamond with a line to the one nearest neighbor, which has a malignant label.
</p>
</div>
<p>Suppose we have another new observation with standardized perimeter 0.2 and
concavity of 3.3. Looking at the scatter plot in Figure <a href="classification.html#fig:05-knn-4">5.4</a>, how would you
classify this red, diamond observation? The nearest neighbor to this new point is a
<strong>benign</strong> observation at (0.2, 2.7).
Does this seem like the right prediction to make for this observation? Probably
not, if you consider the other nearby points…</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:05-knn-4"></span>
<img src="_main_files/figure-html/05-knn-4-1.png" alt="Scatter plot of concavity versus perimeter. The new observation is represented as a red diamond with a line to the one nearest neighbor, which has a benign label." width="432" />
<p class="caption">
Figure 5.4: Scatter plot of concavity versus perimeter. The new observation is represented as a red diamond with a line to the one nearest neighbor, which has a benign label.
</p>
</div>
<p>To improve the prediction we can consider several
neighboring points, say <span class="math inline">\(K = 3\)</span>, that are closest to the new observation
to predict its diagnosis class. Among those 3 closest points, we use the
<em>majority class</em> as our prediction for the new observation. As shown in Figure <a href="classification.html#fig:05-knn-5">5.5</a>, we
see that the diagnoses of 2 of the 3 nearest neighbors to our new observation
are malignant. Therefore we take majority vote and classify our new red, diamond
observation as malignant.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:05-knn-5"></span>
<img src="_main_files/figure-html/05-knn-5-1.png" alt="Scatter plot of concavity versus perimeter with three nearest neighbors." width="432" />
<p class="caption">
Figure 5.5: Scatter plot of concavity versus perimeter with three nearest neighbors.
</p>
</div>
<p>Here we chose the <span class="math inline">\(K=3\)</span> nearest observations, but there is nothing special
about <span class="math inline">\(K=3\)</span>. We could have used <span class="math inline">\(K=4, 5\)</span> or more (though we may want to choose
an odd number to avoid ties). We will discuss more about choosing <span class="math inline">\(K\)</span> in the
next chapter.</p>
<div id="distance-between-points" class="section level3" number="5.5.1">
<h3><span class="header-section-number">5.5.1</span> Distance between points</h3>
<p>We decide which points are the <span class="math inline">\(K\)</span> “nearest” to our new observation
using the <em>straight-line distance</em> (we will often just refer to this as <em>distance</em>). 
Suppose we have two observations <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>, each having two predictor variables, <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>.
Denote <span class="math inline">\(a_x\)</span> and <span class="math inline">\(a_y\)</span> to be the values of variables <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> for observation <span class="math inline">\(a\)</span>;
<span class="math inline">\(b_x\)</span> and <span class="math inline">\(b_y\)</span> have similar definitions for observation <span class="math inline">\(b\)</span>.
Then the straight-line distance between observation <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> on the x-y plane can
be computed using the following formula:</p>
<p><span class="math display">\[\mathrm{Distance} = \sqrt{(a_x -b_x)^2 + (a_y - b_y)^2}\]</span></p>
<p>To find the <span class="math inline">\(K\)</span> nearest neighbors to our new observation, we compute the distance
from that new observation to each observation in our training data, and select the <span class="math inline">\(K\)</span> observations corresponding to the
<span class="math inline">\(K\)</span> <em>smallest</em> distance values. For example, suppose we want to use <span class="math inline">\(K=5\)</span> neighbors to classify a new
observation with perimeter of 0 and
concavity of 3.5, shown as a red diamond in Figure <a href="classification.html#fig:05-multiknn-1">5.6</a>. Let’s calculate the distances
between our new point and each of the observations in the training set to find
the <span class="math inline">\(K=5\)</span> neighbors that are nearest to our new point.
You will see in the <code>mutate</code>  step below, we compute the straight-line
distance using the formula above: we square the differences between the two observations’ perimeter
and concavity coordinates, add the squared differences, and then take the square root.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:05-multiknn-1"></span>
<img src="_main_files/figure-html/05-multiknn-1-1.png" alt="Scatter plot of concavity versus perimeter with new observation represented as a red diamond." width="432" />
<p class="caption">
Figure 5.6: Scatter plot of concavity versus perimeter with new observation represented as a red diamond.
</p>
</div>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb267-1"><a href="classification.html#cb267-1" aria-hidden="true" tabindex="-1"></a>new_obs_Perimeter <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb267-2"><a href="classification.html#cb267-2" aria-hidden="true" tabindex="-1"></a>new_obs_Concavity <span class="ot">&lt;-</span> <span class="fl">3.5</span></span>
<span id="cb267-3"><a href="classification.html#cb267-3" aria-hidden="true" tabindex="-1"></a>cancer <span class="sc">|&gt;</span></span>
<span id="cb267-4"><a href="classification.html#cb267-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ID, Perimeter, Concavity, Class) <span class="sc">|&gt;</span></span>
<span id="cb267-5"><a href="classification.html#cb267-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">dist_from_new =</span> <span class="fu">sqrt</span>((Perimeter <span class="sc">-</span> new_obs_Perimeter)<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> </span>
<span id="cb267-6"><a href="classification.html#cb267-6" aria-hidden="true" tabindex="-1"></a>                              (Concavity <span class="sc">-</span> new_obs_Concavity)<span class="sc">^</span><span class="dv">2</span>)) <span class="sc">|&gt;</span></span>
<span id="cb267-7"><a href="classification.html#cb267-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(dist_from_new) <span class="sc">|&gt;</span></span>
<span id="cb267-8"><a href="classification.html#cb267-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>) <span class="co"># take the first 5 rows</span></span></code></pre></div>
<pre><code>## # A tibble: 5 × 5
##        ID Perimeter Concavity Class dist_from_new
##     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;fct&gt;         &lt;dbl&gt;
## 1   86409     0.241      2.65 B             0.881
## 2  887181     0.750      2.87 M             0.980
## 3  899667     0.623      2.54 M             1.14 
## 4  907914     0.417      2.31 M             1.26 
## 5 8710441    -1.16       4.04 B             1.28</code></pre>
<p>In Table <a href="classification.html#tab:05-multiknn-mathtable">5.1</a> we show in mathematical detail how
the <code>mutate</code> step was used to compute the <code>dist_from_new</code> variable (the
distance to the new observation) for each of the 5 nearest neighbors in the
training data.</p>
<table>
<caption><span id="tab:05-multiknn-mathtable">Table 5.1: </span>Evaluating the distances from the new observation to each of its 5 nearest neighbors</caption>
<thead>
<tr class="header">
<th align="right">Perimeter</th>
<th align="right">Concavity</th>
<th align="left">Distance</th>
<th align="left">Class</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.24</td>
<td align="right">2.65</td>
<td align="left"><span class="math inline">\(\sqrt{(0 - 0.24)^2 + (3.5 - 2.65)^2} = 0.88\)</span></td>
<td align="left">B</td>
</tr>
<tr class="even">
<td align="right">0.75</td>
<td align="right">2.87</td>
<td align="left"><span class="math inline">\(\sqrt{(0 - 0.75)^2 + (3.5 - 2.87)^2} = 0.98\)</span></td>
<td align="left">M</td>
</tr>
<tr class="odd">
<td align="right">0.62</td>
<td align="right">2.54</td>
<td align="left"><span class="math inline">\(\sqrt{(0 - 0.62)^2 + (3.5 - 2.54)^2} = 1.14\)</span></td>
<td align="left">M</td>
</tr>
<tr class="even">
<td align="right">0.42</td>
<td align="right">2.31</td>
<td align="left"><span class="math inline">\(\sqrt{(0 - 0.42)^2 + (3.5 - 2.31)^2} = 1.26\)</span></td>
<td align="left">M</td>
</tr>
<tr class="odd">
<td align="right">-1.16</td>
<td align="right">4.04</td>
<td align="left"><span class="math inline">\(\sqrt{(0 - (-1.16))^2 + (3.5 - 4.04)^2} = 1.28\)</span></td>
<td align="left">B</td>
</tr>
</tbody>
</table>
<p>The result of this computation shows that 3 of the 5 nearest neighbors to our new observation are
malignant (<code>M</code>); since this is the majority, we classify our new observation as malignant.
These 5 neighbors are circled in Figure <a href="classification.html#fig:05-multiknn-3">5.7</a>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:05-multiknn-3"></span>
<img src="_main_files/figure-html/05-multiknn-3-1.png" alt="Scatter plot of concavity versus perimeter with 5 nearest neighbors circled." width="432" />
<p class="caption">
Figure 5.7: Scatter plot of concavity versus perimeter with 5 nearest neighbors circled.
</p>
</div>
</div>
<div id="more-than-two-explanatory-variables" class="section level3" number="5.5.2">
<h3><span class="header-section-number">5.5.2</span> More than two explanatory variables</h3>
<p>Although the above description is directed toward two predictor variables,
exactly the same <span class="math inline">\(K\)</span>-nearest neighbors algorithm applies when you
have a higher number of predictor variables. Each predictor variable may give us new
information to help create our classifier. The only difference is the formula
for the distance between points. Suppose we have <span class="math inline">\(m\)</span> predictor
variables for two observations <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>, i.e.,
<span class="math inline">\(a = (a_{1}, a_{2}, \dots, a_{m})\)</span> and
<span class="math inline">\(b = (b_{1}, b_{2}, \dots, b_{m})\)</span>.</p>
<p>The distance formula becomes </p>
<p><span class="math display">\[\mathrm{Distance} = \sqrt{(a_{1} -b_{1})^2 + (a_{2} - b_{2})^2 + \dots + (a_{m} - b_{m})^2}.\]</span></p>
<p>This formula still corresponds to a straight-line distance, just in a space
with more dimensions. Suppose we want to calculate the distance between a new
observation with a perimeter of 0, concavity of 3.5 and symmetry of 1 and
another observation with a perimeter, concavity and symmetry of 0.417, 2.31 and
0.837 respectively. We have two observations with three predictor variables:
perimeter, concavity, and symmetry. Previously, when we had two variables, we
added up the squared difference between each of our (two) variables, and then
took the square root. Now we will do the same, except for our three variables.
We calculate the distance as follows</p>
<p><span class="math display">\[\mathrm{Distance} =\sqrt{(0 - 0.417)^2 + (3.5 - 2.31)^2 + (1 - 0.837)^2} = 1.27.\]</span></p>
<p>Let’s calculate the distances between our new observation and each of the
observations in the training set to find the <span class="math inline">\(K=5\)</span> neighbors when we have these
three predictors.</p>
<div class="sourceCode" id="cb269"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb269-1"><a href="classification.html#cb269-1" aria-hidden="true" tabindex="-1"></a>new_obs_Perimeter <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb269-2"><a href="classification.html#cb269-2" aria-hidden="true" tabindex="-1"></a>new_obs_Concavity <span class="ot">&lt;-</span> <span class="fl">3.5</span></span>
<span id="cb269-3"><a href="classification.html#cb269-3" aria-hidden="true" tabindex="-1"></a>new_obs_Symmetry <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb269-4"><a href="classification.html#cb269-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb269-5"><a href="classification.html#cb269-5" aria-hidden="true" tabindex="-1"></a>cancer <span class="sc">|&gt;</span></span>
<span id="cb269-6"><a href="classification.html#cb269-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ID, Perimeter, Concavity, Symmetry, Class) <span class="sc">|&gt;</span></span>
<span id="cb269-7"><a href="classification.html#cb269-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">dist_from_new =</span> <span class="fu">sqrt</span>((Perimeter <span class="sc">-</span> new_obs_Perimeter)<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> </span>
<span id="cb269-8"><a href="classification.html#cb269-8" aria-hidden="true" tabindex="-1"></a>                              (Concavity <span class="sc">-</span> new_obs_Concavity)<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span></span>
<span id="cb269-9"><a href="classification.html#cb269-9" aria-hidden="true" tabindex="-1"></a>                                (Symmetry <span class="sc">-</span> new_obs_Symmetry)<span class="sc">^</span><span class="dv">2</span>)) <span class="sc">|&gt;</span></span>
<span id="cb269-10"><a href="classification.html#cb269-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(dist_from_new) <span class="sc">|&gt;</span></span>
<span id="cb269-11"><a href="classification.html#cb269-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>) <span class="co"># take the first 5 rows</span></span></code></pre></div>
<pre><code>## # A tibble: 5 × 6
##         ID Perimeter Concavity Symmetry Class dist_from_new
##      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;fct&gt;         &lt;dbl&gt;
## 1   907914     0.417      2.31    0.837 M              1.27
## 2 90439701     1.33       2.89    1.10  M              1.47
## 3   925622     0.470      2.08    1.15  M              1.50
## 4   859471    -1.37       2.81    1.09  B              1.53
## 5   899667     0.623      2.54    2.06  M              1.56</code></pre>
<p>Based on <span class="math inline">\(K=5\)</span> nearest neighbors with these three predictors we would classify the new observation as malignant since 4 out of 5 of the nearest neighbors are malignant class.
Figure <a href="classification.html#fig:05-more">5.8</a> shows what the data look like when we visualize them
as a 3-dimensional scatter with lines from the new observation to its five nearest neighbors.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:05-more"></span>
<div id="htmlwidget-467f3ada599dec390e71" style="width:100%;height:480px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-467f3ada599dec390e71">{"x":{"visdat":{"724641a97":["function () ","plotlyVisDat"]},"cur_data":"724641a97","attrs":{"724641a97":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"x":{},"y":{},"z":{},"color":{},"opacity":0.4,"size":2,"colors":["orange2","steelblue2","red"],"symbol":{},"symbols":["circle","circle","diamond"],"inherit":true},"724641a97.1":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"x":[0,0.416929689023843],"y":[3.5,2.31436436154554],"z":[1,0.836722174162893],"type":"scatter3d","mode":"lines","name":"lines","showlegend":false,"color":["steelblue2"],"inherit":true},"724641a97.2":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"x":[0,1.33466364521046],"y":[3.5,2.8863677411207],"z":[1,1.09935900610259],"type":"scatter3d","mode":"lines","name":"lines","showlegend":false,"color":["steelblue2"],"inherit":true},"724641a97.3":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"x":[0,0.470429874810507],"y":[3.5,2.08481037368972],"z":[1,1.15407501275669],"type":"scatter3d","mode":"lines","name":"lines","showlegend":false,"color":["steelblue2"],"inherit":true},"724641a97.4":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"x":[0,-1.36544957745338],"y":[3.5,2.81235853192128],"z":[1,1.09206353854871],"type":"scatter3d","mode":"lines","name":"lines","showlegend":false,"color":["orange2"],"inherit":true},"724641a97.5":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"x":[0,0.622699634357164],"y":[3.5,2.54140956264884],"z":[1,2.05506525566093],"type":"scatter3d","mode":"lines","name":"lines","showlegend":false,"color":["steelblue2"],"inherit":true}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"scene":{"xaxis":{"title":"Perimeter"},"yaxis":{"title":"Concavity"},"zaxis":{"title":"Symmetry"}},"hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":[-0.185564710912121,-0.260876510904117,-1.30166089440005,-0.385161557885442,-1.65681982004537,-0.573235287920097,-0.208199404898786,-0.709866531621423,-0.195853208178787,-0.669124082445426,-0.766659036533419,-0.385161557885442,-1.54858482880004,-1.1284026004294,-1.53541555229871,-1.34857644193605,-1.31112631188539,-0.830036179696082,-1.36544957745338,-0.436192504328106,-1.36544957745338,-0.525908200493434,-0.167045415832122,-0.361292244226777,-0.747316661672087,-0.225484080306785,-0.618093136002762,-0.501627346944102,0.156424938231859,0.107040151351861,-0.297503561173448,-0.220957141509452,-0.583523785186764,-1.22881833375206,-0.725505047466755,-1.98275941345335,-0.606981558954762,-1.1530949938694,-1.01070219169874,-0.691347236541424,-0.533315918525433,-0.80205146713075,-1.21276827801606,-0.404092392856108,0.241202155709187,-0.960082785146741,-1.48685384520004,-0.635377811410761,-1.36750727690672,-0.766659036533419,0.0951054945225291,-0.241534136042784,-0.14523380162679,0.313221636575849,-0.530435139290767,0.412814290117177,-0.709866531621423,-0.778182153472085,-0.780651392816085,-1.26462230424006,-0.753489760032087,-0.338657550240112,-0.975721300992073,-0.570354508685431,0.241613695599854,0.0823477579118631,-0.158403078128122,-0.348122967725444,-1.59261959710137,-1.16009117201073,-0.86830938952808,-0.274045787405449,-0.563769870434765,0.676199820143828,-0.622620074800095,-0.958025085693408,-0.653074026709426,-0.498746567709436,0.145313361183859,-0.954732766568075,0.174944233311858,-0.5399005567761,-0.895471022312079,-1.00740987257341,-1.54529250967471,-1.12634490097606,-0.409853951325441,-0.439484823453439,-0.758839778610753,-1.16091425179206,-0.711512691184089,-0.687231837634758,-0.540723636557433,-0.409442411434774,-1.28561083866406,-0.388453877010775,-0.552658293386765,-0.447715621266772,-1.19548360260806,-0.203672466101453,0.255194511991853,-0.677354880258758,-0.602866160048096,-1.10782560589607,-0.168280035504122,-0.13906070326679,-1.1049448266614,-0.305322819096114,0.0222629338745336,-1.0432138430614,0.225563639863855,-0.437015584109439,-0.831682339258749,-0.871601708653413,-1.30701091297872,-0.089675916386793,0.0239090934371999,-0.188857030037454,-0.549777514152099,-0.742378182984087,-0.141118402720123,-1.03909844415474,-0.322607494504113,-0.288861223469448,-0.98600979825874,-0.744847422328087,-0.769128275877419,-0.933744232144076,-0.19791090763212,-0.394626975370775,-0.92469035454941,-0.0686873819627946,-0.812339964397417,-1.25392226708272,-0.64895862780276,-0.830447719586749,-0.235772577573451,-0.122599107640125,-0.729620446373422,-0.324665193957446,-0.499569647490769,-0.58023146606143,-0.41479243001344,-0.751020520688087,-0.814809203741417,0.167124975389191,0.208278964455856,-0.36334994368011,-0.676120260586758,-0.419319368810773,-0.160872317472122,-0.939505790613409,-0.0308257120214635,-1.03374842557607,-0.47487725405077,-1.0333368856854,-0.756370539266753,-0.730031986264088,-0.325076733848113,-1.46545377088538,-0.258407271560117,-0.381046158978776,-0.725916587357422,0.0292591120158666,-0.398330834386775,-0.75060898079742,-1.55887332606671,-0.525908200493434,-0.605746939282762,-1.31277247144805,-0.550189054042766,-1.04732924196807,-0.376519220181443,-0.574469907592097,-0.441130983016106,-0.0797989590107938,-0.653485566600093,-0.306557438768114,-0.824274621226749,-0.847320855104082,-0.579819926170764,-0.324665193957446,-1.13416415889873,0.0897554759438629,-1.24816070861339,-0.842793916306748,-0.697108795010757,-1.0604985184694,-0.630027792832094,0.119386348071861,-0.779828313034752,-0.606570019064095,-0.75184360046942,-0.853082413573415,-0.41355781034144,-0.283099665000115,-0.141941482501457,-1.44981525504005,-1.32306096871472,-0.516442783008101,-0.276926566640116,-0.415615509794774,0.602122639823832,-0.267049609264116,-0.562123710872098,0.233794437677188,-0.169926195066788,0.589776443103833,-0.897940261656078,-0.250176473746784,-0.152229979768123,-0.774066754565419,-0.876540187341413,-0.544015955682766,-0.466234916346771,-0.25429187265345,-0.542781336010766,-0.148114580861456,-0.765012876970753,-1.0790178135494,-1.51031161896804,-0.572000668248098,-0.0913220759494598,-0.159226157909456,-0.36705380269611,-0.891355623405412,-0.687643377525424,-0.65142786714676,-0.320549795050779,-0.361703784117443,-0.562946790653431,-0.888063304280079,0.507468464970504,-0.384338478104109,-0.558008311965432,-0.801639927240084,-0.866251690074747,-1.32594174794939,0.228855958989188,-0.641139369880094,-1.33211484630939,-0.456357958970772,-0.865017070402747,-0.731266605936088,0.257252211445186,-0.679412579712092,-0.103256732778793,-1.23622605178406,-1.18437202556006,-1.00740987257341,-0.953909686786741,-0.884770985154746,-0.452242560064105,-0.43207710542144,0.120209427853194,-0.382692318541442,-0.0900874562774598,-0.13535684425079,-0.0979067142001259,-0.832916958930749,-0.148114580861456,-1.03498304524807,-0.590931503218763,0.160951877029192,0.0938708748505291,-0.623031614690761,-0.625500854034761,0.0778208191145301,-0.467057996128104,-0.231657178666785,-0.703693433261423,-0.323842114176113,-0.385161557885442,-1.24651454905072,0.0115628967172007,-0.744435882437421,-0.316434396144113,-0.209845564461453,-0.246472614730784,-1.27203002227206,-0.64155090977076,-1.25433380697339,-0.622208534909428,0.18440965079719,-0.598750761141429,-0.887240224498746,-0.373638440946776,0.0181475349678668,-0.123422187421458,-0.739908943640088,-0.562946790653431,-0.133299144797457,-0.191326269381454,-0.173218514192121,0.445737481370508,-0.375284600509443,0.0922247152878623,-0.678177960040092,-0.567473729450764,0.931354552357146,-0.540723636557433,-0.325488273738779,0.170828834405191,-0.381869238760109,-0.474054174269437,0.278240745869185,-0.441130983016106,-1.25433380697339,-1.14609881572806,-0.514385083554768,-0.852670873682748,0.52393006059717,-0.644431689005427,0.110744010367861,0.095517034413196,-0.790528350192084,-0.30943821800278,-0.389276956792108,-1.31729941024539,-0.850613174229415,-0.133299144797457,-1.19219128348273,-1.54076557087737,-0.186387790693454,-0.5361966977601,-0.0682758420721278,-0.581877625624097,-0.661716364413426,-0.689701076978758,-0.173218514192121,-0.871601708653413,-0.641962449661427,-1.81032419926402,-1.79550876320002,-0.712747310856089,0.158071097794525,0.112390169930528,-0.291742002704115,-0.0904989961681267,-0.19667628796012,-1.09712556873873,-1.07490241464273,-1.27244156216272,-0.949794287880075,-0.965432803725407,-0.842793916306748,-0.437015584109439,-1.35639569985872,-0.389688496682775,-1.08231013267473,-1.1209948823974,-1.34610720259205,0.181940411453191,-0.718097329434756,-0.0242410737707973,-0.876540187341413,-1.81279343860802],"y":[-0.277964989836072,-0.540885841500442,-0.743094053753764,-0.79251715277846,-0.914695067626311,-0.286996622145153,-0.51793044271486,-0.906039753330108,-0.880951885804882,-0.866526361977877,-0.733058906743674,-1.10521233361288,-0.855362260929151,-0.977916493789881,-0.737574722898215,-0.362761982071336,-0.841438494452651,-0.648638232521288,2.81235853192128,-0.655662835428351,-0.0343617961661264,-0.690911289301294,-0.251246410921706,-0.626059151748585,-0.538000736735041,0.352493121072861,-0.593194045290538,-0.359375119955431,0.136235703005411,-0.724779910460349,-0.704835055777794,-0.615396808050363,-0.801548785087541,-1.02823021211172,-0.587549275097362,-1.11389273577661,-0.814970794213537,-0.341939052025399,-0.738201919586345,-0.227036618759863,-0.782356566430743,-0.470012615741678,-0.570238646504956,0.222036209941685,2.6530505731361,-0.301547585309785,-0.595577392705435,-0.696430620156844,0.0480518486542413,-0.673349782033636,-0.00475811248635957,-0.0988376157059574,-0.935768876347501,0.31360692640876,-0.755763426854004,-0.218883061814165,-0.663314635023545,-0.674478736072271,-0.532481405879491,-1.11389273577661,-0.859125441057935,-0.499992617434323,-0.831528786780186,-0.648512793183662,0.0213332697398756,-0.0492890773436359,-0.752502004075724,-0.720514972981061,0.543160914264579,4.03915525390484,-0.865271968601616,0.0518150287830253,-0.626560909099089,-0.467880147002034,-0.866526361977877,-1.07513198045013,-0.255511348400995,-0.440283492724285,-0.86966234541853,-0.79640577224487,-0.787499579273415,-0.613766096661224,-0.81747958096606,-1.11389273577661,-1.11389273577661,0.525599406996921,-1.09388516142524,-0.998576352696904,-0.338552189909493,-1.09386007355771,-0.636094298758675,-0.818733974342321,-0.63170392194176,-0.723525517084088,-1.11389273577661,-0.628066181150603,-0.588678229135998,-0.109750838079431,-0.893621258905121,-0.0219433017411394,-0.374804158483445,-0.779095143652464,-0.281477291289604,-0.389606000323328,-0.626184591086211,-0.12793954203522,-0.892115986853607,-0.668081329853338,-0.395877967204635,-1.03056338379157,-0.297909844518627,-0.431753617765708,-0.909050297433135,-1.05158701677771,-0.906666950018239,-0.930500424167204,0.269703158239614,-0.523700652245662,-0.981805113256291,0.827908210675895,-0.524704166946671,-0.507895295704769,-0.569987767829704,0.609643763206428,-0.815472551564042,-0.570991282530713,-0.782983763118874,-0.31271168635851,-0.603103752963003,-0.624679319034697,-0.054181211511055,-1.02294921599766,-0.70433329842729,-0.975533146374984,-0.370162902991278,-1.0952399062716,-0.863390378537224,-0.552049942549168,-0.832281422805943,0.28475587875475,-1.09056101897815,-0.289254530222424,-0.830399832741551,0.0494316813681289,-0.812963764811519,0.594591042691292,-0.368783070277391,-0.341813612687772,-0.776711796237567,-0.95232686891415,-0.98055071988003,-0.958849714470709,-0.803430375151933,-0.800921588399411,-0.257142059790134,-0.825758577249385,-0.694423590754826,-0.866275483302624,-1.09556604854943,-1.06771851559643,-1.07929656645932,-1.05670494175285,-0.915322264314442,-0.932382014231596,-0.605612539715525,-0.942417161241686,-1.11389273577661,-1.05778372005644,-0.973024359622462,1.36353418233947,-0.945553144682339,-0.270187750903252,-0.63722325279731,-0.863766696550102,-0.713364930736371,-0.892492304866486,-1.09449981417961,-0.222395363267696,-1.05109780336097,-1.10167870747195,-1.01660198551378,-0.64500049173013,-0.798914558997393,-0.109499959404179,-0.0574426342893344,-0.436896630608379,-0.611382749246327,-0.664694467737433,-1.01968779321938,-0.535868267995397,-0.789381169337807,-0.967003271416408,-1.00970282194434,-0.548788519770888,0.178132441772539,0.0907012234471257,-0.925482850662158,-0.521693622843644,-0.773952130809793,-1.09891527886405,-0.694423590754826,-0.776711796237567,-0.378567338612229,-0.840309540414016,-0.562963164922641,-0.688277063211145,-0.793269788804217,-0.279595701225212,1.74612416209917,-0.954459337653794,-0.580900990203178,-0.122921968530175,-0.669084844554347,-0.117528077012251,-0.374804158483445,-0.477037218648741,-0.256013105751499,-0.857369290331169,0.149281394118529,-0.872672889521557,-1.11389273577661,-0.513916383910824,-0.77758987160095,-0.0376232189444058,-0.186896030719501,-0.77370125213454,-0.756014305529256,-0.78699782192291,-0.604985343027394,-0.70044467896088,-0.849341172723097,-0.493720650553017,-0.423976378832888,-0.34545135347893,-0.711107022659101,-0.764795059163085,-0.731804513367413,-0.645376809743009,-0.253504318998977,-0.793395228141843,-0.857118411655917,-0.817855898978938,-1.00156180893241,-0.42585796889728,0.704977659802287,-0.223649756643957,0.0974749476789369,-1.00182523154142,-1.08290921938295,-0.319234531915069,-0.66055496959577,-0.942166282566434,-0.938026784424771,-0.142866823212729,-0.694172712079573,-0.88847824606245,-0.670590116605861,-0.945553144682339,-0.852100838150872,0.0723870801537108,-0.981554234581039,-0.863892135887728,-0.43137729975283,-0.603480070975881,-0.00789409592701284,-0.012911669432058,-0.605236221702647,-0.248988502844436,-0.741839660377503,-0.760279243008544,-0.215747078373511,-0.766174891876973,-0.962612894599493,-0.920590716494739,-0.677865598188176,-0.691538485989425,-0.504382994251238,0.153044574247313,0.247124077466911,-0.928367955427559,0.165588508009926,-0.744097568454773,-0.816977823615555,-0.419084244665469,-1.11389273577661,-0.472270523818948,-0.381954200728134,-0.478793369375507,-0.834915648896092,-0.448060731657105,-0.74811162725881,-0.738201919586345,-0.388100728271815,-0.543394628252964,0.380089775350609,0.82289063717085,-0.462611694821736,-0.577137810074394,-0.898889711085419,-0.556314880028456,-1.02391509889738,-0.888101928049571,-0.257894695815891,-0.108245566027917,-0.661182166283901,-0.145375609965252,-0.370288342328904,0.106632019325644,0.376326595221825,-0.0884261506829886,-0.604232707001638,-0.420714956054609,-0.270187750903252,-0.685391958445744,-0.0825305018145605,-0.574252705308993,-0.508647931730526,-0.62718810578722,-0.695928862806339,-1.05033262340145,-0.438401902659893,-0.821619079107722,-0.792140834765581,-0.586922078409232,-0.742843175078512,0.153044574247313,-0.639606600212207,-0.451322154435384,-0.587047517746858,-0.894123016255626,-0.453705501850281,-0.547534126394627,-1.11389273577661,0.0466720159403541,-0.268807918189365,0.151790180871052,-0.59896425482134,-0.739205434287354,-0.651272458611437,-0.740836145676494,-0.986948126098962,-0.567228102401929,-0.820741003744339,-0.919712641131356,-1.11389273577661,-0.508773371068152,-0.863390378537224,-0.612637142622589,-0.336796039182727,-0.361382149357449,-1.05085946861948,-1.11389273577661,0.176878048396278,0.280992698625966,-0.554182411288812,-1.11389273577661,-1.11389273577661],"z":[0.267675704960214,0.566789874669315,0.0123343405743969,-1.25707701380081,-0.155461413164854,-0.498348388197237,-0.00955206208724415,-1.15494046804648,-1.672918664372,0.20566423075223,0.395346387153123,0.0269252756821583,-0.469166517981715,3.39743128557494,0.0597548796746199,1.93104230724497,-0.345143569565747,-1.07833805873074,1.09206353854871,-0.808405759237158,0.329687179168199,-0.334200368234927,2.15720180141526,-0.341495835788806,0.110823152551784,0.475596530245809,0.975336057686622,0.431823724922525,1.11030220743341,-0.461871050427834,-1.55254344973297,-0.633314537944026,0.322391711614318,-1.68386186570282,-0.69897374592895,0.431823724922525,-0.264893426473062,0.486539731576629,1.47872331890438,-0.0387339323027659,-0.764632953913875,-1.184122338262,-0.830292161898799,-0.279484361580823,-0.39256410866597,0.402641854707004,-0.593189466397684,-0.450927849097014,-1.84800988566513,-0.52753025841276,0.161891425428947,-1.42122503376312,-0.720860148590592,0.690812823085283,0.249437036075513,0.0159820743513378,-1.72398693724916,-0.283132095357763,-0.148165945610973,0.333334912945139,-0.607780401505444,-0.122631809172391,-1.50512291063274,0.668926420423641,-0.24665475758836,-0.319609433127165,-1.23519061113917,2.65694132885607,1.49696198778908,2.6861231990716,0.0670503472285006,0.0378684770129789,0.577733076000134,0.118118620105665,-0.808405759237158,-1.34827035822431,0.661630952869761,-0.950667376537828,-1.08198579250768,-1.57078211861767,-0.115336341618511,0.537608004453792,-0.895951369883724,0.424528257368645,-0.326904900681046,-0.520234790858879,-1.51971384574051,-1.26072474757775,-2.35139714688288,-0.39621184244291,-1.07833805873074,-0.341495835788806,-0.52753025841276,-0.429041446435373,-0.578598531289922,0.0634026134515608,0.610562679992597,0.413585056037824,0.446414660030286,0.140005022767306,-1.65103226171035,-1.01632658452275,0.566789874669315,0.555846673338493,-1.64738452793341,0.548551205784614,0.35886904938372,-1.15129273426954,0.96074512257886,-0.08615447140299,0.253084769852453,-1.08563352628462,0.209311964529171,0.121766353882604,-0.950667376537828,-1.0746903249538,-1.71304373591834,-0.345143569565747,-0.968906045422529,0.884142713263116,-0.140870478057093,-0.272188894026942,-1.184122338262,-0.786519356575517,0.311448510283497,0.260380237406334,0.081641282336262,0.402641854707004,-0.644257739274847,0.723642427077745,-0.523882524635819,-1.10751992894626,-0.155461413164854,0.982631525240502,0.741881095962446,0.519369335569091,-0.870417233445142,1.08841580477177,1.05558620077931,-1.38474769599372,-0.418098245104552,-0.815701226791039,-1.73128240480304,2.85756668658779,0.734585628408566,-0.356086770896568,0.245789302298573,-0.297723030465523,0.231198367190812,-0.633314537944026,-0.801110291683277,-1.32273622178573,-0.644257739274847,-0.425393712658432,-0.111688607841571,-1.2023610071467,-1.46135010530946,0.450062393807227,-0.655200940605667,-0.08615447140299,-1.62914585904871,-1.30814528667797,0.453710127584167,-0.655200940605667,-0.768280687690815,0.0779935485593212,1.2817456949496,-2.17630592558975,-0.505643855751117,1.89091723569862,-1.23883834491611,-0.2503024913653,-0.97984924675335,-0.633314537944026,-0.38162090733515,-1.59996398883319,-1.56713438484073,-0.184643283380376,0.468301062691927,-0.140870478057093,-0.99444018186111,-0.582246265066862,0.285914373844915,0.366164516937601,0.818483505278191,-0.129927276726272,0.719994693300804,-0.651553206828727,-0.936076441430066,-1.06009938984603,-0.647905473051787,2.36147489292391,-0.512939323304998,-0.443632381543134,-1.01632658452275,0.81483577150125,-1.41392956620924,0.431823724922525,-1.11481539650014,-1.03456525340745,0.0123343405743969,-0.191938750934257,-1.15494046804648,-0.589541732620743,-0.425393712658432,-0.330552634457986,0.220255165859991,0.650687751538939,1.37293903937311,-1.42487276754006,-0.0715635362952286,0.752824297293267,0.698108290639163,-2.22007873091303,-0.118984075395452,-0.709916947259771,-0.604132667728504,-0.746394285029173,-0.00590432831030329,-0.0423816660797068,0.632449082654239,0.457357861361107,-0.622371336613206,-0.0204952634180647,-0.866769499668201,-1.00903111696887,0.129061821436485,-0.768280687690815,0.227550633413872,-0.279484361580823,-0.877712700999023,-1.18777007203894,-0.279484361580823,-0.84488309700656,0.563142140892374,-0.768280687690815,-0.356086770896568,-1.96108963275027,0.482891997799688,0.756472031070207,0.778358433731849,-0.83393989567574,-0.717212414813652,0.80024483639349,1.0008701941252,0.271323438737154,0.132709555213425,2.64964586130219,-0.662496408159548,0.413585056037824,0.745528829739386,-1.09657672761544,-1.28625888401633,-0.00225659453336345,-0.870417233445142,0.180130094313648,-0.356086770896568,-0.936076441430066,-0.812053493014098,-1.17682687070812,-1.4832365079711,2.04412205433011,0.0305730094590982,0.296857575175736,-1.23519061113917,-1.68750959947976,-0.717212414813652,-0.589541732620743,-0.0460293998566466,-1.59266852127931,-0.0460293998566466,-0.702621479705891,-0.52753025841276,-0.695326012152011,-0.38162090733515,-1.07833805873074,-1.30449755290103,-0.768280687690815,-0.910542304991485,-0.480109719312535,0.530312536899912,1.55532572822012,0.154595957875067,-0.454575582873955,-0.403507309996791,0.180130094313648,-0.388916374889029,-1.11481539650014,0.00503887302051623,-0.118984075395452,-1.26802021513163,-0.8485308307835,-0.118984075395452,-0.290427562911643,-0.10074540651075,0.986279259017442,-1.46864557286334,0.150948224098126,-0.976201512976409,-2.15806725670505,-0.724507882367532,-0.359734504673508,-1.184122338262,-0.622371336613206,-1.04186072096133,-0.523882524635819,0.479244264022749,2.06600845699176,0.895085914593936,1.13948407764893,0.519369335569091,-0.367029972227388,-1.14034953293872,-0.556712128628281,-0.264893426473062,0.420880523591705,-0.374325439781269,1.12489314254117,1.40576864336557,-0.636962271720966,-0.356086770896568,-1.54889571595603,-0.487405186866416,-0.323257166904105,-0.447280115320074,0.599619478661776,-0.564007596182162,-0.779223889021636,0.172834626759768,-0.658848674382608,-0.702621479705891,1.16501821408751,0.212959698306111,0.822131239055131,0.0232775419052175,0.220255165859991,0.103527684997903,-0.669791875713429,-0.69897374592895,-0.53847345974358,0.267675704960214,-0.520234790858879,-0.84488309700656,0.599619478661776,-0.549416661074401,0.79659710261655,-0.99444018186111,-0.436336913989253,-0.895951369883724,-0.797462557906337,-0.0752112700721684,-0.253950225142241,-1.30449755290103,-1.54524798217909,-1.00173564941499,-2.74170466101549,-0.819348960567978],"opacity":0.4,"type":"scatter3d","mode":"markers","name":"Benign","marker":{"color":"rgba(238,154,0,1)","size":[55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55],"sizemode":"area","symbol":"circle","line":{"color":"rgba(238,154,0,1)"}},"textfont":{"color":"rgba(238,154,0,1)","size":55},"error_y":{"color":"rgba(238,154,0,1)","width":55},"error_x":{"color":"rgba(238,154,0,1)","width":55},"line":{"color":"rgba(238,154,0,1)","width":55},"frame":null},{"x":[1.26881726270379,1.6844725522771,1.56512598398377,-0.592166122890763,1.77501132822376,-0.386807717448109,1.13712449769047,-0.0728027808694608,-0.183918551349454,-0.329192132754779,0.441622082463842,0.478660672623839,1.66389555774377,0.482776071530506,0.0671207819571972,0.195932767735857,0.114036329493194,0.663853623423828,1.56512598398377,0.433391284650509,1.86143470526376,0.74204620265049,0.988970137050476,0.223917480301188,1.24000947035713,0.429275885743843,0.947816147983811,1.35112524083712,-0.57776222671743,0.85727737203715,1.47870260694378,0.618584235450498,0.746161601557157,0.0683554016291971,0.146959520746526,-0.146879961189456,-0.238241816917451,-0.825920780789416,1.49516420257045,-0.191326269381454,-0.269518848608116,1.30585585286379,-0.246472614730784,1.16593229003713,0.217744381941189,1.37993303318379,0.147371060637192,0.183175031125191,-0.381869238760109,0.223505940410522,1.30174045395712,0.91489295673048,-0.0633373633841279,0.499237667157171,1.16181689113047,2.12893563419707,3.27301653025034,1.52808739382378,1.19885548129046,0.0938708748505291,1.23589407145046,0.338737109797181,0.342852508703847,1.66389555774377,0.103336292335862,-0.161283857362789,-0.195853208178787,2.50343693470372,0.274536886853185,0.565084049663834,0.91489295673048,1.21120167801046,3.05490038819702,-0.173218514192121,1.29350965614379,1.58158757961044,0.400468093397178,0.585661044197166,1.16181689113047,-0.421788608154773,0.200871246423856,0.540391656223836,-0.534138998306767,1.04658572174381,1.41285622443712,1.59393377633044,2.47462914235705,0.713238410303825,0.993085535957142,-0.252234173200117,0.433391284650509,0.713238410303825,3.70924881435698,2.08778164513041,0.379891098863845,0.286060003791851,1.0959705086238,0.098809353538529,-0.445246381922772,0.346967907610514,-0.0551065655707955,1.04658572174381,1.46224101131711,0.103747832226528,0.951931546890478,2.75447626801037,-0.0168333557387975,0.280298445322518,0.729700005930491,1.7585497325971,3.97263434438363,0.927239153450479,0.0370783699385327,-0.0415257491787964,1.55277978726377,1.48281800585045,0.437506683557175,-0.276103486858782,0.881969765477149,1.7462035358771,2.53224472705038,1.66801095665044,0.881969765477149,1.52808739382378,1.93139648667709,1.59393377633044,0.865508169850483,1.42108702225045,-0.0221833743174637,1.71328034462377,0.462199076997174,0.750277000463823,0.482776071530506,1.6844725522771,0.783200191717155,0.923123754543813,0.330506311983848,0.807892585157153,1.79970372166376,2.27708999483707,0.956046945797144,1.19062468347713,1.40874082553045,1.44989481459711,0.692661415770493,-0.698343414682757,1.54454898945044,1.7585497325971,1.10008590753047,1.6103953719571,1.80793451947709,0.614468836543832,0.63916122998383,0.569199448570501,0.816123382970486,1.27293266161046,2.59809110955705,1.56101058507711,0.622699634357164,3.38413230073033,0.24819833385052,1.7215111424371,1.71739574353043,2.01370446481041,2.2729745959304,0.700892213583826,2.03016606043708,1.76266513150376,-0.768305196096086,0.0823477579118631,1.51985659601044,0.429275885743843,2.15774342654374,1.33466364521046,1.06304731737047,0.195109687954523,0.449852880277175,0.416929689023843,1.7215111424371,1.30585585286379,-0.0349411109281296,0.840815776410485,1.05070112065047,1.04247032283714,1.89847329542375,1.47047180913045,0.791430989530488,3.90678796187697,1.11243210425047,0.733815404837157,1.48693340475711,0.622699634357164,1.08773971081047,1.2070862791038,1.88612709870376,0.0148552158425338,2.47462914235705,0.486891470437172,-0.137003003813457,0.217744381941189,1.18650928457046,1.58570297851711,3.02609259585035,1.7585497325971,1.88612709870376,0.0741169600985301,0.470429874810507,2.10012784185041,2.05897385278374,1.61451077086377,0.672084421237161,1.98078127355708],"y":[2.65054178638357,-0.0238248918055313,1.36227978896321,1.91421287451819,1.36980614922078,0.865540011963735,0.299808599269886,0.060972100429733,1.21802455069316,1.73734340846534,-0.700068360948002,0.134730430953898,1.47642958620299,0.13272340155188,1.55545636890745,0.942058007915674,-0.186268834031371,1.04617265814536,0.741355067713865,1.49148230671813,0.262176797982046,0.799057163021885,1.68215009990984,0.673617825395755,0.75515339485274,0.997251316471172,0.124820723281433,1.79504550377336,0.413958396509665,1.91797605464697,0.964637088688378,0.584555895681202,0.577029535423634,0.540652127512056,-0.813089204149145,0.219527423189162,-0.72377639575934,0.195693949040197,1.52911410800597,0.121308421827902,-0.0778892463223937,1.36227978896321,0.423993543519755,1.10889232695843,-0.454959895226542,0.545669701017102,0.508037899729262,1.56423712254128,0.301062992646147,0.475423671946469,0.240852110585604,1.00854085685752,-0.136845735006675,0.111524153493064,0.998505709847433,3.59509999870834,3.07452674755989,1.31586723404154,0.560722421532237,0.396396889242006,0.727556740574991,0.293536632388579,1.01857600386761,0.723793560446207,0.0637317658575077,-0.03197844875123,1.48395594646056,4.2348406206016,1.006032070105,1.56172833578876,-0.199063646469236,0.713758413436117,4.23985819410665,-0.450945836422506,0.0490553633552505,2.07853840680842,0.725047953822468,0.194439555663936,0.33242282705268,-0.522948016219905,0.816618670289544,0.0711326867774495,0.9671458754409,1.21300697718812,0.382598562103132,2.03212585188675,0.546924094393363,-0.0574426342893344,1.59434256357155,-0.379069095962733,1.43503460478637,1.13523458785992,2.4874706474696,2.00578359098526,-0.286871182807527,-0.439656296036154,-0.0891787867087455,1.37106054259704,0.247124077466911,1.01481282373883,0.623442090345303,0.269703158239614,0.283501485378489,0.366291448211735,0.185658802030107,3.30533512879198,0.840452144438508,-0.16682573669932,-0.242089339274999,0.943312401291935,2.90142046163583,0.99599692309491,0.28475587875475,0.128082146059713,0.481695638827775,0.322387680042589,0.324896466795112,1.01230403698631,1.28199861288249,0.835434570933463,1.33217434793294,0.0203297550388666,0.663582678385664,1.45635929218281,2.28802210064406,1.91797605464697,0.474169278570207,0.615915730087735,0.114032940245586,1.12394504747356,1.95686224931107,2.8700606272293,1.08255006605694,0.791530802764318,-0.751247610699463,0.102492521183982,-0.585918563708223,0.022713102453763,0.600863009572599,1.63950072511696,-0.399013950645288,-0.107869248015039,1.29579694002136,0.925750894024277,1.32966556118042,-0.777088114250446,1.64200951186948,1.74988734222796,0.30357177939867,0.334931613805202,2.10362627433364,0.740100674337604,1.14276094811748,0.396396889242006,0.777732475625443,0.215764243060378,1.78124717663449,1.22304212419821,2.54140956264884,3.11090415547147,0.435283083906107,0.115287333621847,0.944566794668197,0.351238727696599,1.95686224931107,1.15781366863262,1.30959526716024,0.801565949774408,1.00477767672874,-0.0614566930933706,1.21426137056438,1.25816513873352,2.41095265151766,2.8863677411207,0.392633709113222,-0.526083999660558,0.795293982893102,2.31436436154554,1.56172833578876,0.885610305983915,0.298554205893624,0.396396889242006,0.253396044348217,1.01606721711509,0.858013651706167,0.962128301935855,0.149281394118529,3.44582718693324,1.56549151591754,1.69093085354367,1.7160187210689,-0.656164592778856,0.353747514449122,0.756407788229001,1.63071997148313,0.588319075809986,0.988470562837343,1.43252581803385,0.698705692920981,-0.174853854307393,0.854250471577383,0.656056318128097,1.78375596338701,0.796548376269363,1.50151745372822,0.721284773693685,2.08481037368972,2.86755184047678,1.94557270892472,0.692433726039675,0.046546576602728,3.29404558840562],"z":[2.2155655418463,0.00139113924357638,0.938858719917219,2.86486215414167,-0.00955206208724415,1.00451792790214,-0.0642680687413479,1.40212090958863,1.96387191123743,0.79659710261655,-1.03456525340745,0.110823152551784,2.13531539875362,0.129061821436485,0.938858719917219,1.79242842372124,-0.822996694344919,1.28539342872654,-0.83758762945268,2.58763438709421,-0.155461413164854,0.668926420423641,4.4808082173262,1.60639400109728,-0.418098245104552,0.417232789814764,-0.264893426473062,1.35470037048841,1.78513295616736,1.59180306598952,0.150948224098126,0.679869621754462,0.307800776506557,0.267675704960214,-0.899599103660664,-0.334200368234927,-0.10074540651075,0.304153042729617,1.81796256015982,0.592324011107896,-0.23935929003448,0.3479258480529,1.15407501275669,1.02275659678684,-0.713564681036712,0.384403185822302,0.785653901285729,0.50113066668439,0.340630380499019,0.515721601792151,-0.83758762945268,0.420880523591705,-0.545768927297461,-0.0496771336335875,1.24162062340326,3.99201189121621,0.0634026134515608,-0.647905473051787,1.16866594786445,0.96074512257886,0.515721601792151,-0.345143569565747,0.158243691652007,1.03369979811767,0.245789302298573,-0.739098817475294,0.413585056037824,2.71530506928712,1.25985929228796,1.03734753189461,1.15772274653363,0.563142140892374,3.0764307132042,-0.184643283380376,0.490187465353569,1.42400731225027,0.435471458699465,1.27080249361878,-0.436336913989253,-0.826644428121859,0.530312536899912,0.180130094313648,3.16032859007383,0.581380809777075,-0.257597958919181,0.785653901285729,-0.0387339323027659,0.296857575175736,-0.998087915638051,-0.779223889021636,0.563142140892374,-0.0642680687413479,-0.0423816660797068,2.12801993119974,-0.706269213482831,-0.308666231796345,-0.695326012152011,2.0878948596534,0.479244264022749,-0.272188894026942,0.081641282336262,-0.151813679387914,-0.162756880718735,0.50477840046133,-1.11481539650014,1.41671184469639,1.60274626732034,-0.793814824129397,0.782006167508789,-0.170052348272615,-0.596837200174624,-1.83706668433431,1.5443825268893,1.07382486966401,1.03005206434073,-1.39933863110148,0.450062393807227,1.13583634387199,1.16501821408751,-1.32638395556267,0.35522131560678,-1.25707701380081,-0.00955206208724415,0.606914946215657,1.43495051358109,-0.286779829134703,0.00503887302051623,-0.129927276726272,0.35157358182984,0.296857575175736,2.13896313253056,2.49279330889376,1.0191088630099,0.00868660679745708,-0.903246837437604,1.08112033721789,-0.965258311645588,0.20201649697529,-0.155461413164854,-0.330552634457986,-0.998087915638051,-0.954315110314768,0.329687179168199,0.296857575175736,0.234846100967752,-0.702621479705891,-0.0715635362952286,1.59545079976646,-0.0168475296411249,0.424528257368645,2.76272560838734,0.49748293290745,0.209311964529171,-0.108040874064631,-0.308666231796345,0.515721601792151,-0.0533248674105273,0.986279259017442,2.05506525566093,0.526664803122971,-0.600484933951563,-0.706269213482831,0.231198367190812,-0.345143569565747,0.0451639445668596,1.32551850027289,0.588676277330956,-0.877712700999023,1.40212090958863,-0.673439609490368,0.647040017761999,0.428175991145585,1.27809796117266,1.09935900610259,0.65798321909282,0.147300490321186,0.997222460348263,0.836722174162893,-0.319609433127165,0.479244264022749,-0.520234790858879,-1.25707701380081,-0.334200368234927,-0.359734504673508,-0.939724175207006,-0.54212119352052,-0.0679158025182887,0.909676849701698,-0.421745978881492,1.23797288962632,0.0415162107899187,0.125414087659544,1.11030220743341,0.0743458147823814,0.132709555213425,1.69029187796691,-1.11846313027708,-0.0168475296411249,1.11030220743341,-0.914190038768425,0.176482360536709,-0.0350861985258261,0.65433548531588,1.29268889628042,1.15042727897975,0.417232789814764,1.15407501275669,1.23067742207244,-0.312313965573285,-0.217472887372838,-0.808405759237158,2.13531539875362],"opacity":0.4,"type":"scatter3d","mode":"markers","name":"Malignant","marker":{"color":"rgba(92,172,238,1)","size":[55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55],"sizemode":"area","symbol":"circle","line":{"color":"rgba(92,172,238,1)"}},"textfont":{"color":"rgba(92,172,238,1)","size":55},"error_y":{"color":"rgba(92,172,238,1)","width":55},"error_x":{"color":"rgba(92,172,238,1)","width":55},"line":{"color":"rgba(92,172,238,1)","width":55},"frame":null},{"x":[0],"y":[3.5],"z":[1],"opacity":0.4,"type":"scatter3d","mode":"markers","name":"Unknown","marker":{"color":"rgba(255,0,0,1)","size":[55],"sizemode":"area","symbol":"diamond","line":{"color":"rgba(255,0,0,1)"}},"textfont":{"color":"rgba(255,0,0,1)","size":55},"error_y":{"color":"rgba(255,0,0,1)","width":55},"error_x":{"color":"rgba(255,0,0,1)","width":55},"line":{"color":"rgba(255,0,0,1)","width":55},"frame":null},{"x":[0,0.416929689023843],"y":[3.5,2.31436436154554],"z":[1,0.836722174162893],"type":"scatter3d","mode":"lines","name":"lines","showlegend":false,"marker":{"color":"rgba(92,172,238,1)","line":{"color":"rgba(92,172,238,1)"}},"textfont":{"color":"rgba(92,172,238,1)"},"error_y":{"color":"rgba(92,172,238,1)"},"error_x":{"color":"rgba(92,172,238,1)"},"line":{"color":"rgba(92,172,238,1)"},"frame":null},{"x":[0,1.33466364521046],"y":[3.5,2.8863677411207],"z":[1,1.09935900610259],"type":"scatter3d","mode":"lines","name":"lines","showlegend":false,"marker":{"color":"rgba(92,172,238,1)","line":{"color":"rgba(92,172,238,1)"}},"textfont":{"color":"rgba(92,172,238,1)"},"error_y":{"color":"rgba(92,172,238,1)"},"error_x":{"color":"rgba(92,172,238,1)"},"line":{"color":"rgba(92,172,238,1)"},"frame":null},{"x":[0,0.470429874810507],"y":[3.5,2.08481037368972],"z":[1,1.15407501275669],"type":"scatter3d","mode":"lines","name":"lines","showlegend":false,"marker":{"color":"rgba(92,172,238,1)","line":{"color":"rgba(92,172,238,1)"}},"textfont":{"color":"rgba(92,172,238,1)"},"error_y":{"color":"rgba(92,172,238,1)"},"error_x":{"color":"rgba(92,172,238,1)"},"line":{"color":"rgba(92,172,238,1)"},"frame":null},{"x":[0,-1.36544957745338],"y":[3.5,2.81235853192128],"z":[1,1.09206353854871],"type":"scatter3d","mode":"lines","name":"lines","showlegend":false,"marker":{"color":"rgba(238,154,0,1)","line":{"color":"rgba(238,154,0,1)"}},"textfont":{"color":"rgba(238,154,0,1)"},"error_y":{"color":"rgba(238,154,0,1)"},"error_x":{"color":"rgba(238,154,0,1)"},"line":{"color":"rgba(238,154,0,1)"},"frame":null},{"x":[0,0.622699634357164],"y":[3.5,2.54140956264884],"z":[1,2.05506525566093],"type":"scatter3d","mode":"lines","name":"lines","showlegend":false,"marker":{"color":"rgba(92,172,238,1)","line":{"color":"rgba(92,172,238,1)"}},"textfont":{"color":"rgba(92,172,238,1)"},"error_y":{"color":"rgba(92,172,238,1)"},"error_x":{"color":"rgba(92,172,238,1)"},"line":{"color":"rgba(92,172,238,1)"},"frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p class="caption">
Figure 5.8: 3D scatter plot of the standardized symmetry, concavity, and perimeter variables. Note that in general we recommend against using 3D visualizations; here we show the data in 3D only to illustrate what higher dimensions and nearest neighbors look like, for learning purposes.
</p>
</div>
</div>
<div id="summary-of-k-nearest-neighbors-algorithm" class="section level3" number="5.5.3">
<h3><span class="header-section-number">5.5.3</span> Summary of <span class="math inline">\(K\)</span>-nearest neighbors algorithm</h3>
<p>In order to classify a new observation using a <span class="math inline">\(K\)</span>-nearest neighbor classifier, we have to:</p>
<ol style="list-style-type: decimal">
<li>Compute the distance between the new observation and each observation in the training set.</li>
<li>Sort the data table in ascending order according to the distances.</li>
<li>Choose the top <span class="math inline">\(K\)</span> rows of the sorted table.</li>
<li>Classify the new observation based on a majority vote of the neighbor classes.</li>
</ol>
</div>
</div>
<div id="k-nearest-neighbors-with-tidymodels" class="section level2" number="5.6">
<h2><span class="header-section-number">5.6</span> <span class="math inline">\(K\)</span>-nearest neighbors with <code>tidymodels</code></h2>
<p>Coding the <span class="math inline">\(K\)</span>-nearest neighbors algorithm in R ourselves can get complicated,
especially if we want to handle multiple classes, more than two variables,
or predict the class for multiple new observations. Thankfully, in R,
the <span class="math inline">\(K\)</span>-nearest neighbors algorithm is implemented in the <code>parsnip</code> package
included in the
<a href="https://www.tidymodels.org/"><code>tidymodels</code> package</a>, along with
many <a href="https://www.tidymodels.org/find/parsnip/">other models</a> 
that you will encounter in this and future chapters of the book. The <code>tidymodels</code> collection
provides tools to help make and use models, such as classifiers. Using the packages
in this collection will help keep our code simple, readable and accurate; the
less we have to code ourselves, the fewer mistakes we will likely make. We
start by loading <code>tidymodels</code>.</p>
<div class="sourceCode" id="cb271"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb271-1"><a href="classification.html#cb271-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span></code></pre></div>
<p>Let’s walk through how to use <code>tidymodels</code> to perform <span class="math inline">\(K\)</span>-nearest neighbors classification.
We will use the <code>cancer</code> data set from above, with
perimeter and concavity as predictors and <span class="math inline">\(K = 5\)</span> neighbors to build our classifier. Then
we will use the classifier to predict the diagnosis label for a new observation with
perimeter 0, concavity 3.5, and an unknown diagnosis label. Let’s pick out our two desired
predictor variables and class label and store them as a new data set named <code>cancer_train</code>:</p>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb272-1"><a href="classification.html#cb272-1" aria-hidden="true" tabindex="-1"></a>cancer_train <span class="ot">&lt;-</span> cancer <span class="sc">|&gt;</span></span>
<span id="cb272-2"><a href="classification.html#cb272-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Class, Perimeter, Concavity)</span>
<span id="cb272-3"><a href="classification.html#cb272-3" aria-hidden="true" tabindex="-1"></a>cancer_train</span></code></pre></div>
<pre><code>## # A tibble: 569 × 3
##    Class Perimeter Concavity
##    &lt;fct&gt;     &lt;dbl&gt;     &lt;dbl&gt;
##  1 M        1.27      2.65  
##  2 M        1.68     -0.0238
##  3 M        1.57      1.36  
##  4 M       -0.592     1.91  
##  5 M        1.78      1.37  
##  6 M       -0.387     0.866 
##  7 M        1.14      0.300 
##  8 M       -0.0728    0.0610
##  9 M       -0.184     1.22  
## 10 M       -0.329     1.74  
## # … with 559 more rows</code></pre>
<p>Next, we create a <em>model specification</em> for  <span class="math inline">\(K\)</span>-nearest neighbors classification
by calling the <code>nearest_neighbor</code> function, specifying that we want to use <span class="math inline">\(K = 5\)</span> neighbors
(we will discuss how to choose <span class="math inline">\(K\)</span> in the next chapter) and the straight-line
distance (<code>weight_func = "rectangular"</code>). The <code>weight_func</code> argument controls
how neighbors vote when classifying a new observation; by setting it to <code>"rectangular"</code>,
each of the <span class="math inline">\(K\)</span> nearest neighbors gets exactly 1 vote as described above. Other choices,
which weigh each neighbor’s vote differently, can be found on
<a href="https://parsnip.tidymodels.org/reference/nearest_neighbor.html">the <code>tidymodels</code> website</a>.
In the <code>set_engine</code>  argument, we specify which package or system will be used for training
the model. Here <code>kknn</code> is the R package we will use for performing <span class="math inline">\(K\)</span>-nearest neighbors classification.
Finally, we specify that this is a classification problem with the <code>set_mode</code> function.</p>
<div class="sourceCode" id="cb274"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb274-1"><a href="classification.html#cb274-1" aria-hidden="true" tabindex="-1"></a>knn_spec <span class="ot">&lt;-</span> <span class="fu">nearest_neighbor</span>(<span class="at">weight_func =</span> <span class="st">&quot;rectangular&quot;</span>, <span class="at">neighbors =</span> <span class="dv">5</span>) <span class="sc">|&gt;</span></span>
<span id="cb274-2"><a href="classification.html#cb274-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">&quot;kknn&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb274-3"><a href="classification.html#cb274-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">&quot;classification&quot;</span>)</span>
<span id="cb274-4"><a href="classification.html#cb274-4" aria-hidden="true" tabindex="-1"></a>knn_spec</span></code></pre></div>
<pre><code>## K-Nearest Neighbor Model Specification (classification)
## 
## Main Arguments:
##   neighbors = 5
##   weight_func = rectangular
## 
## Computational engine: kknn</code></pre>
<p>In order to fit the model on the breast cancer data, we need to pass the model specification
and the data set to the <code>fit</code> function. We also need to specify what variables to use as predictors
and what variable to use as the target. Below, the <code>Class ~ Perimeter + Concavity</code> argument specifies
that <code>Class</code> is the target variable (the one we want to predict),
and both <code>Perimeter</code> and <code>Concavity</code> are to be used as the predictors.</p>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb276-1"><a href="classification.html#cb276-1" aria-hidden="true" tabindex="-1"></a>knn_fit <span class="ot">&lt;-</span> knn_spec <span class="sc">|&gt;</span></span>
<span id="cb276-2"><a href="classification.html#cb276-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(Class <span class="sc">~</span> Perimeter <span class="sc">+</span> Concavity, <span class="at">data =</span> cancer_train)</span></code></pre></div>
<p>We can also use a convenient shorthand syntax using a period, <code>Class ~ .</code>, to indicate
that we want to use every variable <em>except</em> <code>Class</code>  as a predictor in the model.
In this particular setup, since <code>Concavity</code> and <code>Perimeter</code> are the only two predictors in the <code>cancer_train</code>
data frame, <code>Class ~ Perimeter + Concavity</code> and <code>Class ~ .</code> are equivalent.
In general, you can choose individual predictors using the <code>+</code> symbol, or you can specify to
use <em>all</em> predictors using the <code>.</code> symbol.</p>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb277-1"><a href="classification.html#cb277-1" aria-hidden="true" tabindex="-1"></a>knn_fit <span class="ot">&lt;-</span> knn_spec <span class="sc">|&gt;</span></span>
<span id="cb277-2"><a href="classification.html#cb277-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(Class <span class="sc">~</span> ., <span class="at">data =</span> cancer_train)</span>
<span id="cb277-3"><a href="classification.html#cb277-3" aria-hidden="true" tabindex="-1"></a>knn_fit</span></code></pre></div>
<pre><code>## parsnip model object
## 
## Fit time:  15ms 
## 
## Call:
## kknn::train.kknn(formula = Class ~ ., data = data, ks = min_rows(5,     data, 5), kernel = ~&quot;rectangular&quot;)
## 
## Type of response variable: nominal
## Minimal misclassification: 0.07557118
## Best kernel: rectangular
## Best k: 5</code></pre>
<p>Here you can see the final trained model summary. It confirms that the computational engine used
to train the model was <code>kknn::train.kknn</code>. It also shows the fraction of errors made by
the nearest neighbor model, but we will ignore this for now and discuss it in more detail
in the next chapter.
Finally it shows (somewhat confusingly) that the “best” weight function
was “rectangular” and “best” setting of <span class="math inline">\(K\)</span> was 5; but since we specified these earlier,
R is just repeating those settings to us here. In the next chapter, we will actually
let R find the value of <span class="math inline">\(K\)</span> for us.</p>
<p>Finally, we make the prediction on the new observation by calling the <code>predict</code>  function,
passing both the fit object we just created and the new observation itself. As above
when we ran the <span class="math inline">\(K\)</span>-nearest neighbors
classification algorithm manually, the <code>knn_fit</code> object classifies the new observation as
malignant (“M”). Note that the <code>predict</code> function outputs a data frame with a single
variable named <code>.pred_class</code>.</p>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb279-1"><a href="classification.html#cb279-1" aria-hidden="true" tabindex="-1"></a>new_obs <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Perimeter =</span> <span class="dv">0</span>, <span class="at">Concavity =</span> <span class="fl">3.5</span>)</span>
<span id="cb279-2"><a href="classification.html#cb279-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(knn_fit, new_obs)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   .pred_class
##   &lt;fct&gt;      
## 1 M</code></pre>
<p>Is this predicted malignant label the true class for this observation?
Well, we don’t know because we do not have this
observation’s diagnosis— that is what we were trying to predict! The
classifier’s prediction is not necessarily correct, but in the next chapter, we will
learn ways to quantify how accurate we think our predictions are.</p>
</div>
<div id="data-preprocessing-with-tidymodels" class="section level2" number="5.7">
<h2><span class="header-section-number">5.7</span> Data preprocessing with <code>tidymodels</code></h2>
<div id="centering-and-scaling" class="section level3" number="5.7.1">
<h3><span class="header-section-number">5.7.1</span> Centering and scaling</h3>
<p>When using <span class="math inline">\(K\)</span>-nearest neighbor classification, the <em>scale</em>  of each variable
(i.e., its size and range of values) matters. Since the classifier predicts
classes by identifying observations nearest to it, any variables with
a large scale will have a much larger effect than variables with a small
scale. But just because a variable has a large scale <em>doesn’t mean</em> that it is
more important for making accurate predictions. For example, suppose you have a
data set with two features, salary (in dollars) and years of education, and
you want to predict the corresponding type of job. When we compute the
neighbor distances, a difference of $1000 is huge compared to a difference of
10 years of education. But for our conceptual understanding and answering of
the problem, it’s the opposite; 10 years of education is huge compared to a
difference of $1000 in yearly salary!</p>
<p>In many other predictive models, the <em>center</em> of each variable (e.g., its mean)
matters as well. For example, if we had a data set with a temperature variable
measured in degrees Kelvin, and the same data set with temperature measured in
degrees Celcius, the two variables would differ by a constant shift of 273
(even though they contain exactly the same information). Likewise, in our
hypothetical job classification example, we would likely see that the center of
the salary variable is in the tens of thousands, while the center of the years
of education variable is in the single digits. Although this doesn’t affect the
<span class="math inline">\(K\)</span>-nearest neighbor classification algorithm, this large shift can change the
outcome of using many other predictive models. </p>
<p>To scale and center our data, we need to find
our variables’ <em>mean</em> (the average, which quantifies the “central” value of a
set of numbers) and <em>standard deviation</em> (a number quantifying how spread out values are).
For each observed value of the variable, we subtract the mean (i.e., center the variable)
and divide by the standard deviation (i.e., scale the variable). When we do this, the data
is said to be <em>standardized</em>,  and all variables in a data set will have a mean of 0
and a standard deviation of 1. To illustrate the effect that standardization can have on the <span class="math inline">\(K\)</span>-nearest
neighbor algorithm, we will read in the original, unstandardized Wisconsin breast
cancer data set; we have been using a standardized version of the data set up
until now. To keep things simple, we will just use the <code>Area</code>, <code>Smoothness</code>, and <code>Class</code>
variables:</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="classification.html#cb281-1" aria-hidden="true" tabindex="-1"></a>unscaled_cancer <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/unscaled_wdbc.csv&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb281-2"><a href="classification.html#cb281-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Class =</span> <span class="fu">as_factor</span>(Class)) <span class="sc">|&gt;</span></span>
<span id="cb281-3"><a href="classification.html#cb281-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Class, Area, Smoothness)</span>
<span id="cb281-4"><a href="classification.html#cb281-4" aria-hidden="true" tabindex="-1"></a>unscaled_cancer</span></code></pre></div>
<pre><code>## # A tibble: 569 × 3
##    Class  Area Smoothness
##    &lt;fct&gt; &lt;dbl&gt;      &lt;dbl&gt;
##  1 M     1001      0.118 
##  2 M     1326      0.0847
##  3 M     1203      0.110 
##  4 M      386.     0.142 
##  5 M     1297      0.100 
##  6 M      477.     0.128 
##  7 M     1040      0.0946
##  8 M      578.     0.119 
##  9 M      520.     0.127 
## 10 M      476.     0.119 
## # … with 559 more rows</code></pre>
<p>Looking at the unscaled and uncentered data above, you can see that the differences
between the values for area measurements are much larger than those for
smoothness. Will this affect
predictions? In order to find out, we will create a scatter plot of these two
predictors (colored by diagnosis) for both the unstandardized data we just
loaded, and the standardized version of that same data. But first, we need to
standardize the <code>unscaled_cancer</code> data set with <code>tidymodels</code>.</p>
<p>In the <code>tidymodels</code> framework, all data preprocessing happens
using a <a href="https://tidymodels.github.io/recipes/reference/index.html"><code>recipe</code></a>.
Here we will initialize a recipe   for the <code>unscaled_cancer</code> data above, specifying
that the <code>Class</code> variable is the target, and all other variables are predictors:</p>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb283-1"><a href="classification.html#cb283-1" aria-hidden="true" tabindex="-1"></a>uc_recipe <span class="ot">&lt;-</span> <span class="fu">recipe</span>(Class <span class="sc">~</span> ., <span class="at">data =</span> unscaled_cancer)</span>
<span id="cb283-2"><a href="classification.html#cb283-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(uc_recipe)</span></code></pre></div>
<pre><code>## Recipe
## 
## Inputs:
## 
##       role #variables
##    outcome          1
##  predictor          2</code></pre>
<p>So far, there is not much in the recipe; just a statement about the number of targets
and predictors. Let’s add scaling (<code>step_scale</code>)  and centering (<code>step_center</code>)  steps for
all of the predictors so that they each have a mean of 0 and standard deviation of 1.
Note that <code>tidyverse</code> actually provides <code>step_normalize</code>, which does both centering and scaling in
a single recipe step; in this book we will keep <code>step_scale</code> and <code>step_center</code> separate
to emphasize conceptually that there are two steps happening.
The <code>prep</code> function finalizes the recipe by using the data (here, <code>unscaled_cancer</code>) 
to compute anything necessary to run the recipe (in this case, the column means and standard
deviations):</p>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb285-1"><a href="classification.html#cb285-1" aria-hidden="true" tabindex="-1"></a>uc_recipe <span class="ot">&lt;-</span> uc_recipe <span class="sc">|&gt;</span></span>
<span id="cb285-2"><a href="classification.html#cb285-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_scale</span>(<span class="fu">all_predictors</span>()) <span class="sc">|&gt;</span></span>
<span id="cb285-3"><a href="classification.html#cb285-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_center</span>(<span class="fu">all_predictors</span>()) <span class="sc">|&gt;</span></span>
<span id="cb285-4"><a href="classification.html#cb285-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prep</span>()</span>
<span id="cb285-5"><a href="classification.html#cb285-5" aria-hidden="true" tabindex="-1"></a>uc_recipe</span></code></pre></div>
<pre><code>## Recipe
## 
## Inputs:
## 
##       role #variables
##    outcome          1
##  predictor          2
## 
## Training data contained 569 data points and no missing data.
## 
## Operations:
## 
## Scaling for Area, Smoothness [trained]
## Centering for Area, Smoothness [trained]</code></pre>
<p>You can now see that the recipe includes a scaling and centering step for all predictor variables.
Note that when you add a step to a recipe, you must specify what columns to apply the step to.
Here we used the <code>all_predictors()</code>  function to specify that each step should be applied to
all predictor variables. However, there are a number of different arguments one could use here,
as well as naming particular columns with the same syntax as the <code>select</code> function.
For example:</p>
<ul>
<li><code>all_nominal()</code> and <code>all_numeric()</code>: specify all categorical or all numeric variables</li>
<li><code>all_predictors()</code> and <code>all_outcomes()</code>: specify all predictor or all target variables</li>
<li><code>Area, Smoothness</code>: specify both the <code>Area</code> and <code>Smoothness</code> variable</li>
<li><code>-Class</code>: specify everything except the <code>Class</code> variable</li>
</ul>
<p>You can find <a href="https://tidymodels.github.io/recipes/reference/index.html">a full set of all the steps and variable selection functions</a>
on the <code>recipes</code> home page.</p>
<p>At this point, we have calculated the required statistics based on the data input into the
recipe, but the data are not yet scaled and centred. To actually scale and center
the data, we need to apply the <code>bake</code>   function to the unscaled data.</p>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb287-1"><a href="classification.html#cb287-1" aria-hidden="true" tabindex="-1"></a>scaled_cancer <span class="ot">&lt;-</span> <span class="fu">bake</span>(uc_recipe, unscaled_cancer)</span>
<span id="cb287-2"><a href="classification.html#cb287-2" aria-hidden="true" tabindex="-1"></a>scaled_cancer</span></code></pre></div>
<pre><code>## # A tibble: 569 × 3
##      Area Smoothness Class
##     &lt;dbl&gt;      &lt;dbl&gt; &lt;fct&gt;
##  1  0.984      1.57  M    
##  2  1.91      -0.826 M    
##  3  1.56       0.941 M    
##  4 -0.764      3.28  M    
##  5  1.82       0.280 M    
##  6 -0.505      2.24  M    
##  7  1.09      -0.123 M    
##  8 -0.219      1.60  M    
##  9 -0.384      2.20  M    
## 10 -0.509      1.58  M    
## # … with 559 more rows</code></pre>
<p>It may seem redundant that we had to both <code>bake</code> <em>and</em> <code>prep</code> to scale and center the data.
However, we do this in two steps so we can specify a different data set in the <code>bake</code> step if we want.
For example, we may want to specify new data that were not part of the training set.</p>
<p>You may wonder why we are doing so much work just to center and
scale our variables. Can’t we just manually scale and center the <code>Area</code> and
<code>Smoothness</code> variables ourselves before building our <span class="math inline">\(K\)</span>-nearest neighbor model? Well,
technically <em>yes</em>; but doing so is error-prone. In particular, we might
accidentally forget to apply the same centering / scaling when making
predictions, or accidentally apply a <em>different</em> centering / scaling than what
we used while training. Proper use of a <code>recipe</code> helps keep our code simple,
readable, and error-free. Furthermore, note that using <code>prep</code> and <code>bake</code> is
required only when you want to inspect the result of the preprocessing steps
yourself. You will see further on in Section
<a href="classification.html#puttingittogetherworkflow">5.8</a> that <code>tidymodels</code> provides tools to
automatically apply <code>prep</code> and <code>bake</code> as necessary without additional coding effort.</p>
<p>Figure <a href="classification.html#fig:05-scaling-plt">5.9</a> shows the two scatter plots side-by-side—one for <code>unscaled_cancer</code> and one for
<code>scaled_cancer</code>. Each has the same new observation annotated with its <span class="math inline">\(K=3\)</span> nearest neighbors.
In the original unstandardized data plot, you can see some odd choices
for the three nearest neighbors. In particular, the “neighbors” are visually
well within the cloud of benign observations, and the neighbors are all nearly
vertically aligned with the new observation (which is why it looks like there
is only one black line on this plot). Figure <a href="classification.html#fig:05-scaling-plt-zoomed">5.10</a>
shows a close-up of that region on the unstandardized plot. Here the computation of nearest
neighbors is dominated by the much larger-scale area variable. The plot for standardized data
on the right in Figure <a href="classification.html#fig:05-scaling-plt">5.9</a> shows a much more intuitively reasonable
selection of nearest neighbors. Thus, standardizing the data can change things
in an important way when we are using predictive algorithms.
Standardizing your data should be a part of the preprocessing you do
before predictive modeling and you should always think carefully about your problem domain and
whether you need to standardize your data.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:05-scaling-plt"></span>
<img src="_main_files/figure-html/05-scaling-plt-1.png" alt="Comparison of K = 3 nearest neighbors with standardized and unstandardized data." width="672" />
<p class="caption">
Figure 5.9: Comparison of K = 3 nearest neighbors with standardized and unstandardized data.
</p>
</div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:05-scaling-plt-zoomed"></span>
<img src="_main_files/figure-html/05-scaling-plt-zoomed-1.png" alt="Close up of three nearest neighbors for unstandardized data." width="864" />
<p class="caption">
Figure 5.10: Close up of three nearest neighbors for unstandardized data.
</p>
</div>
</div>
<div id="balancing" class="section level3" number="5.7.2">
<h3><span class="header-section-number">5.7.2</span> Balancing</h3>
<p>Another potential issue in a data set for a classifier is <em>class imbalance</em>, 
i.e., when one label is much more common than another. Since classifiers like
the <span class="math inline">\(K\)</span>-nearest neighbor algorithm use the labels of nearby points to predict
the label of a new point, if there are many more data points with one label
overall, the algorithm is more likely to pick that label in general (even if
the “pattern” of data suggests otherwise). Class imbalance is actually quite a
common and important problem: from rare disease diagnosis to malicious email
detection, there are many cases in which the “important” class to identify
(presence of disease, malicious email) is much rarer than the “unimportant”
class (no disease, normal email).</p>
<p>To better illustrate the problem, let’s revisit the scaled breast cancer data,
<code>cancer</code>; except now we will remove many of the observations of malignant tumors, simulating
what the data would look like if the cancer was rare. We will do this by
picking only 3 observations from the malignant group, and keeping all
of the benign observations. We choose these 3 observations using the <code>slice_head</code>
function, which takes two arguments: a data frame-like object,
and the number of rows to select from the top (<code>n</code>).
The new imbalanced data is shown in Figure <a href="classification.html#fig:05-unbalanced">5.11</a>.</p>
<div class="sourceCode" id="cb289"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb289-1"><a href="classification.html#cb289-1" aria-hidden="true" tabindex="-1"></a>rare_cancer <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb289-2"><a href="classification.html#cb289-2" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(cancer, Class <span class="sc">==</span> <span class="st">&quot;B&quot;</span>),</span>
<span id="cb289-3"><a href="classification.html#cb289-3" aria-hidden="true" tabindex="-1"></a>      cancer <span class="sc">|&gt;</span> <span class="fu">filter</span>(Class <span class="sc">==</span> <span class="st">&quot;M&quot;</span>) <span class="sc">|&gt;</span> <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">3</span>)</span>
<span id="cb289-4"><a href="classification.html#cb289-4" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">|&gt;</span></span>
<span id="cb289-5"><a href="classification.html#cb289-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(Class, Perimeter, Concavity)</span>
<span id="cb289-6"><a href="classification.html#cb289-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb289-7"><a href="classification.html#cb289-7" aria-hidden="true" tabindex="-1"></a>rare_plot <span class="ot">&lt;-</span> rare_cancer <span class="sc">|&gt;</span></span>
<span id="cb289-8"><a href="classification.html#cb289-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Perimeter, <span class="at">y =</span> Concavity, <span class="at">color =</span> Class)) <span class="sc">+</span></span>
<span id="cb289-9"><a href="classification.html#cb289-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb289-10"><a href="classification.html#cb289-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Perimeter (standardized)&quot;</span>, </span>
<span id="cb289-11"><a href="classification.html#cb289-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Concavity (standardized)&quot;</span>,</span>
<span id="cb289-12"><a href="classification.html#cb289-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">&quot;Diagnosis&quot;</span>) <span class="sc">+</span></span>
<span id="cb289-13"><a href="classification.html#cb289-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Malignant&quot;</span>, <span class="st">&quot;Benign&quot;</span>), </span>
<span id="cb289-14"><a href="classification.html#cb289-14" aria-hidden="true" tabindex="-1"></a>                     <span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;orange2&quot;</span>, <span class="st">&quot;steelblue2&quot;</span>))</span>
<span id="cb289-15"><a href="classification.html#cb289-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb289-16"><a href="classification.html#cb289-16" aria-hidden="true" tabindex="-1"></a>rare_plot</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:05-unbalanced"></span>
<img src="_main_files/figure-html/05-unbalanced-1.png" alt="Imbalanced data." width="432" />
<p class="caption">
Figure 5.11: Imbalanced data.
</p>
</div>
<p>Suppose we now decided to use <span class="math inline">\(K = 7\)</span> in <span class="math inline">\(K\)</span>-nearest neighbor classification.
With only 3 observations of malignant tumors, the classifier
will <em>always predict that the tumor is benign, no matter what its concavity and perimeter
are!</em> This is because in a majority vote of 7 observations, at most 3 will be
malignant (we only have 3 total malignant observations), so at least 4 must be
benign, and the benign vote will always win. For example, Figure <a href="classification.html#fig:05-upsample">5.12</a>
shows what happens for a new tumor observation that is quite close to three observations
in the training data that were tagged as malignant.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:05-upsample"></span>
<img src="_main_files/figure-html/05-upsample-1.png" alt="Imbalanced data with 7 nearest neighbors to a new observation highlighted." width="432" />
<p class="caption">
Figure 5.12: Imbalanced data with 7 nearest neighbors to a new observation highlighted.
</p>
</div>
<p>Figure <a href="classification.html#fig:05-upsample-2">5.13</a> shows what happens if we set the background color of
each area of the plot to the predictions the <span class="math inline">\(K\)</span>-nearest neighbor
classifier would make. We can see that the decision is
always “benign,” corresponding to the blue color.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:05-upsample-2"></span>
<img src="_main_files/figure-html/05-upsample-2-1.png" alt="Imbalanced data with background color indicating the decision of the classifier and the points represent the labeled data." width="432" />
<p class="caption">
Figure 5.13: Imbalanced data with background color indicating the decision of the classifier and the points represent the labeled data.
</p>
</div>
<p>Despite the simplicity of the problem, solving it in a statistically sound manner is actually
fairly nuanced, and a careful treatment would require a lot more detail and mathematics than we will cover in this textbook.
For the present purposes, it will suffice to rebalance the data by <em>oversampling</em> the rare class. 
In other words, we will replicate rare observations multiple times in our data set to give them more
voting power in the <span class="math inline">\(K\)</span>-nearest neighbor algorithm. In order to do this, we will add an oversampling
step to the earlier <code>uc_recipe</code> recipe with the <code>step_upsample</code> function from the <code>themis</code> R package. 
We show below how to do this, and also
use the <code>group_by</code> and <code>summarize</code> functions to see that our classes are now balanced:</p>
<div class="sourceCode" id="cb290"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb290-1"><a href="classification.html#cb290-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(themis)</span>
<span id="cb290-2"><a href="classification.html#cb290-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb290-3"><a href="classification.html#cb290-3" aria-hidden="true" tabindex="-1"></a>ups_recipe <span class="ot">&lt;-</span> <span class="fu">recipe</span>(Class <span class="sc">~</span> ., <span class="at">data =</span> rare_cancer) <span class="sc">|&gt;</span></span>
<span id="cb290-4"><a href="classification.html#cb290-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_upsample</span>(Class, <span class="at">over_ratio =</span> <span class="dv">1</span>, <span class="at">skip =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span></span>
<span id="cb290-5"><a href="classification.html#cb290-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prep</span>()</span>
<span id="cb290-6"><a href="classification.html#cb290-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb290-7"><a href="classification.html#cb290-7" aria-hidden="true" tabindex="-1"></a>ups_recipe</span></code></pre></div>
<pre><code>## Recipe
## 
## Inputs:
## 
##       role #variables
##    outcome          1
##  predictor          2
## 
## Training data contained 360 data points and no missing data.
## 
## Operations:
## 
## Up-sampling based on Class [trained]</code></pre>
<div class="sourceCode" id="cb292"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb292-1"><a href="classification.html#cb292-1" aria-hidden="true" tabindex="-1"></a>upsampled_cancer <span class="ot">&lt;-</span> <span class="fu">bake</span>(ups_recipe, rare_cancer)</span>
<span id="cb292-2"><a href="classification.html#cb292-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb292-3"><a href="classification.html#cb292-3" aria-hidden="true" tabindex="-1"></a>upsampled_cancer <span class="sc">|&gt;</span></span>
<span id="cb292-4"><a href="classification.html#cb292-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Class) <span class="sc">|&gt;</span></span>
<span id="cb292-5"><a href="classification.html#cb292-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 2 × 2
##   Class     n
##   &lt;fct&gt; &lt;int&gt;
## 1 M       357
## 2 B       357</code></pre>
<p>Now suppose we train our <span class="math inline">\(K\)</span>-nearest neighbor classifier with <span class="math inline">\(K=7\)</span> on this <em>balanced</em> data.
Figure <a href="classification.html#fig:05-upsample-plot">5.14</a> shows what happens now when we set the background color
of each area of our scatter plot to the decision the <span class="math inline">\(K\)</span>-nearest neighbor
classifier would make. We can see that the decision is more reasonable; when the points are close
to those labeled malignant, the classifier predicts a malignant tumor, and vice versa when they are
closer to the benign tumor observations.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:05-upsample-plot"></span>
<img src="_main_files/figure-html/05-upsample-plot-1.png" alt="Upsampled data with background color indicating the decision of the classifier." width="432" />
<p class="caption">
Figure 5.14: Upsampled data with background color indicating the decision of the classifier.
</p>
</div>
</div>
</div>
<div id="puttingittogetherworkflow" class="section level2" number="5.8">
<h2><span class="header-section-number">5.8</span> Putting it together in a <code>workflow</code></h2>
<p>The <code>tidymodels</code> package collection also provides the <code>workflow</code>, a way to chain  
together multiple data analysis steps without a lot of otherwise necessary code for intermediate steps.
To illustrate the whole pipeline, let’s start from scratch with the <code>unscaled_wdbc.csv</code> data.
First we will load the data, create a model, and specify a recipe for how the data should be preprocessed:</p>
<div class="sourceCode" id="cb294"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb294-1"><a href="classification.html#cb294-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load the unscaled cancer data </span></span>
<span id="cb294-2"><a href="classification.html#cb294-2" aria-hidden="true" tabindex="-1"></a><span class="co"># and make sure the target Class variable is a factor</span></span>
<span id="cb294-3"><a href="classification.html#cb294-3" aria-hidden="true" tabindex="-1"></a>unscaled_cancer <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/unscaled_wdbc.csv&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb294-4"><a href="classification.html#cb294-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Class =</span> <span class="fu">as_factor</span>(Class))</span>
<span id="cb294-5"><a href="classification.html#cb294-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb294-6"><a href="classification.html#cb294-6" aria-hidden="true" tabindex="-1"></a><span class="co"># create the KNN model</span></span>
<span id="cb294-7"><a href="classification.html#cb294-7" aria-hidden="true" tabindex="-1"></a>knn_spec <span class="ot">&lt;-</span> <span class="fu">nearest_neighbor</span>(<span class="at">weight_func =</span> <span class="st">&quot;rectangular&quot;</span>, <span class="at">neighbors =</span> <span class="dv">7</span>) <span class="sc">|&gt;</span></span>
<span id="cb294-8"><a href="classification.html#cb294-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">&quot;kknn&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb294-9"><a href="classification.html#cb294-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">&quot;classification&quot;</span>)</span>
<span id="cb294-10"><a href="classification.html#cb294-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb294-11"><a href="classification.html#cb294-11" aria-hidden="true" tabindex="-1"></a><span class="co"># create the centering / scaling recipe</span></span>
<span id="cb294-12"><a href="classification.html#cb294-12" aria-hidden="true" tabindex="-1"></a>uc_recipe <span class="ot">&lt;-</span> <span class="fu">recipe</span>(Class <span class="sc">~</span> Area <span class="sc">+</span> Smoothness, <span class="at">data =</span> unscaled_cancer) <span class="sc">|&gt;</span></span>
<span id="cb294-13"><a href="classification.html#cb294-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_scale</span>(<span class="fu">all_predictors</span>()) <span class="sc">|&gt;</span></span>
<span id="cb294-14"><a href="classification.html#cb294-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_center</span>(<span class="fu">all_predictors</span>())</span></code></pre></div>
<p>Note that each of these steps is exactly the same as earlier, except for one major difference:
we did not use the <code>select</code> function to extract the relevant variables from the data frame,
and instead simply specified the relevant variables to use via the
formula <code>Class ~ Area + Smoothness</code> (instead of <code>Class ~ .</code>) in the recipe.
You will also notice that we did not call <code>prep()</code> on the recipe; this is unnecessary when it is
placed in a workflow.</p>
<p>We will now place these steps in a <code>workflow</code> using the <code>add_recipe</code> and <code>add_model</code> functions, 
and finally we will use the <code>fit</code> function to run the whole workflow on the <code>unscaled_cancer</code> data.
Note another difference from earlier here: we do not include a formula in the <code>fit</code> function. This 
is again because we included the formula in the recipe, so there is no need to respecify it:</p>
<div class="sourceCode" id="cb295"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb295-1"><a href="classification.html#cb295-1" aria-hidden="true" tabindex="-1"></a>knn_fit <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">|&gt;</span></span>
<span id="cb295-2"><a href="classification.html#cb295-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(uc_recipe) <span class="sc">|&gt;</span></span>
<span id="cb295-3"><a href="classification.html#cb295-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(knn_spec) <span class="sc">|&gt;</span></span>
<span id="cb295-4"><a href="classification.html#cb295-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(<span class="at">data =</span> unscaled_cancer)</span>
<span id="cb295-5"><a href="classification.html#cb295-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb295-6"><a href="classification.html#cb295-6" aria-hidden="true" tabindex="-1"></a>knn_fit</span></code></pre></div>
<pre><code>## ══ Workflow [trained] ══════════════════════════════════════════════════════════
## Preprocessor: Recipe
## Model: nearest_neighbor()
## 
## ── Preprocessor ────────────────────────────────────────────────────────────────
## 2 Recipe Steps
## 
## • step_scale()
## • step_center()
## 
## ── Model ───────────────────────────────────────────────────────────────────────
## 
## Call:
## kknn::train.kknn(formula = ..y ~ ., data = data, ks = min_rows(7,     data, 5), kernel = ~&quot;rectangular&quot;)
## 
## Type of response variable: nominal
## Minimal misclassification: 0.112478
## Best kernel: rectangular
## Best k: 7</code></pre>
<p>As before, the fit object lists the function that trains the model as well as the “best” settings
for the number of neighbors and weight function (for now, these are just the values we chose
manually when we created <code>knn_spec</code> above). But now the fit object also includes information about
the overall workflow, including the centering and scaling preprocessing steps.
In other words, when we use the <code>predict</code> function with the <code>knn_fit</code> object to make a prediction for a new
observation, it will first apply the same recipe steps to the new observation.
As an example, we will predict the class label of two new observations:
one with <code>Area = 500</code> and <code>Smoothness = 0.075</code>, and one with <code>Area = 1500</code> and <code>Smoothness = 0.1</code>.</p>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb297-1"><a href="classification.html#cb297-1" aria-hidden="true" tabindex="-1"></a>new_observation <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Area =</span> <span class="fu">c</span>(<span class="dv">500</span>, <span class="dv">1500</span>), <span class="at">Smoothness =</span> <span class="fu">c</span>(<span class="fl">0.075</span>, <span class="fl">0.1</span>))</span>
<span id="cb297-2"><a href="classification.html#cb297-2" aria-hidden="true" tabindex="-1"></a>prediction <span class="ot">&lt;-</span> <span class="fu">predict</span>(knn_fit, new_observation)</span>
<span id="cb297-3"><a href="classification.html#cb297-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb297-4"><a href="classification.html#cb297-4" aria-hidden="true" tabindex="-1"></a>prediction</span></code></pre></div>
<pre><code>## # A tibble: 2 × 1
##   .pred_class
##   &lt;fct&gt;      
## 1 B          
## 2 M</code></pre>
<p>The classifier predicts that the first observation is benign (“B”), while the second is
malignant (“M”). Figure <a href="classification.html#fig:05-workflow-plot-show">5.15</a> visualizes the predictions that this
trained <span class="math inline">\(K\)</span>-nearest neighbor model will make on a large range of new observations.
Although you have seen colored prediction map visualizations like this a few times now,
we have not included the code to generate them, as it is a little bit complicated.
For the interested reader who wants a learning challenge, we now include it below.
The basic idea is to create a grid of synthetic new observations using the <code>expand.grid</code> function,
predict the label of each, and visualize the predictions with a colored scatter having a very high transparency
(low <code>alpha</code> value) and large point radius. See if you can figure out what each line is doing!</p>
<blockquote>
<p><strong>Note:</strong> Understanding this code is not required for the remainder of the
textbook. It is included for those readers who would like to use similar
visualizations in their own data analyses.</p>
</blockquote>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb299-1"><a href="classification.html#cb299-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create the grid of area/smoothness vals, and arrange in a data frame</span></span>
<span id="cb299-2"><a href="classification.html#cb299-2" aria-hidden="true" tabindex="-1"></a>are_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(unscaled_cancer<span class="sc">$</span>Area), </span>
<span id="cb299-3"><a href="classification.html#cb299-3" aria-hidden="true" tabindex="-1"></a>                <span class="fu">max</span>(unscaled_cancer<span class="sc">$</span>Area), </span>
<span id="cb299-4"><a href="classification.html#cb299-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">length.out =</span> <span class="dv">100</span>)</span>
<span id="cb299-5"><a href="classification.html#cb299-5" aria-hidden="true" tabindex="-1"></a>smo_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(unscaled_cancer<span class="sc">$</span>Smoothness), </span>
<span id="cb299-6"><a href="classification.html#cb299-6" aria-hidden="true" tabindex="-1"></a>                <span class="fu">max</span>(unscaled_cancer<span class="sc">$</span>Smoothness), </span>
<span id="cb299-7"><a href="classification.html#cb299-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">length.out =</span> <span class="dv">100</span>)</span>
<span id="cb299-8"><a href="classification.html#cb299-8" aria-hidden="true" tabindex="-1"></a>asgrid <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(<span class="fu">expand.grid</span>(<span class="at">Area =</span> are_grid, </span>
<span id="cb299-9"><a href="classification.html#cb299-9" aria-hidden="true" tabindex="-1"></a>                                <span class="at">Smoothness =</span> smo_grid))</span>
<span id="cb299-10"><a href="classification.html#cb299-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb299-11"><a href="classification.html#cb299-11" aria-hidden="true" tabindex="-1"></a><span class="co"># use the fit workflow to make predictions at the grid points</span></span>
<span id="cb299-12"><a href="classification.html#cb299-12" aria-hidden="true" tabindex="-1"></a>knnPredGrid <span class="ot">&lt;-</span> <span class="fu">predict</span>(knn_fit, asgrid)</span>
<span id="cb299-13"><a href="classification.html#cb299-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb299-14"><a href="classification.html#cb299-14" aria-hidden="true" tabindex="-1"></a><span class="co"># bind the predictions as a new column with the grid points</span></span>
<span id="cb299-15"><a href="classification.html#cb299-15" aria-hidden="true" tabindex="-1"></a>prediction_table <span class="ot">&lt;-</span> <span class="fu">bind_cols</span>(knnPredGrid, asgrid) <span class="sc">|&gt;</span> </span>
<span id="cb299-16"><a href="classification.html#cb299-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Class =</span> .pred_class)</span>
<span id="cb299-17"><a href="classification.html#cb299-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb299-18"><a href="classification.html#cb299-18" aria-hidden="true" tabindex="-1"></a><span class="co"># plot:</span></span>
<span id="cb299-19"><a href="classification.html#cb299-19" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. the colored scatter of the original data</span></span>
<span id="cb299-20"><a href="classification.html#cb299-20" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. the faded colored scatter for the grid points</span></span>
<span id="cb299-21"><a href="classification.html#cb299-21" aria-hidden="true" tabindex="-1"></a>wkflw_plot <span class="ot">&lt;-</span></span>
<span id="cb299-22"><a href="classification.html#cb299-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb299-23"><a href="classification.html#cb299-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> unscaled_cancer, </span>
<span id="cb299-24"><a href="classification.html#cb299-24" aria-hidden="true" tabindex="-1"></a>             <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Area, </span>
<span id="cb299-25"><a href="classification.html#cb299-25" aria-hidden="true" tabindex="-1"></a>                           <span class="at">y =</span> Smoothness, </span>
<span id="cb299-26"><a href="classification.html#cb299-26" aria-hidden="true" tabindex="-1"></a>                           <span class="at">color =</span> Class), </span>
<span id="cb299-27"><a href="classification.html#cb299-27" aria-hidden="true" tabindex="-1"></a>             <span class="at">alpha =</span> <span class="fl">0.75</span>) <span class="sc">+</span></span>
<span id="cb299-28"><a href="classification.html#cb299-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> prediction_table, </span>
<span id="cb299-29"><a href="classification.html#cb299-29" aria-hidden="true" tabindex="-1"></a>             <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Area, </span>
<span id="cb299-30"><a href="classification.html#cb299-30" aria-hidden="true" tabindex="-1"></a>                           <span class="at">y =</span> Smoothness, </span>
<span id="cb299-31"><a href="classification.html#cb299-31" aria-hidden="true" tabindex="-1"></a>                           <span class="at">color =</span> Class), </span>
<span id="cb299-32"><a href="classification.html#cb299-32" aria-hidden="true" tabindex="-1"></a>             <span class="at">alpha =</span> <span class="fl">0.02</span>, </span>
<span id="cb299-33"><a href="classification.html#cb299-33" aria-hidden="true" tabindex="-1"></a>             <span class="at">size =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb299-34"><a href="classification.html#cb299-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">color =</span> <span class="st">&quot;Diagnosis&quot;</span>, </span>
<span id="cb299-35"><a href="classification.html#cb299-35" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Area (standardized)&quot;</span>, </span>
<span id="cb299-36"><a href="classification.html#cb299-36" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Smoothness (standardized)&quot;</span>) <span class="sc">+</span></span>
<span id="cb299-37"><a href="classification.html#cb299-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Malignant&quot;</span>, <span class="st">&quot;Benign&quot;</span>), </span>
<span id="cb299-38"><a href="classification.html#cb299-38" aria-hidden="true" tabindex="-1"></a>                     <span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;orange2&quot;</span>, <span class="st">&quot;steelblue2&quot;</span>))</span>
<span id="cb299-39"><a href="classification.html#cb299-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb299-40"><a href="classification.html#cb299-40" aria-hidden="true" tabindex="-1"></a>wkflw_plot</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:05-workflow-plot-show"></span>
<img src="_main_files/figure-html/05-workflow-plot-show-1.png" alt="Scatter plot of smoothness versus area where background color indicates the decision of the classifier." width="441.6" />
<p class="caption">
Figure 5.15: Scatter plot of smoothness versus area where background color indicates the decision of the classifier.
</p>
</div>
</div>
<div id="exercises-4" class="section level2" number="5.9">
<h2><span class="header-section-number">5.9</span> Exercises</h2>
<p>Practice exercises for the material covered in this chapter
can be found in the accompanying <a href="https://github.com/UBC-DSCI/data-science-a-first-intro-worksheets/blob/main/worksheet_06/worksheet_06.ipynb">worksheet</a>.
The worksheet tries to provide automated feedback
and help guide you through the problems.
To make sure this functionality works as intended,
please follow the instructions for computer setup needed to run the worksheets
found in Chapter <a href="move-to-your-own-machine.html#move-to-your-own-machine">13</a>.</p>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-stanfordhealthcare" class="csl-entry">
Stanford Health Care. 2021. <span>“What Is Cancer?”</span> <a href="https://stanfordhealthcare.org/medical-conditions/cancer/cancer.html">https://stanfordhealthcare.org/medical-conditions/cancer/cancer.html</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="viz.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="classification2.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/classification1.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
