<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 11 Introduction to Statistical Inference | Data Science: A First Introduction</title>
  <meta name="description" content="This is a textbook for teaching a first introduction to data science." />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 11 Introduction to Statistical Inference | Data Science: A First Introduction" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a textbook for teaching a first introduction to data science." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 11 Introduction to Statistical Inference | Data Science: A First Introduction" />
  
  <meta name="twitter:description" content="This is a textbook for teaching a first introduction to data science." />
  

<meta name="author" content="Tiffany-Anne Timbers" />
<meta name="author" content="Trevor Campbell" />
<meta name="author" content="Melissa Lee" />


<meta name="date" content="2021-05-26" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="clustering.html"/>
<link rel="next" href="move-to-your-own-machine.html"/>
<script src="libs/header-attrs-2.8/header-attrs.js"></script>
<script src="libs/jquery-3.5.1/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.3/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.9.3/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.57.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.57.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Data Science: A First Introduction</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> R, Jupyter, and the tidyverse</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#chapter-learning-objectives"><i class="fa fa-check"></i><b>1.1</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#jupyter-notebooks"><i class="fa fa-check"></i><b>1.2</b> Jupyter notebooks</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#loading-a-spreadsheet-like-dataset"><i class="fa fa-check"></i><b>1.3</b> Loading a spreadsheet-like dataset</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#assigning-value-to-a-data-frame"><i class="fa fa-check"></i><b>1.4</b> Assigning value to a data frame</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#creating-subsets-of-data-frames-with-select-filter"><i class="fa fa-check"></i><b>1.5</b> Creating subsets of data frames with <code>select</code> &amp; <code>filter</code></a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="index.html"><a href="index.html#using-select-to-extract-multiple-columns"><i class="fa fa-check"></i><b>1.5.1</b> Using <code>select</code> to extract multiple columns</a></li>
<li class="chapter" data-level="1.5.2" data-path="index.html"><a href="index.html#using-select-to-extract-a-range-of-columns"><i class="fa fa-check"></i><b>1.5.2</b> Using <code>select</code> to extract a range of columns</a></li>
<li class="chapter" data-level="1.5.3" data-path="index.html"><a href="index.html#using-filter-to-extract-a-single-row"><i class="fa fa-check"></i><b>1.5.3</b> Using <code>filter</code> to extract a single row</a></li>
<li class="chapter" data-level="1.5.4" data-path="index.html"><a href="index.html#using-filter-to-extract-rows-with-values-above-a-threshold"><i class="fa fa-check"></i><b>1.5.4</b> Using <code>filter</code> to extract rows with values above a threshold</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#exploring-data-with-visualizations"><i class="fa fa-check"></i><b>1.6</b> Exploring data with visualizations</a>
<ul>
<li class="chapter" data-level="1.6.1" data-path="index.html"><a href="index.html#using-ggplot-to-create-a-scatter-plot"><i class="fa fa-check"></i><b>1.6.1</b> Using <code>ggplot</code> to create a scatter plot</a></li>
<li class="chapter" data-level="1.6.2" data-path="index.html"><a href="index.html#formatting-ggplot-objects"><i class="fa fa-check"></i><b>1.6.2</b> Formatting ggplot objects</a></li>
<li class="chapter" data-level="1.6.3" data-path="index.html"><a href="index.html#changing-the-units"><i class="fa fa-check"></i><b>1.6.3</b> Changing the units</a></li>
<li class="chapter" data-level="1.6.4" data-path="index.html"><a href="index.html#coloring-points-by-group"><i class="fa fa-check"></i><b>1.6.4</b> Coloring points by group</a></li>
<li class="chapter" data-level="1.6.5" data-path="index.html"><a href="index.html#putting-it-all-together"><i class="fa fa-check"></i><b>1.6.5</b> Putting it all together</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="reading.html"><a href="reading.html"><i class="fa fa-check"></i><b>2</b> Reading in data locally and from the web</a>
<ul>
<li class="chapter" data-level="2.1" data-path="reading.html"><a href="reading.html#overview"><i class="fa fa-check"></i><b>2.1</b> Overview</a></li>
<li class="chapter" data-level="2.2" data-path="reading.html"><a href="reading.html#chapter-learning-objectives-1"><i class="fa fa-check"></i><b>2.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="2.3" data-path="reading.html"><a href="reading.html#absolute-and-relative-file-paths"><i class="fa fa-check"></i><b>2.3</b> Absolute and relative file paths</a></li>
<li class="chapter" data-level="2.4" data-path="reading.html"><a href="reading.html#reading-tabular-data-from-a-plain-text-file-into-r"><i class="fa fa-check"></i><b>2.4</b> Reading tabular data from a plain text file into R</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="reading.html"><a href="reading.html#skipping-rows-when-reading-in-data"><i class="fa fa-check"></i><b>2.4.1</b> Skipping rows when reading in data</a></li>
<li class="chapter" data-level="2.4.2" data-path="reading.html"><a href="reading.html#read_delim-as-a-more-flexible-method-to-get-tabular-data-into-r"><i class="fa fa-check"></i><b>2.4.2</b> <code>read_delim</code> as a more flexible method to get tabular data into R</a></li>
<li class="chapter" data-level="2.4.3" data-path="reading.html"><a href="reading.html#reading-tabular-data-directly-from-a-url"><i class="fa fa-check"></i><b>2.4.3</b> Reading tabular data directly from a URL</a></li>
<li class="chapter" data-level="2.4.4" data-path="reading.html"><a href="reading.html#previewing-a-data-file-before-reading-it-into-r"><i class="fa fa-check"></i><b>2.4.4</b> Previewing a data file before reading it into R</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="reading.html"><a href="reading.html#reading-data-from-an-microsoft-excel-file"><i class="fa fa-check"></i><b>2.5</b> Reading data from an Microsoft Excel file</a></li>
<li class="chapter" data-level="2.6" data-path="reading.html"><a href="reading.html#reading-data-from-a-database"><i class="fa fa-check"></i><b>2.6</b> Reading data from a database</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="reading.html"><a href="reading.html#connecting-to-a-database"><i class="fa fa-check"></i><b>2.6.1</b> Connecting to a database</a></li>
<li class="chapter" data-level="2.6.2" data-path="reading.html"><a href="reading.html#interacting-with-a-database"><i class="fa fa-check"></i><b>2.6.2</b> Interacting with a database</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="reading.html"><a href="reading.html#writing-data-from-r-to-a-.csv-file"><i class="fa fa-check"></i><b>2.7</b> Writing data from R to a <code>.csv</code> file</a></li>
<li class="chapter" data-level="2.8" data-path="reading.html"><a href="reading.html#obtaining-data-from-the-web"><i class="fa fa-check"></i><b>2.8</b> Obtaining data from the web</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="reading.html"><a href="reading.html#web-scraping"><i class="fa fa-check"></i><b>2.8.1</b> Web scraping</a></li>
<li class="chapter" data-level="2.8.2" data-path="reading.html"><a href="reading.html#using-an-api"><i class="fa fa-check"></i><b>2.8.2</b> Using an API</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="reading.html"><a href="reading.html#additional-resources"><i class="fa fa-check"></i><b>2.9</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="wrangling.html"><a href="wrangling.html"><i class="fa fa-check"></i><b>3</b> Cleaning and wrangling data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="wrangling.html"><a href="wrangling.html#overview-1"><i class="fa fa-check"></i><b>3.1</b> Overview</a></li>
<li class="chapter" data-level="3.2" data-path="wrangling.html"><a href="wrangling.html#chapter-learning-objectives-2"><i class="fa fa-check"></i><b>3.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="3.3" data-path="wrangling.html"><a href="wrangling.html#vectors-and-data-frames"><i class="fa fa-check"></i><b>3.3</b> Vectors and Data frames</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="wrangling.html"><a href="wrangling.html#what-is-a-data-frame"><i class="fa fa-check"></i><b>3.3.1</b> What is a data frame?</a></li>
<li class="chapter" data-level="3.3.2" data-path="wrangling.html"><a href="wrangling.html#what-is-a-vector"><i class="fa fa-check"></i><b>3.3.2</b> What is a vector?</a></li>
<li class="chapter" data-level="3.3.3" data-path="wrangling.html"><a href="wrangling.html#how-are-vectors-different-from-a-list"><i class="fa fa-check"></i><b>3.3.3</b> How are vectors different from a list?</a></li>
<li class="chapter" data-level="3.3.4" data-path="wrangling.html"><a href="wrangling.html#what-does-this-have-to-do-with-data-frames"><i class="fa fa-check"></i><b>3.3.4</b> What does this have to do with data frames?</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="wrangling.html"><a href="wrangling.html#tidy-data"><i class="fa fa-check"></i><b>3.4</b> Tidy Data</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="wrangling.html"><a href="wrangling.html#what-is-tidy-data"><i class="fa fa-check"></i><b>3.4.1</b> What is tidy data?</a></li>
<li class="chapter" data-level="3.4.2" data-path="wrangling.html"><a href="wrangling.html#why-is-tidy-data-important-in-r"><i class="fa fa-check"></i><b>3.4.2</b> Why is tidy data important in R?</a></li>
<li class="chapter" data-level="3.4.3" data-path="wrangling.html"><a href="wrangling.html#going-from-wide-to-long-or-tidy-using-pivot_longer"><i class="fa fa-check"></i><b>3.4.3</b> Going from wide to long (or tidy!) using <code>pivot_longer</code></a></li>
<li class="chapter" data-level="3.4.4" data-path="wrangling.html"><a href="wrangling.html#going-from-long-to-wide-using-pivot_wider"><i class="fa fa-check"></i><b>3.4.4</b> Going from long to wide using <code>pivot_wider</code></a></li>
<li class="chapter" data-level="3.4.5" data-path="wrangling.html"><a href="wrangling.html#using-separate-to-deal-with-multiple-delimiters"><i class="fa fa-check"></i><b>3.4.5</b> Using <code>separate</code> to deal with multiple delimiters</a></li>
<li class="chapter" data-level="3.4.6" data-path="wrangling.html"><a href="wrangling.html#notes-on-defining-tidy-data"><i class="fa fa-check"></i><b>3.4.6</b> Notes on defining tidy data</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="wrangling.html"><a href="wrangling.html#combining-functions-using-the-pipe-operator"><i class="fa fa-check"></i><b>3.5</b> Combining functions using the pipe operator, <code>%&gt;%</code>:</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="wrangling.html"><a href="wrangling.html#using-to-combine-filter-and-select"><i class="fa fa-check"></i><b>3.5.1</b> Using <code>%&gt;%</code> to combine <code>filter</code> and <code>select</code></a></li>
<li class="chapter" data-level="3.5.2" data-path="wrangling.html"><a href="wrangling.html#using-with-more-than-two-functions"><i class="fa fa-check"></i><b>3.5.2</b> Using <code>%&gt;%</code> with more than two functions</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="wrangling.html"><a href="wrangling.html#iterating-over-data-with-group_by-summarize"><i class="fa fa-check"></i><b>3.6</b> Iterating over data with <code>group_by</code> + <code>summarize</code></a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="wrangling.html"><a href="wrangling.html#calculating-summary-statistics"><i class="fa fa-check"></i><b>3.6.1</b> Calculating summary statistics:</a></li>
<li class="chapter" data-level="3.6.2" data-path="wrangling.html"><a href="wrangling.html#calculating-group-summary-statistics"><i class="fa fa-check"></i><b>3.6.2</b> Calculating group summary statistics:</a></li>
<li class="chapter" data-level="3.6.3" data-path="wrangling.html"><a href="wrangling.html#additional-reading-on-the-dplyr-functions"><i class="fa fa-check"></i><b>3.6.3</b> Additional reading on the <code>dplyr</code> functions</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="wrangling.html"><a href="wrangling.html#using-purrrs-map-functions-to-iterate"><i class="fa fa-check"></i><b>3.7</b> Using <code>purrr</code>’s <code>map*</code> functions to iterate</a></li>
<li class="chapter" data-level="3.8" data-path="wrangling.html"><a href="wrangling.html#additional-resources-1"><i class="fa fa-check"></i><b>3.8</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="viz.html"><a href="viz.html"><i class="fa fa-check"></i><b>4</b> Effective data visualization</a>
<ul>
<li class="chapter" data-level="4.1" data-path="viz.html"><a href="viz.html#overview-2"><i class="fa fa-check"></i><b>4.1</b> Overview</a></li>
<li class="chapter" data-level="4.2" data-path="viz.html"><a href="viz.html#chapter-learning-objectives-3"><i class="fa fa-check"></i><b>4.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="4.3" data-path="viz.html"><a href="viz.html#choosing-the-visualization"><i class="fa fa-check"></i><b>4.3</b> Choosing the visualization</a></li>
<li class="chapter" data-level="4.4" data-path="viz.html"><a href="viz.html#refining-the-visualization"><i class="fa fa-check"></i><b>4.4</b> Refining the visualization</a></li>
<li class="chapter" data-level="4.5" data-path="viz.html"><a href="viz.html#creating-visualizations-with-ggplot2"><i class="fa fa-check"></i><b>4.5</b> Creating visualizations with <code>ggplot2</code></a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="viz.html"><a href="viz.html#the-mauna-loa-co2-data-set"><i class="fa fa-check"></i><b>4.5.1</b> The Mauna Loa CO2 data set</a></li>
<li class="chapter" data-level="4.5.2" data-path="viz.html"><a href="viz.html#the-island-landmass-data-set"><i class="fa fa-check"></i><b>4.5.2</b> The island landmass data set</a></li>
<li class="chapter" data-level="4.5.3" data-path="viz.html"><a href="viz.html#the-old-faithful-eruptionwaiting-time-data-set"><i class="fa fa-check"></i><b>4.5.3</b> The Old Faithful eruption/waiting time data set</a></li>
<li class="chapter" data-level="4.5.4" data-path="viz.html"><a href="viz.html#the-michelson-speed-of-light-data-set"><i class="fa fa-check"></i><b>4.5.4</b> The Michelson speed of light data set</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="viz.html"><a href="viz.html#explaining-the-visualization"><i class="fa fa-check"></i><b>4.6</b> Explaining the visualization</a></li>
<li class="chapter" data-level="4.7" data-path="viz.html"><a href="viz.html#saving-the-visualization"><i class="fa fa-check"></i><b>4.7</b> Saving the visualization</a></li>
<li class="chapter" data-level="4.8" data-path="viz.html"><a href="viz.html#additional-resources-2"><i class="fa fa-check"></i><b>4.8</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="version-control.html"><a href="version-control.html"><i class="fa fa-check"></i><b>5</b> Collaboration with version control</a>
<ul>
<li class="chapter" data-level="5.1" data-path="version-control.html"><a href="version-control.html#overview-3"><i class="fa fa-check"></i><b>5.1</b> Overview</a></li>
<li class="chapter" data-level="5.2" data-path="version-control.html"><a href="version-control.html#chapter-learning-objectives-4"><i class="fa fa-check"></i><b>5.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="5.3" data-path="version-control.html"><a href="version-control.html#what-is-version-control-and-why-should-i-use-it"><i class="fa fa-check"></i><b>5.3</b> What is version control, and why should I use it?</a></li>
<li class="chapter" data-level="5.4" data-path="version-control.html"><a href="version-control.html#creating-a-space-for-your-project-online"><i class="fa fa-check"></i><b>5.4</b> Creating a space for your project online</a></li>
<li class="chapter" data-level="5.5" data-path="version-control.html"><a href="version-control.html#creating-and-editing-files-on-github"><i class="fa fa-check"></i><b>5.5</b> Creating and editing files on GitHub</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="version-control.html"><a href="version-control.html#the-pen-tool"><i class="fa fa-check"></i><b>5.5.1</b> The pen tool</a></li>
<li class="chapter" data-level="5.5.2" data-path="version-control.html"><a href="version-control.html#the-add-file-menu"><i class="fa fa-check"></i><b>5.5.2</b> The “Add file” menu</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="version-control.html"><a href="version-control.html#cloning-your-repository-on-jupyterhub"><i class="fa fa-check"></i><b>5.6</b> Cloning your repository on JupyterHub</a></li>
<li class="chapter" data-level="5.7" data-path="version-control.html"><a href="version-control.html#working-in-a-cloned-repository-on-jupyterhub"><i class="fa fa-check"></i><b>5.7</b> Working in a cloned repository on JupyterHub</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="version-control.html"><a href="version-control.html#specifying-files-to-commit"><i class="fa fa-check"></i><b>5.7.1</b> Specifying files to commit</a></li>
<li class="chapter" data-level="5.7.2" data-path="version-control.html"><a href="version-control.html#making-the-commit"><i class="fa fa-check"></i><b>5.7.2</b> Making the commit</a></li>
<li class="chapter" data-level="5.7.3" data-path="version-control.html"><a href="version-control.html#pushing-the-commits-to-github"><i class="fa fa-check"></i><b>5.7.3</b> Pushing the commits to GitHub</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="version-control.html"><a href="version-control.html#collaboration"><i class="fa fa-check"></i><b>5.8</b> Collaboration</a>
<ul>
<li class="chapter" data-level="5.8.1" data-path="version-control.html"><a href="version-control.html#giving-collaborators-access-to-your-project"><i class="fa fa-check"></i><b>5.8.1</b> Giving collaborators access to your project</a></li>
<li class="chapter" data-level="5.8.2" data-path="version-control.html"><a href="version-control.html#pulling-changes-from-github"><i class="fa fa-check"></i><b>5.8.2</b> Pulling changes from GitHub</a></li>
<li class="chapter" data-level="5.8.3" data-path="version-control.html"><a href="version-control.html#handling-merge-conflicts"><i class="fa fa-check"></i><b>5.8.3</b> Handling merge conflicts</a></li>
<li class="chapter" data-level="5.8.4" data-path="version-control.html"><a href="version-control.html#communicating-using-github-issues"><i class="fa fa-check"></i><b>5.8.4</b> Communicating using GitHub issues</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="version-control.html"><a href="version-control.html#additional-resources-3"><i class="fa fa-check"></i><b>5.9</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="classification.html"><a href="classification.html"><i class="fa fa-check"></i><b>6</b> Classification I: training &amp; predicting</a>
<ul>
<li class="chapter" data-level="6.1" data-path="classification.html"><a href="classification.html#overview-4"><i class="fa fa-check"></i><b>6.1</b> Overview</a></li>
<li class="chapter" data-level="6.2" data-path="classification.html"><a href="classification.html#chapter-learning-objectives-5"><i class="fa fa-check"></i><b>6.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="6.3" data-path="classification.html"><a href="classification.html#the-classification-problem"><i class="fa fa-check"></i><b>6.3</b> The classification problem</a></li>
<li class="chapter" data-level="6.4" data-path="classification.html"><a href="classification.html#exploring-a-labelled-data-set"><i class="fa fa-check"></i><b>6.4</b> Exploring a labelled data set</a></li>
<li class="chapter" data-level="6.5" data-path="classification.html"><a href="classification.html#classification-with-k-nearest-neighbours"><i class="fa fa-check"></i><b>6.5</b> Classification with K-nearest neighbours</a></li>
<li class="chapter" data-level="6.6" data-path="classification.html"><a href="classification.html#k-nearest-neighbours-with-tidymodels"><i class="fa fa-check"></i><b>6.6</b> K-nearest neighbours with <code>tidymodels</code></a></li>
<li class="chapter" data-level="6.7" data-path="classification.html"><a href="classification.html#data-preprocessing-with-tidymodels"><i class="fa fa-check"></i><b>6.7</b> Data preprocessing with <code>tidymodels</code></a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="classification.html"><a href="classification.html#centering-and-scaling"><i class="fa fa-check"></i><b>6.7.1</b> Centering and scaling</a></li>
<li class="chapter" data-level="6.7.2" data-path="classification.html"><a href="classification.html#balancing"><i class="fa fa-check"></i><b>6.7.2</b> Balancing</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="classification.html"><a href="classification.html#putting-it-together-in-a-workflow"><i class="fa fa-check"></i><b>6.8</b> Putting it together in a <code>workflow</code></a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="classification-continued.html"><a href="classification-continued.html"><i class="fa fa-check"></i><b>7</b> Classification II: evaluation &amp; tuning</a>
<ul>
<li class="chapter" data-level="7.1" data-path="classification-continued.html"><a href="classification-continued.html#overview-5"><i class="fa fa-check"></i><b>7.1</b> Overview</a></li>
<li class="chapter" data-level="7.2" data-path="classification-continued.html"><a href="classification-continued.html#chapter-learning-objectives-6"><i class="fa fa-check"></i><b>7.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="7.3" data-path="classification-continued.html"><a href="classification-continued.html#evaluating-accuracy"><i class="fa fa-check"></i><b>7.3</b> Evaluating accuracy</a></li>
<li class="chapter" data-level="7.4" data-path="classification-continued.html"><a href="classification-continued.html#tuning-the-classifier"><i class="fa fa-check"></i><b>7.4</b> Tuning the classifier</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="classification-continued.html"><a href="classification-continued.html#cross-validation"><i class="fa fa-check"></i><b>7.4.1</b> Cross-validation</a></li>
<li class="chapter" data-level="7.4.2" data-path="classification-continued.html"><a href="classification-continued.html#parameter-value-selection"><i class="fa fa-check"></i><b>7.4.2</b> Parameter value selection</a></li>
<li class="chapter" data-level="7.4.3" data-path="classification-continued.html"><a href="classification-continued.html#underoverfitting"><i class="fa fa-check"></i><b>7.4.3</b> Under/overfitting</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="classification-continued.html"><a href="classification-continued.html#splitting-data"><i class="fa fa-check"></i><b>7.5</b> Splitting data</a></li>
<li class="chapter" data-level="7.6" data-path="classification-continued.html"><a href="classification-continued.html#summary"><i class="fa fa-check"></i><b>7.6</b> Summary</a></li>
<li class="chapter" data-level="7.7" data-path="classification-continued.html"><a href="classification-continued.html#additional-resources-4"><i class="fa fa-check"></i><b>7.7</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="regression1.html"><a href="regression1.html"><i class="fa fa-check"></i><b>8</b> Regression I: K-nearest neighbours</a>
<ul>
<li class="chapter" data-level="8.1" data-path="regression1.html"><a href="regression1.html#overview-6"><i class="fa fa-check"></i><b>8.1</b> Overview</a></li>
<li class="chapter" data-level="8.2" data-path="regression1.html"><a href="regression1.html#chapter-learning-objectives-7"><i class="fa fa-check"></i><b>8.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="8.3" data-path="regression1.html"><a href="regression1.html#regression"><i class="fa fa-check"></i><b>8.3</b> Regression</a></li>
<li class="chapter" data-level="8.4" data-path="regression1.html"><a href="regression1.html#exploring-a-labelled-data-set-1"><i class="fa fa-check"></i><b>8.4</b> Exploring a labelled data set</a></li>
<li class="chapter" data-level="8.5" data-path="regression1.html"><a href="regression1.html#k-nearest-neighbours-regression"><i class="fa fa-check"></i><b>8.5</b> K-nearest neighbours regression</a></li>
<li class="chapter" data-level="8.6" data-path="regression1.html"><a href="regression1.html#training-evaluating-and-tuning-the-model"><i class="fa fa-check"></i><b>8.6</b> Training, evaluating, and tuning the model</a></li>
<li class="chapter" data-level="8.7" data-path="regression1.html"><a href="regression1.html#underfitting-and-overfitting"><i class="fa fa-check"></i><b>8.7</b> Underfitting and overfitting</a></li>
<li class="chapter" data-level="8.8" data-path="regression1.html"><a href="regression1.html#evaluating-on-the-test-set"><i class="fa fa-check"></i><b>8.8</b> Evaluating on the test set</a></li>
<li class="chapter" data-level="8.9" data-path="regression1.html"><a href="regression1.html#strengths-and-limitations-of-k-nn-regression"><i class="fa fa-check"></i><b>8.9</b> Strengths and limitations of K-NN regression</a></li>
<li class="chapter" data-level="8.10" data-path="regression1.html"><a href="regression1.html#multivariate-k-nn-regression"><i class="fa fa-check"></i><b>8.10</b> Multivariate K-NN regression</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="regression2.html"><a href="regression2.html"><i class="fa fa-check"></i><b>9</b> Regression II: linear regression</a>
<ul>
<li class="chapter" data-level="9.1" data-path="regression2.html"><a href="regression2.html#overview-7"><i class="fa fa-check"></i><b>9.1</b> Overview</a></li>
<li class="chapter" data-level="9.2" data-path="regression2.html"><a href="regression2.html#chapter-learning-objectives-8"><i class="fa fa-check"></i><b>9.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="9.3" data-path="regression2.html"><a href="regression2.html#simple-linear-regression"><i class="fa fa-check"></i><b>9.3</b> Simple linear regression</a></li>
<li class="chapter" data-level="9.4" data-path="regression2.html"><a href="regression2.html#linear-regression-in-r"><i class="fa fa-check"></i><b>9.4</b> Linear regression in R</a></li>
<li class="chapter" data-level="9.5" data-path="regression2.html"><a href="regression2.html#comparing-simple-linear-and-k-nn-regression"><i class="fa fa-check"></i><b>9.5</b> Comparing simple linear and K-NN regression</a></li>
<li class="chapter" data-level="9.6" data-path="regression2.html"><a href="regression2.html#multivariate-linear-regression"><i class="fa fa-check"></i><b>9.6</b> Multivariate linear regression</a></li>
<li class="chapter" data-level="9.7" data-path="regression2.html"><a href="regression2.html#the-other-side-of-regression"><i class="fa fa-check"></i><b>9.7</b> The other side of regression</a></li>
<li class="chapter" data-level="9.8" data-path="regression2.html"><a href="regression2.html#additional-resources-5"><i class="fa fa-check"></i><b>9.8</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="clustering.html"><a href="clustering.html"><i class="fa fa-check"></i><b>10</b> Clustering</a>
<ul>
<li class="chapter" data-level="10.1" data-path="clustering.html"><a href="clustering.html#overview-8"><i class="fa fa-check"></i><b>10.1</b> Overview</a></li>
<li class="chapter" data-level="10.2" data-path="clustering.html"><a href="clustering.html#chapter-learning-objectives-9"><i class="fa fa-check"></i><b>10.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="10.3" data-path="clustering.html"><a href="clustering.html#clustering-1"><i class="fa fa-check"></i><b>10.3</b> Clustering</a></li>
<li class="chapter" data-level="10.4" data-path="clustering.html"><a href="clustering.html#k-means"><i class="fa fa-check"></i><b>10.4</b> K-means</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="clustering.html"><a href="clustering.html#measuring-cluster-quality"><i class="fa fa-check"></i><b>10.4.1</b> Measuring cluster quality</a></li>
<li class="chapter" data-level="10.4.2" data-path="clustering.html"><a href="clustering.html#the-clustering-algorithm"><i class="fa fa-check"></i><b>10.4.2</b> The clustering algorithm</a></li>
<li class="chapter" data-level="10.4.3" data-path="clustering.html"><a href="clustering.html#random-restarts"><i class="fa fa-check"></i><b>10.4.3</b> Random restarts</a></li>
<li class="chapter" data-level="10.4.4" data-path="clustering.html"><a href="clustering.html#choosing-k"><i class="fa fa-check"></i><b>10.4.4</b> Choosing K</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="clustering.html"><a href="clustering.html#data-pre-processing-for-k-means"><i class="fa fa-check"></i><b>10.5</b> Data pre-processing for K-means</a></li>
<li class="chapter" data-level="10.6" data-path="clustering.html"><a href="clustering.html#k-means-in-r"><i class="fa fa-check"></i><b>10.6</b> K-means in R</a></li>
<li class="chapter" data-level="10.7" data-path="clustering.html"><a href="clustering.html#additional-resources-6"><i class="fa fa-check"></i><b>10.7</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="inference.html"><a href="inference.html"><i class="fa fa-check"></i><b>11</b> Introduction to Statistical Inference</a>
<ul>
<li class="chapter" data-level="11.1" data-path="inference.html"><a href="inference.html#overview-9"><i class="fa fa-check"></i><b>11.1</b> Overview</a></li>
<li class="chapter" data-level="11.2" data-path="inference.html"><a href="inference.html#chapter-learning-objectives-10"><i class="fa fa-check"></i><b>11.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="11.3" data-path="inference.html"><a href="inference.html#why-do-we-need-sampling"><i class="fa fa-check"></i><b>11.3</b> Why do we need sampling?</a></li>
<li class="chapter" data-level="11.4" data-path="inference.html"><a href="inference.html#sampling-distributions"><i class="fa fa-check"></i><b>11.4</b> Sampling distributions</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="inference.html"><a href="inference.html#sampling-distributions-for-proportions"><i class="fa fa-check"></i><b>11.4.1</b> Sampling distributions for proportions</a></li>
<li class="chapter" data-level="11.4.2" data-path="inference.html"><a href="inference.html#sampling-distributions-for-means"><i class="fa fa-check"></i><b>11.4.2</b> Sampling distributions for means</a></li>
<li class="chapter" data-level="11.4.3" data-path="inference.html"><a href="inference.html#summary-1"><i class="fa fa-check"></i><b>11.4.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="inference.html"><a href="inference.html#bootstrapping"><i class="fa fa-check"></i><b>11.5</b> Bootstrapping</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="inference.html"><a href="inference.html#overview-10"><i class="fa fa-check"></i><b>11.5.1</b> Overview</a></li>
<li class="chapter" data-level="11.5.2" data-path="inference.html"><a href="inference.html#bootstrapping-in-r"><i class="fa fa-check"></i><b>11.5.2</b> Bootstrapping in R</a></li>
<li class="chapter" data-level="11.5.3" data-path="inference.html"><a href="inference.html#using-the-bootstrap-to-calculate-a-plausible-range"><i class="fa fa-check"></i><b>11.5.3</b> Using the bootstrap to calculate a plausible range</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="inference.html"><a href="inference.html#additional-resources-7"><i class="fa fa-check"></i><b>11.6</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html"><i class="fa fa-check"></i><b>12</b> Moving to your own machine</a>
<ul>
<li class="chapter" data-level="12.1" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#overview-11"><i class="fa fa-check"></i><b>12.1</b> Overview</a></li>
<li class="chapter" data-level="12.2" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#chapter-learning-objectives-11"><i class="fa fa-check"></i><b>12.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="12.3" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#installing-software-on-your-own-computer"><i class="fa fa-check"></i><b>12.3</b> Installing software on your own computer</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#git"><i class="fa fa-check"></i><b>12.3.1</b> Git</a></li>
<li class="chapter" data-level="12.3.2" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#miniconda"><i class="fa fa-check"></i><b>12.3.2</b> Miniconda</a></li>
<li class="chapter" data-level="12.3.3" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#jupyterlab"><i class="fa fa-check"></i><b>12.3.3</b> JupyterLab</a></li>
<li class="chapter" data-level="12.3.4" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#r-and-the-irkernel"><i class="fa fa-check"></i><b>12.3.4</b> R and the IRkernel</a></li>
<li class="chapter" data-level="12.3.5" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#r-packages"><i class="fa fa-check"></i><b>12.3.5</b> R packages</a></li>
<li class="chapter" data-level="12.3.6" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#latex"><i class="fa fa-check"></i><b>12.3.6</b> LaTeX</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#moving-files-to-your-computer"><i class="fa fa-check"></i><b>12.4</b> Moving files to your computer</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Science: A First Introduction</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="inference" class="section level1" number="11">
<h1><span class="header-section-number">Chapter 11</span> Introduction to Statistical Inference</h1>
<div id="overview-9" class="section level2" number="11.1">
<h2><span class="header-section-number">11.1</span> Overview</h2>
<p>A typical data analysis task in practice is to draw conclusions about some unknown
aspect of a population of interest based on observed data sampled from that
population; we typically do not get data on the <em>entire</em> population.
Data analysis questions regarding how summaries,
patterns, trends, or relationships in a data set
extend to the wider population are called <em>inferential questions</em>. This chapter will start
with the fundamental ideas of sampling from populations and then introduce two common techniques in statistical inference: <em>point estimation</em> and
<em>interval estimation</em>.</p>
</div>
<div id="chapter-learning-objectives-10" class="section level2" number="11.2">
<h2><span class="header-section-number">11.2</span> Chapter learning objectives</h2>
<p>By the end of the chapter, students will be able to:</p>
<ul>
<li>Describe real-world examples of questions that can be answered with the statistical inference.</li>
<li>Define common population parameters (e.g. mean, proportion, standard deviation) that are often estimated using sampled data, and estimate these from a sample.</li>
<li>Define the following statistical sampling terms (population, sample, population parameter, point estimate, sampling distribution).</li>
<li>Explain the difference between a population parameter and sample point estimate.</li>
<li>Use R to draw random samples from a finite population.</li>
<li>Use R to create a sampling distribution from a finite population.</li>
<li>Describe how sample size influences the sampling distribution.</li>
<li>Define bootstrapping.</li>
<li>Use R to create a bootstrap distribution to approximate a sampling distribution.</li>
<li>Contrast the bootstrap and sampling distributions.</li>
</ul>
</div>
<div id="why-do-we-need-sampling" class="section level2" number="11.3">
<h2><span class="header-section-number">11.3</span> Why do we need sampling?</h2>
<p>Statistical inference can help us decide how quantities we observe in
a subset of data relate to the same quantities in the broader
population. Suppose a retailer is considering selling iPhone accessories, and they want to estimate how big the market might be. Additionally, they want to strategize how they can market their products on North American college and university campuses. This retailer might use statistical inference to answer the question:</p>
<p><em>What proportion of all undergraduate students in North America own an iPhone?</em></p>
<p>In the above question, we are interested in making a conclusion about <em>all</em>
undergraduate students in North America; this is our <strong>population</strong>.
In general, the population is the complete collection of individuals or cases we are interested in studying.
Further, in the above question, we are interested in computing a quantity—the proportion
of iPhone owners—based on the entire population. This is our <strong>population parameter</strong>.
In general, a population parameter is a numerical characteristic
of the entire population. To compute this number in the example above, we would need to ask
every single undergraduate in North America whether or not they own an iPhone. In practice,
directly computing population parameters is often time-consuming and costly, and sometimes impossible.</p>
<p>A more practical approach would be to collect measurements for a <strong>sample</strong>: a subset of
individuals collected from the population. We can then compute a <strong>sample estimate</strong>—a numerical
characteristic of the sample—that estimates the population parameter. For example, suppose we randomly selected 100 undergraduate students across North America (the sample) and computed the proportion of those
students who own an iPhone (the sample estimate). In that case, we might suspect that that proportion is a reasonable estimate of the proportion of students who own an iPhone in the entire population.</p>
<div class="figure"><span id="fig:11-population-vs-sample"></span>
<img src="img/population_vs_sample.svg" alt="Population versus sample"  />
<p class="caption">
Figure 11.1: Population versus sample
</p>
</div>
</center>
<p>Note that proportions are not the <em>only</em> kind of population parameter we might be interested in. Suppose an undergraduate student studying at the University of British Columbia in Vancouver, British Columbia, is looking for an apartment to rent. They need to create a budget, so they want to know something about studio apartment rental prices in Vancouver, BC. This student might use statistical inference to tackle the question:</p>
<p><em>What is the average price-per-month of studio apartment rentals in Vancouver, Canada?</em></p>
<p>The population consists of all studio apartment rentals in Vancouver, and the population parameter is the <em>average price-per-month</em>. Here we used the average as a measure of center to describe the “typical value” of studio apartment rental prices. But even within this one example, we could also be interested in many other population parameters. For instance, we know that not every studio apartment rental in Vancouver will have the same price-per-month. The student might be interested in how much monthly prices vary and want to find a measure of the rentals’ spread (or variability), such as the standard deviation. We might be interested in the fraction of studio apartment rentals that cost more than $1000 per month. And the list of population parameters we might want to calculate goes on. The question we want to answer will help us determine the parameter we want to estimate. If we were somehow able to observe the whole population of studio apartment rental offerings in Vancouver, we could compute each of these numbers exactly; therefore, these are all population parameters. There are many kinds of observations and population parameters that you will run into in practice, but in this chapter, we will focus on two settings:</p>
<ol style="list-style-type: decimal">
<li>Using categorical observations to estimate the proportion of each category</li>
<li>Using quantitative observations to estimate the average (or mean)</li>
</ol>
</div>
<div id="sampling-distributions" class="section level2" number="11.4">
<h2><span class="header-section-number">11.4</span> Sampling distributions</h2>
<div id="sampling-distributions-for-proportions" class="section level3" number="11.4.1">
<h3><span class="header-section-number">11.4.1</span> Sampling distributions for proportions</h3>
<p>Let’s start with an illustrative (and tasty!) example. Timbits are
bite-sized doughnuts sold at Tim Hortons, a popular Canadian-based fast-food restaurant
chain founded in Hamilton, Ontario, Canada.</p>
<div class="figure"><span id="fig:11-timbits-picture"></span>
<img src="img/timbits.jpg" alt="A box of Timbits" width="30%" />
<p class="caption">
Figure 11.2: A box of Timbits
</p>
</div>
<p>Suppose we wanted to estimate the true proportion of chocolate doughnuts at Tim
Hortons restaurants. Now, of course, we (the authors!) do not have access to the true population.
So for this chapter, we created a fictitious box of 10,000 Timbits with two flavours—old-fashioned
and chocolate—as our population, and use this to illustrate
inferential concepts. Below we have a <code>tibble()</code> called <code>virtual_box</code> with a Timbit ID and flavour as our columns. We have also loaded our necessary packages: <code>tidyverse</code> and the <code>infer</code> package, which we will need to perform sampling later in the chapter.</p>
<div class="sourceCode" id="cb310"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb310-1"><a href="inference.html#cb310-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb310-2"><a href="inference.html#cb310-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(infer)</span>
<span id="cb310-3"><a href="inference.html#cb310-3" aria-hidden="true" tabindex="-1"></a>virtual_box</span></code></pre></div>
<pre><code>## # A tibble: 10,000 x 2
##    timbit_id flavour      
##        &lt;dbl&gt; &lt;fct&gt;        
##  1         1 chocolate    
##  2         2 old fashioned
##  3         3 chocolate    
##  4         4 chocolate    
##  5         5 chocolate    
##  6         6 old fashioned
##  7         7 chocolate    
##  8         8 chocolate    
##  9         9 old fashioned
## 10        10 old fashioned
## # … with 9,990 more rows</code></pre>
<p>From our simulated box, we can see that the proportion of chocolate Timbits is
0.63. This value, 0.63, is the <em>population parameter</em>. Note that this parameter value is usually unknown in real data analysis problems.</p>
<div class="sourceCode" id="cb312"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb312-1"><a href="inference.html#cb312-1" aria-hidden="true" tabindex="-1"></a>virtual_box <span class="sc">%&gt;%</span></span>
<span id="cb312-2"><a href="inference.html#cb312-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(flavour) <span class="sc">%&gt;%</span></span>
<span id="cb312-3"><a href="inference.html#cb312-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb312-4"><a href="inference.html#cb312-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb312-5"><a href="inference.html#cb312-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">proportion =</span> <span class="fu">n</span>() <span class="sc">/</span> <span class="dv">10000</span></span>
<span id="cb312-6"><a href="inference.html#cb312-6" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 2 x 3
##   flavour           n proportion
##   &lt;fct&gt;         &lt;int&gt;      &lt;dbl&gt;
## 1 old fashioned  3751      0.375
## 2 chocolate      6249      0.625</code></pre>
<p>What would happen if we were to buy a box of 40 randomly-selected Timbits and count the number of chocolate Timbits (<em>i.e.,</em> take a random sample of size 40 from our Timbits population)? Let’s use R to simulate this using our <code>virtual_box</code> population. We can do this using the <code>rep_sample_n</code> function from the <code>infer</code> package. The arguments
of <code>rep_sample_n</code> are (1) the data frame (or tibble) to sample from, and (2) the size of the sample to take.</p>
<div class="sourceCode" id="cb314"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb314-1"><a href="inference.html#cb314-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb314-2"><a href="inference.html#cb314-2" aria-hidden="true" tabindex="-1"></a>samples_1 <span class="ot">&lt;-</span> <span class="fu">rep_sample_n</span>(<span class="at">tbl =</span> virtual_box, <span class="at">size =</span> <span class="dv">40</span>)</span>
<span id="cb314-3"><a href="inference.html#cb314-3" aria-hidden="true" tabindex="-1"></a>choc_sample_1 <span class="ot">&lt;-</span> <span class="fu">summarize</span>(samples_1,</span>
<span id="cb314-4"><a href="inference.html#cb314-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> <span class="fu">sum</span>(flavour <span class="sc">==</span> <span class="st">&quot;chocolate&quot;</span>),</span>
<span id="cb314-5"><a href="inference.html#cb314-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">prop =</span> <span class="fu">sum</span>(flavour <span class="sc">==</span> <span class="st">&quot;chocolate&quot;</span>) <span class="sc">/</span> <span class="dv">40</span></span>
<span id="cb314-6"><a href="inference.html#cb314-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb314-7"><a href="inference.html#cb314-7" aria-hidden="true" tabindex="-1"></a>choc_sample_1</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   replicate     n  prop
##       &lt;int&gt; &lt;int&gt; &lt;dbl&gt;
## 1         1    24   0.6</code></pre>
<p>Here we see that the proportion of chocolate Timbits in this random sample is
0.6. This value is our estimate — our best guess of our population parameter using this sample. Given that it is a single
value that we are estimating, we often refer to it as a <strong>point estimate</strong>.</p>
<p>Now imagine we took another random sample of 40 Timbits from the population. Do you
think we would get the same proportion? Let’s try sampling from the population
again and see what happens.</p>
<div class="sourceCode" id="cb316"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb316-1"><a href="inference.html#cb316-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2</span>)</span>
<span id="cb316-2"><a href="inference.html#cb316-2" aria-hidden="true" tabindex="-1"></a>samples_2 <span class="ot">&lt;-</span> <span class="fu">rep_sample_n</span>(virtual_box, <span class="at">size =</span> <span class="dv">40</span>)</span>
<span id="cb316-3"><a href="inference.html#cb316-3" aria-hidden="true" tabindex="-1"></a>choc_sample_2 <span class="ot">&lt;-</span> <span class="fu">summarize</span>(samples_2,</span>
<span id="cb316-4"><a href="inference.html#cb316-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> <span class="fu">sum</span>(flavour <span class="sc">==</span> <span class="st">&quot;chocolate&quot;</span>),</span>
<span id="cb316-5"><a href="inference.html#cb316-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">prop =</span> <span class="fu">sum</span>(flavour <span class="sc">==</span> <span class="st">&quot;chocolate&quot;</span>) <span class="sc">/</span> <span class="dv">40</span></span>
<span id="cb316-6"><a href="inference.html#cb316-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb316-7"><a href="inference.html#cb316-7" aria-hidden="true" tabindex="-1"></a>choc_sample_2</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   replicate     n  prop
##       &lt;int&gt; &lt;int&gt; &lt;dbl&gt;
## 1         1    26  0.65</code></pre>
<p>Notice that we get a different value for our estimate this time. The
proportion of chocolate Timbits in this sample is 0.65.
If we were to do this again, another random sample could also give a
different result. Estimates vary from sample to sample
due to <strong>sampling variability</strong>.</p>
<p>But just how much should we expect the estimates of our random
samples to vary? In order to understand this, we will simulate taking more samples
of size 40 from our population of Timbits, and calculate the
proportion of chocolate Timbits in each sample. We can then
visualize the distribution of sample proportions we calculate. The distribution
of the estimate for all possible samples of a given size (which we commonly refer to as <span class="math inline">\(n\)</span>) from a population is
called a <strong>sampling distribution</strong>. The sampling distribution will help us see
how much we would expect our sample proportions from this population to vary
for samples of size 40. Below we again use the <code>rep_sample_n</code> to take samples
of size 40 from our population of Timbits, but we set the <code>reps</code> argument
to specify the number of samples to take, here 15,000. We will use the function <code>tail()</code> to see the last few rows of our <code>samples</code> data frame.</p>
<div class="sourceCode" id="cb318"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb318-1"><a href="inference.html#cb318-1" aria-hidden="true" tabindex="-1"></a>samples <span class="ot">&lt;-</span> <span class="fu">rep_sample_n</span>(virtual_box, <span class="at">size =</span> <span class="dv">40</span>, <span class="at">reps =</span> <span class="dv">15000</span>)</span>
<span id="cb318-2"><a href="inference.html#cb318-2" aria-hidden="true" tabindex="-1"></a>samples</span></code></pre></div>
<pre><code>## # A tibble: 600,000 x 3
## # Groups:   replicate [15,000]
##    replicate timbit_id flavour      
##        &lt;int&gt;     &lt;dbl&gt; &lt;fct&gt;        
##  1         1      4419 old fashioned
##  2         1      6533 chocolate    
##  3         1      8005 chocolate    
##  4         1      7419 chocolate    
##  5         1      2649 old fashioned
##  6         1       510 chocolate    
##  7         1      4974 chocolate    
##  8         1      3647 chocolate    
##  9         1      6717 chocolate    
## 10         1         4 chocolate    
## # … with 599,990 more rows</code></pre>
<div class="sourceCode" id="cb320"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb320-1"><a href="inference.html#cb320-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(samples)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
## # Groups:   replicate [1]
##   replicate timbit_id flavour      
##       &lt;int&gt;     &lt;dbl&gt; &lt;fct&gt;        
## 1     15000       525 chocolate    
## 2     15000      8931 chocolate    
## 3     15000      6080 old fashioned
## 4     15000      1026 old fashioned
## 5     15000      6388 chocolate    
## 6     15000      7814 chocolate</code></pre>
<p>Notice the column <code>replicate</code> is indicating the replicate, or sample, with which each
Timbit belongs. Since we took 15,000 samples of size 40, there are 15,000 replicates.
Now that we have taken 15,000 samples, to create a sampling distribution of sample proportions for samples of size 40, we need to calculate the proportion of chocolate Timbits for each sample, <span class="math inline">\(\hat{p}_\text{chocolate}\)</span>:</p>
<div class="sourceCode" id="cb322"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb322-1"><a href="inference.html#cb322-1" aria-hidden="true" tabindex="-1"></a>sample_estimates <span class="ot">&lt;-</span> samples <span class="sc">%&gt;%</span></span>
<span id="cb322-2"><a href="inference.html#cb322-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(replicate) <span class="sc">%&gt;%</span></span>
<span id="cb322-3"><a href="inference.html#cb322-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">sample_proportion =</span> <span class="fu">sum</span>(flavour <span class="sc">==</span> <span class="st">&quot;chocolate&quot;</span>) <span class="sc">/</span> <span class="dv">40</span>)</span>
<span id="cb322-4"><a href="inference.html#cb322-4" aria-hidden="true" tabindex="-1"></a>sample_estimates</span></code></pre></div>
<pre><code>## # A tibble: 15,000 x 2
##    replicate sample_proportion
##        &lt;int&gt;             &lt;dbl&gt;
##  1         1             0.675
##  2         2             0.85 
##  3         3             0.7  
##  4         4             0.425
##  5         5             0.65 
##  6         6             0.7  
##  7         7             0.75 
##  8         8             0.575
##  9         9             0.55 
## 10        10             0.575
## # … with 14,990 more rows</code></pre>
<div class="sourceCode" id="cb324"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb324-1"><a href="inference.html#cb324-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(sample_estimates)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 2
##   replicate sample_proportion
##       &lt;int&gt;             &lt;dbl&gt;
## 1     14995             0.625
## 2     14996             0.65 
## 3     14997             0.775
## 4     14998             0.6  
## 5     14999             0.55 
## 6     15000             0.55</code></pre>
<p>Now that we have calculated the proportion of chocolate Timbits for each sample, <span class="math inline">\(\hat{p}_\text{chocolate}\)</span>, we can visualize the sampling distribution of sample proportions for samples of size 40:</p>
<div class="sourceCode" id="cb326"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb326-1"><a href="inference.html#cb326-1" aria-hidden="true" tabindex="-1"></a>sampling_distribution <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(sample_estimates, <span class="fu">aes</span>(<span class="at">x =</span> sample_proportion)) <span class="sc">+</span></span>
<span id="cb326-2"><a href="inference.html#cb326-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">&quot;dodgerblue3&quot;</span>, <span class="at">color =</span> <span class="st">&quot;lightgrey&quot;</span>, <span class="at">bins =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb326-3"><a href="inference.html#cb326-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Sample proportions&quot;</span>)</span>
<span id="cb326-4"><a href="inference.html#cb326-4" aria-hidden="true" tabindex="-1"></a>sampling_distribution</span></code></pre></div>
<div class="figure"><span id="fig:11-example-proportions7"></span>
<img src="_main_files/figure-html/11-example-proportions7-1.png" alt="Sampling distribution of the sample proportion for sample size 40" width="60%" />
<p class="caption">
Figure 11.3: Sampling distribution of the sample proportion for sample size 40
</p>
</div>
<p>The sampling distribution appears to be bell-shaped with one peak. It is
centered around 0.6 and the
sample proportions range from about 0.3 to
about 0.9. In fact, we can calculate
the mean of the sample proportions.</p>
<div class="sourceCode" id="cb327"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb327-1"><a href="inference.html#cb327-1" aria-hidden="true" tabindex="-1"></a>sample_estimates <span class="sc">%&gt;%</span></span>
<span id="cb327-2"><a href="inference.html#cb327-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(sample_proportion))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##    mean
##   &lt;dbl&gt;
## 1 0.624</code></pre>
<p>We notice that the sample proportions are centred around the population proportion value, 0.62! In general, the mean of the distribution of <span class="math inline">\(\hat{p}\)</span> should be equal to <span class="math inline">\(p\)</span>, which is good because that means the sample proportion is neither an overestimate nor an underestimate of the population proportion.</p>
<p>So what can we learn from this sampling distribution? This distribution tells us what we might expect from proportions from samples of size <span class="math inline">\(40\)</span> when our population proportion is 0.63. In practice, we usually don’t know the proportion of our population, but if we can use what we know about the sampling distribution, we can use it to make inferences about our population when we only have a single sample.</p>
<!--- > **Note:** If random samples of size $n$ are taken from a population, $\hat{p}$ will be approximately Normal with mean $p$ and standard deviation $\sqrt{\frac{p(1-p)}{n}}$ as long as the sample size $n$ is large enough such that $np$ and $n(1 - p)$ are at least 10, where $p$ is the population proportion, $\hat{p}$ is the sample proportion and $n$ is the sample size. 
--->
</div>
<div id="sampling-distributions-for-means" class="section level3" number="11.4.2">
<h3><span class="header-section-number">11.4.2</span> Sampling distributions for means</h3>
<p>In the previous section, our variable of interest—Timbit flavour—was
<em>categorical</em>, and the population parameter of interest was the proportion of chocolate
Timbits. As mentioned in the introduction to this chapter, there are many choices of population parameter for each type of observed variable. What if we wanted to infer something about a population of <em>quantitative</em> variables instead? For instance, a traveller visiting Vancouver, BC may wish to know about the prices of staying somewhere using Airbnb, an online marketplace for arranging places to stay. Particularly, they might be interested in estimating the population mean price per night of Airbnb listings in Vancouver, BC. This section will study the case where we are interested in the population mean of a quantitative variable.</p>
<p>We will look at an example using data from <a href="http://insideAirbnb.com/">Inside Airbnb</a>. The data set contains Airbnb listings for Vancouver, Canada, in September 2020. Let’s imagine (for learning purposes) that our data set represents the population of all Airbnb rental listings in Vancouver, and we are interested in the population mean price per night.
Our data contains an ID number, neighbourhood,
type of room, the number of people the rental accommodates, number of bathrooms, bedrooms, beds, and the price per night.</p>
<pre><code>## # A tibble: 6 x 8
##      id neighbourhood           room_type      accommodates bathrooms bedrooms  beds price
##   &lt;int&gt; &lt;chr&gt;                   &lt;chr&gt;                 &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     1 Downtown                Entire home/a…            5 2 baths          2     2   150
## 2     2 Downtown Eastside       Entire home/a…            4 2 baths          2     2   132
## 3     3 West End                Entire home/a…            2 1 bath           1     1    85
## 4     4 Kensington-Cedar Cotta… Entire home/a…            2 1 bath           1     0   146
## 5     5 Kensington-Cedar Cotta… Entire home/a…            4 1 bath           1     2   110
## 6     6 Hastings-Sunrise        Entire home/a…            4 1 bath           2     3   195</code></pre>
<p>We can visualize the population distribution of the price per night with a histogram.</p>
<div class="sourceCode" id="cb330"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb330-1"><a href="inference.html#cb330-1" aria-hidden="true" tabindex="-1"></a>population_distribution <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(airbnb, <span class="fu">aes</span>(<span class="at">x =</span> price)) <span class="sc">+</span></span>
<span id="cb330-2"><a href="inference.html#cb330-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">&quot;dodgerblue3&quot;</span>, <span class="at">color =</span> <span class="st">&quot;lightgrey&quot;</span>) <span class="sc">+</span></span>
<span id="cb330-3"><a href="inference.html#cb330-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Price per night ($)&quot;</span>)</span>
<span id="cb330-4"><a href="inference.html#cb330-4" aria-hidden="true" tabindex="-1"></a>population_distribution</span></code></pre></div>
<div class="figure"><span id="fig:11-example-means2"></span>
<img src="_main_files/figure-html/11-example-means2-1.png" alt="Population distribution of price per night ($) for all Airbnb listings in Vancouver, Canada" width="60%" />
<p class="caption">
Figure 11.4: Population distribution of price per night ($) for all Airbnb listings in Vancouver, Canada
</p>
</div>
<p>We see that the distribution has one peak and is skewed—most of the listings
are less than $250 per night, but a small proportion of listings cost more
than that, creating a long tail on the histogram’s right side.</p>
<p>We can also calculate the population mean, the average price per night for all the Airbnb listings.</p>
<div class="sourceCode" id="cb331"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb331-1"><a href="inference.html#cb331-1" aria-hidden="true" tabindex="-1"></a>population_parameters <span class="ot">&lt;-</span> airbnb <span class="sc">%&gt;%</span></span>
<span id="cb331-2"><a href="inference.html#cb331-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">pop_mean =</span> <span class="fu">mean</span>(price))</span>
<span id="cb331-3"><a href="inference.html#cb331-3" aria-hidden="true" tabindex="-1"></a>population_parameters</span></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   pop_mean
##      &lt;dbl&gt;
## 1     155.</code></pre>
<p>The price per night of all Airbnb rentals in Vancouver, BC is $154.51, on average. This value is our population parameter since we are calculating it using the population data.</p>
<p>Suppose that we did not have access to the population data, yet we still wanted to estimate the mean price per night. We could answer this question by taking a random sample of as many Airbnb listings as we had time to, let’s say we could do this for 40 listings. What would such a sample look like?</p>
<p>Let’s take advantage of the fact that we do have access to the population data and simulate taking one random sample of 40 listings in R, again using <code>rep_sample_n</code>. After doing this we create a histogram to visualize the
distribution of observations in the sample,
and calculate the mean of our sample. This number is a <strong>point estimate</strong> for the mean of the full population.</p>
<div class="sourceCode" id="cb333"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb333-1"><a href="inference.html#cb333-1" aria-hidden="true" tabindex="-1"></a>sample_1 <span class="ot">&lt;-</span> airbnb <span class="sc">%&gt;%</span></span>
<span id="cb333-2"><a href="inference.html#cb333-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rep_sample_n</span>(<span class="dv">40</span>)</span>
<span id="cb333-3"><a href="inference.html#cb333-3" aria-hidden="true" tabindex="-1"></a>sample_1</span></code></pre></div>
<pre><code>## # A tibble: 40 x 9
## # Groups:   replicate [1]
##    replicate    id neighbourhood   room_type  accommodates bathrooms  bedrooms  beds price
##        &lt;int&gt; &lt;int&gt; &lt;chr&gt;           &lt;chr&gt;             &lt;dbl&gt; &lt;chr&gt;         &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1         1  1423 Sunset          Entire ho…            2 1 bath            1     1    99
##  2         1  2945 Grandview-Wood… Entire ho…            4 1 bath            2     3   140
##  3         1  1510 West End        Entire ho…            4 1 bath            1     1   104
##  4         1  3099 Downtown        Entire ho…            2 1 bath            1     1   119
##  5         1    51 Downtown        Private r…            2 1 shared …        2     1   249
##  6         1  4480 Downtown        Private r…            1 1 shared …        1     1    69
##  7         1   609 Hastings-Sunri… Entire ho…            3 1 bath            1     1   145
##  8         1  1635 Grandview-Wood… Entire ho…            6 2 baths           4     4   350
##  9         1  3262 Mount Pleasant  Entire ho…            7 2 baths           3     4   499
## 10         1  1497 Downtown        Entire ho…            2 1 bath            1     1    90
## # … with 30 more rows</code></pre>
<div class="sourceCode" id="cb335"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb335-1"><a href="inference.html#cb335-1" aria-hidden="true" tabindex="-1"></a>sample_distribution <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(sample_1, <span class="fu">aes</span>(price)) <span class="sc">+</span></span>
<span id="cb335-2"><a href="inference.html#cb335-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">&quot;dodgerblue3&quot;</span>, <span class="at">color =</span> <span class="st">&quot;lightgrey&quot;</span>) <span class="sc">+</span></span>
<span id="cb335-3"><a href="inference.html#cb335-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Price per night ($)&quot;</span>)</span>
<span id="cb335-4"><a href="inference.html#cb335-4" aria-hidden="true" tabindex="-1"></a>sample_distribution</span></code></pre></div>
<div class="figure"><span id="fig:11-example-means3"></span>
<img src="_main_files/figure-html/11-example-means3-1.png" alt="Distribution of price per night ($) for sample of 40 Airbnb listings" width="60%" />
<p class="caption">
Figure 11.5: Distribution of price per night ($) for sample of 40 Airbnb listings
</p>
</div>
<div class="sourceCode" id="cb336"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb336-1"><a href="inference.html#cb336-1" aria-hidden="true" tabindex="-1"></a>estimates <span class="ot">&lt;-</span> sample_1 <span class="sc">%&gt;%</span></span>
<span id="cb336-2"><a href="inference.html#cb336-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">sample_mean =</span> <span class="fu">mean</span>(price))</span>
<span id="cb336-3"><a href="inference.html#cb336-3" aria-hidden="true" tabindex="-1"></a>estimates</span></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##   replicate sample_mean
##       &lt;int&gt;       &lt;dbl&gt;
## 1         1        163.</code></pre>
<p>Recall that the population mean
was $154.51. We see that our point
estimate for the mean is $163.39. So our estimate was actually quite close to the population parameter: the mean was
about 5.7% off.
Note that in practice, we usually cannot compute the accuracy of the estimate, since we do not have access to the population
parameter; if we did, we wouldn’t need to estimate it!</p>
<p>Also recall from the previous section that the point estimate can vary; if
we took another random sample from the population, then the value of our estimate may change.
So then did we just get lucky with our point estimate above?
How much does our estimate vary across different samples of size 40 in this example? Again, since we have access to the population,
we can take many samples and plot the <strong>sampling distribution</strong> of sample means for samples of size 40 to get a sense
for this variation. In this case, we’ll use 15,000 samples of size 40.</p>
<div class="sourceCode" id="cb338"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb338-1"><a href="inference.html#cb338-1" aria-hidden="true" tabindex="-1"></a>samples <span class="ot">&lt;-</span> <span class="fu">rep_sample_n</span>(airbnb, <span class="at">size =</span> <span class="dv">40</span>, <span class="at">reps =</span> <span class="dv">15000</span>)</span>
<span id="cb338-2"><a href="inference.html#cb338-2" aria-hidden="true" tabindex="-1"></a>samples</span></code></pre></div>
<pre><code>## # A tibble: 600,000 x 9
## # Groups:   replicate [15,000]
##    replicate    id neighbourhood   room_type   accommodates bathrooms bedrooms  beds price
##        &lt;int&gt; &lt;int&gt; &lt;chr&gt;           &lt;chr&gt;              &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1         1  3461 West End        Entire hom…            5 2 baths          2     1   150
##  2         1  3380 Sunset          Entire hom…            2 1 bath           1     1    56
##  3         1  2653 Kensington-Ced… Private ro…            3 1 shared…        1     2    39
##  4         1   324 Killarney       Private ro…            2 1 privat…        1     1    90
##  5         1  1260 Dunbar Southla… Private ro…            1 1 shared…        1     1    46
##  6         1  4412 West End        Entire hom…            6 2 baths          2     2   199
##  7         1  3262 Mount Pleasant  Entire hom…            7 2 baths          3     4   499
##  8         1  2986 West End        Entire hom…            3 1 bath           1     1   208
##  9         1  1988 Downtown        Entire hom…            6 2 baths          2     3   266
## 10         1  4276 Kensington-Ced… Private ro…            4 1 privat…        1     2    85
## # … with 599,990 more rows</code></pre>
<div class="sourceCode" id="cb340"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb340-1"><a href="inference.html#cb340-1" aria-hidden="true" tabindex="-1"></a>sample_estimates <span class="ot">&lt;-</span> samples <span class="sc">%&gt;%</span></span>
<span id="cb340-2"><a href="inference.html#cb340-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(replicate) <span class="sc">%&gt;%</span></span>
<span id="cb340-3"><a href="inference.html#cb340-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">sample_mean =</span> <span class="fu">mean</span>(price))</span>
<span id="cb340-4"><a href="inference.html#cb340-4" aria-hidden="true" tabindex="-1"></a>sample_estimates</span></code></pre></div>
<pre><code>## # A tibble: 15,000 x 2
##    replicate sample_mean
##        &lt;int&gt;       &lt;dbl&gt;
##  1         1        137.
##  2         2        171.
##  3         3        164.
##  4         4        150.
##  5         5        168.
##  6         6        172.
##  7         7        184.
##  8         8        159.
##  9         9        229.
## 10        10        152.
## # … with 14,990 more rows</code></pre>
<div class="sourceCode" id="cb342"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb342-1"><a href="inference.html#cb342-1" aria-hidden="true" tabindex="-1"></a>sampling_distribution_40 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(sample_estimates, <span class="fu">aes</span>(<span class="at">x =</span> sample_mean)) <span class="sc">+</span></span>
<span id="cb342-2"><a href="inference.html#cb342-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">&quot;dodgerblue3&quot;</span>, <span class="at">color =</span> <span class="st">&quot;lightgrey&quot;</span>) <span class="sc">+</span></span>
<span id="cb342-3"><a href="inference.html#cb342-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Sample mean price per night ($)&quot;</span>)</span>
<span id="cb342-4"><a href="inference.html#cb342-4" aria-hidden="true" tabindex="-1"></a>sampling_distribution_40</span></code></pre></div>
<div class="figure"><span id="fig:11-example-means4"></span>
<img src="_main_files/figure-html/11-example-means4-1.png" alt="Sampling distribution of the sample means for sample size of 40" width="60%" />
<p class="caption">
Figure 11.6: Sampling distribution of the sample means for sample size of 40
</p>
</div>
<p>Here we see that the sampling distribution of the mean has one peak and is
bell-shaped. Most of the estimates are between
about $140 and
$170; but there are
a good fraction of cases outside this range (i.e., where the point estimate
was not close to the population parameter). So it does indeed look like we were quite lucky
when we estimated the population mean
with only 5.7% error.
Let’s visualize the population
distribution, distribution of the sample, and the sampling distribution on one
plot to compare them.
<!---

```r
sample_estimates %>%
  summarise(mean_of_sample_means = mean(sample_mean))
```

```
## # A tibble: 1 x 1
##   mean_of_sample_means
##                  <dbl>
## 1                 155.
```
Notice that the mean of the sample means is \$154.59. Recall that the population mean
was \$154.51. 
--></p>
<div class="figure"><span id="fig:11-example-means5"></span>
<img src="_main_files/figure-html/11-example-means5-1.png" alt="Comparision of population distribution, sample distribution and sampling distribution" width="70%" />
<p class="caption">
Figure 11.7: Comparision of population distribution, sample distribution and sampling distribution
</p>
</div>
<p>Given that there is quite a bit of variation in the sampling distribution of the sample mean—i.e.,
the point estimate that we obtain is not very reliable—is there any way to improve the estimate?
One way to improve a point estimate is to take a <em>larger</em> sample. To illustrate what effect this has,
we will take many samples of size 20, 50, 100, and 500, and plot the sampling distribution of the sample mean
below.</p>
<div class="figure"><span id="fig:11-example-means7"></span>
<img src="_main_files/figure-html/11-example-means7-1.png" alt="Comparision of sampling distributions" width="672" />
<p class="caption">
Figure 11.8: Comparision of sampling distributions
</p>
</div>
<p>Based on the visualization, two points about the sample mean become clear.
First, the
mean of the sample mean (across samples) is equal to the population mean.
Second, increasing the size of the sample
decreases the spread (i.e., the variability) in the sample mean
point estimate of the population mean. Therefore, a larger sample size results
in a more reliable point estimate of the population parameter.</p>
<!--- > **Note:** If random samples of size $n$ are taken from a population, the sample mean $\bar{x}$ will be approximately Normal with mean $\mu$ and standard deviation $\frac{\sigma}{\sqrt{n}}$ as long as the sample size $n$ is large enough. $\mu$ is the population mean, $\sigma$ is the population standard deviation, $\bar{x}$ is the sample mean, and $n$ is the sample size. 
> If samples are selected from a finite population as we are doing in this chapter, we should apply a finite population correction. We multiply $\frac{\sigma}{\sqrt{n}}$ by $\sqrt{\frac{N - n}{N - 1}}$ where $N$ is the population size and $n$ is the sample size. If our sample size, $n$, is small relative to the population size, this finite correction factor is less important. 
--->
</div>
<div id="summary-1" class="section level3" number="11.4.3">
<h3><span class="header-section-number">11.4.3</span> Summary</h3>
<ol style="list-style-type: decimal">
<li>A <em>point estimate</em> is a single value computed using a sample from a population (e.g. a mean or proportion)</li>
<li>The <em>sampling distribution</em> of an estimate is the distribution of the estimate for all possible samples of a fixed size from the same population.</li>
<li>The sample means and proportions calculated from samples are centered around the population mean and proportion, respectively.</li>
<li>The spread of the sampling distribution is related to the sample size. As the sample size increases, the spread of the sampling distribution decreases.</li>
<li>The shape of the sampling distribution is usually bell-shaped with one peak and centred at the population mean or proportion.</li>
</ol>
<p><em>Why all this emphasis on sampling distributions?</em></p>
<p>Usually, we don’t have access to the population data, so we cannot construct the sampling distribution as we did in this section. As we saw, our sample estimate’s value will likely not equal the population parameter value exactly. We saw from the sampling distribution just how much our estimates can vary. So reporting a single <em>point estimate</em> for the population parameter alone may not be enough. Using simulations, we can see patterns of the sample estimate’s sampling distribution would look like for a sample of a given size. We can use these patterns to approximate the sampling distribution when we only have one sample, which is the realistic case. If we can “predict” what the sampling distribution would look like for a sample, we could construct a range of values we think the population parameter’s value might lie. We can use our single sample and its properties that influence sampling distributions, such as the spread and sample size, to approximate the sampling distribution as best as we can. There are several methods to do this; however, in this book, we will use the bootstrap method to do this, as we will see in the next section.</p>
</div>
</div>
<div id="bootstrapping" class="section level2" number="11.5">
<h2><span class="header-section-number">11.5</span> Bootstrapping</h2>
<div id="overview-10" class="section level3" number="11.5.1">
<h3><span class="header-section-number">11.5.1</span> Overview</h3>
<p>We saw in the previous section that we could compute a <strong>point estimate</strong> of a population
parameter using a sample of observations from the population. And since we had access to the
population, we could evaluate how accurate the estimate was, and even get a sense for how much
the estimate would vary for different samples from the population.
But in real data analysis settings, we usually have <em>just one sample</em> from our population,
and do not have access to the population itself. So how do we get a sense for how
variable our point estimate is when we only have one sample to work with?
In this section, we will discuss <strong>interval estimation</strong> and construct <strong>confidence intervals</strong> using just a single sample from a population. A confidence interval is a range of plausible values for our population parameter.</p>
<p>Here is the key idea. First, if you take a big enough sample, it <em>looks like</em> the population. Notice the histograms’ shapes for samples of different sizes taken from the population in the picture below. We see that for a large enough sample, the sample’s distribution looks like that of the population.</p>
<div class="figure"><span id="fig:11-example-bootstrapping0"></span>
<img src="_main_files/figure-html/11-example-bootstrapping0-1.png" alt="Comparision of samples of different sizes from the population" width="672" />
<p class="caption">
Figure 11.9: Comparision of samples of different sizes from the population
</p>
</div>
<p>In the previous section, we took many samples of the same size <em>from our population</em> to get
a sense for the variability of a sample estimate. But if our sample is big enough that it looks like our population,
we can pretend that our sample <em>is</em> the population, and take more samples (with replacement) of the same size
from it instead! This very clever technique is called <strong>the bootstrap</strong>.
Note that by taking many samples from our single, observed sample, we do not obtain the true sampling distribution,
but rather an approximation that we call <strong>the bootstrap distribution</strong>.</p>
<blockquote>
<p>Note that we need to sample <em>with</em> replacement when using the bootstrap. Otherwise, if we had a sample of size <span class="math inline">\(n\)</span>,
and obtained a sample from it of size <span class="math inline">\(n\)</span> <em>without</em> replacement, it would just return our original sample.</p>
</blockquote>
<p>This section will explore how to create a bootstrap distribution from a single sample using R.
For a sample of size <span class="math inline">\(n\)</span>, the process we will go through is as follows:</p>
<ol style="list-style-type: decimal">
<li>Randomly select an observation from the original sample, which was drawn from the population</li>
<li>Record the observation’s value</li>
<li>Replace that observation</li>
<li>Repeat steps 1 - 3 (sampling <em>with</em> replacement) until you have <span class="math inline">\(n\)</span> observations, which form a bootstrap sample</li>
<li>Calculate the bootstrap point estimate (e.g., mean, median, proportion, slope, etc.) of the <span class="math inline">\(n\)</span> observations in your bootstrap sample</li>
<li>Repeat steps (1) - (5) many times to create a distribution of point estimates (the bootstrap distribution)</li>
<li>Calculate the plausible range of values around our observed point estimate</li>
</ol>
<div class="figure"><span id="fig:11-intro-bootstrap-image"></span>
<img src="img/intro-bootstrap.jpeg" alt="Overview of the bootstrap process" width="880" />
<p class="caption">
Figure 11.10: Overview of the bootstrap process
</p>
</div>
</div>
<div id="bootstrapping-in-r" class="section level3" number="11.5.2">
<h3><span class="header-section-number">11.5.2</span> Bootstrapping in R</h3>
<p>Let’s continue working with our Airbnb data. Once again, let’s say we are interested in estimating the population mean price per night of all Airbnb listings in
Vancouver, Canada using a single sample we collected of size 40.</p>
<p>To simulate doing this in R, we will use <code>rep_sample_n</code> to take a random sample from from our population. In real life we wouldn’t do this step in R, we would instead simply load the data into R, that we, or our collaborators collected.</p>
<p>After we have our sample, we will visualize it’s distribution and calculate our point estimate, the sample mean.</p>
<div class="sourceCode" id="cb343"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb343-1"><a href="inference.html#cb343-1" aria-hidden="true" tabindex="-1"></a>one_sample <span class="ot">&lt;-</span> airbnb <span class="sc">%&gt;%</span></span>
<span id="cb343-2"><a href="inference.html#cb343-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rep_sample_n</span>(<span class="dv">40</span>) <span class="sc">%&gt;%</span></span>
<span id="cb343-3"><a href="inference.html#cb343-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span> <span class="co"># ungroup the data frame</span></span>
<span id="cb343-4"><a href="inference.html#cb343-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(price) <span class="co"># drop the replicate column</span></span>
<span id="cb343-5"><a href="inference.html#cb343-5" aria-hidden="true" tabindex="-1"></a>one_sample</span></code></pre></div>
<pre><code>## # A tibble: 40 x 1
##    price
##    &lt;dbl&gt;
##  1    32
##  2    65
##  3   199
##  4   192
##  5    94
##  6    68
##  7   179
##  8   240
##  9   112
## 10   369
## # … with 30 more rows</code></pre>
<div class="sourceCode" id="cb345"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb345-1"><a href="inference.html#cb345-1" aria-hidden="true" tabindex="-1"></a>one_sample_dist <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(one_sample, <span class="fu">aes</span>(price)) <span class="sc">+</span></span>
<span id="cb345-2"><a href="inference.html#cb345-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">&quot;dodgerblue3&quot;</span>, <span class="at">color =</span> <span class="st">&quot;lightgrey&quot;</span>) <span class="sc">+</span></span>
<span id="cb345-3"><a href="inference.html#cb345-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Price per night ($)&quot;</span>)</span>
<span id="cb345-4"><a href="inference.html#cb345-4" aria-hidden="true" tabindex="-1"></a>one_sample_dist</span></code></pre></div>
<div class="figure"><span id="fig:11-bootstrapping1"></span>
<img src="_main_files/figure-html/11-bootstrapping1-1.png" alt="Histogram of price per night ($) for one sample of size 40" width="60%" />
<p class="caption">
Figure 11.11: Histogram of price per night ($) for one sample of size 40
</p>
</div>
<div class="sourceCode" id="cb346"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb346-1"><a href="inference.html#cb346-1" aria-hidden="true" tabindex="-1"></a>one_sample_estimates <span class="ot">&lt;-</span> one_sample <span class="sc">%&gt;%</span></span>
<span id="cb346-2"><a href="inference.html#cb346-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">sample_mean =</span> <span class="fu">mean</span>(price))</span>
<span id="cb346-3"><a href="inference.html#cb346-3" aria-hidden="true" tabindex="-1"></a>one_sample_estimates</span></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   sample_mean
##         &lt;dbl&gt;
## 1        156.</code></pre>
<p>The sample distribution is skewed with a few observations out to the right. The
mean of the sample is $156.49.
Remember, in practice, we usually only have one sample from the population. So
this sample and estimate are the only data we can work with.</p>
<p>We now perform steps (1) - (5) listed above to generate a single bootstrap sample in R using the
sample we just took, and calculate the bootstrap estimate for that sample. We
will use the <code>rep_sample_n</code> function as we did when we were creating our
sampling distribution. Since we want to sample with replacement, we change the
argument for <code>replace</code> from its default value of <code>FALSE</code> to <code>TRUE</code>.</p>
<div class="sourceCode" id="cb348"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb348-1"><a href="inference.html#cb348-1" aria-hidden="true" tabindex="-1"></a>boot1 <span class="ot">&lt;-</span> one_sample <span class="sc">%&gt;%</span></span>
<span id="cb348-2"><a href="inference.html#cb348-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rep_sample_n</span>(<span class="at">size =</span> <span class="dv">40</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">reps =</span> <span class="dv">1</span>)</span>
<span id="cb348-3"><a href="inference.html#cb348-3" aria-hidden="true" tabindex="-1"></a>boot1</span></code></pre></div>
<pre><code>## # A tibble: 40 x 2
## # Groups:   replicate [1]
##    replicate price
##        &lt;int&gt; &lt;dbl&gt;
##  1         1   180
##  2         1   394
##  3         1    97
##  4         1   192
##  5         1    49
##  6         1    32
##  7         1    32
##  8         1   189
##  9         1    94
## 10         1    35
## # … with 30 more rows</code></pre>
<div class="sourceCode" id="cb350"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb350-1"><a href="inference.html#cb350-1" aria-hidden="true" tabindex="-1"></a>boot1_dist <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(boot1, <span class="fu">aes</span>(price)) <span class="sc">+</span></span>
<span id="cb350-2"><a href="inference.html#cb350-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">&quot;dodgerblue3&quot;</span>, <span class="at">color =</span> <span class="st">&quot;lightgrey&quot;</span>) <span class="sc">+</span></span>
<span id="cb350-3"><a href="inference.html#cb350-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Price per night ($)&quot;</span>)</span>
<span id="cb350-4"><a href="inference.html#cb350-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb350-5"><a href="inference.html#cb350-5" aria-hidden="true" tabindex="-1"></a>boot1_dist</span></code></pre></div>
<div class="figure"><span id="fig:11-bootstrapping3"></span>
<img src="_main_files/figure-html/11-bootstrapping3-1.png" alt="Bootstrap distribution" width="60%" />
<p class="caption">
Figure 11.12: Bootstrap distribution
</p>
</div>
<div class="sourceCode" id="cb351"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb351-1"><a href="inference.html#cb351-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summarise</span>(boot1, <span class="at">mean =</span> <span class="fu">mean</span>(price))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##   replicate  mean
##       &lt;int&gt; &lt;dbl&gt;
## 1         1  167.</code></pre>
<p>Notice that our bootstrap distribution has a similar shape to the original
sample distribution. Though the shapes of the distributions are similar, they
are not identical. You’ll also notice that the original sample mean and the
bootstrap sample mean differ. How might that happen? Remember that we are
sampling with replacement from the original sample, so we don’t end up with the
same sample values again. We are trying to mimic drawing another sample from
the population without actually having to do that.</p>
<p>Let’s now take 15,000 bootstrap samples from the original sample we drew from the
population (<code>one_sample</code>) using <code>rep_sample_n</code> and calculate the means for
each of those replicates. Recall that this assumes that <code>one_sample</code> <em>looks like</em>
our original population; but since we do not have access to the population itself,
this is often the best we can do.</p>
<div class="sourceCode" id="cb353"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb353-1"><a href="inference.html#cb353-1" aria-hidden="true" tabindex="-1"></a>boot15000 <span class="ot">&lt;-</span> one_sample <span class="sc">%&gt;%</span></span>
<span id="cb353-2"><a href="inference.html#cb353-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rep_sample_n</span>(<span class="at">size =</span> <span class="dv">40</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">reps =</span> <span class="dv">15000</span>)</span>
<span id="cb353-3"><a href="inference.html#cb353-3" aria-hidden="true" tabindex="-1"></a>boot15000</span></code></pre></div>
<pre><code>## # A tibble: 600,000 x 2
## # Groups:   replicate [15,000]
##    replicate price
##        &lt;int&gt; &lt;dbl&gt;
##  1         1    65
##  2         1   240
##  3         1    68
##  4         1   369
##  5         1   192
##  6         1   180
##  7         1   245
##  8         1    65
##  9         1    94
## 10         1   350
## # … with 599,990 more rows</code></pre>
<div class="sourceCode" id="cb355"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb355-1"><a href="inference.html#cb355-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(boot15000)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 2
## # Groups:   replicate [1]
##   replicate price
##       &lt;int&gt; &lt;dbl&gt;
## 1     15000  217 
## 2     15000   75 
## 3     15000   89 
## 4     15000   75 
## 5     15000  111.
## 6     15000   32</code></pre>
<p>Let’s take a look at histograms of the first six replicates of our bootstrap samples.</p>
<div class="sourceCode" id="cb357"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb357-1"><a href="inference.html#cb357-1" aria-hidden="true" tabindex="-1"></a>six_bootstrap_samples <span class="ot">&lt;-</span> boot15000 <span class="sc">%&gt;%</span></span>
<span id="cb357-2"><a href="inference.html#cb357-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(replicate <span class="sc">&lt;=</span> <span class="dv">6</span>)</span>
<span id="cb357-3"><a href="inference.html#cb357-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(six_bootstrap_samples, <span class="fu">aes</span>(price)) <span class="sc">+</span></span>
<span id="cb357-4"><a href="inference.html#cb357-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">&quot;dodgerblue3&quot;</span>, <span class="at">color =</span> <span class="st">&quot;lightgrey&quot;</span>) <span class="sc">+</span></span>
<span id="cb357-5"><a href="inference.html#cb357-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Price per night ($)&quot;</span>) <span class="sc">+</span></span>
<span id="cb357-6"><a href="inference.html#cb357-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>replicate)</span></code></pre></div>
<p><img src="_main_files/figure-html/11-bootstrapping-six-bootstrap-samples-1.png" width="672" /></p>
<p>We see in the graph above how the bootstrap samples differ. We can also calculate the sample mean for each of these six replicates.</p>
<div class="sourceCode" id="cb358"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb358-1"><a href="inference.html#cb358-1" aria-hidden="true" tabindex="-1"></a>six_bootstrap_samples <span class="sc">%&gt;%</span></span>
<span id="cb358-2"><a href="inference.html#cb358-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(replicate) <span class="sc">%&gt;%</span></span>
<span id="cb358-3"><a href="inference.html#cb358-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(price))</span></code></pre></div>
<pre><code>## # A tibble: 6 x 2
##   replicate  mean
##       &lt;int&gt; &lt;dbl&gt;
## 1         1  166.
## 2         2  144.
## 3         3  143.
## 4         4  213.
## 5         5  148.
## 6         6  162</code></pre>
<p>We can see that the bootstrap sample distributions and the sample means are different. This is because we are sampling with replacement. We will now calculate point estimates for our 15,000 bootstrap samples and generate a bootstrap distribution of our point estimates. The bootstrap distribution suggests how we might expect our point estimate to behave if we took another sample.</p>
<div class="sourceCode" id="cb360"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb360-1"><a href="inference.html#cb360-1" aria-hidden="true" tabindex="-1"></a>boot15000_means <span class="ot">&lt;-</span> boot15000 <span class="sc">%&gt;%</span></span>
<span id="cb360-2"><a href="inference.html#cb360-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(replicate) <span class="sc">%&gt;%</span></span>
<span id="cb360-3"><a href="inference.html#cb360-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(price))</span>
<span id="cb360-4"><a href="inference.html#cb360-4" aria-hidden="true" tabindex="-1"></a>boot15000_means</span></code></pre></div>
<pre><code>## # A tibble: 15,000 x 2
##    replicate  mean
##        &lt;int&gt; &lt;dbl&gt;
##  1         1  166.
##  2         2  144.
##  3         3  143.
##  4         4  213.
##  5         5  148.
##  6         6  162 
##  7         7  153.
##  8         8  168.
##  9         9  166.
## 10        10  139.
## # … with 14,990 more rows</code></pre>
<div class="sourceCode" id="cb362"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb362-1"><a href="inference.html#cb362-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(boot15000_means)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 2
##   replicate  mean
##       &lt;int&gt; &lt;dbl&gt;
## 1     14995  151.
## 2     14996  179.
## 3     14997  133.
## 4     14998  150.
## 5     14999  139 
## 6     15000  156.</code></pre>
<div class="sourceCode" id="cb364"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb364-1"><a href="inference.html#cb364-1" aria-hidden="true" tabindex="-1"></a>boot_est_dist <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(boot15000_means, <span class="fu">aes</span>(<span class="at">x =</span> mean)) <span class="sc">+</span></span>
<span id="cb364-2"><a href="inference.html#cb364-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">&quot;dodgerblue3&quot;</span>, <span class="at">color =</span> <span class="st">&quot;lightgrey&quot;</span>) <span class="sc">+</span></span>
<span id="cb364-3"><a href="inference.html#cb364-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Sample mean price per night ($)&quot;</span>)</span></code></pre></div>
<p>Let’s compare our bootstrap distribution with the true sampling distribution (taking many samples from the population).</p>
<div class="figure"><span id="fig:11-bootstrapping6"></span>
<img src="_main_files/figure-html/11-bootstrapping6-1.png" alt="Comparison of distribution of the bootstrap sample means and sampling distribution" width="672" height="50%" />
<p class="caption">
Figure 11.13: Comparison of distribution of the bootstrap sample means and sampling distribution
</p>
</div>
<p>There are two essential points that we can take away from these plots. First, the shape and spread of the true sampling distribution and the bootstrap distribution are similar; the bootstrap distribution lets us get a sense of the point estimate’s variability. The second important point is that the means of these two distributions are different. The sampling distribution is centred at $154.51, the population mean value. However, the bootstrap distribution is centred at the original sample’s mean price per night, $156.52. Because we are resampling from the original sample repeatedly, we see that the bootstrap distribution is centred at the original sample’s mean value (unlike the sampling distribution of the sample mean, which is centred at the population parameter value).</p>
<p>The idea here is that we can use this distribution of bootstrap sample means to approximate the sampling distribution of the sample means when we only have one sample. Since the bootstrap distribution pretty well approximates the sampling distribution spread, we can use the bootstrap spread to help us develop a plausible range for our population parameter along with our estimate!</p>
<div class="figure"><span id="fig:11-bootstrapping7"></span>
<img src="_main_files/figure-html/11-bootstrapping7-1.png" alt="Summary of bootstrapping process" width="672" />
<p class="caption">
Figure 11.14: Summary of bootstrapping process
</p>
</div>
</div>
<div id="using-the-bootstrap-to-calculate-a-plausible-range" class="section level3" number="11.5.3">
<h3><span class="header-section-number">11.5.3</span> Using the bootstrap to calculate a plausible range</h3>
<p>Now that we have constructed our bootstrap distribution let’s use it to create an approximate bootstrap confidence interval, a range of plausible values for the population mean. We will build a 95% percentile bootstrap confidence interval and find the range of values that cover the middle 95% of the bootstrap distribution. A 95% confidence interval means that if we were to repeat the sampling process and calculate 95% confidence intervals each time and repeat this process many times, then 95% of the intervals would capture the population parameter’s value. Note that there’s nothing particularly special about 95%, we could have used other confidence levels, such as 90% or 99%. There is a balance between our level of confidence and precision. A higher confidence level corresponds to a wider range of the interval, and a lower confidence level corresponds to a narrower range. Therefore the level we choose is based on what chance we are willing to take of being wrong based on the implications of being wrong for our application. In general, we choose confidence levels to be comfortable with our level of uncertainty, but not so strict that the interval is unhelpful. For instance, if our decision impacts human life and the implications of being wrong are deadly, we may want to be very confident and choose a higher confidence level.</p>
<p>To calculate our 95% percentile bootstrap confidence interval, we will do the following:</p>
<ol style="list-style-type: decimal">
<li>Arrange the observations in the bootstrap distribution in ascending order</li>
<li>Find the value such that 2.5% of observations fall below it (the 2.5% percentile). Use that value as the lower bound of the interval</li>
<li>Find the value such that 97.5% of observations fall below it (the 97.5% percentile). Use that value as the upper bound of the interval</li>
</ol>
<p>To do this in R, we can use the <code>quantile()</code> function:</p>
<div class="sourceCode" id="cb365"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb365-1"><a href="inference.html#cb365-1" aria-hidden="true" tabindex="-1"></a>bounds <span class="ot">&lt;-</span> boot15000_means <span class="sc">%&gt;%</span></span>
<span id="cb365-2"><a href="inference.html#cb365-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(mean) <span class="sc">%&gt;%</span></span>
<span id="cb365-3"><a href="inference.html#cb365-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>() <span class="sc">%&gt;%</span></span>
<span id="cb365-4"><a href="inference.html#cb365-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">quantile</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>))</span>
<span id="cb365-5"><a href="inference.html#cb365-5" aria-hidden="true" tabindex="-1"></a>bounds</span></code></pre></div>
<pre><code>##    2.5%   97.5% 
## 122.700 193.269</code></pre>
<p>Our interval, $122.7 to $193.27, captures the middle 95% of the sample mean prices in the bootstrap distribution. We can visualize the interval on our distribution in the picture below.</p>
<div class="figure"><span id="fig:11-bootstrapping9"></span>
<img src="_main_files/figure-html/11-bootstrapping9-1.png" alt="Distribution of the bootstrap sample means with percentile lower and upper bounds" width="70%" />
<p class="caption">
Figure 11.15: Distribution of the bootstrap sample means with percentile lower and upper bounds
</p>
</div>
<p>To finish our estimation of the population parameter, we would report the point estimate and our confidence interval’s lower and upper bounds. Here the sample mean price-per-night of 40 Airbnb listings was $163.39, and we are 95% “confident” that the true population mean price-per-night for all Airbnb listings in Vancouver is between $(122.7, 193.27).</p>
<p>Notice that our interval does indeed contain the true
population mean value, $154.51! However, in
practice, we would not know whether our interval captured the population parameter or not because we usually only have a single sample, not the entire population. However, this is the best we can do when we only have one sample!</p>
<p>This chapter is only the beginning of the journey into statistical inference. We can extend the concepts learned here to do much more than report point estimates and confidence intervals, such as hypothesis testing for differences between populations, tests for associations between variables, and so much more! We have just scratched the surface of statistical inference; however, the material presented here will serve as the foundation for more advanced statistical techniques you may learn about in the future!</p>
</div>
</div>
<div id="additional-resources-7" class="section level2" number="11.6">
<h2><span class="header-section-number">11.6</span> Additional resources</h2>
<ul>
<li>Chapters 7 to 10 of <a href="https://moderndive.com/">Modern Dive</a> provide a great next step in learning about inference. In particular, Chapters 7 and 8 cover sampling and bootstrapping using <code>tidyverse</code> and <code>infer</code> in a slightly more in-depth manner than the present chapter. Chapters 9 and 10 take the next step beyond the scope of this chapter and begin to provide some of the initial mathematical underpinnings of inference and more advanced applications of the concept of inference in testing hypotheses and performing regression. This material offers a great starting point for getting more into the technical side of statistics.</li>
<li>Chapters 4 to 7 of <a href="https://www.openintro.org/">OpenIntro Statistics - Fourth Edition</a> provide a good next step after Modern Dive. Although it is still certainly an introductory text, things get a bit more mathematical here. Depending on your background, you may actually want to start going through Chapters 1 to 3 first, where you will learn some fundamental concepts in probability theory. Although it may seem like a diversion, probability theory is <em>the language of statistics</em>; if you have a solid grasp of probability, more advanced statistics will come naturally to you!</li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="clustering.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="move-to-your-own-machine.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/10-inference.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
