<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Reading in data locally and from the web |  Data Science</title>
  <meta name="description" content="This is a textbook for teaching a first introduction to data science." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Reading in data locally and from the web |  Data Science" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://datasciencebook.ca" />
  <meta property="og:image" content="https://datasciencebook.ca/img/ds-a-first-intro-graphic.png" />
  <meta property="og:description" content="This is a textbook for teaching a first introduction to data science." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Reading in data locally and from the web |  Data Science" />
  
  <meta name="twitter:description" content="This is a textbook for teaching a first introduction to data science." />
  <meta name="twitter:image" content="https://datasciencebook.ca/img/ds-a-first-intro-graphic.png" />

<meta name="author" content="Tiffany Timbers, Trevor Campbell, and Melissa Lee   Foreword by Roger Peng" />


<meta name="date" content="2022-02-11" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="intro.html"/>
<link rel="next" href="wrangling.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.5.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.5.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="https://datasciencebook.ca">Data Science: A First Introduction</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome!</a></li>
<li class="chapter" data-level="" data-path="foreword.html"><a href="foreword.html"><i class="fa fa-check"></i>Foreword</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="" data-path="acknowledgments.html"><a href="acknowledgments.html"><i class="fa fa-check"></i>Acknowledgments</a></li>
<li class="chapter" data-level="" data-path="about-the-authors.html"><a href="about-the-authors.html"><i class="fa fa-check"></i>About the authors</a></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> R and the Tidyverse</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#overview"><i class="fa fa-check"></i><b>1.1</b> Overview</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#chapter-learning-objectives"><i class="fa fa-check"></i><b>1.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#canadian-languages-data-set"><i class="fa fa-check"></i><b>1.3</b> Canadian languages data set</a></li>
<li class="chapter" data-level="1.4" data-path="intro.html"><a href="intro.html#asking-a-question"><i class="fa fa-check"></i><b>1.4</b> Asking a question</a></li>
<li class="chapter" data-level="1.5" data-path="intro.html"><a href="intro.html#loading-a-tabular-data-set"><i class="fa fa-check"></i><b>1.5</b> Loading a tabular data set</a></li>
<li class="chapter" data-level="1.6" data-path="intro.html"><a href="intro.html#naming-things-in-r"><i class="fa fa-check"></i><b>1.6</b> Naming things in R</a></li>
<li class="chapter" data-level="1.7" data-path="intro.html"><a href="intro.html#creating-subsets-of-data-frames-with-filter-select"><i class="fa fa-check"></i><b>1.7</b> Creating subsets of data frames with <code>filter</code> &amp; <code>select</code></a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="intro.html"><a href="intro.html#using-filter-to-extract-rows"><i class="fa fa-check"></i><b>1.7.1</b> Using <code>filter</code> to extract rows</a></li>
<li class="chapter" data-level="1.7.2" data-path="intro.html"><a href="intro.html#using-select-to-extract-columns"><i class="fa fa-check"></i><b>1.7.2</b> Using <code>select</code> to extract columns</a></li>
<li class="chapter" data-level="1.7.3" data-path="intro.html"><a href="intro.html#using-arrange-to-order-and-slice-to-select-rows-by-index-number"><i class="fa fa-check"></i><b>1.7.3</b> Using <code>arrange</code> to order and <code>slice</code> to select rows by index number</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="intro.html"><a href="intro.html#exploring-data-with-visualizations"><i class="fa fa-check"></i><b>1.8</b> Exploring data with visualizations</a>
<ul>
<li class="chapter" data-level="1.8.1" data-path="intro.html"><a href="intro.html#using-ggplot-to-create-a-bar-plot"><i class="fa fa-check"></i><b>1.8.1</b> Using <code>ggplot</code> to create a bar plot</a></li>
<li class="chapter" data-level="1.8.2" data-path="intro.html"><a href="intro.html#formatting-ggplot-objects"><i class="fa fa-check"></i><b>1.8.2</b> Formatting ggplot objects</a></li>
<li class="chapter" data-level="1.8.3" data-path="intro.html"><a href="intro.html#putting-it-all-together"><i class="fa fa-check"></i><b>1.8.3</b> Putting it all together</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="intro.html"><a href="intro.html#accessing-documentation"><i class="fa fa-check"></i><b>1.9</b> Accessing documentation</a></li>
<li class="chapter" data-level="1.10" data-path="intro.html"><a href="intro.html#exercises"><i class="fa fa-check"></i><b>1.10</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="reading.html"><a href="reading.html"><i class="fa fa-check"></i><b>2</b> Reading in data locally and from the web</a>
<ul>
<li class="chapter" data-level="2.1" data-path="reading.html"><a href="reading.html#overview-1"><i class="fa fa-check"></i><b>2.1</b> Overview</a></li>
<li class="chapter" data-level="2.2" data-path="reading.html"><a href="reading.html#chapter-learning-objectives-1"><i class="fa fa-check"></i><b>2.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="2.3" data-path="reading.html"><a href="reading.html#absolute-and-relative-file-paths"><i class="fa fa-check"></i><b>2.3</b> Absolute and relative file paths</a></li>
<li class="chapter" data-level="2.4" data-path="reading.html"><a href="reading.html#reading-tabular-data-from-a-plain-text-file-into-r"><i class="fa fa-check"></i><b>2.4</b> Reading tabular data from a plain text file into R</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="reading.html"><a href="reading.html#readcsv"><i class="fa fa-check"></i><b>2.4.1</b> <code>read_csv</code> to read in comma-separated files</a></li>
<li class="chapter" data-level="2.4.2" data-path="reading.html"><a href="reading.html#skipping-rows-when-reading-in-data"><i class="fa fa-check"></i><b>2.4.2</b> Skipping rows when reading in data</a></li>
<li class="chapter" data-level="2.4.3" data-path="reading.html"><a href="reading.html#read_tsv-to-read-in-tab-separated-files"><i class="fa fa-check"></i><b>2.4.3</b> <code>read_tsv</code> to read in tab-separated files</a></li>
<li class="chapter" data-level="2.4.4" data-path="reading.html"><a href="reading.html#read_delim-as-a-more-flexible-method-to-get-tabular-data-into-r"><i class="fa fa-check"></i><b>2.4.4</b> <code>read_delim</code> as a more flexible method to get tabular data into R</a></li>
<li class="chapter" data-level="2.4.5" data-path="reading.html"><a href="reading.html#reading-tabular-data-directly-from-a-url"><i class="fa fa-check"></i><b>2.4.5</b> Reading tabular data directly from a URL</a></li>
<li class="chapter" data-level="2.4.6" data-path="reading.html"><a href="reading.html#previewing-a-data-file-before-reading-it-into-r"><i class="fa fa-check"></i><b>2.4.6</b> Previewing a data file before reading it into R</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="reading.html"><a href="reading.html#reading-tabular-data-from-a-microsoft-excel-file"><i class="fa fa-check"></i><b>2.5</b> Reading tabular data from a Microsoft Excel file</a></li>
<li class="chapter" data-level="2.6" data-path="reading.html"><a href="reading.html#reading-data-from-a-database"><i class="fa fa-check"></i><b>2.6</b> Reading data from a database</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="reading.html"><a href="reading.html#reading-data-from-a-sqlite-database"><i class="fa fa-check"></i><b>2.6.1</b> Reading data from a SQLite database</a></li>
<li class="chapter" data-level="2.6.2" data-path="reading.html"><a href="reading.html#reading-data-from-a-postgresql-database"><i class="fa fa-check"></i><b>2.6.2</b> Reading data from a PostgreSQL database</a></li>
<li class="chapter" data-level="2.6.3" data-path="reading.html"><a href="reading.html#why-should-we-bother-with-databases-at-all"><i class="fa fa-check"></i><b>2.6.3</b> Why should we bother with databases at all?</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="reading.html"><a href="reading.html#writing-data-from-r-to-a-.csv-file"><i class="fa fa-check"></i><b>2.7</b> Writing data from R to a <code>.csv</code> file</a></li>
<li class="chapter" data-level="2.8" data-path="reading.html"><a href="reading.html#obtaining-data-from-the-web"><i class="fa fa-check"></i><b>2.8</b> Obtaining data from the web</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="reading.html"><a href="reading.html#web-scraping"><i class="fa fa-check"></i><b>2.8.1</b> Web scraping</a></li>
<li class="chapter" data-level="2.8.2" data-path="reading.html"><a href="reading.html#using-an-api"><i class="fa fa-check"></i><b>2.8.2</b> Using an API</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="reading.html"><a href="reading.html#exercises-1"><i class="fa fa-check"></i><b>2.9</b> Exercises</a></li>
<li class="chapter" data-level="2.10" data-path="reading.html"><a href="reading.html#additional-resources"><i class="fa fa-check"></i><b>2.10</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="wrangling.html"><a href="wrangling.html"><i class="fa fa-check"></i><b>3</b> Cleaning and wrangling data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="wrangling.html"><a href="wrangling.html#overview-2"><i class="fa fa-check"></i><b>3.1</b> Overview</a></li>
<li class="chapter" data-level="3.2" data-path="wrangling.html"><a href="wrangling.html#chapter-learning-objectives-2"><i class="fa fa-check"></i><b>3.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="3.3" data-path="wrangling.html"><a href="wrangling.html#data-frames-vectors-and-lists"><i class="fa fa-check"></i><b>3.3</b> Data frames, vectors, and lists</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="wrangling.html"><a href="wrangling.html#what-is-a-data-frame"><i class="fa fa-check"></i><b>3.3.1</b> What is a data frame?</a></li>
<li class="chapter" data-level="3.3.2" data-path="wrangling.html"><a href="wrangling.html#what-is-a-vector"><i class="fa fa-check"></i><b>3.3.2</b> What is a vector?</a></li>
<li class="chapter" data-level="3.3.3" data-path="wrangling.html"><a href="wrangling.html#what-is-a-list"><i class="fa fa-check"></i><b>3.3.3</b> What is a list?</a></li>
<li class="chapter" data-level="3.3.4" data-path="wrangling.html"><a href="wrangling.html#what-does-this-have-to-do-with-data-frames"><i class="fa fa-check"></i><b>3.3.4</b> What does this have to do with data frames?</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="wrangling.html"><a href="wrangling.html#tidy-data"><i class="fa fa-check"></i><b>3.4</b> Tidy data</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="wrangling.html"><a href="wrangling.html#tidying-up-going-from-wide-to-long-using-pivot_longer"><i class="fa fa-check"></i><b>3.4.1</b> Tidying up: going from wide to long using <code>pivot_longer</code></a></li>
<li class="chapter" data-level="3.4.2" data-path="wrangling.html"><a href="wrangling.html#pivot-wider"><i class="fa fa-check"></i><b>3.4.2</b> Tidying up: going from long to wide using <code>pivot_wider</code></a></li>
<li class="chapter" data-level="3.4.3" data-path="wrangling.html"><a href="wrangling.html#separate"><i class="fa fa-check"></i><b>3.4.3</b> Tidying up: using <code>separate</code> to deal with multiple delimiters</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="wrangling.html"><a href="wrangling.html#using-select-to-extract-a-range-of-columns"><i class="fa fa-check"></i><b>3.5</b> Using <code>select</code> to extract a range of columns</a></li>
<li class="chapter" data-level="3.6" data-path="wrangling.html"><a href="wrangling.html#using-filter-to-extract-rows-1"><i class="fa fa-check"></i><b>3.6</b> Using <code>filter</code> to extract rows</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="wrangling.html"><a href="wrangling.html#extracting-rows-that-have-a-certain-value-with"><i class="fa fa-check"></i><b>3.6.1</b> Extracting rows that have a certain value with <code>==</code></a></li>
<li class="chapter" data-level="3.6.2" data-path="wrangling.html"><a href="wrangling.html#extracting-rows-that-do-not-have-a-certain-value-with"><i class="fa fa-check"></i><b>3.6.2</b> Extracting rows that do not have a certain value with <code>!=</code></a></li>
<li class="chapter" data-level="3.6.3" data-path="wrangling.html"><a href="wrangling.html#filter-and"><i class="fa fa-check"></i><b>3.6.3</b> Extracting rows satisfying multiple conditions using <code>,</code> or <code>&amp;</code></a></li>
<li class="chapter" data-level="3.6.4" data-path="wrangling.html"><a href="wrangling.html#extracting-rows-satisfying-at-least-one-condition-using"><i class="fa fa-check"></i><b>3.6.4</b> Extracting rows satisfying at least one condition using <code>|</code></a></li>
<li class="chapter" data-level="3.6.5" data-path="wrangling.html"><a href="wrangling.html#extracting-rows-with-values-in-a-vector-using-in"><i class="fa fa-check"></i><b>3.6.5</b> Extracting rows with values in a vector using <code>%in%</code></a></li>
<li class="chapter" data-level="3.6.6" data-path="wrangling.html"><a href="wrangling.html#extracting-rows-above-or-below-a-threshold-using-and"><i class="fa fa-check"></i><b>3.6.6</b> Extracting rows above or below a threshold using <code>&gt;</code> and <code>&lt;</code></a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="wrangling.html"><a href="wrangling.html#using-mutate-to-modify-or-add-columns"><i class="fa fa-check"></i><b>3.7</b> Using <code>mutate</code> to modify or add columns</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="wrangling.html"><a href="wrangling.html#using-mutate-to-modify-columns"><i class="fa fa-check"></i><b>3.7.1</b> Using <code>mutate</code> to modify columns</a></li>
<li class="chapter" data-level="3.7.2" data-path="wrangling.html"><a href="wrangling.html#using-mutate-to-create-new-columns"><i class="fa fa-check"></i><b>3.7.2</b> Using <code>mutate</code> to create new columns</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="wrangling.html"><a href="wrangling.html#combining-functions-using-the-pipe-operator"><i class="fa fa-check"></i><b>3.8</b> Combining functions using the pipe operator, <code>|&gt;</code></a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="wrangling.html"><a href="wrangling.html#using-to-combine-filter-and-select"><i class="fa fa-check"></i><b>3.8.1</b> Using <code>|&gt;</code> to combine <code>filter</code> and <code>select</code></a></li>
<li class="chapter" data-level="3.8.2" data-path="wrangling.html"><a href="wrangling.html#using-with-more-than-two-functions"><i class="fa fa-check"></i><b>3.8.2</b> Using <code>|&gt;</code> with more than two functions</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="wrangling.html"><a href="wrangling.html#aggregating-data-with-summarize-and-map"><i class="fa fa-check"></i><b>3.9</b> Aggregating data with <code>summarize</code> and <code>map</code></a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="wrangling.html"><a href="wrangling.html#calculating-summary-statistics-on-whole-columns"><i class="fa fa-check"></i><b>3.9.1</b> Calculating summary statistics on whole columns</a></li>
<li class="chapter" data-level="3.9.2" data-path="wrangling.html"><a href="wrangling.html#calculating-summary-statistics-when-there-are-nas"><i class="fa fa-check"></i><b>3.9.2</b> Calculating summary statistics when there are <code>NA</code>s</a></li>
<li class="chapter" data-level="3.9.3" data-path="wrangling.html"><a href="wrangling.html#calculating-summary-statistics-for-groups-of-rows"><i class="fa fa-check"></i><b>3.9.3</b> Calculating summary statistics for groups of rows</a></li>
<li class="chapter" data-level="3.9.4" data-path="wrangling.html"><a href="wrangling.html#calculating-summary-statistics-on-many-columns"><i class="fa fa-check"></i><b>3.9.4</b> Calculating summary statistics on many columns</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="wrangling.html"><a href="wrangling.html#apply-functions-across-many-columns-with-mutate-and-across"><i class="fa fa-check"></i><b>3.10</b> Apply functions across many columns with <code>mutate</code> and <code>across</code></a></li>
<li class="chapter" data-level="3.11" data-path="wrangling.html"><a href="wrangling.html#apply-functions-across-columns-within-one-row-with-rowwise-and-mutate"><i class="fa fa-check"></i><b>3.11</b> Apply functions across columns within one row with <code>rowwise</code> and <code>mutate</code></a></li>
<li class="chapter" data-level="3.12" data-path="wrangling.html"><a href="wrangling.html#summary"><i class="fa fa-check"></i><b>3.12</b> Summary</a></li>
<li class="chapter" data-level="3.13" data-path="wrangling.html"><a href="wrangling.html#exercises-2"><i class="fa fa-check"></i><b>3.13</b> Exercises</a></li>
<li class="chapter" data-level="3.14" data-path="wrangling.html"><a href="wrangling.html#additional-resources-1"><i class="fa fa-check"></i><b>3.14</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="viz.html"><a href="viz.html"><i class="fa fa-check"></i><b>4</b> Effective data visualization</a>
<ul>
<li class="chapter" data-level="4.1" data-path="viz.html"><a href="viz.html#overview-3"><i class="fa fa-check"></i><b>4.1</b> Overview</a></li>
<li class="chapter" data-level="4.2" data-path="viz.html"><a href="viz.html#chapter-learning-objectives-3"><i class="fa fa-check"></i><b>4.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="4.3" data-path="viz.html"><a href="viz.html#choosing-the-visualization"><i class="fa fa-check"></i><b>4.3</b> Choosing the visualization</a></li>
<li class="chapter" data-level="4.4" data-path="viz.html"><a href="viz.html#refining-the-visualization"><i class="fa fa-check"></i><b>4.4</b> Refining the visualization</a></li>
<li class="chapter" data-level="4.5" data-path="viz.html"><a href="viz.html#creating-visualizations-with-ggplot2"><i class="fa fa-check"></i><b>4.5</b> Creating visualizations with <code>ggplot2</code></a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="viz.html"><a href="viz.html#scatter-plots-and-line-plots-the-mauna-loa-co_text2-data-set"><i class="fa fa-check"></i><b>4.5.1</b> Scatter plots and line plots: the Mauna Loa CO<span class="math inline">\(_{\text{2}}\)</span> data set</a></li>
<li class="chapter" data-level="4.5.2" data-path="viz.html"><a href="viz.html#scatter-plots-the-old-faithful-eruption-time-data-set"><i class="fa fa-check"></i><b>4.5.2</b> Scatter plots: the Old Faithful eruption time data set</a></li>
<li class="chapter" data-level="4.5.3" data-path="viz.html"><a href="viz.html#axis-transformation-and-colored-scatter-plots-the-canadian-languages-data-set"><i class="fa fa-check"></i><b>4.5.3</b> Axis transformation and colored scatter plots: the Canadian languages data set</a></li>
<li class="chapter" data-level="4.5.4" data-path="viz.html"><a href="viz.html#bar-plots-the-island-landmass-data-set"><i class="fa fa-check"></i><b>4.5.4</b> Bar plots: the island landmass data set</a></li>
<li class="chapter" data-level="4.5.5" data-path="viz.html"><a href="viz.html#histograms-the-michelson-speed-of-light-data-set"><i class="fa fa-check"></i><b>4.5.5</b> Histograms: the Michelson speed of light data set</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="viz.html"><a href="viz.html#explaining-the-visualization"><i class="fa fa-check"></i><b>4.6</b> Explaining the visualization</a></li>
<li class="chapter" data-level="4.7" data-path="viz.html"><a href="viz.html#saving-the-visualization"><i class="fa fa-check"></i><b>4.7</b> Saving the visualization</a></li>
<li class="chapter" data-level="4.8" data-path="viz.html"><a href="viz.html#exercises-3"><i class="fa fa-check"></i><b>4.8</b> Exercises</a></li>
<li class="chapter" data-level="4.9" data-path="viz.html"><a href="viz.html#additional-resources-2"><i class="fa fa-check"></i><b>4.9</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="classification.html"><a href="classification.html"><i class="fa fa-check"></i><b>5</b> Classification I: training &amp; predicting</a>
<ul>
<li class="chapter" data-level="5.1" data-path="classification.html"><a href="classification.html#overview-4"><i class="fa fa-check"></i><b>5.1</b> Overview</a></li>
<li class="chapter" data-level="5.2" data-path="classification.html"><a href="classification.html#chapter-learning-objectives-4"><i class="fa fa-check"></i><b>5.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="5.3" data-path="classification.html"><a href="classification.html#the-classification-problem"><i class="fa fa-check"></i><b>5.3</b> The classification problem</a></li>
<li class="chapter" data-level="5.4" data-path="classification.html"><a href="classification.html#exploring-a-data-set"><i class="fa fa-check"></i><b>5.4</b> Exploring a data set</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="classification.html"><a href="classification.html#loading-the-cancer-data"><i class="fa fa-check"></i><b>5.4.1</b> Loading the cancer data</a></li>
<li class="chapter" data-level="5.4.2" data-path="classification.html"><a href="classification.html#describing-the-variables-in-the-cancer-data-set"><i class="fa fa-check"></i><b>5.4.2</b> Describing the variables in the cancer data set</a></li>
<li class="chapter" data-level="5.4.3" data-path="classification.html"><a href="classification.html#exploring-the-cancer-data"><i class="fa fa-check"></i><b>5.4.3</b> Exploring the cancer data</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="classification.html"><a href="classification.html#classification-with-k-nearest-neighbors"><i class="fa fa-check"></i><b>5.5</b> Classification with <span class="math inline">\(K\)</span>-nearest neighbors</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="classification.html"><a href="classification.html#distance-between-points"><i class="fa fa-check"></i><b>5.5.1</b> Distance between points</a></li>
<li class="chapter" data-level="5.5.2" data-path="classification.html"><a href="classification.html#more-than-two-explanatory-variables"><i class="fa fa-check"></i><b>5.5.2</b> More than two explanatory variables</a></li>
<li class="chapter" data-level="5.5.3" data-path="classification.html"><a href="classification.html#summary-of-k-nearest-neighbors-algorithm"><i class="fa fa-check"></i><b>5.5.3</b> Summary of <span class="math inline">\(K\)</span>-nearest neighbors algorithm</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="classification.html"><a href="classification.html#k-nearest-neighbors-with-tidymodels"><i class="fa fa-check"></i><b>5.6</b> <span class="math inline">\(K\)</span>-nearest neighbors with <code>tidymodels</code></a></li>
<li class="chapter" data-level="5.7" data-path="classification.html"><a href="classification.html#data-preprocessing-with-tidymodels"><i class="fa fa-check"></i><b>5.7</b> Data preprocessing with <code>tidymodels</code></a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="classification.html"><a href="classification.html#centering-and-scaling"><i class="fa fa-check"></i><b>5.7.1</b> Centering and scaling</a></li>
<li class="chapter" data-level="5.7.2" data-path="classification.html"><a href="classification.html#balancing"><i class="fa fa-check"></i><b>5.7.2</b> Balancing</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="classification.html"><a href="classification.html#puttingittogetherworkflow"><i class="fa fa-check"></i><b>5.8</b> Putting it together in a <code>workflow</code></a></li>
<li class="chapter" data-level="5.9" data-path="classification.html"><a href="classification.html#exercises-4"><i class="fa fa-check"></i><b>5.9</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="classification2.html"><a href="classification2.html"><i class="fa fa-check"></i><b>6</b> Classification II: evaluation &amp; tuning</a>
<ul>
<li class="chapter" data-level="6.1" data-path="classification2.html"><a href="classification2.html#overview-5"><i class="fa fa-check"></i><b>6.1</b> Overview</a></li>
<li class="chapter" data-level="6.2" data-path="classification2.html"><a href="classification2.html#chapter-learning-objectives-5"><i class="fa fa-check"></i><b>6.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="6.3" data-path="classification2.html"><a href="classification2.html#evaluating-accuracy"><i class="fa fa-check"></i><b>6.3</b> Evaluating accuracy</a></li>
<li class="chapter" data-level="6.4" data-path="classification2.html"><a href="classification2.html#randomseeds"><i class="fa fa-check"></i><b>6.4</b> Randomness and seeds</a></li>
<li class="chapter" data-level="6.5" data-path="classification2.html"><a href="classification2.html#evaluating-accuracy-with-tidymodels"><i class="fa fa-check"></i><b>6.5</b> Evaluating accuracy with <code>tidymodels</code></a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="classification2.html"><a href="classification2.html#create-the-train-test-split"><i class="fa fa-check"></i><b>6.5.1</b> Create the train / test split</a></li>
<li class="chapter" data-level="6.5.2" data-path="classification2.html"><a href="classification2.html#preprocess-the-data"><i class="fa fa-check"></i><b>6.5.2</b> Preprocess the data</a></li>
<li class="chapter" data-level="6.5.3" data-path="classification2.html"><a href="classification2.html#train-the-classifier"><i class="fa fa-check"></i><b>6.5.3</b> Train the classifier</a></li>
<li class="chapter" data-level="6.5.4" data-path="classification2.html"><a href="classification2.html#predict-the-labels-in-the-test-set"><i class="fa fa-check"></i><b>6.5.4</b> Predict the labels in the test set</a></li>
<li class="chapter" data-level="6.5.5" data-path="classification2.html"><a href="classification2.html#compute-the-accuracy"><i class="fa fa-check"></i><b>6.5.5</b> Compute the accuracy</a></li>
<li class="chapter" data-level="6.5.6" data-path="classification2.html"><a href="classification2.html#critically-analyze-performance"><i class="fa fa-check"></i><b>6.5.6</b> Critically analyze performance</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="classification2.html"><a href="classification2.html#tuning-the-classifier"><i class="fa fa-check"></i><b>6.6</b> Tuning the classifier</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="classification2.html"><a href="classification2.html#cross-validation"><i class="fa fa-check"></i><b>6.6.1</b> Cross-validation</a></li>
<li class="chapter" data-level="6.6.2" data-path="classification2.html"><a href="classification2.html#parameter-value-selection"><i class="fa fa-check"></i><b>6.6.2</b> Parameter value selection</a></li>
<li class="chapter" data-level="6.6.3" data-path="classification2.html"><a href="classification2.html#underoverfitting"><i class="fa fa-check"></i><b>6.6.3</b> Under/Overfitting</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="classification2.html"><a href="classification2.html#summary-1"><i class="fa fa-check"></i><b>6.7</b> Summary</a></li>
<li class="chapter" data-level="6.8" data-path="classification2.html"><a href="classification2.html#predictor-variable-selection"><i class="fa fa-check"></i><b>6.8</b> Predictor variable selection</a>
<ul>
<li class="chapter" data-level="6.8.1" data-path="classification2.html"><a href="classification2.html#the-effect-of-irrelevant-predictors"><i class="fa fa-check"></i><b>6.8.1</b> The effect of irrelevant predictors</a></li>
<li class="chapter" data-level="6.8.2" data-path="classification2.html"><a href="classification2.html#finding-a-good-subset-of-predictors"><i class="fa fa-check"></i><b>6.8.2</b> Finding a good subset of predictors</a></li>
<li class="chapter" data-level="6.8.3" data-path="classification2.html"><a href="classification2.html#forward-selection-in-r"><i class="fa fa-check"></i><b>6.8.3</b> Forward selection in R</a></li>
</ul></li>
<li class="chapter" data-level="6.9" data-path="classification2.html"><a href="classification2.html#exercises-5"><i class="fa fa-check"></i><b>6.9</b> Exercises</a></li>
<li class="chapter" data-level="6.10" data-path="classification2.html"><a href="classification2.html#additional-resources-3"><i class="fa fa-check"></i><b>6.10</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="regression1.html"><a href="regression1.html"><i class="fa fa-check"></i><b>7</b> Regression I: K-nearest neighbors</a>
<ul>
<li class="chapter" data-level="7.1" data-path="regression1.html"><a href="regression1.html#overview-6"><i class="fa fa-check"></i><b>7.1</b> Overview</a></li>
<li class="chapter" data-level="7.2" data-path="regression1.html"><a href="regression1.html#chapter-learning-objectives-6"><i class="fa fa-check"></i><b>7.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="7.3" data-path="regression1.html"><a href="regression1.html#the-regression-problem"><i class="fa fa-check"></i><b>7.3</b> The regression problem</a></li>
<li class="chapter" data-level="7.4" data-path="regression1.html"><a href="regression1.html#exploring-a-data-set-1"><i class="fa fa-check"></i><b>7.4</b> Exploring a data set</a></li>
<li class="chapter" data-level="7.5" data-path="regression1.html"><a href="regression1.html#k-nearest-neighbors-regression"><i class="fa fa-check"></i><b>7.5</b> K-nearest neighbors regression</a></li>
<li class="chapter" data-level="7.6" data-path="regression1.html"><a href="regression1.html#training-evaluating-and-tuning-the-model"><i class="fa fa-check"></i><b>7.6</b> Training, evaluating, and tuning the model</a></li>
<li class="chapter" data-level="7.7" data-path="regression1.html"><a href="regression1.html#underfitting-and-overfitting"><i class="fa fa-check"></i><b>7.7</b> Underfitting and overfitting</a></li>
<li class="chapter" data-level="7.8" data-path="regression1.html"><a href="regression1.html#evaluating-on-the-test-set"><i class="fa fa-check"></i><b>7.8</b> Evaluating on the test set</a></li>
<li class="chapter" data-level="7.9" data-path="regression1.html"><a href="regression1.html#multivariable-knn-regression"><i class="fa fa-check"></i><b>7.9</b> Multivariable KNN regression</a></li>
<li class="chapter" data-level="7.10" data-path="regression1.html"><a href="regression1.html#strengths-and-limitations-of-knn-regression"><i class="fa fa-check"></i><b>7.10</b> Strengths and limitations of KNN regression</a></li>
<li class="chapter" data-level="7.11" data-path="regression1.html"><a href="regression1.html#exercises-6"><i class="fa fa-check"></i><b>7.11</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="regression2.html"><a href="regression2.html"><i class="fa fa-check"></i><b>8</b> Regression II: linear regression</a>
<ul>
<li class="chapter" data-level="8.1" data-path="regression2.html"><a href="regression2.html#overview-7"><i class="fa fa-check"></i><b>8.1</b> Overview</a></li>
<li class="chapter" data-level="8.2" data-path="regression2.html"><a href="regression2.html#chapter-learning-objectives-7"><i class="fa fa-check"></i><b>8.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="8.3" data-path="regression2.html"><a href="regression2.html#simple-linear-regression"><i class="fa fa-check"></i><b>8.3</b> Simple linear regression</a></li>
<li class="chapter" data-level="8.4" data-path="regression2.html"><a href="regression2.html#linear-regression-in-r"><i class="fa fa-check"></i><b>8.4</b> Linear regression in R</a></li>
<li class="chapter" data-level="8.5" data-path="regression2.html"><a href="regression2.html#comparing-simple-linear-and-knn-regression"><i class="fa fa-check"></i><b>8.5</b> Comparing simple linear and KNN regression</a></li>
<li class="chapter" data-level="8.6" data-path="regression2.html"><a href="regression2.html#multivariable-linear-regression"><i class="fa fa-check"></i><b>8.6</b> Multivariable linear regression</a></li>
<li class="chapter" data-level="8.7" data-path="regression2.html"><a href="regression2.html#multicollinearity-and-outliers"><i class="fa fa-check"></i><b>8.7</b> Multicollinearity and outliers</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="regression2.html"><a href="regression2.html#outliers"><i class="fa fa-check"></i><b>8.7.1</b> Outliers</a></li>
<li class="chapter" data-level="8.7.2" data-path="regression2.html"><a href="regression2.html#multicollinearity"><i class="fa fa-check"></i><b>8.7.2</b> Multicollinearity</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="regression2.html"><a href="regression2.html#designing-new-predictors"><i class="fa fa-check"></i><b>8.8</b> Designing new predictors</a></li>
<li class="chapter" data-level="8.9" data-path="regression2.html"><a href="regression2.html#the-other-sides-of-regression"><i class="fa fa-check"></i><b>8.9</b> The other sides of regression</a></li>
<li class="chapter" data-level="8.10" data-path="regression2.html"><a href="regression2.html#exercises-7"><i class="fa fa-check"></i><b>8.10</b> Exercises</a></li>
<li class="chapter" data-level="8.11" data-path="regression2.html"><a href="regression2.html#additional-resources-4"><i class="fa fa-check"></i><b>8.11</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="clustering.html"><a href="clustering.html"><i class="fa fa-check"></i><b>9</b> Clustering</a>
<ul>
<li class="chapter" data-level="9.1" data-path="clustering.html"><a href="clustering.html#overview-8"><i class="fa fa-check"></i><b>9.1</b> Overview</a></li>
<li class="chapter" data-level="9.2" data-path="clustering.html"><a href="clustering.html#chapter-learning-objectives-8"><i class="fa fa-check"></i><b>9.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="9.3" data-path="clustering.html"><a href="clustering.html#clustering-1"><i class="fa fa-check"></i><b>9.3</b> Clustering</a></li>
<li class="chapter" data-level="9.4" data-path="clustering.html"><a href="clustering.html#k-means"><i class="fa fa-check"></i><b>9.4</b> K-means</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="clustering.html"><a href="clustering.html#measuring-cluster-quality"><i class="fa fa-check"></i><b>9.4.1</b> Measuring cluster quality</a></li>
<li class="chapter" data-level="9.4.2" data-path="clustering.html"><a href="clustering.html#the-clustering-algorithm"><i class="fa fa-check"></i><b>9.4.2</b> The clustering algorithm</a></li>
<li class="chapter" data-level="9.4.3" data-path="clustering.html"><a href="clustering.html#random-restarts"><i class="fa fa-check"></i><b>9.4.3</b> Random restarts</a></li>
<li class="chapter" data-level="9.4.4" data-path="clustering.html"><a href="clustering.html#choosing-k"><i class="fa fa-check"></i><b>9.4.4</b> Choosing K</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="clustering.html"><a href="clustering.html#data-pre-processing-for-k-means"><i class="fa fa-check"></i><b>9.5</b> Data pre-processing for K-means</a></li>
<li class="chapter" data-level="9.6" data-path="clustering.html"><a href="clustering.html#k-means-in-r"><i class="fa fa-check"></i><b>9.6</b> K-means in R</a></li>
<li class="chapter" data-level="9.7" data-path="clustering.html"><a href="clustering.html#exercises-8"><i class="fa fa-check"></i><b>9.7</b> Exercises</a></li>
<li class="chapter" data-level="9.8" data-path="clustering.html"><a href="clustering.html#additional-resources-5"><i class="fa fa-check"></i><b>9.8</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="inference.html"><a href="inference.html"><i class="fa fa-check"></i><b>10</b> Statistical inference</a>
<ul>
<li class="chapter" data-level="10.1" data-path="inference.html"><a href="inference.html#overview-9"><i class="fa fa-check"></i><b>10.1</b> Overview</a></li>
<li class="chapter" data-level="10.2" data-path="inference.html"><a href="inference.html#chapter-learning-objectives-9"><i class="fa fa-check"></i><b>10.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="10.3" data-path="inference.html"><a href="inference.html#why-do-we-need-sampling"><i class="fa fa-check"></i><b>10.3</b> Why do we need sampling?</a></li>
<li class="chapter" data-level="10.4" data-path="inference.html"><a href="inference.html#sampling-distributions"><i class="fa fa-check"></i><b>10.4</b> Sampling distributions</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="inference.html"><a href="inference.html#sampling-distributions-for-proportions"><i class="fa fa-check"></i><b>10.4.1</b> Sampling distributions for proportions</a></li>
<li class="chapter" data-level="10.4.2" data-path="inference.html"><a href="inference.html#sampling-distributions-for-means"><i class="fa fa-check"></i><b>10.4.2</b> Sampling distributions for means</a></li>
<li class="chapter" data-level="10.4.3" data-path="inference.html"><a href="inference.html#summary-2"><i class="fa fa-check"></i><b>10.4.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="inference.html"><a href="inference.html#bootstrapping"><i class="fa fa-check"></i><b>10.5</b> Bootstrapping</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="inference.html"><a href="inference.html#overview-10"><i class="fa fa-check"></i><b>10.5.1</b> Overview</a></li>
<li class="chapter" data-level="10.5.2" data-path="inference.html"><a href="inference.html#bootstrapping-in-r"><i class="fa fa-check"></i><b>10.5.2</b> Bootstrapping in R</a></li>
<li class="chapter" data-level="10.5.3" data-path="inference.html"><a href="inference.html#using-the-bootstrap-to-calculate-a-plausible-range"><i class="fa fa-check"></i><b>10.5.3</b> Using the bootstrap to calculate a plausible range</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="inference.html"><a href="inference.html#exercises-9"><i class="fa fa-check"></i><b>10.6</b> Exercises</a></li>
<li class="chapter" data-level="10.7" data-path="inference.html"><a href="inference.html#additional-resources-6"><i class="fa fa-check"></i><b>10.7</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html"><i class="fa fa-check"></i><b>11</b> Combining code and text with Jupyter</a>
<ul>
<li class="chapter" data-level="11.1" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#overview-11"><i class="fa fa-check"></i><b>11.1</b> Overview</a></li>
<li class="chapter" data-level="11.2" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#chapter-learning-objectives-10"><i class="fa fa-check"></i><b>11.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="11.3" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#jupyter"><i class="fa fa-check"></i><b>11.3</b> Jupyter</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#accessing-jupyter"><i class="fa fa-check"></i><b>11.3.1</b> Accessing Jupyter</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#code-cells"><i class="fa fa-check"></i><b>11.4</b> Code cells</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#executing-code-cells"><i class="fa fa-check"></i><b>11.4.1</b> Executing code cells</a></li>
<li class="chapter" data-level="11.4.2" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#the-kernel"><i class="fa fa-check"></i><b>11.4.2</b> The Kernel</a></li>
<li class="chapter" data-level="11.4.3" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#creating-new-code-cells"><i class="fa fa-check"></i><b>11.4.3</b> Creating new code cells</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#markdown-cells"><i class="fa fa-check"></i><b>11.5</b> Markdown cells</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#editing-markdown-cells"><i class="fa fa-check"></i><b>11.5.1</b> Editing Markdown cells</a></li>
<li class="chapter" data-level="11.5.2" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#creating-new-markdown-cells"><i class="fa fa-check"></i><b>11.5.2</b> Creating new Markdown cells</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#saving-your-work"><i class="fa fa-check"></i><b>11.6</b> Saving your work</a></li>
<li class="chapter" data-level="11.7" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#best-practices-for-running-a-notebook"><i class="fa fa-check"></i><b>11.7</b> Best practices for running a notebook</a>
<ul>
<li class="chapter" data-level="11.7.1" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#best-practices-for-executing-code-cells"><i class="fa fa-check"></i><b>11.7.1</b> Best practices for executing code cells</a></li>
<li class="chapter" data-level="11.7.2" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#best-practices-for-including-r-packages-in-notebooks"><i class="fa fa-check"></i><b>11.7.2</b> Best practices for including R packages in notebooks</a></li>
<li class="chapter" data-level="11.7.3" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#summary-of-best-practices-for-running-a-notebook"><i class="fa fa-check"></i><b>11.7.3</b> Summary of best practices for running a notebook</a></li>
</ul></li>
<li class="chapter" data-level="11.8" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#exploring-data-files"><i class="fa fa-check"></i><b>11.8</b> Exploring data files</a></li>
<li class="chapter" data-level="11.9" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#exporting-to-a-different-file-format"><i class="fa fa-check"></i><b>11.9</b> Exporting to a different file format</a>
<ul>
<li class="chapter" data-level="11.9.1" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#exporting-to-html"><i class="fa fa-check"></i><b>11.9.1</b> Exporting to HTML</a></li>
<li class="chapter" data-level="11.9.2" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#exporting-to-pdf"><i class="fa fa-check"></i><b>11.9.2</b> Exporting to PDF</a></li>
</ul></li>
<li class="chapter" data-level="11.10" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#creating-a-new-jupyter-notebook"><i class="fa fa-check"></i><b>11.10</b> Creating a new Jupyter notebook</a></li>
<li class="chapter" data-level="11.11" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#additional-resources-7"><i class="fa fa-check"></i><b>11.11</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html"><i class="fa fa-check"></i><b>12</b> Collaboration with version control</a>
<ul>
<li class="chapter" data-level="12.1" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#overview-12"><i class="fa fa-check"></i><b>12.1</b> Overview</a></li>
<li class="chapter" data-level="12.2" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#chapter-learning-objectives-11"><i class="fa fa-check"></i><b>12.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="12.3" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#what-is-version-control-and-why-should-i-use-it"><i class="fa fa-check"></i><b>12.3</b> What is version control, and why should I use it?</a></li>
<li class="chapter" data-level="12.4" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#version-control-repositories"><i class="fa fa-check"></i><b>12.4</b> Version control repositories</a></li>
<li class="chapter" data-level="12.5" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#version-control-workflows"><i class="fa fa-check"></i><b>12.5</b> Version control workflows</a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#commit-changes"><i class="fa fa-check"></i><b>12.5.1</b> Committing changes to a local repository</a></li>
<li class="chapter" data-level="12.5.2" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#pushing-changes-to-a-remote-repository"><i class="fa fa-check"></i><b>12.5.2</b> Pushing changes to a remote repository</a></li>
<li class="chapter" data-level="12.5.3" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#pulling-changes-from-a-remote-repository"><i class="fa fa-check"></i><b>12.5.3</b> Pulling changes from a remote repository</a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#working-with-remote-repositories-using-github"><i class="fa fa-check"></i><b>12.6</b> Working with remote repositories using GitHub</a>
<ul>
<li class="chapter" data-level="12.6.1" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#creating-a-remote-repository-on-github"><i class="fa fa-check"></i><b>12.6.1</b> Creating a remote repository on GitHub</a></li>
<li class="chapter" data-level="12.6.2" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#editing-files-on-github-with-the-pen-tool"><i class="fa fa-check"></i><b>12.6.2</b> Editing files on GitHub with the pen tool</a></li>
<li class="chapter" data-level="12.6.3" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#creating-files-on-github-with-the-add-file-menu"><i class="fa fa-check"></i><b>12.6.3</b> Creating files on GitHub with the “Add file” menu</a></li>
</ul></li>
<li class="chapter" data-level="12.7" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#local-repo-jupyter"><i class="fa fa-check"></i><b>12.7</b> Working with local repositories using Jupyter</a>
<ul>
<li class="chapter" data-level="12.7.1" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#generating-a-github-personal-access-token"><i class="fa fa-check"></i><b>12.7.1</b> Generating a GitHub personal access token</a></li>
<li class="chapter" data-level="12.7.2" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#cloning-a-repository-using-jupyter"><i class="fa fa-check"></i><b>12.7.2</b> Cloning a repository using Jupyter</a></li>
<li class="chapter" data-level="12.7.3" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#specifying-files-to-commit"><i class="fa fa-check"></i><b>12.7.3</b> Specifying files to commit</a></li>
<li class="chapter" data-level="12.7.4" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#making-the-commit"><i class="fa fa-check"></i><b>12.7.4</b> Making the commit</a></li>
<li class="chapter" data-level="12.7.5" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#pushing-the-commits-to-github"><i class="fa fa-check"></i><b>12.7.5</b> Pushing the commits to GitHub</a></li>
</ul></li>
<li class="chapter" data-level="12.8" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#collaboration"><i class="fa fa-check"></i><b>12.8</b> Collaboration</a>
<ul>
<li class="chapter" data-level="12.8.1" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#giving-collaborators-access-to-your-project"><i class="fa fa-check"></i><b>12.8.1</b> Giving collaborators access to your project</a></li>
<li class="chapter" data-level="12.8.2" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#pulling-changes-from-github-using-jupyter"><i class="fa fa-check"></i><b>12.8.2</b> Pulling changes from GitHub using Jupyter</a></li>
<li class="chapter" data-level="12.8.3" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#handling-merge-conflicts"><i class="fa fa-check"></i><b>12.8.3</b> Handling merge conflicts</a></li>
<li class="chapter" data-level="12.8.4" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#communicating-using-github-issues"><i class="fa fa-check"></i><b>12.8.4</b> Communicating using GitHub issues</a></li>
</ul></li>
<li class="chapter" data-level="12.9" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#exercises-10"><i class="fa fa-check"></i><b>12.9</b> Exercises</a></li>
<li class="chapter" data-level="12.10" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#vc-add-res"><i class="fa fa-check"></i><b>12.10</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html"><i class="fa fa-check"></i><b>13</b> Setting up your computer</a>
<ul>
<li class="chapter" data-level="13.1" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#overview-13"><i class="fa fa-check"></i><b>13.1</b> Overview</a></li>
<li class="chapter" data-level="13.2" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#chapter-learning-objectives-12"><i class="fa fa-check"></i><b>13.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="13.3" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#installing-software-on-your-own-computer"><i class="fa fa-check"></i><b>13.3</b> Installing software on your own computer</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#git"><i class="fa fa-check"></i><b>13.3.1</b> Git</a></li>
<li class="chapter" data-level="13.3.2" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#miniconda"><i class="fa fa-check"></i><b>13.3.2</b> Miniconda</a></li>
<li class="chapter" data-level="13.3.3" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#jupyterlab"><i class="fa fa-check"></i><b>13.3.3</b> JupyterLab</a></li>
<li class="chapter" data-level="13.3.4" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#r-r-packages-and-the-irkernel"><i class="fa fa-check"></i><b>13.3.4</b> R, R packages, and the IRkernel</a></li>
<li class="chapter" data-level="13.3.5" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#latex"><i class="fa fa-check"></i><b>13.3.5</b> LaTeX</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#finishing-up-installation"><i class="fa fa-check"></i><b>13.4</b> Finishing up installation</a></li>
<li class="chapter" data-level="13.5" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#downloading-the-worksheets-for-this-book"><i class="fa fa-check"></i><b>13.5</b> Downloading the worksheets for this book</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="appendixA.html"><a href="appendixA.html"><i class="fa fa-check"></i><b>A</b> Downloading files from JupyterHub</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"><p><img src="img/ds-a-first-intro-graphic.png" /><br />
Data Science</p></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="reading" class="section level1" number="2">
<h1><span class="header-section-number">Chapter 2</span> Reading in data locally and from the web</h1>
<div id="overview-1" class="section level2" number="2.1">
<h2><span class="header-section-number">2.1</span> Overview</h2>
<p>In this chapter, you’ll learn to read tabular data of various formats into R
from your local device (e.g., your laptop) and the web. “Reading” (or “loading”)
 is the process of
converting data (stored as plain text, a database, HTML, etc.) into an object
(e.g., a data frame) that R can easily access and manipulate. Thus reading data
is the gateway to any data analysis; you won’t be able to analyze data unless
you’ve loaded it first. And because there are many ways to store data, there
are similarly many ways to read data into R. The more time you spend upfront
matching the data reading method to the type of data you have, the less time
you will have to devote to re-formatting, cleaning and wrangling your data (the
second step to all data analyses). It’s like making sure your shoelaces are
tied well before going for a run so that you don’t trip later on!</p>
</div>
<div id="chapter-learning-objectives-1" class="section level2" number="2.2">
<h2><span class="header-section-number">2.2</span> Chapter learning objectives</h2>
<p>By the end of the chapter, readers will be able to do the following:</p>
<ul>
<li>Define the following:
<ul>
<li>absolute file path</li>
<li>relative file path</li>
<li><strong>U</strong>niform <strong>R</strong>esource <strong>L</strong>ocator (URL)</li>
</ul></li>
<li>Read data into R using a relative path and a URL.</li>
<li>Compare and contrast the following functions:
<ul>
<li><code>read_csv</code></li>
<li><code>read_tsv</code></li>
<li><code>read_csv2</code></li>
<li><code>read_delim</code></li>
<li><code>read_excel</code></li>
</ul></li>
<li>Match the following <code>tidyverse</code> <code>read_*</code> function arguments to their descriptions:
<ul>
<li><code>file</code></li>
<li><code>delim</code></li>
<li><code>col_names</code></li>
<li><code>skip</code></li>
</ul></li>
<li>Choose the appropriate <code>tidyverse</code> <code>read_*</code> function and function arguments to load a given plain text tabular data set into R.</li>
<li>Use <code>readxl</code> package’s <code>read_excel</code> function and arguments to load a sheet from an excel file into R.</li>
<li>Connect to a database using the <code>DBI</code> package’s <code>dbConnect</code> function.</li>
<li>List the tables in a database using the <code>DBI</code> package’s <code>dbListTables</code> function.</li>
<li>Create a reference to a database table that is queriable using the <code>tbl</code> from the <code>dbplyr</code> package.</li>
<li>Retrieve data from a database query and bring it into R using the <code>collect</code> function from the <code>dbplyr</code> package.</li>
<li>Use <code>write_csv</code> to save a data frame to a <code>.csv</code> file.</li>
<li>(<em>Optional</em>) Obtain data using <strong>a</strong>pplication <strong>p</strong>rogramming <strong>i</strong>nterfaces (APIs) and web scraping.
<ul>
<li>Read HTML source code from a URL using the <code>rvest</code> package.</li>
<li>Read data from the Twitter API using the <code>rtweet</code> package.</li>
<li>Compare downloading tabular data from a plain text file (e.g., <code>.csv</code>), accessing data from an API, and scraping the HTML source code from a website.</li>
</ul></li>
</ul>
</div>
<div id="absolute-and-relative-file-paths" class="section level2" number="2.3">
<h2><span class="header-section-number">2.3</span> Absolute and relative file paths</h2>
<p>This chapter will discuss the different functions we can use to import data
into R, but before we can talk about <em>how</em> we read the data into R with these
functions, we first need to talk about <em>where</em> the data lives. When you load a
data set into R, you first need to tell R where those files live. The file
could live on your computer (<em>local</em>)
 
or somewhere on the internet (<em>remote</em>).</p>
<p>The place where the file lives on your computer is called the “path.” You can
think of the path as directions to the file. There are two kinds of paths:
<em>relative</em> paths and <em>absolute</em> paths. A relative path is where the file is
with respect to where you currently are on the computer (e.g., where the file
you’re working in is). On the other hand, an absolute path is where the file is
in respect to the computer’s filesystem base (or root) folder.</p>
<p>Suppose our computer’s filesystem looks like the picture in Figure
<a href="reading.html#fig:file-system-for-export-to-intro-datascience">2.1</a>, and we are working in a
file titled <code>worksheet_02.ipynb</code>. If we want to
read the <code>.csv</code> file named <code>happiness_report.csv</code> into R, we could do this
using either a relative or an absolute path. We show both choices
below.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:file-system-for-export-to-intro-datascience"></span>
<img src="img/filesystem.jpeg" alt="Example file system." width="100%" />
<p class="caption">
Figure 2.1: Example file system.
</p>
</div>
<p><strong>Reading <code>happiness_report.csv</code> using a relative path:</strong></p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="reading.html#cb30-1" aria-hidden="true" tabindex="-1"></a>happy_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/happiness_report.csv&quot;</span>)</span></code></pre></div>
<p><strong>Reading <code>happiness_report.csv</code> using an absolute path:</strong></p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="reading.html#cb31-1" aria-hidden="true" tabindex="-1"></a>happy_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;/home/dsci-100/worksheet_02/data/happiness_report.csv&quot;</span>)</span></code></pre></div>
<p>So which one should you use? Generally speaking, to ensure your code can be run
on a different computer, you should use relative paths. An added bonus is that
it’s also less typing! Generally, you should use relative paths because the file’s
absolute path (the names of
folders between the computer’s root <code>/</code> and the file) isn’t usually the same
across different computers. For example, suppose Fatima and Jayden are working on a
project together on the <code>happiness_report.csv</code> data. Fatima’s file is stored at</p>
<p><code>/home/Fatima/project/data/happiness_report.csv</code>,</p>
<p>while Jayden’s is stored at</p>
<p><code>/home/Jayden/project/data/happiness_report.csv</code>.</p>
<p>Even though Fatima and Jayden stored their files in the same place on their
computers (in their home folders), the absolute paths are different due to
their different usernames. If Jayden has code that loads the
<code>happiness_report.csv</code> data using an absolute path, the code won’t work on
Fatima’s computer. But the relative path from inside the <code>project</code> folder
(<code>data/happiness_report.csv</code>) is the same on both computers; any code that uses
relative paths will work on both!</p>
<p>In the additional resources section, we include a link to a short video on the
difference between absolute and relative paths. You can also check out the
<code>here</code> package, which provides methods for finding and constructing file paths
in R.</p>
<p>Your file could be stored locally, as we discussed, or it could also be
somewhere on the internet (remotely). A <em>Uniform Resource Locator (URL)</em> (web
address)  indicates the location of a resource on the internet and
helps us retrieve that resource. Next, we will discuss how to get either
locally or remotely stored data into R.</p>
</div>
<div id="reading-tabular-data-from-a-plain-text-file-into-r" class="section level2" number="2.4">
<h2><span class="header-section-number">2.4</span> Reading tabular data from a plain text file into R</h2>
<div id="readcsv" class="section level3" number="2.4.1">
<h3><span class="header-section-number">2.4.1</span> <code>read_csv</code> to read in comma-separated files</h3>
<p>Now that we have learned about <em>where</em> data could be, we will learn about <em>how</em>
to import data into R using various functions. Specifically, we will learn how
to <em>read</em> tabular data from a plain text file (a document containing only text)
<em>into</em> R and <em>write</em> tabular data to a file <em>out of</em> R. The function we use to do this
depends on the file’s format. For example, in the last chapter, we learned about using
the <code>tidyverse</code> <code>read_csv</code> function when reading .csv (<strong>c</strong>omma-<strong>s</strong>eparated <strong>v</strong>alues)
files.  In that case, the separator or <em>delimiter</em>  that divided our columns was a
comma (<code>,</code>). We only learned the case where the data matched the expected defaults
of the <code>read_csv</code> function 
(column names are present, and commas are used as the delimiter between columns).
In this section, we will learn how to read
files that do not satisfy the default expectations of <code>read_csv</code>.</p>
<p>Before we jump into the cases where the data aren’t in the expected default format
for <code>tidyverse</code> and <code>read_csv</code>, let’s revisit the more straightforward
case where the defaults hold, and the only argument we need to give to the function
is the path to the file, <code>data/can_lang.csv</code>. The <code>can_lang</code> data set contains
language data from the 2016 Canadian census. 
We put <code>data/</code> before the file’s
name when we are loading the data set because this data set is located in a
sub-folder, named <code>data</code>, relative to where we are running our R code.</p>
<p>Here is what the file would look like in a plain text editor (a program that removes
all formatting, like bolding or different fonts):</p>
<pre class="code"><code>category,language,mother_tongue,most_at_home,most_at_work,lang_known
Aboriginal languages,&quot;Aboriginal languages, n.o.s.&quot;,590,235,30,665
Non-Official &amp; Non-Aboriginal languages,Afrikaans,10260,4785,85,23415
Non-Official &amp; Non-Aboriginal languages,&quot;Afro-Asiatic languages, n.i.e.&quot;,1150,44
Non-Official &amp; Non-Aboriginal languages,Akan (Twi),13460,5985,25,22150
Non-Official &amp; Non-Aboriginal languages,Albanian,26895,13135,345,31930
Aboriginal languages,&quot;Algonquian languages, n.i.e.&quot;,45,10,0,120
Aboriginal languages,Algonquin,1260,370,40,2480
Non-Official &amp; Non-Aboriginal languages,American Sign Language,2685,3020,1145,21
Non-Official &amp; Non-Aboriginal languages,Amharic,22465,12785,200,33670</code></pre>
<p>And here is a review of how we can use <code>read_csv</code> to load it into R. First we
load the <code>tidyverse</code>  package to gain access to useful
functions for reading the data.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="reading.html#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<p>Next we use <code>read_csv</code> to load the data into R, and in that call we specify the
relative path to the file.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="reading.html#cb34-1" aria-hidden="true" tabindex="-1"></a>canlang_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/can_lang.csv&quot;</span>)</span></code></pre></div>
<pre><code>## Rows: 214 Columns: 6</code></pre>
<pre><code>## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr (2): category, language
## dbl (4): mother_tongue, most_at_home, most_at_work, lang_known</code></pre>
<pre><code>## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div style="page-break-after: always;"></div>
<blockquote>
<p><strong>Note:</strong> It is also normal and expected that  a message is
printed out after using
the <code>read_csv</code> and related functions. This message lets you know the data types
of each of the columns that R inferred while reading the data into R. In the
future when we use this and related functions to load data in this book, we will
silence these messages to help with the readability of the book.</p>
</blockquote>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="reading.html#cb38-1" aria-hidden="true" tabindex="-1"></a>canlang_data</span></code></pre></div>
<pre><code>## # A tibble: 214 × 6
##    category       language    mother_tongue most_at_home most_at_work lang_known
##    &lt;chr&gt;          &lt;chr&gt;               &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt;
##  1 Aboriginal la… Aboriginal…           590          235           30        665
##  2 Non-Official … Afrikaans           10260         4785           85      23415
##  3 Non-Official … Afro-Asiat…          1150          445           10       2775
##  4 Non-Official … Akan (Twi)          13460         5985           25      22150
##  5 Non-Official … Albanian            26895        13135          345      31930
##  6 Aboriginal la… Algonquian…            45           10            0        120
##  7 Aboriginal la… Algonquin            1260          370           40       2480
##  8 Non-Official … American S…          2685         3020         1145      21930
##  9 Non-Official … Amharic             22465        12785          200      33670
## 10 Non-Official … Arabic             419890       223535         5585     629055
## # … with 204 more rows</code></pre>
</div>
<div id="skipping-rows-when-reading-in-data" class="section level3" number="2.4.2">
<h3><span class="header-section-number">2.4.2</span> Skipping rows when reading in data</h3>
<p>Oftentimes, information about how data was collected, or other relevant
information, is included at the top of the data file. This information is
usually written in sentence and paragraph form, with no delimiter because it is
not organized into columns. An example of this is shown below. This information
gives the data scientist useful context and information about the data,
however, it is not well formatted or intended to be read into a data frame cell
along with the tabular data that follows later in the file.</p>
<pre class="code"><code>Data source: https://ttimbers.github.io/canlang/
Data originally published in: Statistics Canada Census of Population 2016.
Reproduced and distributed on an as-is basis with their permission.
category,language,mother_tongue,most_at_home,most_at_work,lang_known
Aboriginal languages,&quot;Aboriginal languages, n.o.s.&quot;,590,235,30,665
Non-Official &amp; Non-Aboriginal languages,Afrikaans,10260,4785,85,23415
Non-Official &amp; Non-Aboriginal languages,&quot;Afro-Asiatic languages, n.i.e.&quot;,1150,44
Non-Official &amp; Non-Aboriginal languages,Akan (Twi),13460,5985,25,22150
Non-Official &amp; Non-Aboriginal languages,Albanian,26895,13135,345,31930
Aboriginal languages,&quot;Algonquian languages, n.i.e.&quot;,45,10,0,120
Aboriginal languages,Algonquin,1260,370,40,2480
Non-Official &amp; Non-Aboriginal languages,American Sign Language,2685,3020,1145,21
Non-Official &amp; Non-Aboriginal languages,Amharic,22465,12785,200,33670</code></pre>
<p>With this extra information being present at the top of the file, using
<code>read_csv</code> as we did previously does not allow us to correctly load the data
into R. In the case of this file we end up only reading in one column of the
data set:</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="reading.html#cb41-1" aria-hidden="true" tabindex="-1"></a>canlang_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/can_lang_meta-data.csv&quot;</span>)</span></code></pre></div>
<blockquote>
<p><strong>Note:</strong> In contrast to the normal and expected messages above, this time R
printed out a warning for us indicating that there might be a problem with how
our data is being read in. </p>
</blockquote>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="reading.html#cb42-1" aria-hidden="true" tabindex="-1"></a>canlang_data</span></code></pre></div>
<pre><code>## Warning: One or more parsing issues, see `problems()` for details</code></pre>
<pre><code>## # A tibble: 217 × 1
##    `Data source: https://ttimbers.github.io/canlang/`                           
##    &lt;chr&gt;                                                                        
##  1 &quot;Data originally published in: Statistics Canada Census of Population 2016.&quot; 
##  2 &quot;Reproduced and distributed on an as-is basis with their permission.&quot;        
##  3 &quot;category,language,mother_tongue,most_at_home,most_at_work,lang_known&quot;       
##  4 &quot;Aboriginal languages,\&quot;Aboriginal languages, n.o.s.\&quot;,590,235,30,665&quot;       
##  5 &quot;Non-Official &amp; Non-Aboriginal languages,Afrikaans,10260,4785,85,23415&quot;      
##  6 &quot;Non-Official &amp; Non-Aboriginal languages,\&quot;Afro-Asiatic languages, n.i.e.\&quot;,…
##  7 &quot;Non-Official &amp; Non-Aboriginal languages,Akan (Twi),13460,5985,25,22150&quot;     
##  8 &quot;Non-Official &amp; Non-Aboriginal languages,Albanian,26895,13135,345,31930&quot;     
##  9 &quot;Aboriginal languages,\&quot;Algonquian languages, n.i.e.\&quot;,45,10,0,120&quot;          
## 10 &quot;Aboriginal languages,Algonquin,1260,370,40,2480&quot;                            
## # … with 207 more rows</code></pre>
<p>To successfully read data like this into R, the <code>skip</code>
argument  can be useful to tell R
how many lines to skip before
it should start reading in the data. In the example above, we would set this
value to 3.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="reading.html#cb45-1" aria-hidden="true" tabindex="-1"></a>canlang_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/can_lang_meta-data.csv&quot;</span>, </span>
<span id="cb45-2"><a href="reading.html#cb45-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">skip =</span> <span class="dv">3</span>)</span>
<span id="cb45-3"><a href="reading.html#cb45-3" aria-hidden="true" tabindex="-1"></a>canlang_data</span></code></pre></div>
<pre><code>## # A tibble: 214 × 6
##    category       language    mother_tongue most_at_home most_at_work lang_known
##    &lt;chr&gt;          &lt;chr&gt;               &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt;
##  1 Aboriginal la… Aboriginal…           590          235           30        665
##  2 Non-Official … Afrikaans           10260         4785           85      23415
##  3 Non-Official … Afro-Asiat…          1150          445           10       2775
##  4 Non-Official … Akan (Twi)          13460         5985           25      22150
##  5 Non-Official … Albanian            26895        13135          345      31930
##  6 Aboriginal la… Algonquian…            45           10            0        120
##  7 Aboriginal la… Algonquin            1260          370           40       2480
##  8 Non-Official … American S…          2685         3020         1145      21930
##  9 Non-Official … Amharic             22465        12785          200      33670
## 10 Non-Official … Arabic             419890       223535         5585     629055
## # … with 204 more rows</code></pre>
<p>How did we know to skip three lines? We looked at the data! The first three lines
of the data had information we didn’t need to import:</p>
<pre class="code"><code>Data source: https://ttimbers.github.io/canlang/
Data originally published in: Statistics Canada Census of Population 2016.
Reproduced and distributed on an as-is basis with their permission.</code></pre>
<p>The column names began at line 4, so we skipped the first three lines.</p>
</div>
<div id="read_tsv-to-read-in-tab-separated-files" class="section level3" number="2.4.3">
<h3><span class="header-section-number">2.4.3</span> <code>read_tsv</code> to read in tab-separated files</h3>
<p>Another common way data is stored is with tabs as the delimiter. Notice the
data file, <code>can_lang_tab.tsv</code>, has tabs in between the columns instead of
commas.</p>
<pre class="code"><code>category    language    mother_tongue   most_at_home    most_at_work    lang_kno
Aboriginal languages    Aboriginal languages, n.o.s.    590 235 30  665
Non-Official &amp; Non-Aboriginal languages Afrikaans   10260   4785    85  23415
Non-Official &amp; Non-Aboriginal languages Afro-Asiatic languages, n.i.e.  1150    
Non-Official &amp; Non-Aboriginal languages Akan (Twi)  13460   5985    25  22150
Non-Official &amp; Non-Aboriginal languages Albanian    26895   13135   345 31930
Aboriginal languages    Algonquian languages, n.i.e.    45  10  0   120
Aboriginal languages    Algonquin   1260    370 40  2480
Non-Official &amp; Non-Aboriginal languages American Sign Language  2685    3020    
Non-Official &amp; Non-Aboriginal languages Amharic 22465   12785   200 33670</code></pre>
<p>To read in this type of data, we can use the <code>read_tsv</code>

to read in .tsv (<strong>t</strong>ab <strong>s</strong>eparated <strong>v</strong>alues) files.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="reading.html#cb49-1" aria-hidden="true" tabindex="-1"></a>canlang_data <span class="ot">&lt;-</span> <span class="fu">read_tsv</span>(<span class="st">&quot;data/can_lang_tab.tsv&quot;</span>)</span>
<span id="cb49-2"><a href="reading.html#cb49-2" aria-hidden="true" tabindex="-1"></a>canlang_data</span></code></pre></div>
<pre><code>## # A tibble: 214 × 6
##    category       language    mother_tongue most_at_home most_at_work lang_known
##    &lt;chr&gt;          &lt;chr&gt;               &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt;
##  1 Aboriginal la… Aboriginal…           590          235           30        665
##  2 Non-Official … Afrikaans           10260         4785           85      23415
##  3 Non-Official … Afro-Asiat…          1150          445           10       2775
##  4 Non-Official … Akan (Twi)          13460         5985           25      22150
##  5 Non-Official … Albanian            26895        13135          345      31930
##  6 Aboriginal la… Algonquian…            45           10            0        120
##  7 Aboriginal la… Algonquin            1260          370           40       2480
##  8 Non-Official … American S…          2685         3020         1145      21930
##  9 Non-Official … Amharic             22465        12785          200      33670
## 10 Non-Official … Arabic             419890       223535         5585     629055
## # … with 204 more rows</code></pre>
<p>Let’s compare the data frame here to the resulting data frame in Section
<a href="reading.html#readcsv">2.4.1</a> after using <code>read_csv</code>. Notice anything? They look the same! The
same number of columns/rows and column names! So we needed to use different
tools for the job depending on the file format and our resulting table
(<code>canlang_data</code>) in both cases was the same!</p>
</div>
<div id="read_delim-as-a-more-flexible-method-to-get-tabular-data-into-r" class="section level3" number="2.4.4">
<h3><span class="header-section-number">2.4.4</span> <code>read_delim</code> as a more flexible method to get tabular data into R</h3>
<p><code>read_csv</code> and <code>read_tsv</code> are actually just special cases of the more general
<code>read_delim</code>  function. We can use
<code>read_delim</code> to import both comma and tab-separated files (and more), we just
have to specify the delimiter. The <code>can_lang.tsv</code> is a different version of
this same data set with no column names and uses tabs as the delimiter
 instead of commas.</p>
<p>Here is how the file would look in a plain text editor:</p>
<pre class="code"><code>Aboriginal languages    Aboriginal languages, n.o.s.    590 235 30  665
Non-Official &amp; Non-Aboriginal languages Afrikaans   10260   4785    85  23415
Non-Official &amp; Non-Aboriginal languages Afro-Asiatic languages, n.i.e.  1150    
Non-Official &amp; Non-Aboriginal languages Akan (Twi)  13460   5985    25  22150
Non-Official &amp; Non-Aboriginal languages Albanian    26895   13135   345 31930
Aboriginal languages    Algonquian languages, n.i.e.    45  10  0   120
Aboriginal languages    Algonquin   1260    370 40  2480
Non-Official &amp; Non-Aboriginal languages American Sign Language  2685    3020    
Non-Official &amp; Non-Aboriginal languages Amharic 22465   12785   200 33670
Non-Official &amp; Non-Aboriginal languages Arabic  419890  223535  5585    629055</code></pre>
<p>To get this into R using the <code>read_delim</code> function, we specify the first
argument as the path to the file (as done with <code>read_csv</code>), and then provide
values to the <code>delim</code>  argument (here a
tab, which we represent by <code>"\t"</code>) and the <code>col_names</code> argument (here we
specify that there are no column names to assign, and give it the value of
<code>FALSE</code>). <code>read_csv</code>, <code>read_tsv</code> and <code>read_delim</code> have a <code>col_names</code> argument
 and the default is <code>TRUE</code>.</p>
<blockquote>
<p><strong>Note:</strong> <code>\t</code> is an example of an <em>escaped character</em>,
which always starts with a backslash (<code>\</code>). 
Escaped characters are used to represent non-printing characters
(like the tab) or characters with special meanings (such as quotation marks).</p>
</blockquote>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="reading.html#cb52-1" aria-hidden="true" tabindex="-1"></a>canlang_data <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="st">&quot;data/can_lang.tsv&quot;</span>, </span>
<span id="cb52-2"><a href="reading.html#cb52-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">delim =</span> <span class="st">&quot;</span><span class="sc">\t</span><span class="st">&quot;</span>, </span>
<span id="cb52-3"><a href="reading.html#cb52-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">col_names =</span> <span class="cn">FALSE</span>)</span>
<span id="cb52-4"><a href="reading.html#cb52-4" aria-hidden="true" tabindex="-1"></a>canlang_data</span></code></pre></div>
<pre><code>## # A tibble: 214 × 6
##    X1                                      X2             X3     X4    X5     X6
##    &lt;chr&gt;                                   &lt;chr&gt;       &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
##  1 Aboriginal languages                    Aborigina…    590    235    30    665
##  2 Non-Official &amp; Non-Aboriginal languages Afrikaans   10260   4785    85  23415
##  3 Non-Official &amp; Non-Aboriginal languages Afro-Asia…   1150    445    10   2775
##  4 Non-Official &amp; Non-Aboriginal languages Akan (Twi)  13460   5985    25  22150
##  5 Non-Official &amp; Non-Aboriginal languages Albanian    26895  13135   345  31930
##  6 Aboriginal languages                    Algonquia…     45     10     0    120
##  7 Aboriginal languages                    Algonquin    1260    370    40   2480
##  8 Non-Official &amp; Non-Aboriginal languages American …   2685   3020  1145  21930
##  9 Non-Official &amp; Non-Aboriginal languages Amharic     22465  12785   200  33670
## 10 Non-Official &amp; Non-Aboriginal languages Arabic     419890 223535  5585 629055
## # … with 204 more rows</code></pre>
<p>Data frames in R need to have column names. Thus if you read in data that
don’t have column names, R will assign names automatically. In the example
above, R assigns each column a name of <code>X1, X2, X3, X4, X5, X6</code>.</p>
<p>It is best to rename your columns to help differentiate between them
(e.g., <code>X1, X2</code>, etc., are not very descriptive names and will make it more confusing as
you code). To rename your columns, you can use the <code>rename</code> function
 from <a href="https://dplyr.tidyverse.org/">the <code>dplyr</code> R package</a> <span class="citation">(<a href="#ref-dplyr" role="doc-biblioref">Wickham, François, et al. 2021</a>)</span>
 (one of the packages
loaded with <code>tidyverse</code>, so we don’t need to load it separately). The first
argument is the data set, and in the subsequent arguments you
write <code>new_name = old_name</code> for the selected variables to
rename. We rename the <code>X1, X2, ..., X6</code>
columns in the <code>canlang_data</code> data frame to more descriptive names below.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="reading.html#cb54-1" aria-hidden="true" tabindex="-1"></a>canlang_data <span class="ot">&lt;-</span> <span class="fu">rename</span>(canlang_data,</span>
<span id="cb54-2"><a href="reading.html#cb54-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">category =</span> X1, </span>
<span id="cb54-3"><a href="reading.html#cb54-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">language =</span> X2, </span>
<span id="cb54-4"><a href="reading.html#cb54-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">mother_tongue =</span> X3,</span>
<span id="cb54-5"><a href="reading.html#cb54-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">most_at_home =</span> X4, </span>
<span id="cb54-6"><a href="reading.html#cb54-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">most_at_work =</span> X5, </span>
<span id="cb54-7"><a href="reading.html#cb54-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">lang_known =</span> X6)</span>
<span id="cb54-8"><a href="reading.html#cb54-8" aria-hidden="true" tabindex="-1"></a>canlang_data</span></code></pre></div>
<pre><code>## # A tibble: 214 × 6
##    category       language    mother_tongue most_at_home most_at_work lang_known
##    &lt;chr&gt;          &lt;chr&gt;               &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt;
##  1 Aboriginal la… Aboriginal…           590          235           30        665
##  2 Non-Official … Afrikaans           10260         4785           85      23415
##  3 Non-Official … Afro-Asiat…          1150          445           10       2775
##  4 Non-Official … Akan (Twi)          13460         5985           25      22150
##  5 Non-Official … Albanian            26895        13135          345      31930
##  6 Aboriginal la… Algonquian…            45           10            0        120
##  7 Aboriginal la… Algonquin            1260          370           40       2480
##  8 Non-Official … American S…          2685         3020         1145      21930
##  9 Non-Official … Amharic             22465        12785          200      33670
## 10 Non-Official … Arabic             419890       223535         5585     629055
## # … with 204 more rows</code></pre>
</div>
<div id="reading-tabular-data-directly-from-a-url" class="section level3" number="2.4.5">
<h3><span class="header-section-number">2.4.5</span> Reading tabular data directly from a URL</h3>
<p>We can also use <code>read_csv</code>, <code>read_tsv</code> or <code>read_delim</code> (and related functions)
to read in data directly from a <strong>U</strong>niform <strong>R</strong>esource <strong>L</strong>ocator (URL) that
contains tabular data.  Here, we provide the URL to
<code>read_*</code> as the path to the file instead of a path to a local file on our
computer. We need to surround the URL with quotes similar to when we specify a
path on our local computer. All other arguments that we use are the same as
when using these functions with a local file on our computer.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="reading.html#cb56-1" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">&quot;https://raw.githubusercontent.com/UBC-DSCI/data/main/can_lang.csv&quot;</span></span>
<span id="cb56-2"><a href="reading.html#cb56-2" aria-hidden="true" tabindex="-1"></a>canlang_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(url)</span>
<span id="cb56-3"><a href="reading.html#cb56-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-4"><a href="reading.html#cb56-4" aria-hidden="true" tabindex="-1"></a>canlang_data</span></code></pre></div>
<pre><code>## # A tibble: 214 × 6
##    category       language    mother_tongue most_at_home most_at_work lang_known
##    &lt;chr&gt;          &lt;chr&gt;               &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt;
##  1 Aboriginal la… Aboriginal…           590          235           30        665
##  2 Non-Official … Afrikaans           10260         4785           85      23415
##  3 Non-Official … Afro-Asiat…          1150          445           10       2775
##  4 Non-Official … Akan (Twi)          13460         5985           25      22150
##  5 Non-Official … Albanian            26895        13135          345      31930
##  6 Aboriginal la… Algonquian…            45           10            0        120
##  7 Aboriginal la… Algonquin            1260          370           40       2480
##  8 Non-Official … American S…          2685         3020         1145      21930
##  9 Non-Official … Amharic             22465        12785          200      33670
## 10 Non-Official … Arabic             419890       223535         5585     629055
## # … with 204 more rows</code></pre>
</div>
<div id="previewing-a-data-file-before-reading-it-into-r" class="section level3" number="2.4.6">
<h3><span class="header-section-number">2.4.6</span> Previewing a data file before reading it into R</h3>
<p>In all the examples above, we gave you previews of the data file before we read
it into R. Previewing data is essential to see whether or not there are column
names, what the delimiters are, and if there are lines you need to skip. You
should do this yourself when trying to read in data files. You can preview
files in a plain text editor by right-clicking on the file, selecting “Open
With,” and choosing a plain text editor (e.g., Notepad).</p>
</div>
</div>
<div id="reading-tabular-data-from-a-microsoft-excel-file" class="section level2" number="2.5">
<h2><span class="header-section-number">2.5</span> Reading tabular data from a Microsoft Excel file</h2>
<p>There are many other ways to store tabular data sets beyond plain text files,
and similarly, many ways to load those data sets into R. For example, it is
very common to encounter, and need to load into R, data stored as a Microsoft
Excel  spreadsheet (with the file name
extension <code>.xlsx</code>). To be able to do this, a key thing to know is that even
though <code>.csv</code> and <code>.xlsx</code> files look almost identical when loaded into Excel,
the data themselves are stored completely differently. While <code>.csv</code> files are
plain text files, where the characters you see when you open the file in a text
editor are exactly the data they represent, this is not the case for <code>.xlsx</code>
files. Take a look at a snippet of what a <code>.xlsx</code> file would look like in a text editor:</p>
<pre><code>,?&#39;O
    _rels/.rels???J1??&gt;E?{7?
&lt;?V????w8?&#39;J???&#39;QrJ???Tf?d??d?o?wZ&#39;???@&gt;?4&#39;?|??hlIo??F
t                                                       8f??3wn
????t??u&quot;/
          %~Ed2??&lt;?w??
                       ?Pd(??J-?E???7?&#39;t(?-GZ?????y???c~N?g[^_r?4
                                                                  yG?O
                                                                      ?K??G?
                                                                      
                                                                                                                    
     ]TUEe??O??c[???????6q??s??d?m???\???H?^????3} ?rZY? ?:L60?^?????XTP+?|?
X?a??4VT?,D?Jq</code></pre>
<p>This type of file representation allows Excel files to store additional things
that you cannot store in a <code>.csv</code> file, such as fonts, text formatting,
graphics, multiple sheets and more. And despite looking odd in a plain text
editor, we can read Excel spreadsheets into R using the <code>readxl</code> package
developed specifically for this
purpose. </p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="reading.html#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb59-2"><a href="reading.html#cb59-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-3"><a href="reading.html#cb59-3" aria-hidden="true" tabindex="-1"></a>canlang_data <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">&quot;data/can_lang.xlsx&quot;</span>)</span>
<span id="cb59-4"><a href="reading.html#cb59-4" aria-hidden="true" tabindex="-1"></a>canlang_data</span></code></pre></div>
<pre><code>## # A tibble: 214 × 6
##    category       language    mother_tongue most_at_home most_at_work lang_known
##    &lt;chr&gt;          &lt;chr&gt;               &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt;
##  1 Aboriginal la… Aboriginal…           590          235           30        665
##  2 Non-Official … Afrikaans           10260         4785           85      23415
##  3 Non-Official … Afro-Asiat…          1150          445           10       2775
##  4 Non-Official … Akan (Twi)          13460         5985           25      22150
##  5 Non-Official … Albanian            26895        13135          345      31930
##  6 Aboriginal la… Algonquian…            45           10            0        120
##  7 Aboriginal la… Algonquin            1260          370           40       2480
##  8 Non-Official … American S…          2685         3020         1145      21930
##  9 Non-Official … Amharic             22465        12785          200      33670
## 10 Non-Official … Arabic             419890       223535         5585     629055
## # … with 204 more rows</code></pre>
<p>If the <code>.xlsx</code> file has multiple sheets, you have to use the <code>sheet</code> argument
to specify the sheet number or name. You can also specify cell ranges using the
<code>range</code> argument. This functionality is useful when a single sheet contains
multiple tables (a sad thing that happens to many Excel spreadsheets since this
makes reading in data more difficult).</p>
<p>As with plain text files, you should always explore the data file before
importing it into R. Exploring the data beforehand helps you decide which
arguments you need to load the data into R successfully. If you do not have
the Excel program on your computer, you can use other programs to preview the
file. Examples include Google Sheets and Libre Office.</p>
<p>In Table <a href="reading.html#tab:read-table">2.1</a> we summarize the <code>read_*</code> functions we covered
in this chapter. We also include the <code>read_csv2</code> function for data separated by
semicolons <code>;</code>, which you may run into with data sets where the decimal is
represented by a comma instead of a period (as with some data sets from
European countries).</p>
<table>
<caption><span id="tab:read-table">Table 2.1: </span> Summary of <code>read_*</code> functions</caption>
<thead>
<tr class="header">
<th>Data File Type</th>
<th>R Function</th>
<th>R Package</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Comma (<code>,</code>) separated files</td>
<td><code>read_csv</code></td>
<td><code>readr</code></td>
</tr>
<tr class="even">
<td>Tab (<code>\t</code>) separated files</td>
<td><code>read_tsv</code></td>
<td><code>readr</code></td>
</tr>
<tr class="odd">
<td>Semicolon (<code>;</code>) separated files</td>
<td><code>read_csv2</code></td>
<td><code>readr</code></td>
</tr>
<tr class="even">
<td>Various formats (<code>.csv</code>, <code>.tsv</code>)</td>
<td><code>read_delim</code></td>
<td><code>readr</code></td>
</tr>
<tr class="odd">
<td>Excel files (<code>.xlsx</code>)</td>
<td><code>read_excel</code></td>
<td><code>readxl</code></td>
</tr>
</tbody>
</table>
<blockquote>
<p><strong>Note:</strong> <code>readr</code> is a part of the <code>tidyverse</code> package so we did not need to load
this package separately since we loaded <code>tidyverse</code>.</p>
</blockquote>
</div>
<div id="reading-data-from-a-database" class="section level2" number="2.6">
<h2><span class="header-section-number">2.6</span> Reading data from a database</h2>
<p>Another very common form of data storage is the relational database. Databases
 are great when you have large data sets or multiple users
working on a project. There are many relational database management systems,
such as SQLite, MySQL, PostgreSQL, Oracle,
and many more. These
different relational database management systems each have their own advantages
and limitations. Almost all employ SQL (<em>structured query language</em>) to obtain
data from the database. But you don’t need to know SQL to analyze data from
a database; several packages have been written that allow you to connect to
relational databases and use the R programming language
to obtain data. In this book, we will give examples of how to do this
using R with SQLite and PostgreSQL databases.</p>
<div id="reading-data-from-a-sqlite-database" class="section level3" number="2.6.1">
<h3><span class="header-section-number">2.6.1</span> Reading data from a SQLite database</h3>
<p>SQLite  is probably the simplest relational database system
that one can use in combination with R. SQLite databases are self-contained and
usually stored and accessed locally on one computer. Data is usually stored in
a file with a <code>.db</code> extension. Similar to Excel files, these are not plain text
files and cannot be read in a plain text editor.</p>
<p>The first thing you need to do to read data into R from a database is to
connect to the database. We do that using the <code>dbConnect</code> function from the
<code>DBI</code> (database interface) package.  This does not read
in the data, but simply tells R where the database is and opens up a
communication channel that R can use to send SQL commands to the database.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="reading.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DBI)</span>
<span id="cb61-2"><a href="reading.html#cb61-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-3"><a href="reading.html#cb61-3" aria-hidden="true" tabindex="-1"></a>conn_lang_data <span class="ot">&lt;-</span> <span class="fu">dbConnect</span>(RSQLite<span class="sc">::</span><span class="fu">SQLite</span>(), <span class="st">&quot;data/can_lang.db&quot;</span>)</span></code></pre></div>
<p>Often relational databases have many tables; thus, in order to retrieve
data from a database, you need to know the name of the table
in which the data is stored. You can get the names of
all the tables in the database using the <code>dbListTables</code> 
function:</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="reading.html#cb62-1" aria-hidden="true" tabindex="-1"></a>tables <span class="ot">&lt;-</span> <span class="fu">dbListTables</span>(conn_lang_data)</span>
<span id="cb62-2"><a href="reading.html#cb62-2" aria-hidden="true" tabindex="-1"></a>tables</span></code></pre></div>
<pre><code>## [1] &quot;lang&quot;</code></pre>
<p>The <code>dbListTables</code> function returned only one name, which tells us
that there is only one table in this database. To reference a table in the
database (so that we can perform operations like selecting columns and filtering rows), we
use the <code>tbl</code> function  from the <code>dbplyr</code> package. The object returned
by the <code>tbl</code> function  allows us to work with data
stored in databases as if they were just regular data frames; but secretly, behind
the scenes, <code>dbplyr</code> is turning your function calls (e.g., <code>select</code> and <code>filter</code>)
into SQL queries!</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="reading.html#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dbplyr)</span>
<span id="cb64-2"><a href="reading.html#cb64-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-3"><a href="reading.html#cb64-3" aria-hidden="true" tabindex="-1"></a>lang_db <span class="ot">&lt;-</span> <span class="fu">tbl</span>(conn_lang_data, <span class="st">&quot;lang&quot;</span>)</span>
<span id="cb64-4"><a href="reading.html#cb64-4" aria-hidden="true" tabindex="-1"></a>lang_db </span></code></pre></div>
<pre><code>## # Source:   table&lt;lang&gt; [?? x 6]
## # Database: sqlite 3.36.0
## #   [/home/rstudio/introduction-to-datascience/data/can_lang.db]
##    category       language    mother_tongue most_at_home most_at_work lang_known
##    &lt;chr&gt;          &lt;chr&gt;               &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt;
##  1 Aboriginal la… Aboriginal…           590          235           30        665
##  2 Non-Official … Afrikaans           10260         4785           85      23415
##  3 Non-Official … Afro-Asiat…          1150          445           10       2775
##  4 Non-Official … Akan (Twi)          13460         5985           25      22150
##  5 Non-Official … Albanian            26895        13135          345      31930
##  6 Aboriginal la… Algonquian…            45           10            0        120
##  7 Aboriginal la… Algonquin            1260          370           40       2480
##  8 Non-Official … American S…          2685         3020         1145      21930
##  9 Non-Official … Amharic             22465        12785          200      33670
## 10 Non-Official … Arabic             419890       223535         5585     629055
## # … with more rows</code></pre>
<p>Although it looks like we just got a data frame from the database, we didn’t!
It’s a <em>reference</em>; the data is still stored only in the SQLite database. The
<code>dbplyr</code> package works this way because databases are often more efficient at selecting, filtering
and joining large data sets than R. And typically the database will not even
be stored on your computer, but rather a more powerful machine somewhere on the
web. So R is lazy and waits to bring this data into memory until you explicitly
tell it to using the <code>collect</code>  function.
Figure <a href="reading.html#fig:01-ref-vs-tibble">2.2</a> highlights the difference
between a <code>tibble</code> object in R and the output we just created. Notice in the table
on the right, the first two lines of the output indicate the source is SQL. The
last line doesn’t show how many rows there are (R is trying to avoid performing
expensive query operations), whereas the output for the <code>tibble</code> object does.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:01-ref-vs-tibble"></span>
<img src="_main_files/figure-html/01-ref-vs-tibble-1.png" alt="Comparison of a reference to data in a database and a tibble in R." width="80%" />
<p class="caption">
Figure 2.2: Comparison of a reference to data in a database and a tibble in R.
</p>
</div>
<p>We can look at the SQL commands that are sent to the database when we write
<code>tbl(conn_lang_data, "lang")</code> in R with the <code>show_query</code> function from the
<code>dbplyr</code> package. </p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="reading.html#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">show_query</span>(<span class="fu">tbl</span>(conn_lang_data, <span class="st">&quot;lang&quot;</span>))</span></code></pre></div>
<pre><code>## &lt;SQL&gt;
## SELECT *
## FROM `lang`</code></pre>
<p>The output above shows the SQL code that is sent to the database. When we
write <code>tbl(conn_lang_data, "lang")</code> in R, in the background, the function is
translating the R code into SQL, sending that SQL to the database, and then translating the
response for us. So <code>dbplyr</code> does all the hard work of translating from R to SQL and back for us;
we can just stick with R!</p>
<p>With our <code>lang_db</code> table reference for the 2016 Canadian Census data in hand, we
can mostly continue onward as if it were a regular data frame. For example,
we can use the <code>filter</code> function
to obtain only certain rows. Below we filter the data to include only Aboriginal languages.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="reading.html#cb68-1" aria-hidden="true" tabindex="-1"></a>aboriginal_lang_db <span class="ot">&lt;-</span> <span class="fu">filter</span>(lang_db, category <span class="sc">==</span> <span class="st">&quot;Aboriginal languages&quot;</span>)</span>
<span id="cb68-2"><a href="reading.html#cb68-2" aria-hidden="true" tabindex="-1"></a>aboriginal_lang_db </span></code></pre></div>
<pre><code>## # Source:   lazy query [?? x 6]
## # Database: sqlite 3.36.0
## #   [/home/rstudio/introduction-to-datascience/data/can_lang.db]
##    category     language      mother_tongue most_at_home most_at_work lang_known
##    &lt;chr&gt;        &lt;chr&gt;                 &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt;
##  1 Aboriginal … Aboriginal l…           590          235           30        665
##  2 Aboriginal … Algonquian l…            45           10            0        120
##  3 Aboriginal … Algonquin              1260          370           40       2480
##  4 Aboriginal … Athabaskan l…            50           10            0         85
##  5 Aboriginal … Atikamekw              6150         5465         1100       6645
##  6 Aboriginal … Babine (Wets…           110           20           10        210
##  7 Aboriginal … Beaver                  190           50            0        340
##  8 Aboriginal … Blackfoot              2815         1110           85       5645
##  9 Aboriginal … Carrier                1025          250           15       2100
## 10 Aboriginal … Cayuga                   45           10           10        125
## # … with more rows</code></pre>
<p>Above you can again see the hints that this data is not actually stored in R yet:
the source is a <code>lazy query [?? x 6]</code> and the output says <code>... with more rows</code> at the end
(both indicating that R does not know how many rows there are in total!),
and a database type <code>sqlite 3.36.0</code> is listed.
In order to actually retrieve this data in R as a data frame,
we use the <code>collect</code> function. 
Below you will see that after running <code>collect</code>, R knows that the retrieved
data has 67 rows, and there is no database listed any more.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="reading.html#cb70-1" aria-hidden="true" tabindex="-1"></a>aboriginal_lang_data <span class="ot">&lt;-</span> <span class="fu">collect</span>(aboriginal_lang_db)</span>
<span id="cb70-2"><a href="reading.html#cb70-2" aria-hidden="true" tabindex="-1"></a>aboriginal_lang_data</span></code></pre></div>
<pre><code>## # A tibble: 67 × 6
##    category     language      mother_tongue most_at_home most_at_work lang_known
##    &lt;chr&gt;        &lt;chr&gt;                 &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt;
##  1 Aboriginal … Aboriginal l…           590          235           30        665
##  2 Aboriginal … Algonquian l…            45           10            0        120
##  3 Aboriginal … Algonquin              1260          370           40       2480
##  4 Aboriginal … Athabaskan l…            50           10            0         85
##  5 Aboriginal … Atikamekw              6150         5465         1100       6645
##  6 Aboriginal … Babine (Wets…           110           20           10        210
##  7 Aboriginal … Beaver                  190           50            0        340
##  8 Aboriginal … Blackfoot              2815         1110           85       5645
##  9 Aboriginal … Carrier                1025          250           15       2100
## 10 Aboriginal … Cayuga                   45           10           10        125
## # … with 57 more rows</code></pre>
<p>Aside from knowing the number of rows, the data looks pretty similar in both
outputs shown above. And <code>dbplyr</code> provides many more functions (not just <code>filter</code>)
that you can use to directly feed the database reference (<code>lang_db</code>) into
downstream analysis functions (e.g., <code>ggplot2</code> for data visualization).
But <code>dbplyr</code> does not provide <em>every</em> function that we need for analysis;
we do eventually need to call <code>collect</code>.
For example, look what happens when we try to use <code>nrow</code> to count rows
in a data frame: </p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="reading.html#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(aboriginal_lang_db)</span></code></pre></div>
<pre><code>## [1] NA</code></pre>
<p>or <code>tail</code> to preview the last six rows of a data frame:
</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="reading.html#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(aboriginal_lang_db)</span></code></pre></div>
<pre><code>## Error: tail() is not supported by sql sources</code></pre>
<div style="page-break-after: always;"></div>
<p>Additionally, some operations will not work to extract columns or single values
from the reference given by the <code>tbl</code> function. Thus, once you have finished
your data wrangling of the <code>tbl</code> database reference object, it is advisable to
bring it into R as a data frame using <code>collect</code>.
But be very careful using <code>collect</code>: databases are often <em>very</em> big,
and reading an entire table into R might take a long time to run or even possibly
crash your machine. So make sure you use <code>filter</code> and <code>select</code> on the database table
to reduce the data to a reasonable size before using <code>collect</code> to read it into R!</p>
</div>
<div id="reading-data-from-a-postgresql-database" class="section level3" number="2.6.2">
<h3><span class="header-section-number">2.6.2</span> Reading data from a PostgreSQL database</h3>
<p>PostgreSQL (also called Postgres)  is a very popular
and open-source option for relational database software.
Unlike SQLite,
PostgreSQL uses a client–server database engine, as it was designed to be used
and accessed on a network. This means that you have to provide more information
to R when connecting to Postgres databases. The additional information that you
need to include when you call the <code>dbConnect</code> function is listed below:</p>
<ul>
<li><code>dbname</code>: the name of the database (a single PostgreSQL instance can host more than one database)</li>
<li><code>host</code>: the URL pointing to where the database is located</li>
<li><code>port</code>: the communication endpoint between R and the PostgreSQL database (usually <code>5432</code>)</li>
<li><code>user</code>: the username for accessing the database</li>
<li><code>password</code>: the password for accessing the database</li>
</ul>
<p>Additionally, we must use the <code>RPostgres</code> package instead of <code>RSQLite</code> in the
<code>dbConnect</code> function call. Below we demonstrate how to connect to a version of
the <code>can_mov_db</code> database, which contains information about Canadian movies.
Note that the <code>host</code> (<code>fakeserver.stat.ubc.ca</code>), <code>user</code> (<code>user0001</code>), and
<code>password</code> (<code>abc123</code>) below are <em>not real</em>; you will not actually
be able to connect to a database using this information.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="reading.html#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RPostgres)</span>
<span id="cb76-2"><a href="reading.html#cb76-2" aria-hidden="true" tabindex="-1"></a>conn_mov_data <span class="ot">&lt;-</span> <span class="fu">dbConnect</span>(RPostgres<span class="sc">::</span><span class="fu">Postgres</span>(), <span class="at">dbname =</span> <span class="st">&quot;can_mov_db&quot;</span>,</span>
<span id="cb76-3"><a href="reading.html#cb76-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">host =</span> <span class="st">&quot;fakeserver.stat.ubc.ca&quot;</span>, <span class="at">port =</span> <span class="dv">5432</span>,</span>
<span id="cb76-4"><a href="reading.html#cb76-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">user =</span> <span class="st">&quot;user0001&quot;</span>, <span class="at">password =</span> <span class="st">&quot;abc123&quot;</span>)</span></code></pre></div>
<p>After opening the connection, everything looks and behaves almost identically
to when we were using an SQLite database in R. For example, we can again use
<code>dbListTables</code> to find out what tables are in the <code>can_mov_db</code> database:</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="reading.html#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbListTables</span>(conn_mov_data)</span></code></pre></div>
<pre><code> [1] &quot;themes&quot;            &quot;medium&quot;           &quot;titles&quot;     &quot;title_aliases&quot;       &quot;forms&quot;            
 [6] &quot;episodes&quot;          &quot;names&quot;      &quot;names_occupations&quot; &quot;occupation&quot;       &quot;ratings&quot; </code></pre>
<p>We see that there are 10 tables in this database. Let’s first look at the
<code>"ratings"</code> table to find the lowest rating that exists in the <code>can_mov_db</code>
database:</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="reading.html#cb79-1" aria-hidden="true" tabindex="-1"></a>ratings_db <span class="ot">&lt;-</span> <span class="fu">tbl</span>(conn_mov_data, <span class="st">&quot;ratings&quot;</span>)</span>
<span id="cb79-2"><a href="reading.html#cb79-2" aria-hidden="true" tabindex="-1"></a>ratings_db</span></code></pre></div>
<pre><code># Source:   table&lt;ratings&gt; [?? x 3]
# Database: postgres [user0001@fakeserver.stat.ubc.ca:5432/can_mov_db]
   title              average_rating num_votes
   &lt;chr&gt;                    &lt;dbl&gt;     &lt;int&gt;
 1 The Grand Seduction       6.6       150
 2 Rhymes for Young Ghouls   6.3      1685
 3 Mommy                     7.5      1060
 4 Incendies                 6.1      1101
 5 Bon Cop, Bad Cop          7.0       894
 6 Goon                      5.5      1111
 7 Monsieur Lazhar           5.6       610
 8 What if                   5.3      1401
 9 The Barbarian Invations   5.8        99
10 Away from Her             6.9      2311
# … with more rows</code></pre>
<p>To find the lowest rating that exists in the data base, we first need to
extract the <code>average_rating</code> column using <code>select</code>:
</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="reading.html#cb81-1" aria-hidden="true" tabindex="-1"></a>avg_rating_db <span class="ot">&lt;-</span> <span class="fu">select</span>(ratings_db, average_rating)</span>
<span id="cb81-2"><a href="reading.html#cb81-2" aria-hidden="true" tabindex="-1"></a>avg_rating_db</span></code></pre></div>
<pre><code># Source:   lazy query [?? x 1]
# Database: postgres [user0001@fakeserver.stat.ubc.ca:5432/can_mov_db]
   average_rating
            &lt;dbl&gt;
 1            6.6
 2            6.3
 3            7.5
 4            6.1
 5            7.0
 6            5.5
 7            5.6
 8            5.3
 9            5.8
10            6.9
# … with more rows</code></pre>
<p>Next we use <code>min</code> to find the minimum rating in that column:
</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="reading.html#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(avg_rating_db)</span></code></pre></div>
<pre><code>Error in min(avg_rating_db) : invalid &#39;type&#39; (list) of argument</code></pre>
<p>Instead of the minimum, we get an error! This is another example of when we
need to use the <code>collect</code> function to bring the data into R for further
computation:</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="reading.html#cb85-1" aria-hidden="true" tabindex="-1"></a>avg_rating_data <span class="ot">&lt;-</span> <span class="fu">collect</span>(avg_rating_db)</span>
<span id="cb85-2"><a href="reading.html#cb85-2" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(avg_rating_data)</span></code></pre></div>
<pre><code>[1] 1</code></pre>
<p>We see the lowest rating given to a movie is 1, indicating that it must have
been a really bad movie…</p>
</div>
<div id="why-should-we-bother-with-databases-at-all" class="section level3" number="2.6.3">
<h3><span class="header-section-number">2.6.3</span> Why should we bother with databases at all?</h3>
<p>Opening a database  stored in a <code>.db</code> file
involved a lot more effort than just opening a <code>.csv</code>, <code>.tsv</code>, or any of the
other plain text or Excel formats. It was a bit of a pain to use a database in
that setting since we had to use <code>dbplyr</code> to translate <code>tidyverse</code>-like
commands (<code>filter</code>, <code>select</code>, <code>head</code>, etc.) into SQL commands that the database
understands. Not all <code>tidyverse</code> commands can currently be translated with
SQLite databases. For example, we can compute a mean with an SQLite database
but can’t easily compute a median. So you might be wondering: why should we use
databases at all?</p>
<p>Databases are beneficial in a large-scale setting:</p>
<ul>
<li>They enable storing large data sets across multiple computers with backups.</li>
<li>They provide mechanisms for ensuring data integrity and validating input.</li>
<li>They provide security and data access control.</li>
<li>They allow multiple users to access data simultaneously
and remotely without conflicts and errors.
For example, there are billions of Google searches conducted daily in 2021 <span class="citation">(<a href="#ref-googlesearches" role="doc-biblioref">Real Time Statistics Project 2021</a>)</span>.
Can you imagine if Google stored all of the data
from those searches in a single <code>.csv</code> file!? Chaos would ensue!</li>
</ul>
</div>
</div>
<div id="writing-data-from-r-to-a-.csv-file" class="section level2" number="2.7">
<h2><span class="header-section-number">2.7</span> Writing data from R to a <code>.csv</code> file</h2>
<p>At the middle and end of a data analysis, we often want to write a data frame
that has changed (either through filtering, selecting, mutating or summarizing)
to a file to share it with others or use it for another step in the analysis.
The most straightforward way to do this is to use the <code>write_csv</code> function
 from the <code>tidyverse</code> package. The default
arguments for this file are to use a comma (<code>,</code>) as the delimiter and include
column names. Below we demonstrate creating a new version of the Canadian
languages data set without the official languages category according to the
Canadian 2016 Census, and then writing this to a <code>.csv</code> file:</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="reading.html#cb87-1" aria-hidden="true" tabindex="-1"></a>no_official_lang_data <span class="ot">&lt;-</span> <span class="fu">filter</span>(can_lang, category <span class="sc">!=</span> <span class="st">&quot;Official languages&quot;</span>)</span>
<span id="cb87-2"><a href="reading.html#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(no_official_lang_data, <span class="st">&quot;data/no_official_languages.csv&quot;</span>)</span></code></pre></div>
</div>
<div id="obtaining-data-from-the-web" class="section level2" number="2.8">
<h2><span class="header-section-number">2.8</span> Obtaining data from the web</h2>
<blockquote>
<p><strong>Note:</strong> This section is not required reading for the remainder of the textbook. It
is included for those readers interested in learning a little bit more about
how to obtain different types of data from the web.</p>
</blockquote>
<p>Data doesn’t just magically appear on your computer; you need to get it from
somewhere. Earlier in the chapter we showed you how to access data stored in a
plain text, spreadsheet-like format (e.g., comma- or tab-separated) from a web
URL using one of the <code>read_*</code> functions from the <code>tidyverse</code>. But as time goes
on, it is increasingly uncommon to find data (especially large amounts of data)
in this format available for download from a URL. Instead, websites now often
offer something known as an <strong>a</strong>pplication <strong>p</strong>rogramming <strong>i</strong>nterface
(API),  which
provides a programmatic way to ask for subsets of a data set. This allows the
website owner to control <em>who</em> has access to the data, <em>what portion</em> of the
data they have access to, and <em>how much</em> data they can access. Typically, the
website owner will give you a <em>token</em> (a secret string of characters somewhat
like a password) that you have to provide when accessing the API.</p>
<p>Another interesting thought: websites themselves <em>are</em> data! When you type a
URL into your browser window, your browser asks the <em>web server</em> (another
computer on the internet whose job it is to respond to requests for the
website) to give it the website’s data, and then your browser translates that
data into something you can see. If the website shows you some information that
you’re interested in, you could <em>create</em> a data set for yourself by copying and
pasting that information into a file. This process of taking information
directly from what a website displays is called 
<em>web scraping</em> (or sometimes <em>screen scraping</em>). Now, of course, copying and pasting
information manually is a painstaking and error-prone process, especially when
there is a lot of information to gather. So instead of asking your browser to
translate the information that the web server provides into something you can
see, you can collect that data programmatically—in the form of
<strong>h</strong>yper<strong>t</strong>ext <strong>m</strong>arkup <strong>l</strong>anguage
(HTML) 
and <strong>c</strong>ascading <strong>s</strong>tyle <strong>s</strong>heet (CSS) code—and process it
to extract useful information. HTML provides the
basic structure of a site and tells the webpage how to display the content
(e.g., titles, paragraphs, bullet lists etc.), whereas CSS helps style the
content and tells the webpage how the HTML elements should
be presented (e.g., colors, layouts, fonts etc.).</p>
<p>This subsection will show you the basics of both web scraping
with the <a href="https://rvest.tidyverse.org/"><code>rvest</code> R package</a> <span class="citation">(<a href="#ref-rvest" role="doc-biblioref">Wickham 2021a</a>)</span>
and accessing the Twitter API
using the <a href="https://github.com/ropensci/rtweet"><code>rtweet</code> R package</a> <span class="citation">(<a href="#ref-rtweet" role="doc-biblioref">Kearney 2019</a>)</span>.</p>
<div id="web-scraping" class="section level3" number="2.8.1">
<h3><span class="header-section-number">2.8.1</span> Web scraping</h3>
<div id="html-and-css-selectors" class="section level4 unnumbered">
<h4>HTML and CSS selectors</h4>
<p>When you enter a URL into your browser, your browser connects to the
web server at that URL and asks for the <em>source code</em> for the website.
This is the data that the browser translates

into something you can see; so if we
are going to create our own data by scraping a website, we have to first understand
what that data looks like! For example, let’s say we are interested
in knowing the average rental price (per square foot) of the most recently
available one-bedroom apartments in Vancouver
on <a href="https://vancouver.craigslist.org">Craiglist</a>. When we visit the Vancouver Craigslist
website  and search for one-bedroom apartments,
we should see something similar to Figure <a href="reading.html#fig:craigslist-human">2.3</a>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:craigslist-human"></span>
<img src="img/craigslist_human.png" alt="Craigslist webpage of advertisements for one-bedroom apartments." width="100%" />
<p class="caption">
Figure 2.3: Craigslist webpage of advertisements for one-bedroom apartments.
</p>
</div>
<p>Based on what our browser shows us, it’s pretty easy to find the size and price
for each apartment listed. But we would like to be able to obtain that information
using R, without any manual human effort or copying and pasting. We do this by
examining the <em>source code</em> that the web server actually sent our browser to
display for us. We show a snippet of it below; the
entire source
is <a href="https://github.com/UBC-DSCI/introduction-to-datascience/blob/master/img/website_source.txt">included with the code for this book</a>:</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode html"><code class="sourceCode html"><span id="cb88-1"><a href="reading.html#cb88-1" aria-hidden="true" tabindex="-1"></a>        <span class="kw">&lt;span</span> <span class="er">class</span><span class="ot">=</span><span class="st">&quot;result-meta&quot;</span><span class="kw">&gt;</span></span>
<span id="cb88-2"><a href="reading.html#cb88-2" aria-hidden="true" tabindex="-1"></a>                <span class="kw">&lt;span</span> <span class="er">class</span><span class="ot">=</span><span class="st">&quot;result-price&quot;</span><span class="kw">&gt;</span>$800<span class="kw">&lt;/span&gt;</span></span>
<span id="cb88-3"><a href="reading.html#cb88-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-4"><a href="reading.html#cb88-4" aria-hidden="true" tabindex="-1"></a>                <span class="kw">&lt;span</span> <span class="er">class</span><span class="ot">=</span><span class="st">&quot;housing&quot;</span><span class="kw">&gt;</span></span>
<span id="cb88-5"><a href="reading.html#cb88-5" aria-hidden="true" tabindex="-1"></a>                    1br -</span>
<span id="cb88-6"><a href="reading.html#cb88-6" aria-hidden="true" tabindex="-1"></a>                <span class="kw">&lt;/span&gt;</span></span>
<span id="cb88-7"><a href="reading.html#cb88-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-8"><a href="reading.html#cb88-8" aria-hidden="true" tabindex="-1"></a>                <span class="kw">&lt;span</span> <span class="er">class</span><span class="ot">=</span><span class="st">&quot;result-hood&quot;</span><span class="kw">&gt;</span> (13768 108th Avenue)<span class="kw">&lt;/span&gt;</span></span>
<span id="cb88-9"><a href="reading.html#cb88-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-10"><a href="reading.html#cb88-10" aria-hidden="true" tabindex="-1"></a>                <span class="kw">&lt;span</span> <span class="er">class</span><span class="ot">=</span><span class="st">&quot;result-tags&quot;</span><span class="kw">&gt;</span></span>
<span id="cb88-11"><a href="reading.html#cb88-11" aria-hidden="true" tabindex="-1"></a>                    <span class="kw">&lt;span</span> <span class="er">class</span><span class="ot">=</span><span class="st">&quot;maptag&quot;</span> <span class="er">data-pid</span><span class="ot">=</span><span class="st">&quot;6786042973&quot;</span><span class="kw">&gt;</span>map<span class="kw">&lt;/span&gt;</span></span>
<span id="cb88-12"><a href="reading.html#cb88-12" aria-hidden="true" tabindex="-1"></a>                <span class="kw">&lt;/span&gt;</span></span>
<span id="cb88-13"><a href="reading.html#cb88-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-14"><a href="reading.html#cb88-14" aria-hidden="true" tabindex="-1"></a>                <span class="kw">&lt;span</span> <span class="er">class</span><span class="ot">=</span><span class="st">&quot;banish icon icon-trash&quot;</span> <span class="er">role</span><span class="ot">=</span><span class="st">&quot;button&quot;</span><span class="kw">&gt;</span></span>
<span id="cb88-15"><a href="reading.html#cb88-15" aria-hidden="true" tabindex="-1"></a>                    <span class="kw">&lt;span</span> <span class="er">class</span><span class="ot">=</span><span class="st">&quot;screen-reader-text&quot;</span><span class="kw">&gt;</span>hide this posting<span class="kw">&lt;/span&gt;</span></span>
<span id="cb88-16"><a href="reading.html#cb88-16" aria-hidden="true" tabindex="-1"></a>                <span class="kw">&lt;/span&gt;</span></span>
<span id="cb88-17"><a href="reading.html#cb88-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-18"><a href="reading.html#cb88-18" aria-hidden="true" tabindex="-1"></a>            <span class="kw">&lt;span</span> <span class="er">class</span><span class="ot">=</span><span class="st">&quot;unbanish icon icon-trash red&quot;</span> <span class="er">role</span><span class="ot">=</span><span class="st">&quot;button&quot;</span> <span class="er">aria-hidden</span></span>
<span id="cb88-19"><a href="reading.html#cb88-19" aria-hidden="true" tabindex="-1"></a>            <span class="er">&lt;a</span> <span class="er">href</span><span class="ot">=</span><span class="st">&quot;#&quot;</span> <span class="er">class</span><span class="ot">=</span><span class="st">&quot;restore-link&quot;</span><span class="kw">&gt;</span></span>
<span id="cb88-20"><a href="reading.html#cb88-20" aria-hidden="true" tabindex="-1"></a>                <span class="kw">&lt;span</span> <span class="er">class</span><span class="ot">=</span><span class="st">&quot;restore-narrow-text&quot;</span><span class="kw">&gt;</span>restore<span class="kw">&lt;/span&gt;</span></span>
<span id="cb88-21"><a href="reading.html#cb88-21" aria-hidden="true" tabindex="-1"></a>                <span class="kw">&lt;span</span> <span class="er">class</span><span class="ot">=</span><span class="st">&quot;restore-wide-text&quot;</span><span class="kw">&gt;</span>restore this posting<span class="kw">&lt;/span&gt;</span></span>
<span id="cb88-22"><a href="reading.html#cb88-22" aria-hidden="true" tabindex="-1"></a>            <span class="kw">&lt;/a&gt;</span></span>
<span id="cb88-23"><a href="reading.html#cb88-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-24"><a href="reading.html#cb88-24" aria-hidden="true" tabindex="-1"></a>        <span class="kw">&lt;/span&gt;</span></span>
<span id="cb88-25"><a href="reading.html#cb88-25" aria-hidden="true" tabindex="-1"></a>    <span class="kw">&lt;/p&gt;</span></span>
<span id="cb88-26"><a href="reading.html#cb88-26" aria-hidden="true" tabindex="-1"></a><span class="kw">&lt;/li&gt;</span></span>
<span id="cb88-27"><a href="reading.html#cb88-27" aria-hidden="true" tabindex="-1"></a>         <span class="kw">&lt;li</span> <span class="er">class</span><span class="ot">=</span><span class="st">&quot;result-row&quot;</span> <span class="er">data-pid</span><span class="ot">=</span><span class="st">&quot;6788463837&quot;</span><span class="kw">&gt;</span></span>
<span id="cb88-28"><a href="reading.html#cb88-28" aria-hidden="true" tabindex="-1"></a>                  </span>
<span id="cb88-29"><a href="reading.html#cb88-29" aria-hidden="true" tabindex="-1"></a>        <span class="kw">&lt;a</span> <span class="er">href</span><span class="ot">=</span><span class="st">&quot;https://vancouver.craigslist.org/nvn/apa/d/north-vancouver-luxu</span></span>
<span id="cb88-30"><a href="reading.html#cb88-30" aria-hidden="true" tabindex="-1"></a><span class="st">                </span><span class="er">&lt;</span><span class="st">span class=&quot;</span><span class="er">result-price&quot;</span><span class="kw">&gt;</span>$2285<span class="kw">&lt;/span&gt;</span></span>
<span id="cb88-31"><a href="reading.html#cb88-31" aria-hidden="true" tabindex="-1"></a>        <span class="kw">&lt;/a&gt;</span></span></code></pre></div>
<p>Oof…you can tell that the source code for a web page is not really designed
for humans to understand easily. However, if you look through it closely, you
will find that the information we’re interested in is hidden among the muck.
For example, near the top of the snippet
above you can see a line that looks like</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode html"><code class="sourceCode html"><span id="cb89-1"><a href="reading.html#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="kw">&lt;span</span> <span class="er">class</span><span class="ot">=</span><span class="st">&quot;result-price&quot;</span><span class="kw">&gt;</span>$800<span class="kw">&lt;/span&gt;</span></span></code></pre></div>
<p>That is definitely storing the price of a particular apartment. With some more
investigation, you should be able to find things like the date and time of the
listing, the address of the listing, and more. So this source code most likely
contains all the information we are interested in!</p>
<p>Let’s dig into that line  above a bit more. You can see that
that bit of code has an <em>opening tag</em> (words between <code>&lt;</code> and <code>&gt;</code>, like
<code>&lt;span&gt;</code>) and a <em>closing tag</em> (the same with a slash, like <code>&lt;/span&gt;</code>). HTML
source code generally stores its data between opening and closing tags like
these. Tags are keywords that tell the web browser how to display or format
the content. Above you can see that the information we want (<code>$800</code>) is stored
between an opening and closing tag (<code>&lt;span&gt;</code> and <code>&lt;/span&gt;</code>). In the opening
tag, you can also see a very useful “class” (a special word that is sometimes
included with opening tags): <code>class="result-price"</code>. Since we want R to
programmatically sort through all of the source code for the website to find
apartment prices, maybe we can look for all the tags with the <code>"result-price"</code>
class, and grab the information between the opening and closing tag. Indeed,
take a look at another line of the source snippet above:</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode html"><code class="sourceCode html"><span id="cb90-1"><a href="reading.html#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="kw">&lt;span</span> <span class="er">class</span><span class="ot">=</span><span class="st">&quot;result-price&quot;</span><span class="kw">&gt;</span>$2285<span class="kw">&lt;/span&gt;</span></span></code></pre></div>
<p>It’s yet another price for an apartment listing, and the tags surrounding it
have the <code>"result-price"</code> class. Wonderful! Now that we know what pattern we
are looking for—a dollar amount between opening and closing tags that have the
<code>"result-price"</code> class—we should be able to use code to pull out all of the
matching patterns from the source code to obtain our data. This sort of “pattern”
is known as a <em>CSS selector</em> (where CSS stands for <strong>c</strong>ascading <strong>s</strong>tyle <strong>s</strong>heet).</p>
<p>The above was a simple example of “finding the pattern to look for”; many
websites are quite a bit larger and more complex, and so is their website
source code. Fortunately, there are tools available to make this process
easier. For example,
<a href="https://selectorgadget.com/">SelectorGadget</a> is
an open-source tool that simplifies identifying the generating
and finding of CSS selectors.
At the end of the chapter in the additional resources section, we include a link to
a short video on how to install and use the SelectorGadget tool to
obtain CSS selectors for use in web scraping.
After installing and enabling the tool, you can click the
website element for which you want an appropriate selector. For
example, if we click the price of an apartment listing, we
find that SelectorGadget shows us the selector <code>.result-price</code>
in its toolbar, and highlights all the other apartment
prices that would be obtained using that selector (Figure <a href="reading.html#fig:sg1">2.4</a>).</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:sg1"></span>
<img src="img/sg1.png" alt="Using the SelectorGadget on a Craigslist webpage to obtain the CCS selector useful for obtaining apartment prices." width="100%" />
<p class="caption">
Figure 2.4: Using the SelectorGadget on a Craigslist webpage to obtain the CCS selector useful for obtaining apartment prices.
</p>
</div>
<p>If we then click the size of an apartment listing, SelectorGadget shows us
the <code>span</code> selector, and highlights many of the lines on the page; this indicates that the
<code>span</code> selector is not specific enough to capture only apartment sizes (Figure <a href="reading.html#fig:sg3">2.5</a>).</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:sg3"></span>
<img src="img/sg3.png" alt="Using the SelectorGadget on a Craigslist webpage to obtain a CCS selector useful for obtaining apartment sizes." width="100%" />
<p class="caption">
Figure 2.5: Using the SelectorGadget on a Craigslist webpage to obtain a CCS selector useful for obtaining apartment sizes.
</p>
</div>
<p>To narrow the selector, we can click one of the highlighted elements that
we <em>do not</em> want. For example, we can deselect the “pic/map” links,
resulting in only the data we want highlighted using the <code>.housing</code> selector (Figure <a href="reading.html#fig:sg2">2.6</a>).</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:sg2"></span>
<img src="img/sg2.png" alt="Using the SelectorGadget on a Craigslist webpage to refine the CCS selector to one that is most useful for obtaining apartment sizes." width="100%" />
<p class="caption">
Figure 2.6: Using the SelectorGadget on a Craigslist webpage to refine the CCS selector to one that is most useful for obtaining apartment sizes.
</p>
</div>
<p>So to scrape information about the square footage and rental price
of apartment listings, we need to use
the two CSS selectors <code>.housing</code> and <code>.result-price</code>, respectively.
The selector gadget returns them to us as a comma-separated list (here
<code>.housing , .result-price</code>), which is exactly the format we need to provide to
R if we are using more than one CSS selector.</p>
<p><strong>Stop! Are you allowed to scrape that website?</strong>
<em>Before</em> scraping  data from the web, you should always check whether or not
you are <em>allowed</em> to scrape it! There are two documents that are important
for this: the <code>robots.txt</code> file and the Terms of Service
document. If we take a look at <a href="https://www.craigslist.org/about/terms.of.use">Craigslist’s Terms of Service document</a>,
we find the following text: <em>“You agree not to copy/collect CL content
via robots, spiders, scripts, scrapers, crawlers, or any automated or manual equivalent (e.g., by hand).”</em>
So unfortunately, without explicit permission, we are not allowed to scrape the website.</p>
<p>What to do now? Well, we <em>could</em> ask the owner of Craigslist for permission to scrape.
However, we are not likely to get a response, and even if we did they would not likely give us permission.
The more realistic answer is that we simply cannot scrape Craigslist. If we still want
to find data about rental prices in Vancouver, we must go elsewhere.
To continue learning how to scrape data from the web, let’s instead
scrape data on the population of Canadian cities from Wikipedia. 
We have checked the <a href="https://foundation.wikimedia.org/wiki/Terms_of_Use/en">Terms of Service document</a>,
and it does not mention that web scraping is disallowed.
We will use the SelectorGadget tool to pick elements that we are interested in
(city names and population counts) and deselect others to indicate that we are not
interested in them (province names), as shown in Figure <a href="reading.html#fig:sg4">2.7</a>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:sg4"></span>
<img src="img/sg4.png" alt="Using the SelectorGadget on a Wikipedia webpage." width="100%" />
<p class="caption">
Figure 2.7: Using the SelectorGadget on a Wikipedia webpage.
</p>
</div>
<p>We include a link to a short video tutorial on this process at the end of the chapter
in the additional resources section. SelectorGadget provides in its toolbar
the following list of CSS selectors to use:</p>
<pre><code>td:nth-child(5), 
td:nth-child(7), 
.infobox:nth-child(122) td:nth-child(1), 
.infobox td:nth-child(3)</code></pre>
<p>Now that we have the CSS selectors that describe the properties of the elements
that we want to target (e.g., has a tag name <code>price</code>), we can use them to find
certain elements in web pages and extract data.</p>
<p><strong>Using <code>rvest</code></strong></p>
<p>Now that we have our CSS selectors we can use the <code>rvest</code> R package  to scrape our
desired data from the website. We start by loading the <code>rvest</code> package:</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="reading.html#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rvest)</span></code></pre></div>
<p>Next, we tell R what page we want to scrape by providing the webpage’s URL in quotations to the function <code>read_html</code>:</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="reading.html#cb93-1" aria-hidden="true" tabindex="-1"></a>page <span class="ot">&lt;-</span> <span class="fu">read_html</span>(<span class="st">&quot;https://en.wikipedia.org/wiki/Canada&quot;</span>)</span></code></pre></div>
<p>The <code>read_html</code> function  directly downloads the source code for the page at
the URL you specify, just like your browser would if you navigated to that site. But
instead of displaying the website to you, the <code>read_html</code> function just returns
the HTML source code itself, which we have
stored in the <code>page</code> variable. Next, we send the page object to the <code>html_nodes</code>
function, along with the CSS selectors we obtained from
the SelectorGadget tool. Make sure to surround the selectors with quotation marks; the function, <code>html_nodes</code>, expects that
argument is a string. The <code>html_nodes</code> function then selects <em>nodes</em> from the HTML document that
match the CSS selectors you specified. A <em>node</em> is an HTML tag pair (e.g.,
<code>&lt;td&gt;</code> and <code>&lt;/td&gt;</code> which defines the cell of a table) combined with the content
stored between the tags. For our CSS selector <code>td:nth-child(5)</code>, an example
node that would be selected would be:</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode html"><code class="sourceCode html"><span id="cb94-1"><a href="reading.html#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="kw">&lt;td</span> <span class="er">style</span><span class="ot">=</span><span class="st">&quot;text-align:left;background:#f0f0f0;&quot;</span><span class="kw">&gt;</span></span>
<span id="cb94-2"><a href="reading.html#cb94-2" aria-hidden="true" tabindex="-1"></a><span class="kw">&lt;a</span> <span class="er">href</span><span class="ot">=</span><span class="st">&quot;/wiki/London,_Ontario&quot;</span> <span class="er">title</span><span class="ot">=</span><span class="st">&quot;London, Ontario&quot;</span><span class="kw">&gt;</span>London<span class="kw">&lt;/a&gt;</span></span>
<span id="cb94-3"><a href="reading.html#cb94-3" aria-hidden="true" tabindex="-1"></a><span class="kw">&lt;/td&gt;</span></span></code></pre></div>
<p>We store the result of the <code>html_nodes</code> function in the <code>population_nodes</code> variable.
Note that below we use the <code>paste</code> function with a comma separator (<code>sep=","</code>)
to build the list of selectors. The <code>paste</code> function converts
elements to characters and combines the values into a list. We use this function to
build the list of selectors to maintain code readability; this avoids
having one very long line of code with the string
<code>"td:nth-child(5),td:nth-child(7),.infobox:nth-child(122) td:nth-child(1),.infobox td:nth-child(3)"</code>
as the second argument of <code>html_nodes</code>:</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="reading.html#cb95-1" aria-hidden="true" tabindex="-1"></a>selectors <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">&quot;td:nth-child(5)&quot;</span>,</span>
<span id="cb95-2"><a href="reading.html#cb95-2" aria-hidden="true" tabindex="-1"></a>             <span class="st">&quot;td:nth-child(7)&quot;</span>,</span>
<span id="cb95-3"><a href="reading.html#cb95-3" aria-hidden="true" tabindex="-1"></a>             <span class="st">&quot;.infobox:nth-child(122) td:nth-child(1)&quot;</span>,</span>
<span id="cb95-4"><a href="reading.html#cb95-4" aria-hidden="true" tabindex="-1"></a>             <span class="st">&quot;.infobox td:nth-child(3)&quot;</span>, <span class="at">sep=</span><span class="st">&quot;,&quot;</span>)</span>
<span id="cb95-5"><a href="reading.html#cb95-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-6"><a href="reading.html#cb95-6" aria-hidden="true" tabindex="-1"></a>population_nodes <span class="ot">&lt;-</span> <span class="fu">html_nodes</span>(page, selectors)</span>
<span id="cb95-7"><a href="reading.html#cb95-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(population_nodes)</span></code></pre></div>
<pre><code>## {xml_nodeset (6)}
## [1] &lt;td style=&quot;text-align:left;background:#f0f0f0;&quot;&gt;&lt;a href=&quot;/wiki/London,_On ...
## [2] &lt;td style=&quot;text-align:right;&quot;&gt;543,551\n&lt;/td&gt;
## [3] &lt;td style=&quot;text-align:left;background:#f0f0f0;&quot;&gt;&lt;a href=&quot;/wiki/Halifax,_N ...
## [4] &lt;td style=&quot;text-align:right;&quot;&gt;465,703\n&lt;/td&gt;
## [5] &lt;td style=&quot;text-align:left;background:#f0f0f0;&quot;&gt;\n&lt;a href=&quot;/wiki/St._Cath ...
## [6] &lt;td style=&quot;text-align:right;&quot;&gt;433,604\n&lt;/td&gt;</code></pre>
<p>Next we extract the meaningful data—in other words, we get rid of the HTML code syntax and tags—from
the nodes using the <code>html_text</code>
function. In the case of the example
node above, <code>html_text</code> function returns <code>"London"</code>.</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="reading.html#cb97-1" aria-hidden="true" tabindex="-1"></a>population_text <span class="ot">&lt;-</span> <span class="fu">html_text</span>(population_nodes)</span>
<span id="cb97-2"><a href="reading.html#cb97-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(population_text)</span></code></pre></div>
<pre><code>## [1] &quot;London&quot;                 &quot;543,551\n&quot;              &quot;Halifax&quot;               
## [4] &quot;465,703\n&quot;              &quot;St. Catharines–Niagara&quot; &quot;433,604\n&quot;</code></pre>
<p>Fantastic! We seem to have extracted the data of interest from the
raw HTML source code. But we are not quite done; the data
is not yet in an optimal format for data analysis. Both the city names and
population are encoded as characters in a single vector, instead of being in a
data frame with one character column for city and one numeric column for
population (like a spreadsheet).
Additionally, the populations contain commas (not useful for programmatically
dealing with numbers), and some even contain a line break character at the end
(<code>\n</code>). In Chapter <a href="wrangling.html#wrangling">3</a>, we will learn more about how to <em>wrangle</em> data
such as this into a more useful format for data analysis using R.</p>
</div>
</div>
<div id="using-an-api" class="section level3" number="2.8.2">
<h3><span class="header-section-number">2.8.2</span> Using an API</h3>
<p>Rather than posting a data file at a URL for you to download, many websites these days
provide an API  that must be accessed through a programming language like R. The benefit of this
is that data owners have much more control over the data they provide to users. However, unlike
web scraping, there is no consistent way to access an API across websites. Every website typically
has its own API designed especially for its own use case. Therefore we will just provide one example
of accessing data through an API in this book, with the hope that it gives you enough of a basic
idea that you can learn how to use another API if needed.</p>
<p>In particular, in this book we will show you the basics of how to use
the <code>rtweet</code> package in R to access
data from the Twitter API. One nice feature of this particular
API is that you don’t need a special <em>token</em>  to access it; you simply need to
make an account with them. Your access to the data will then be authenticated and controlled through
your account username and password. If you have a Twitter
account already (or are willing to make one), you can follow
along with the examples that we show here. To get started, load the <code>rtweet</code> package:</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="reading.html#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rtweet)</span></code></pre></div>
<p>This package provides an extensive set of functions to search
Twitter for tweets, users, their followers, and more.
Let’s construct a small data set of the last 400 tweets and
retweets from the @tidyverse account. A few of the most recent tweets
are shown in Figure <a href="reading.html#fig:01-tidyverse-twitter">2.8</a>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:01-tidyverse-twitter"></span>
<img src="img/tidyverse_twitter.png" alt="The tidyverse account Twitter feed." width="100%" />
<p class="caption">
Figure 2.8: The tidyverse account Twitter feed.
</p>
</div>
<p><strong>Stop! Think about your API usage carefully!</strong></p>
<p>When you access an API, you are initiating a transfer of data from a web server
to your computer. Web servers are expensive to run and do not have infinite resources.
If you try to ask for <em>too much data</em> at once, you can use up a huge amount of the server’s bandwidth.
If you try to ask for data <em>too frequently</em>—e.g., if you
make many requests to the server in quick succession—you can also bog the server down and make
it unable to talk to anyone else. Most servers have mechanisms to revoke your access if you are not
careful, but you should try to prevent issues from happening in the first place by being extra careful
with how you write and run your code. You should also keep in mind that when a website owner
grants you API access, they also usually specify a limit (or <em>quota</em>) of how much data you can ask for.
Be careful not to overrun your quota! In this example, we should take a look at
<a href="https://developer.twitter.com/en/docs/twitter-api/rate-limits">the Twitter website</a> to see what limits
we should abide by when using the API.</p>
<p><strong>Using <code>rtweet</code></strong></p>
<p>After checking the Twitter website, it seems like asking for 400 tweets one time is acceptable.
So we can use the <code>get_timelines</code> function to ask for the last 400 tweets from the @tidyverse account.</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="reading.html#cb100-1" aria-hidden="true" tabindex="-1"></a>tidyverse_tweets <span class="ot">&lt;-</span> <span class="fu">get_timelines</span>(<span class="st">&#39;tidyverse&#39;</span>, <span class="at">n=</span><span class="dv">400</span>)</span></code></pre></div>
<p>When you call the <code>get_timelines</code> for the first time (or any other <code>rtweet</code> function that accesses the API),
you will see a browser pop-up that looks something like Figure <a href="reading.html#fig:01-tidyverse-authorize">2.9</a>.</p>

<div class="figure" style="text-align: center"><span style="display:block;" id="fig:01-tidyverse-authorize"></span>
<img src="img/authorize_question.png" alt="The rtweet authorization prompt." width="100%" />
<p class="caption">
Figure 2.9: The <code>rtweet</code> authorization prompt.
</p>
</div>
<p>This is the <code>rtweet</code> package asking you to provide your own Twitter account’s login information.
When <code>rtweet</code> talks to the Twitter API, it uses your account information to authenticate requests;
Twitter then can keep track of how much data you’re asking for, and how frequently you’re asking.
If you want to follow along with this example using your own Twitter account, you should read
over the list of permissions you are granting <code>rtweet</code> <em>very carefully</em> and make sure you are comfortable
with it. Note that <code>rtweet</code> can be used to manage most aspects of your account (make posts, follow others, etc.),
which is why <code>rtweet</code> asks for such extensive permissions.
If you decide to allow <code>rtweet</code> to talk to the Twitter API using your account information, then
input your username and password and hit “Sign In.” Twitter will probably send you an email to say
that there was an unusual login attempt on your account, and in that case you will have to take
the one-time code they send you and provide that to the <code>rtweet</code> login page too.</p>
<blockquote>
<p><strong>Note:</strong> Every API has its own way to authenticate users when they try to access data. Many APIs require you to
sign up to receive a <em>token</em>, which is a secret password that you input into the R package (like <code>rtweet</code>)
that you are using to access the API.</p>
</blockquote>
<p>With the authentication setup out of the way, let’s run the <code>get_timelines</code> function again to actually access
the API and take a look at what was returned:</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="reading.html#cb101-1" aria-hidden="true" tabindex="-1"></a>tidyverse_tweets <span class="ot">&lt;-</span> <span class="fu">get_timelines</span>(<span class="st">&#39;tidyverse&#39;</span>, <span class="at">n=</span><span class="dv">400</span>)</span>
<span id="cb101-2"><a href="reading.html#cb101-2" aria-hidden="true" tabindex="-1"></a>tidyverse_tweets</span></code></pre></div>
<pre><code>## # A tibble: 293 × 71
##    created_at          reply_to_status_id quoted_created_at reply_to_user_id
##    &lt;dttm&gt;              &lt;lgl&gt;              &lt;dttm&gt;            &lt;lgl&gt;           
##  1 2021-04-29 11:59:04 NA                 NA                NA              
##  2 2021-04-26 17:05:47 NA                 NA                NA              
##  3 2021-04-24 09:13:12 NA                 NA                NA              
##  4 2021-04-18 06:06:21 NA                 NA                NA              
##  5 2021-04-12 05:48:33 NA                 NA                NA              
##  6 2021-04-08 17:45:34 NA                 NA                NA              
##  7 2021-04-01 05:01:38 NA                 NA                NA              
##  8 2021-03-25 06:05:49 NA                 NA                NA              
##  9 2021-03-18 17:16:21 NA                 NA                NA              
## 10 2021-03-12 19:12:49 NA                 NA                NA              
## # … with 283 more rows, and 67 more variables: reply_to_screen_name &lt;lgl&gt;,
## #   is_quote &lt;lgl&gt;, is_retweet &lt;lgl&gt;, quoted_verified &lt;lgl&gt;,
## #   retweet_verified &lt;lgl&gt;, protected &lt;lgl&gt;, verified &lt;lgl&gt;,
## #   account_lang &lt;lgl&gt;, profile_background_url &lt;lgl&gt;, user_id &lt;dbl&gt;,
## #   status_id &lt;dbl&gt;, screen_name &lt;chr&gt;, text &lt;chr&gt;, source &lt;chr&gt;,
## #   ext_media_type &lt;lgl&gt;, lang &lt;chr&gt;, quoted_status_id &lt;dbl&gt;,
## #   quoted_text &lt;chr&gt;, quoted_source &lt;chr&gt;, quoted_user_id &lt;dbl&gt;, …</code></pre>
<p>The data has quite a few variables! (Notice that the output above shows that we
have a data table with 293 rows and 71 columns). Let’s reduce this down to a
few variables of interest: <code>created_at</code>, <code>retweet_screen_name</code>, <code>is_retweet</code>,
and <code>text</code>.</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="reading.html#cb103-1" aria-hidden="true" tabindex="-1"></a>tidyverse_tweets <span class="ot">&lt;-</span> <span class="fu">select</span>(tidyverse_tweets, </span>
<span id="cb103-2"><a href="reading.html#cb103-2" aria-hidden="true" tabindex="-1"></a>                           created_at, </span>
<span id="cb103-3"><a href="reading.html#cb103-3" aria-hidden="true" tabindex="-1"></a>                           retweet_screen_name,</span>
<span id="cb103-4"><a href="reading.html#cb103-4" aria-hidden="true" tabindex="-1"></a>                           is_retweet, </span>
<span id="cb103-5"><a href="reading.html#cb103-5" aria-hidden="true" tabindex="-1"></a>                           text)</span>
<span id="cb103-6"><a href="reading.html#cb103-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb103-7"><a href="reading.html#cb103-7" aria-hidden="true" tabindex="-1"></a>tidyverse_tweets</span></code></pre></div>
<pre><code>## # A tibble: 293 × 4
##    created_at          retweet_screen_name is_retweet text                      
##    &lt;dttm&gt;              &lt;chr&gt;               &lt;lgl&gt;      &lt;chr&gt;                     
##  1 2021-04-29 11:59:04 yutannihilat_en     TRUE       &quot;Just curious, after the …
##  2 2021-04-26 17:05:47 statwonk            TRUE       &quot;List columns provide a t…
##  3 2021-04-24 09:13:12 topepos             TRUE       &quot;A new release of the {{r…
##  4 2021-04-18 06:06:21 ninarbrooks         TRUE       &quot;Always typing `? pivot_l…
##  5 2021-04-12 05:48:33 rfunctionaday       TRUE       &quot;If you are fluent in {dp…
##  6 2021-04-08 17:45:34 RhesusMaCassidy     TRUE       &quot;R-Ladies of Göttingen! T…
##  7 2021-04-01 05:01:38 dvaughan32          TRUE       &quot;I am ridiculously excite…
##  8 2021-03-25 06:05:49 rdpeng              TRUE       &quot;New book out on using ti…
##  9 2021-03-18 17:16:21 SolomonKurz         TRUE       &quot;The 0.2.0 version of my …
## 10 2021-03-12 19:12:49 hadleywickham       TRUE       &quot;rvest 1.0.0 out now! — h…
## # … with 283 more rows</code></pre>
<p>If you look back up at the image of the @tidyverse Twitter page, you will
recognize the text of the most recent few tweets in the above data frame. In
other words, we have successfully created a small data set using the Twitter
API—neat! This data is also quite different from what we obtained from web scraping;
it is already well-organized into a <code>tidyverse</code> data frame (although not <em>every</em> API
will provide data in such a nice format).
From this point onward, the <code>tidyverse_tweets</code> data frame is stored on your
machine, and you can play with it to your heart’s content. For example, you can use
<code>write_csv</code> to save it to a file and <code>read_csv</code> to read it into R again later;
and after reading the next few chapters you will have the skills to
compute the percentage of retweets versus tweets, find the most oft-retweeted
account, make visualizations of the data, and much more! If you decide that you want
to ask the Twitter API for more data
(see <a href="https://github.com/ropensci/rtweet">the <code>rtweet</code> page</a>
for more examples of what is possible), just be mindful as usual about how much
data you are requesting and how frequently you are making requests.</p>
</div>
</div>
<div id="exercises-1" class="section level2" number="2.9">
<h2><span class="header-section-number">2.9</span> Exercises</h2>
<p>Practice exercises for the material covered in this chapter
can be found in the accompanying
<a href="https://github.com/UBC-DSCI/data-science-a-first-intro-worksheets#readme">worksheets repository</a>
in the “Reading in data locally and from the web” row.
You can launch an interactive version of the worksheet in your browser by clicking the “launch binder” button.
You can also preview a non-interactive version of the worksheet by clicking “view worksheet.”
If you instead decide to download the worksheet and run it on your own machine,
make sure to follow the instructions for computer setup
found in Chapter <a href="move-to-your-own-machine.html#move-to-your-own-machine">13</a>. This will ensure that the automated feedback
and guidance that the worksheets provide will function as intended.</p>
</div>
<div id="additional-resources" class="section level2" number="2.10">
<h2><span class="header-section-number">2.10</span> Additional resources</h2>
<ul>
<li>The <a href="https://readr.tidyverse.org/"><code>readr</code> documentation</a>
provides the documentation for many of the reading functions we cover in this chapter.
It is where you should look if you want to learn more about the functions in this
chapter, the full set of arguments you can use, and other related functions.
The site also provides a very nice cheat sheet that summarizes many of the data
wrangling functions from this chapter.</li>
<li>Sometimes you might run into data in such poor shape that none of the reading
functions we cover in this chapter work. In that case, you can consult the
<a href="https://r4ds.had.co.nz/data-import.html">data import chapter</a> from <em>R for Data
Science</em> <span class="citation">(<a href="#ref-wickham2016r" role="doc-biblioref">Wickham and Grolemund 2016</a>)</span>, which goes into a lot more detail about how R parses
text from files into data frames.</li>
<li>The <a href="https://here.r-lib.org/"><code>here</code> R package</a> <span class="citation">(<a href="#ref-here" role="doc-biblioref">Müller 2020</a>)</span>
provides a way for you to construct or find your files’ paths.</li>
<li>The <a href="https://readxl.tidyverse.org/"><code>readxl</code> documentation</a> provides more
details on reading data from Excel, such as reading in data with multiple
sheets, or specifying the cells to read in.</li>
<li>The <a href="https://github.com/leeper/rio"><code>rio</code> R package</a> <span class="citation">(<a href="#ref-rio" role="doc-biblioref">Leeper 2021</a>)</span> provides an alternative
set of tools for reading and writing data in R. It aims to be a “Swiss army
knife” for data reading/writing/converting, and supports a wide variety of data
types (including data formats generated by other statistical software like SPSS
and SAS).</li>
<li>A <a href="https://www.youtube.com/embed/ephId3mYu9o">video</a> from the Udacity
course <em>Linux Command Line Basics</em> provides a good explanation of absolute versus relative paths.</li>
<li>If you read the subsection on obtaining data from the web via scraping and
APIs, we provide two companion tutorial video links for how to use the
SelectorGadget tool to obtain desired CSS selectors for:
<ul>
<li><a href="https://www.youtube.com/embed/YdIWI6K64zo">extracting the data for apartment listings on Craigslist</a>, and</li>
<li><a href="https://www.youtube.com/embed/O9HKbdhqYzk">extracting Canadian city names and 2016 populations from Wikipedia</a>.</li>
</ul></li>
<li>The <a href="https://dmi3kno.github.io/polite/"><code>polite</code> R package</a> <span class="citation">(<a href="#ref-polite" role="doc-biblioref">Perepolkin 2021</a>)</span> provides
a set of tools for responsibly scraping data from websites.</li>
</ul>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-rtweet" class="csl-entry">
Kearney, Michael. 2019. <em><span class="nocase">rtweet R package</span></em>. <a href="https://github.com/ropensci/rtweet">https://github.com/ropensci/rtweet</a>.
</div>
<div id="ref-rio" class="csl-entry">
Leeper, Thomas. 2021. <em><span class="nocase">rio R package</span></em>. <a href="https://cloud.r-project.org/web/packages/rio/index.html">https://cloud.r-project.org/web/packages/rio/index.html</a>.
</div>
<div id="ref-here" class="csl-entry">
Müller, Kirill. 2020. <em><span class="nocase">here R package</span></em>. <a href="https://here.r-lib.org/">https://here.r-lib.org/</a>.
</div>
<div id="ref-polite" class="csl-entry">
Perepolkin, Dmytro. 2021. <em><span class="nocase">polite R package</span></em>. <a href="https://dmi3kno.github.io/polite/">https://dmi3kno.github.io/polite/</a>.
</div>
<div id="ref-googlesearches" class="csl-entry">
Real Time Statistics Project. 2021. <span>“Internet Live Stats: Google Search Statistics.”</span> <a href="https://www.internetlivestats.com/google-search-statistics/">https://www.internetlivestats.com/google-search-statistics/</a>.
</div>
<div id="ref-rvest" class="csl-entry">
———. 2021a. <em><span class="nocase">rvest R package</span></em>. <a href="https://rvest.tidyverse.org/">https://rvest.tidyverse.org/</a>.
</div>
<div id="ref-dplyr" class="csl-entry">
Wickham, Hadley, Romain François, Lionel Henry, and Kirill Müller. 2021. <em><span class="nocase">dplyr R package</span></em>. <a href="https://dplyr.tidyverse.org/">https://dplyr.tidyverse.org/</a>.
</div>
<div id="ref-wickham2016r" class="csl-entry">
Wickham, Hadley, and Garrett Grolemund. 2016. <em>R for Data Science: Import, Tidy, Transform, Visualize, and Model Data</em>. O’Reilly. <a href="https://r4ds.had.co.nz/">https://r4ds.had.co.nz/</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="intro.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="wrangling.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
