<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Effective data visualization | Data Science: A First Introduction</title>
  <meta name="description" content="This is a textbook for teaching a first introduction to data science." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Effective data visualization | Data Science: A First Introduction" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a textbook for teaching a first introduction to data science." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Effective data visualization | Data Science: A First Introduction" />
  
  <meta name="twitter:description" content="This is a textbook for teaching a first introduction to data science." />
  

<meta name="author" content="Tiffany-Anne Timbers" />
<meta name="author" content="Trevor Campbell" />
<meta name="author" content="Melissa Lee" />


<meta name="date" content="2022-01-12" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="wrangling.html"/>
<link rel="next" href="classification.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.5.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.5.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Data Science: A First Introduction</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Foreword</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="" data-path="acknowledgments.html"><a href="acknowledgments.html"><i class="fa fa-check"></i>Acknowledgments</a></li>
<li class="chapter" data-level="" data-path="about-the-authors.html"><a href="about-the-authors.html"><i class="fa fa-check"></i>About the authors</a></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> R and the Tidyverse</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#overview"><i class="fa fa-check"></i><b>1.1</b> Overview</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#chapter-learning-objectives"><i class="fa fa-check"></i><b>1.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#canadian-languages-data-set"><i class="fa fa-check"></i><b>1.3</b> Canadian languages data set</a></li>
<li class="chapter" data-level="1.4" data-path="intro.html"><a href="intro.html#asking-a-question"><i class="fa fa-check"></i><b>1.4</b> Asking a question</a></li>
<li class="chapter" data-level="1.5" data-path="intro.html"><a href="intro.html#loading-a-tabular-data-set"><i class="fa fa-check"></i><b>1.5</b> Loading a tabular data set</a></li>
<li class="chapter" data-level="1.6" data-path="intro.html"><a href="intro.html#naming-things-in-r"><i class="fa fa-check"></i><b>1.6</b> Naming things in R</a></li>
<li class="chapter" data-level="1.7" data-path="intro.html"><a href="intro.html#creating-subsets-of-data-frames-with-filter-select"><i class="fa fa-check"></i><b>1.7</b> Creating subsets of data frames with <code>filter</code> &amp; <code>select</code></a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="intro.html"><a href="intro.html#using-filter-to-extract-rows"><i class="fa fa-check"></i><b>1.7.1</b> Using <code>filter</code> to extract rows</a></li>
<li class="chapter" data-level="1.7.2" data-path="intro.html"><a href="intro.html#using-select-to-extract-columns"><i class="fa fa-check"></i><b>1.7.2</b> Using <code>select</code> to extract columns</a></li>
<li class="chapter" data-level="1.7.3" data-path="intro.html"><a href="intro.html#using-arrange-to-order-and-slice-to-select-rows-by-index-number"><i class="fa fa-check"></i><b>1.7.3</b> Using <code>arrange</code> to order and <code>slice</code> to select rows by index number</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="intro.html"><a href="intro.html#exploring-data-with-visualizations"><i class="fa fa-check"></i><b>1.8</b> Exploring data with visualizations</a>
<ul>
<li class="chapter" data-level="1.8.1" data-path="intro.html"><a href="intro.html#using-ggplot-to-create-a-bar-plot"><i class="fa fa-check"></i><b>1.8.1</b> Using <code>ggplot</code> to create a bar plot</a></li>
<li class="chapter" data-level="1.8.2" data-path="intro.html"><a href="intro.html#formatting-ggplot-objects"><i class="fa fa-check"></i><b>1.8.2</b> Formatting ggplot objects</a></li>
<li class="chapter" data-level="1.8.3" data-path="intro.html"><a href="intro.html#putting-it-all-together"><i class="fa fa-check"></i><b>1.8.3</b> Putting it all together</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="intro.html"><a href="intro.html#accessing-documentation"><i class="fa fa-check"></i><b>1.9</b> Accessing documentation</a></li>
<li class="chapter" data-level="1.10" data-path="intro.html"><a href="intro.html#exercises"><i class="fa fa-check"></i><b>1.10</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="reading.html"><a href="reading.html"><i class="fa fa-check"></i><b>2</b> Reading in data locally and from the web</a>
<ul>
<li class="chapter" data-level="2.1" data-path="reading.html"><a href="reading.html#overview-1"><i class="fa fa-check"></i><b>2.1</b> Overview</a></li>
<li class="chapter" data-level="2.2" data-path="reading.html"><a href="reading.html#chapter-learning-objectives-1"><i class="fa fa-check"></i><b>2.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="2.3" data-path="reading.html"><a href="reading.html#absolute-and-relative-file-paths"><i class="fa fa-check"></i><b>2.3</b> Absolute and relative file paths</a></li>
<li class="chapter" data-level="2.4" data-path="reading.html"><a href="reading.html#reading-tabular-data-from-a-plain-text-file-into-r"><i class="fa fa-check"></i><b>2.4</b> Reading tabular data from a plain text file into R</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="reading.html"><a href="reading.html#readcsv"><i class="fa fa-check"></i><b>2.4.1</b> <code>read_csv</code> to read in comma-separated files</a></li>
<li class="chapter" data-level="2.4.2" data-path="reading.html"><a href="reading.html#skipping-rows-when-reading-in-data"><i class="fa fa-check"></i><b>2.4.2</b> Skipping rows when reading in data</a></li>
<li class="chapter" data-level="2.4.3" data-path="reading.html"><a href="reading.html#read_tsv-to-read-in-tab-separated-files"><i class="fa fa-check"></i><b>2.4.3</b> <code>read_tsv</code> to read in tab-separated files</a></li>
<li class="chapter" data-level="2.4.4" data-path="reading.html"><a href="reading.html#read_delim-as-a-more-flexible-method-to-get-tabular-data-into-r"><i class="fa fa-check"></i><b>2.4.4</b> <code>read_delim</code> as a more flexible method to get tabular data into R</a></li>
<li class="chapter" data-level="2.4.5" data-path="reading.html"><a href="reading.html#reading-tabular-data-directly-from-a-url"><i class="fa fa-check"></i><b>2.4.5</b> Reading tabular data directly from a URL</a></li>
<li class="chapter" data-level="2.4.6" data-path="reading.html"><a href="reading.html#previewing-a-data-file-before-reading-it-into-r"><i class="fa fa-check"></i><b>2.4.6</b> Previewing a data file before reading it into R</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="reading.html"><a href="reading.html#reading-tabular-data-from-a-microsoft-excel-file"><i class="fa fa-check"></i><b>2.5</b> Reading tabular data from a Microsoft Excel file</a></li>
<li class="chapter" data-level="2.6" data-path="reading.html"><a href="reading.html#reading-data-from-a-database"><i class="fa fa-check"></i><b>2.6</b> Reading data from a database</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="reading.html"><a href="reading.html#reading-data-from-a-sqlite-database"><i class="fa fa-check"></i><b>2.6.1</b> Reading data from a SQLite database</a></li>
<li class="chapter" data-level="2.6.2" data-path="reading.html"><a href="reading.html#reading-data-from-a-postgresql-database"><i class="fa fa-check"></i><b>2.6.2</b> Reading data from a PostgreSQL database</a></li>
<li class="chapter" data-level="2.6.3" data-path="reading.html"><a href="reading.html#why-should-we-bother-with-databases-at-all"><i class="fa fa-check"></i><b>2.6.3</b> Why should we bother with databases at all?</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="reading.html"><a href="reading.html#writing-data-from-r-to-a-.csv-file"><i class="fa fa-check"></i><b>2.7</b> Writing data from R to a <code>.csv</code> file</a></li>
<li class="chapter" data-level="2.8" data-path="reading.html"><a href="reading.html#obtaining-data-from-the-web"><i class="fa fa-check"></i><b>2.8</b> Obtaining data from the web</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="reading.html"><a href="reading.html#web-scraping"><i class="fa fa-check"></i><b>2.8.1</b> Web scraping</a></li>
<li class="chapter" data-level="2.8.2" data-path="reading.html"><a href="reading.html#using-an-api"><i class="fa fa-check"></i><b>2.8.2</b> Using an API</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="reading.html"><a href="reading.html#exercises-1"><i class="fa fa-check"></i><b>2.9</b> Exercises</a></li>
<li class="chapter" data-level="2.10" data-path="reading.html"><a href="reading.html#additional-resources"><i class="fa fa-check"></i><b>2.10</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="wrangling.html"><a href="wrangling.html"><i class="fa fa-check"></i><b>3</b> Cleaning and wrangling data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="wrangling.html"><a href="wrangling.html#overview-2"><i class="fa fa-check"></i><b>3.1</b> Overview</a></li>
<li class="chapter" data-level="3.2" data-path="wrangling.html"><a href="wrangling.html#chapter-learning-objectives-2"><i class="fa fa-check"></i><b>3.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="3.3" data-path="wrangling.html"><a href="wrangling.html#data-frames-vectors-and-lists"><i class="fa fa-check"></i><b>3.3</b> Data frames, vectors, and lists</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="wrangling.html"><a href="wrangling.html#what-is-a-data-frame"><i class="fa fa-check"></i><b>3.3.1</b> What is a data frame?</a></li>
<li class="chapter" data-level="3.3.2" data-path="wrangling.html"><a href="wrangling.html#what-is-a-vector"><i class="fa fa-check"></i><b>3.3.2</b> What is a vector?</a></li>
<li class="chapter" data-level="3.3.3" data-path="wrangling.html"><a href="wrangling.html#what-is-a-list"><i class="fa fa-check"></i><b>3.3.3</b> What is a list?</a></li>
<li class="chapter" data-level="3.3.4" data-path="wrangling.html"><a href="wrangling.html#what-does-this-have-to-do-with-data-frames"><i class="fa fa-check"></i><b>3.3.4</b> What does this have to do with data frames?</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="wrangling.html"><a href="wrangling.html#tidy-data"><i class="fa fa-check"></i><b>3.4</b> Tidy data</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="wrangling.html"><a href="wrangling.html#tidying-up-going-from-wide-to-long-using-pivot_longer"><i class="fa fa-check"></i><b>3.4.1</b> Tidying up: going from wide to long using <code>pivot_longer</code></a></li>
<li class="chapter" data-level="3.4.2" data-path="wrangling.html"><a href="wrangling.html#pivot-wider"><i class="fa fa-check"></i><b>3.4.2</b> Tidying up: going from long to wide using <code>pivot_wider</code></a></li>
<li class="chapter" data-level="3.4.3" data-path="wrangling.html"><a href="wrangling.html#separate"><i class="fa fa-check"></i><b>3.4.3</b> Tidying up: using <code>separate</code> to deal with multiple delimiters</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="wrangling.html"><a href="wrangling.html#using-select-to-extract-a-range-of-columns"><i class="fa fa-check"></i><b>3.5</b> Using <code>select</code> to extract a range of columns</a></li>
<li class="chapter" data-level="3.6" data-path="wrangling.html"><a href="wrangling.html#using-filter-to-extract-rows-1"><i class="fa fa-check"></i><b>3.6</b> Using <code>filter</code> to extract rows</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="wrangling.html"><a href="wrangling.html#extracting-rows-that-have-a-certain-value-with"><i class="fa fa-check"></i><b>3.6.1</b> Extracting rows that have a certain value with <code>==</code></a></li>
<li class="chapter" data-level="3.6.2" data-path="wrangling.html"><a href="wrangling.html#extracting-rows-that-do-not-have-a-certain-value-with"><i class="fa fa-check"></i><b>3.6.2</b> Extracting rows that do not have a certain value with <code>!=</code></a></li>
<li class="chapter" data-level="3.6.3" data-path="wrangling.html"><a href="wrangling.html#filter-and"><i class="fa fa-check"></i><b>3.6.3</b> Extracting rows satisfying multiple conditions using <code>,</code> or <code>&amp;</code></a></li>
<li class="chapter" data-level="3.6.4" data-path="wrangling.html"><a href="wrangling.html#extracting-rows-satisfying-at-least-one-condition-using"><i class="fa fa-check"></i><b>3.6.4</b> Extracting rows satisfying at least one condition using <code>|</code></a></li>
<li class="chapter" data-level="3.6.5" data-path="wrangling.html"><a href="wrangling.html#extracting-rows-with-values-in-a-vector-using-in"><i class="fa fa-check"></i><b>3.6.5</b> Extracting rows with values in a vector using <code>%in%</code></a></li>
<li class="chapter" data-level="3.6.6" data-path="wrangling.html"><a href="wrangling.html#extracting-rows-above-or-below-a-threshold-using-and"><i class="fa fa-check"></i><b>3.6.6</b> Extracting rows above or below a threshold using <code>&gt;</code> and <code>&lt;</code></a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="wrangling.html"><a href="wrangling.html#using-mutate-to-modify-or-add-columns"><i class="fa fa-check"></i><b>3.7</b> Using <code>mutate</code> to modify or add columns</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="wrangling.html"><a href="wrangling.html#using-mutate-to-modify-columns"><i class="fa fa-check"></i><b>3.7.1</b> Using <code>mutate</code> to modify columns</a></li>
<li class="chapter" data-level="3.7.2" data-path="wrangling.html"><a href="wrangling.html#using-mutate-to-create-new-columns"><i class="fa fa-check"></i><b>3.7.2</b> Using <code>mutate</code> to create new columns</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="wrangling.html"><a href="wrangling.html#combining-functions-using-the-pipe-operator"><i class="fa fa-check"></i><b>3.8</b> Combining functions using the pipe operator, <code>|&gt;</code></a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="wrangling.html"><a href="wrangling.html#using-to-combine-filter-and-select"><i class="fa fa-check"></i><b>3.8.1</b> Using <code>|&gt;</code> to combine <code>filter</code> and <code>select</code></a></li>
<li class="chapter" data-level="3.8.2" data-path="wrangling.html"><a href="wrangling.html#using-with-more-than-two-functions"><i class="fa fa-check"></i><b>3.8.2</b> Using <code>|&gt;</code> with more than two functions</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="wrangling.html"><a href="wrangling.html#aggregating-data-with-summarize-and-map"><i class="fa fa-check"></i><b>3.9</b> Aggregating data with <code>summarize</code> and <code>map</code></a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="wrangling.html"><a href="wrangling.html#calculating-summary-statistics-on-whole-columns"><i class="fa fa-check"></i><b>3.9.1</b> Calculating summary statistics on whole columns</a></li>
<li class="chapter" data-level="3.9.2" data-path="wrangling.html"><a href="wrangling.html#calculating-summary-statistics-when-there-are-nas"><i class="fa fa-check"></i><b>3.9.2</b> Calculating summary statistics when there are <code>NA</code>s</a></li>
<li class="chapter" data-level="3.9.3" data-path="wrangling.html"><a href="wrangling.html#calculating-summary-statistics-for-groups-of-rows"><i class="fa fa-check"></i><b>3.9.3</b> Calculating summary statistics for groups of rows</a></li>
<li class="chapter" data-level="3.9.4" data-path="wrangling.html"><a href="wrangling.html#calculating-summary-statistics-on-many-columns"><i class="fa fa-check"></i><b>3.9.4</b> Calculating summary statistics on many columns</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="wrangling.html"><a href="wrangling.html#apply-functions-across-many-columns-with-mutate-and-across"><i class="fa fa-check"></i><b>3.10</b> Apply functions across many columns with <code>mutate</code> and <code>across</code></a></li>
<li class="chapter" data-level="3.11" data-path="wrangling.html"><a href="wrangling.html#apply-functions-across-columns-within-one-row-with-rowwise-and-mutate"><i class="fa fa-check"></i><b>3.11</b> Apply functions across columns within one row with <code>rowwise</code> and <code>mutate</code></a></li>
<li class="chapter" data-level="3.12" data-path="wrangling.html"><a href="wrangling.html#summary"><i class="fa fa-check"></i><b>3.12</b> Summary</a></li>
<li class="chapter" data-level="3.13" data-path="wrangling.html"><a href="wrangling.html#exercises-2"><i class="fa fa-check"></i><b>3.13</b> Exercises</a></li>
<li class="chapter" data-level="3.14" data-path="wrangling.html"><a href="wrangling.html#additional-resources-1"><i class="fa fa-check"></i><b>3.14</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="viz.html"><a href="viz.html"><i class="fa fa-check"></i><b>4</b> Effective data visualization</a>
<ul>
<li class="chapter" data-level="4.1" data-path="viz.html"><a href="viz.html#overview-3"><i class="fa fa-check"></i><b>4.1</b> Overview</a></li>
<li class="chapter" data-level="4.2" data-path="viz.html"><a href="viz.html#chapter-learning-objectives-3"><i class="fa fa-check"></i><b>4.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="4.3" data-path="viz.html"><a href="viz.html#choosing-the-visualization"><i class="fa fa-check"></i><b>4.3</b> Choosing the visualization</a></li>
<li class="chapter" data-level="4.4" data-path="viz.html"><a href="viz.html#refining-the-visualization"><i class="fa fa-check"></i><b>4.4</b> Refining the visualization</a></li>
<li class="chapter" data-level="4.5" data-path="viz.html"><a href="viz.html#creating-visualizations-with-ggplot2"><i class="fa fa-check"></i><b>4.5</b> Creating visualizations with <code>ggplot2</code></a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="viz.html"><a href="viz.html#scatter-plots-and-line-plots-the-mauna-loa-co_text2-data-set"><i class="fa fa-check"></i><b>4.5.1</b> Scatter plots and line plots: the Mauna Loa CO<span class="math inline">\(_{\text{2}}\)</span> data set</a></li>
<li class="chapter" data-level="4.5.2" data-path="viz.html"><a href="viz.html#scatter-plots-the-old-faithful-eruption-time-data-set"><i class="fa fa-check"></i><b>4.5.2</b> Scatter plots: the Old Faithful eruption time data set</a></li>
<li class="chapter" data-level="4.5.3" data-path="viz.html"><a href="viz.html#axis-transformation-and-colored-scatter-plots-the-canadian-languages-data-set"><i class="fa fa-check"></i><b>4.5.3</b> Axis transformation and colored scatter plots: the Canadian languages data set</a></li>
<li class="chapter" data-level="4.5.4" data-path="viz.html"><a href="viz.html#bar-plots-the-island-landmass-data-set"><i class="fa fa-check"></i><b>4.5.4</b> Bar plots: the island landmass data set</a></li>
<li class="chapter" data-level="4.5.5" data-path="viz.html"><a href="viz.html#histograms-the-michelson-speed-of-light-data-set"><i class="fa fa-check"></i><b>4.5.5</b> Histograms: the Michelson speed of light data set</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="viz.html"><a href="viz.html#explaining-the-visualization"><i class="fa fa-check"></i><b>4.6</b> Explaining the visualization</a></li>
<li class="chapter" data-level="4.7" data-path="viz.html"><a href="viz.html#saving-the-visualization"><i class="fa fa-check"></i><b>4.7</b> Saving the visualization</a></li>
<li class="chapter" data-level="4.8" data-path="viz.html"><a href="viz.html#exercises-3"><i class="fa fa-check"></i><b>4.8</b> Exercises</a></li>
<li class="chapter" data-level="4.9" data-path="viz.html"><a href="viz.html#additional-resources-2"><i class="fa fa-check"></i><b>4.9</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="classification.html"><a href="classification.html"><i class="fa fa-check"></i><b>5</b> Classification I: training &amp; predicting</a>
<ul>
<li class="chapter" data-level="5.1" data-path="classification.html"><a href="classification.html#overview-4"><i class="fa fa-check"></i><b>5.1</b> Overview</a></li>
<li class="chapter" data-level="5.2" data-path="classification.html"><a href="classification.html#chapter-learning-objectives-4"><i class="fa fa-check"></i><b>5.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="5.3" data-path="classification.html"><a href="classification.html#the-classification-problem"><i class="fa fa-check"></i><b>5.3</b> The classification problem</a></li>
<li class="chapter" data-level="5.4" data-path="classification.html"><a href="classification.html#exploring-a-data-set"><i class="fa fa-check"></i><b>5.4</b> Exploring a data set</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="classification.html"><a href="classification.html#loading-the-cancer-data"><i class="fa fa-check"></i><b>5.4.1</b> Loading the cancer data</a></li>
<li class="chapter" data-level="5.4.2" data-path="classification.html"><a href="classification.html#describing-the-variables-in-the-cancer-data-set"><i class="fa fa-check"></i><b>5.4.2</b> Describing the variables in the cancer data set</a></li>
<li class="chapter" data-level="5.4.3" data-path="classification.html"><a href="classification.html#exploring-the-cancer-data"><i class="fa fa-check"></i><b>5.4.3</b> Exploring the cancer data</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="classification.html"><a href="classification.html#classification-with-k-nearest-neighbors"><i class="fa fa-check"></i><b>5.5</b> Classification with <span class="math inline">\(K\)</span>-nearest neighbors</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="classification.html"><a href="classification.html#distance-between-points"><i class="fa fa-check"></i><b>5.5.1</b> Distance between points</a></li>
<li class="chapter" data-level="5.5.2" data-path="classification.html"><a href="classification.html#more-than-two-explanatory-variables"><i class="fa fa-check"></i><b>5.5.2</b> More than two explanatory variables</a></li>
<li class="chapter" data-level="5.5.3" data-path="classification.html"><a href="classification.html#summary-of-k-nearest-neighbors-algorithm"><i class="fa fa-check"></i><b>5.5.3</b> Summary of <span class="math inline">\(K\)</span>-nearest neighbors algorithm</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="classification.html"><a href="classification.html#k-nearest-neighbors-with-tidymodels"><i class="fa fa-check"></i><b>5.6</b> <span class="math inline">\(K\)</span>-nearest neighbors with <code>tidymodels</code></a></li>
<li class="chapter" data-level="5.7" data-path="classification.html"><a href="classification.html#data-preprocessing-with-tidymodels"><i class="fa fa-check"></i><b>5.7</b> Data preprocessing with <code>tidymodels</code></a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="classification.html"><a href="classification.html#centering-and-scaling"><i class="fa fa-check"></i><b>5.7.1</b> Centering and scaling</a></li>
<li class="chapter" data-level="5.7.2" data-path="classification.html"><a href="classification.html#balancing"><i class="fa fa-check"></i><b>5.7.2</b> Balancing</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="classification.html"><a href="classification.html#puttingittogetherworkflow"><i class="fa fa-check"></i><b>5.8</b> Putting it together in a <code>workflow</code></a></li>
<li class="chapter" data-level="5.9" data-path="classification.html"><a href="classification.html#exercises-4"><i class="fa fa-check"></i><b>5.9</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="classification2.html"><a href="classification2.html"><i class="fa fa-check"></i><b>6</b> Classification II: evaluation &amp; tuning</a>
<ul>
<li class="chapter" data-level="6.1" data-path="classification2.html"><a href="classification2.html#overview-5"><i class="fa fa-check"></i><b>6.1</b> Overview</a></li>
<li class="chapter" data-level="6.2" data-path="classification2.html"><a href="classification2.html#chapter-learning-objectives-5"><i class="fa fa-check"></i><b>6.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="6.3" data-path="classification2.html"><a href="classification2.html#evaluating-accuracy"><i class="fa fa-check"></i><b>6.3</b> Evaluating accuracy</a></li>
<li class="chapter" data-level="6.4" data-path="classification2.html"><a href="classification2.html#randomseeds"><i class="fa fa-check"></i><b>6.4</b> Randomness and seeds</a></li>
<li class="chapter" data-level="6.5" data-path="classification2.html"><a href="classification2.html#evaluating-accuracy-with-tidymodels"><i class="fa fa-check"></i><b>6.5</b> Evaluating accuracy with <code>tidymodels</code></a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="classification2.html"><a href="classification2.html#create-the-train-test-split"><i class="fa fa-check"></i><b>6.5.1</b> Create the train / test split</a></li>
<li class="chapter" data-level="6.5.2" data-path="classification2.html"><a href="classification2.html#preprocess-the-data"><i class="fa fa-check"></i><b>6.5.2</b> Preprocess the data</a></li>
<li class="chapter" data-level="6.5.3" data-path="classification2.html"><a href="classification2.html#train-the-classifier"><i class="fa fa-check"></i><b>6.5.3</b> Train the classifier</a></li>
<li class="chapter" data-level="6.5.4" data-path="classification2.html"><a href="classification2.html#predict-the-labels-in-the-test-set"><i class="fa fa-check"></i><b>6.5.4</b> Predict the labels in the test set</a></li>
<li class="chapter" data-level="6.5.5" data-path="classification2.html"><a href="classification2.html#compute-the-accuracy"><i class="fa fa-check"></i><b>6.5.5</b> Compute the accuracy</a></li>
<li class="chapter" data-level="6.5.6" data-path="classification2.html"><a href="classification2.html#critically-analyze-performance"><i class="fa fa-check"></i><b>6.5.6</b> Critically analyze performance</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="classification2.html"><a href="classification2.html#tuning-the-classifier"><i class="fa fa-check"></i><b>6.6</b> Tuning the classifier</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="classification2.html"><a href="classification2.html#cross-validation"><i class="fa fa-check"></i><b>6.6.1</b> Cross-validation</a></li>
<li class="chapter" data-level="6.6.2" data-path="classification2.html"><a href="classification2.html#parameter-value-selection"><i class="fa fa-check"></i><b>6.6.2</b> Parameter value selection</a></li>
<li class="chapter" data-level="6.6.3" data-path="classification2.html"><a href="classification2.html#underoverfitting"><i class="fa fa-check"></i><b>6.6.3</b> Under/Overfitting</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="classification2.html"><a href="classification2.html#summary-1"><i class="fa fa-check"></i><b>6.7</b> Summary</a></li>
<li class="chapter" data-level="6.8" data-path="classification2.html"><a href="classification2.html#predictor-variable-selection"><i class="fa fa-check"></i><b>6.8</b> Predictor variable selection</a>
<ul>
<li class="chapter" data-level="6.8.1" data-path="classification2.html"><a href="classification2.html#the-effect-of-irrelevant-predictors"><i class="fa fa-check"></i><b>6.8.1</b> The effect of irrelevant predictors</a></li>
<li class="chapter" data-level="6.8.2" data-path="classification2.html"><a href="classification2.html#finding-a-good-subset-of-predictors"><i class="fa fa-check"></i><b>6.8.2</b> Finding a good subset of predictors</a></li>
<li class="chapter" data-level="6.8.3" data-path="classification2.html"><a href="classification2.html#forward-selection-in-r"><i class="fa fa-check"></i><b>6.8.3</b> Forward selection in R</a></li>
</ul></li>
<li class="chapter" data-level="6.9" data-path="classification2.html"><a href="classification2.html#exercises-5"><i class="fa fa-check"></i><b>6.9</b> Exercises</a></li>
<li class="chapter" data-level="6.10" data-path="classification2.html"><a href="classification2.html#additional-resources-3"><i class="fa fa-check"></i><b>6.10</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="regression1.html"><a href="regression1.html"><i class="fa fa-check"></i><b>7</b> Regression I: K-nearest neighbors</a>
<ul>
<li class="chapter" data-level="7.1" data-path="regression1.html"><a href="regression1.html#overview-6"><i class="fa fa-check"></i><b>7.1</b> Overview</a></li>
<li class="chapter" data-level="7.2" data-path="regression1.html"><a href="regression1.html#chapter-learning-objectives-6"><i class="fa fa-check"></i><b>7.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="7.3" data-path="regression1.html"><a href="regression1.html#the-regression-problem"><i class="fa fa-check"></i><b>7.3</b> The regression problem</a></li>
<li class="chapter" data-level="7.4" data-path="regression1.html"><a href="regression1.html#exploring-a-data-set-1"><i class="fa fa-check"></i><b>7.4</b> Exploring a data set</a></li>
<li class="chapter" data-level="7.5" data-path="regression1.html"><a href="regression1.html#k-nearest-neighbors-regression"><i class="fa fa-check"></i><b>7.5</b> K-nearest neighbors regression</a></li>
<li class="chapter" data-level="7.6" data-path="regression1.html"><a href="regression1.html#training-evaluating-and-tuning-the-model"><i class="fa fa-check"></i><b>7.6</b> Training, evaluating, and tuning the model</a></li>
<li class="chapter" data-level="7.7" data-path="regression1.html"><a href="regression1.html#underfitting-and-overfitting"><i class="fa fa-check"></i><b>7.7</b> Underfitting and overfitting</a></li>
<li class="chapter" data-level="7.8" data-path="regression1.html"><a href="regression1.html#evaluating-on-the-test-set"><i class="fa fa-check"></i><b>7.8</b> Evaluating on the test set</a></li>
<li class="chapter" data-level="7.9" data-path="regression1.html"><a href="regression1.html#multivariable-knn-regression"><i class="fa fa-check"></i><b>7.9</b> Multivariable KNN regression</a></li>
<li class="chapter" data-level="7.10" data-path="regression1.html"><a href="regression1.html#strengths-and-limitations-of-knn-regression"><i class="fa fa-check"></i><b>7.10</b> Strengths and limitations of KNN regression</a></li>
<li class="chapter" data-level="7.11" data-path="regression1.html"><a href="regression1.html#exercises-6"><i class="fa fa-check"></i><b>7.11</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="regression2.html"><a href="regression2.html"><i class="fa fa-check"></i><b>8</b> Regression II: linear regression</a>
<ul>
<li class="chapter" data-level="8.1" data-path="regression2.html"><a href="regression2.html#overview-7"><i class="fa fa-check"></i><b>8.1</b> Overview</a></li>
<li class="chapter" data-level="8.2" data-path="regression2.html"><a href="regression2.html#chapter-learning-objectives-7"><i class="fa fa-check"></i><b>8.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="8.3" data-path="regression2.html"><a href="regression2.html#simple-linear-regression"><i class="fa fa-check"></i><b>8.3</b> Simple linear regression</a></li>
<li class="chapter" data-level="8.4" data-path="regression2.html"><a href="regression2.html#linear-regression-in-r"><i class="fa fa-check"></i><b>8.4</b> Linear regression in R</a></li>
<li class="chapter" data-level="8.5" data-path="regression2.html"><a href="regression2.html#comparing-simple-linear-and-knn-regression"><i class="fa fa-check"></i><b>8.5</b> Comparing simple linear and KNN regression</a></li>
<li class="chapter" data-level="8.6" data-path="regression2.html"><a href="regression2.html#multivariable-linear-regression"><i class="fa fa-check"></i><b>8.6</b> Multivariable linear regression</a></li>
<li class="chapter" data-level="8.7" data-path="regression2.html"><a href="regression2.html#multicollinearity-and-outliers"><i class="fa fa-check"></i><b>8.7</b> Multicollinearity and outliers</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="regression2.html"><a href="regression2.html#outliers"><i class="fa fa-check"></i><b>8.7.1</b> Outliers</a></li>
<li class="chapter" data-level="8.7.2" data-path="regression2.html"><a href="regression2.html#multicollinearity"><i class="fa fa-check"></i><b>8.7.2</b> Multicollinearity</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="regression2.html"><a href="regression2.html#designing-new-predictors"><i class="fa fa-check"></i><b>8.8</b> Designing new predictors</a></li>
<li class="chapter" data-level="8.9" data-path="regression2.html"><a href="regression2.html#the-other-sides-of-regression"><i class="fa fa-check"></i><b>8.9</b> The other sides of regression</a></li>
<li class="chapter" data-level="8.10" data-path="regression2.html"><a href="regression2.html#exercises-7"><i class="fa fa-check"></i><b>8.10</b> Exercises</a></li>
<li class="chapter" data-level="8.11" data-path="regression2.html"><a href="regression2.html#additional-resources-4"><i class="fa fa-check"></i><b>8.11</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="clustering.html"><a href="clustering.html"><i class="fa fa-check"></i><b>9</b> Clustering</a>
<ul>
<li class="chapter" data-level="9.1" data-path="clustering.html"><a href="clustering.html#overview-8"><i class="fa fa-check"></i><b>9.1</b> Overview</a></li>
<li class="chapter" data-level="9.2" data-path="clustering.html"><a href="clustering.html#chapter-learning-objectives-8"><i class="fa fa-check"></i><b>9.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="9.3" data-path="clustering.html"><a href="clustering.html#clustering-1"><i class="fa fa-check"></i><b>9.3</b> Clustering</a></li>
<li class="chapter" data-level="9.4" data-path="clustering.html"><a href="clustering.html#k-means"><i class="fa fa-check"></i><b>9.4</b> K-means</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="clustering.html"><a href="clustering.html#measuring-cluster-quality"><i class="fa fa-check"></i><b>9.4.1</b> Measuring cluster quality</a></li>
<li class="chapter" data-level="9.4.2" data-path="clustering.html"><a href="clustering.html#the-clustering-algorithm"><i class="fa fa-check"></i><b>9.4.2</b> The clustering algorithm</a></li>
<li class="chapter" data-level="9.4.3" data-path="clustering.html"><a href="clustering.html#random-restarts"><i class="fa fa-check"></i><b>9.4.3</b> Random restarts</a></li>
<li class="chapter" data-level="9.4.4" data-path="clustering.html"><a href="clustering.html#choosing-k"><i class="fa fa-check"></i><b>9.4.4</b> Choosing K</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="clustering.html"><a href="clustering.html#data-pre-processing-for-k-means"><i class="fa fa-check"></i><b>9.5</b> Data pre-processing for K-means</a></li>
<li class="chapter" data-level="9.6" data-path="clustering.html"><a href="clustering.html#k-means-in-r"><i class="fa fa-check"></i><b>9.6</b> K-means in R</a></li>
<li class="chapter" data-level="9.7" data-path="clustering.html"><a href="clustering.html#exercises-8"><i class="fa fa-check"></i><b>9.7</b> Exercises</a></li>
<li class="chapter" data-level="9.8" data-path="clustering.html"><a href="clustering.html#additional-resources-5"><i class="fa fa-check"></i><b>9.8</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="inference.html"><a href="inference.html"><i class="fa fa-check"></i><b>10</b> Statistical inference</a>
<ul>
<li class="chapter" data-level="10.1" data-path="inference.html"><a href="inference.html#overview-9"><i class="fa fa-check"></i><b>10.1</b> Overview</a></li>
<li class="chapter" data-level="10.2" data-path="inference.html"><a href="inference.html#chapter-learning-objectives-9"><i class="fa fa-check"></i><b>10.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="10.3" data-path="inference.html"><a href="inference.html#why-do-we-need-sampling"><i class="fa fa-check"></i><b>10.3</b> Why do we need sampling?</a></li>
<li class="chapter" data-level="10.4" data-path="inference.html"><a href="inference.html#sampling-distributions"><i class="fa fa-check"></i><b>10.4</b> Sampling distributions</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="inference.html"><a href="inference.html#sampling-distributions-for-proportions"><i class="fa fa-check"></i><b>10.4.1</b> Sampling distributions for proportions</a></li>
<li class="chapter" data-level="10.4.2" data-path="inference.html"><a href="inference.html#sampling-distributions-for-means"><i class="fa fa-check"></i><b>10.4.2</b> Sampling distributions for means</a></li>
<li class="chapter" data-level="10.4.3" data-path="inference.html"><a href="inference.html#summary-2"><i class="fa fa-check"></i><b>10.4.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="inference.html"><a href="inference.html#bootstrapping"><i class="fa fa-check"></i><b>10.5</b> Bootstrapping</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="inference.html"><a href="inference.html#overview-10"><i class="fa fa-check"></i><b>10.5.1</b> Overview</a></li>
<li class="chapter" data-level="10.5.2" data-path="inference.html"><a href="inference.html#bootstrapping-in-r"><i class="fa fa-check"></i><b>10.5.2</b> Bootstrapping in R</a></li>
<li class="chapter" data-level="10.5.3" data-path="inference.html"><a href="inference.html#using-the-bootstrap-to-calculate-a-plausible-range"><i class="fa fa-check"></i><b>10.5.3</b> Using the bootstrap to calculate a plausible range</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="inference.html"><a href="inference.html#exercises-9"><i class="fa fa-check"></i><b>10.6</b> Exercises</a></li>
<li class="chapter" data-level="10.7" data-path="inference.html"><a href="inference.html#additional-resources-6"><i class="fa fa-check"></i><b>10.7</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html"><i class="fa fa-check"></i><b>11</b> Combining code and text with Jupyter</a>
<ul>
<li class="chapter" data-level="11.1" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#overview-11"><i class="fa fa-check"></i><b>11.1</b> Overview</a></li>
<li class="chapter" data-level="11.2" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#chapter-learning-objectives-10"><i class="fa fa-check"></i><b>11.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="11.3" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#jupyter"><i class="fa fa-check"></i><b>11.3</b> Jupyter</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#accessing-jupyter"><i class="fa fa-check"></i><b>11.3.1</b> Accessing Jupyter</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#code-cells"><i class="fa fa-check"></i><b>11.4</b> Code cells</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#executing-code-cells"><i class="fa fa-check"></i><b>11.4.1</b> Executing code cells</a></li>
<li class="chapter" data-level="11.4.2" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#the-kernel"><i class="fa fa-check"></i><b>11.4.2</b> The Kernel</a></li>
<li class="chapter" data-level="11.4.3" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#creating-new-code-cells"><i class="fa fa-check"></i><b>11.4.3</b> Creating new code cells</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#markdown-cells"><i class="fa fa-check"></i><b>11.5</b> Markdown cells</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#editing-markdown-cells"><i class="fa fa-check"></i><b>11.5.1</b> Editing Markdown cells</a></li>
<li class="chapter" data-level="11.5.2" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#creating-new-markdown-cells"><i class="fa fa-check"></i><b>11.5.2</b> Creating new Markdown cells</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#saving-your-work"><i class="fa fa-check"></i><b>11.6</b> Saving your work</a></li>
<li class="chapter" data-level="11.7" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#best-practices-for-running-a-notebook"><i class="fa fa-check"></i><b>11.7</b> Best practices for running a notebook</a>
<ul>
<li class="chapter" data-level="11.7.1" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#best-practices-for-executing-code-cells"><i class="fa fa-check"></i><b>11.7.1</b> Best practices for executing code cells</a></li>
<li class="chapter" data-level="11.7.2" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#best-practices-for-including-r-packages-in-notebooks"><i class="fa fa-check"></i><b>11.7.2</b> Best practices for including R packages in notebooks</a></li>
<li class="chapter" data-level="11.7.3" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#summary-of-best-practices-for-running-a-notebook"><i class="fa fa-check"></i><b>11.7.3</b> Summary of best practices for running a notebook</a></li>
</ul></li>
<li class="chapter" data-level="11.8" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#exploring-data-files"><i class="fa fa-check"></i><b>11.8</b> Exploring data files</a></li>
<li class="chapter" data-level="11.9" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#exporting-to-a-different-file-format"><i class="fa fa-check"></i><b>11.9</b> Exporting to a different file format</a>
<ul>
<li class="chapter" data-level="11.9.1" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#exporting-to-html"><i class="fa fa-check"></i><b>11.9.1</b> Exporting to HTML</a></li>
<li class="chapter" data-level="11.9.2" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#exporting-to-pdf"><i class="fa fa-check"></i><b>11.9.2</b> Exporting to PDF</a></li>
</ul></li>
<li class="chapter" data-level="11.10" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#creating-a-new-jupyter-notebook"><i class="fa fa-check"></i><b>11.10</b> Creating a new Jupyter notebook</a></li>
<li class="chapter" data-level="11.11" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#additional-resources-7"><i class="fa fa-check"></i><b>11.11</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html"><i class="fa fa-check"></i><b>12</b> Collaboration with version control</a>
<ul>
<li class="chapter" data-level="12.1" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#overview-12"><i class="fa fa-check"></i><b>12.1</b> Overview</a></li>
<li class="chapter" data-level="12.2" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#chapter-learning-objectives-11"><i class="fa fa-check"></i><b>12.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="12.3" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#what-is-version-control-and-why-should-i-use-it"><i class="fa fa-check"></i><b>12.3</b> What is version control, and why should I use it?</a></li>
<li class="chapter" data-level="12.4" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#version-control-repositories"><i class="fa fa-check"></i><b>12.4</b> Version control repositories</a></li>
<li class="chapter" data-level="12.5" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#version-control-workflows"><i class="fa fa-check"></i><b>12.5</b> Version control workflows</a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#commit-changes"><i class="fa fa-check"></i><b>12.5.1</b> Committing changes to a local repository</a></li>
<li class="chapter" data-level="12.5.2" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#pushing-changes-to-a-remote-repository"><i class="fa fa-check"></i><b>12.5.2</b> Pushing changes to a remote repository</a></li>
<li class="chapter" data-level="12.5.3" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#pulling-changes-from-a-remote-repository"><i class="fa fa-check"></i><b>12.5.3</b> Pulling changes from a remote repository</a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#working-with-remote-repositories-using-github"><i class="fa fa-check"></i><b>12.6</b> Working with remote repositories using GitHub</a>
<ul>
<li class="chapter" data-level="12.6.1" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#creating-a-remote-repository-on-github"><i class="fa fa-check"></i><b>12.6.1</b> Creating a remote repository on GitHub</a></li>
<li class="chapter" data-level="12.6.2" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#editing-files-on-github-with-the-pen-tool"><i class="fa fa-check"></i><b>12.6.2</b> Editing files on GitHub with the pen tool</a></li>
<li class="chapter" data-level="12.6.3" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#creating-files-on-github-with-the-add-file-menu"><i class="fa fa-check"></i><b>12.6.3</b> Creating files on GitHub with the “Add file” menu</a></li>
</ul></li>
<li class="chapter" data-level="12.7" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#local-repo-jupyter"><i class="fa fa-check"></i><b>12.7</b> Working with local repositories using Jupyter</a>
<ul>
<li class="chapter" data-level="12.7.1" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#generating-a-github-personal-access-token"><i class="fa fa-check"></i><b>12.7.1</b> Generating a GitHub personal access token</a></li>
<li class="chapter" data-level="12.7.2" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#cloning-a-repository-using-jupyter"><i class="fa fa-check"></i><b>12.7.2</b> Cloning a repository using Jupyter</a></li>
<li class="chapter" data-level="12.7.3" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#specifying-files-to-commit"><i class="fa fa-check"></i><b>12.7.3</b> Specifying files to commit</a></li>
<li class="chapter" data-level="12.7.4" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#making-the-commit"><i class="fa fa-check"></i><b>12.7.4</b> Making the commit</a></li>
<li class="chapter" data-level="12.7.5" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#pushing-the-commits-to-github"><i class="fa fa-check"></i><b>12.7.5</b> Pushing the commits to GitHub</a></li>
</ul></li>
<li class="chapter" data-level="12.8" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#collaboration"><i class="fa fa-check"></i><b>12.8</b> Collaboration</a>
<ul>
<li class="chapter" data-level="12.8.1" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#giving-collaborators-access-to-your-project"><i class="fa fa-check"></i><b>12.8.1</b> Giving collaborators access to your project</a></li>
<li class="chapter" data-level="12.8.2" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#pulling-changes-from-github-using-jupyter"><i class="fa fa-check"></i><b>12.8.2</b> Pulling changes from GitHub using Jupyter</a></li>
<li class="chapter" data-level="12.8.3" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#handling-merge-conflicts"><i class="fa fa-check"></i><b>12.8.3</b> Handling merge conflicts</a></li>
<li class="chapter" data-level="12.8.4" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#communicating-using-github-issues"><i class="fa fa-check"></i><b>12.8.4</b> Communicating using GitHub issues</a></li>
</ul></li>
<li class="chapter" data-level="12.9" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#exercises-10"><i class="fa fa-check"></i><b>12.9</b> Exercises</a></li>
<li class="chapter" data-level="12.10" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#vc-add-res"><i class="fa fa-check"></i><b>12.10</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html"><i class="fa fa-check"></i><b>13</b> Setting up your computer</a>
<ul>
<li class="chapter" data-level="13.1" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#overview-13"><i class="fa fa-check"></i><b>13.1</b> Overview</a></li>
<li class="chapter" data-level="13.2" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#chapter-learning-objectives-12"><i class="fa fa-check"></i><b>13.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="13.3" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#installing-software-on-your-own-computer"><i class="fa fa-check"></i><b>13.3</b> Installing software on your own computer</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#git"><i class="fa fa-check"></i><b>13.3.1</b> Git</a></li>
<li class="chapter" data-level="13.3.2" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#miniconda"><i class="fa fa-check"></i><b>13.3.2</b> Miniconda</a></li>
<li class="chapter" data-level="13.3.3" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#jupyterlab"><i class="fa fa-check"></i><b>13.3.3</b> JupyterLab</a></li>
<li class="chapter" data-level="13.3.4" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#r-r-packages-and-the-irkernel"><i class="fa fa-check"></i><b>13.3.4</b> R, R packages, and the IRkernel</a></li>
<li class="chapter" data-level="13.3.5" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#latex"><i class="fa fa-check"></i><b>13.3.5</b> LaTeX</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#finishing-up-installation"><i class="fa fa-check"></i><b>13.4</b> Finishing up installation</a></li>
<li class="chapter" data-level="13.5" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#downloading-the-worksheets-for-this-book"><i class="fa fa-check"></i><b>13.5</b> Downloading the worksheets for this book</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="appendixA.html"><a href="appendixA.html"><i class="fa fa-check"></i><b>A</b> Downloading files from JupyterHub</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Science: A First Introduction</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="viz" class="section level1" number="4">
<h1><span class="header-section-number">Chapter 4</span> Effective data visualization</h1>
<div id="overview-3" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Overview</h2>
<p>This chapter will introduce concepts and tools relating to data visualization
beyond what we have seen and practiced so far. We will focus on guiding
principles for effective data visualization and explaining visualizations
independent of any particular tool or programming language. In the process, we
will cover some specifics of creating visualizations (scatter plots, bar
plots, line plots, and histograms) for data using R.</p>
</div>
<div id="chapter-learning-objectives-3" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> Chapter learning objectives</h2>
<p>By the end of the chapter, readers will be able to do the following:</p>
<ul>
<li>Describe when to use the following kinds of visualizations to answer specific questions using a data set:
<ul>
<li>scatter plots</li>
<li>line plots</li>
<li>bar plots</li>
<li>histogram plots</li>
</ul></li>
<li>Given a data set and a question, select from the above plot types and use R to create a visualization that best answers the question.</li>
<li>Given a visualization and a question, evaluate the effectiveness of the visualization and suggest improvements to better answer the question.</li>
<li>Referring to the visualization, communicate the conclusions in non-technical terms.</li>
<li>Identify rules of thumb for creating effective visualizations.</li>
<li>Define the three key aspects of ggplot objects:
<ul>
<li>aesthetic mappings</li>
<li>geometric objects</li>
<li>scales</li>
</ul></li>
<li>Use the <code>ggplot2</code> package in R to create and refine the above visualizations using:
<ul>
<li>geometric objects: <code>geom_point</code>, <code>geom_line</code>, <code>geom_histogram</code>, <code>geom_bar</code>, <code>geom_vline</code>, <code>geom_hline</code></li>
<li>scales: <code>xlim</code>, <code>ylim</code></li>
<li>aesthetic mappings: <code>x</code>, <code>y</code>, <code>fill</code>, <code>color</code>, <code>shape</code></li>
<li>labeling: <code>xlab</code>, <code>ylab</code>, <code>labs</code></li>
<li>font control and legend positioning: <code>theme</code></li>
<li>subplots: <code>facet_grid</code></li>
</ul></li>
<li>Describe the difference in raster and vector output formats.</li>
<li>Use <code>ggsave</code> to save visualizations in <code>.png</code> and <code>.svg</code> format.</li>
</ul>
</div>
<div id="choosing-the-visualization" class="section level2" number="4.3">
<h2><span class="header-section-number">4.3</span> Choosing the visualization</h2>
<div id="ask-a-question-and-answer-it" class="section level4 unnumbered">
<h4><em>Ask a question, and answer it</em></h4>
<p>The purpose of a visualization is to answer a question
 about a data set of interest. So naturally, the
first thing to do <strong>before</strong> creating a visualization is to formulate the
question about the data you are trying to answer. A good visualization will
clearly answer your question without distraction; a <em>great</em> visualization will
suggest even what the question was itself without additional explanation.
Imagine your visualization as part of a poster presentation for a project; even
if you aren’t standing at the poster explaining things, an effective
visualization will convey your message to the audience.</p>
<p>Recall the different data analysis questions
from Chapter <a href="intro.html#intro">1</a>.
With the visualizations we will cover in this chapter,
we will be able to answer <em>only descriptive and exploratory</em> questions.
Be careful to not answer any <em>predictive, inferential, causal</em>
<em>or mechanistic</em> questions with the visualizations presented here,
as we have not learned the tools necessary to do that properly just yet.</p>
<p>As with most coding tasks, it is totally fine (and quite common) to make
mistakes and iterate a few times before you find the right visualization for
your data and question. There are many different kinds of plotting
graphics available to use (see Chapter 5 of <em>Fundamentals of Data Visualization</em> <span class="citation">(<a href="#ref-wilkeviz" role="doc-biblioref">Wilke 2019</a>)</span> for a directory).
The types of plot that we introduce in this book are shown in Figure <a href="viz.html#fig:plot-sketches">4.1</a>;
which one you should select depends on your data
and the question you want to answer.
In general, the guiding principles of when to use each type of plot
are as follows:</p>
<p>


</p>
<ul>
<li><strong>scatter plots</strong> visualize the relationship between two quantitative variables</li>
<li><strong>line plots</strong> visualize trends with respect to an independent, ordered quantity (e.g., time)</li>
<li><strong>bar plots</strong> visualize comparisons of amounts</li>
<li><strong>histograms</strong> visualize the distribution of one quantitative variable (i.e., all its possible values and how often they occur) </li>
</ul>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:plot-sketches"></span>
<img src="_main_files/figure-html/plot-sketches-1.png" alt="Examples of scatter, line and bar plots, as well as histograms." width="432" />
<p class="caption">
Figure 4.1: Examples of scatter, line and bar plots, as well as histograms.
</p>
</div>
<p>All types of visualization have their (mis)uses, but three kinds are usually
hard to understand or are easily replaced with an oft-better alternative. In
particular, you should avoid <strong>pie charts</strong>; it is generally better to use
bars, as it is easier to compare bar heights than pie slice sizes. You should
also not use <strong>3-D visualizations</strong>, as they are typically hard to understand
when converted to a static 2-D image format. Finally, do not use tables to make
numerical comparisons; humans are much better at quickly processing visual
information than text and math. Bar plots are again typically a better
alternative.</p>
</div>
</div>
<div id="refining-the-visualization" class="section level2" number="4.4">
<h2><span class="header-section-number">4.4</span> Refining the visualization</h2>
<div id="convey-the-message-minimize-noise" class="section level4 unnumbered">
<h4><em>Convey the message, minimize noise</em></h4>
<p>Just being able to make a visualization in R with <code>ggplot2</code> (or any other tool
for that matter) doesn’t mean that it effectively communicates your message to
others. Once you have selected a broad type of visualization to use, you will
have to refine it to suit your particular need. Some rules of thumb for doing
this are listed below. They generally fall into two classes: you want to
<em>make your visualization convey your message</em>, and you want to <em>reduce visual noise</em>
as much as possible. Humans have limited cognitive ability to process
information; both of these types of refinement aim to reduce the mental load on
your audience when viewing your visualization, making it easier for them to
understand and remember your message quickly.</p>
<p><strong>Convey the message</strong></p>
<ul>
<li>Make sure the visualization answers the question you have asked most simply and plainly as possible.</li>
<li>Use legends and labels so that your visualization is understandable without reading the surrounding text.</li>
<li>Ensure the text, symbols, lines, etc., on your visualization are big enough to be easily read.</li>
<li>Ensure the data are clearly visible; don’t hide the shape/distribution of the data behind other objects (e.g., a bar).</li>
<li>Make sure to use color schemes that are understandable by those with
colorblindness (a surprisingly large fraction of the overall
population—from about 1% to 10%, depending on sex and ancestry <span class="citation">(<a href="#ref-deebblind" role="doc-biblioref">Deeb 2005</a>)</span>).
For example, <a href="https://colorbrewer2.org">ColorBrewer</a>
and <a href="https://cran.r-project.org/web/packages/RColorBrewer/index.html">the <code>RColorBrewer</code> R package</a> <span class="citation">(<a href="#ref-RColorBrewer" role="doc-biblioref">Neuwirth 2014</a>)</span><br />
provide the ability to pick such color schemes, and you can check
your visualizations after you have created them by uploading to online tools
such as a <a href="https://www.color-blindness.com/coblis-color-blindness-simulator/">color blindness simulator</a>.</li>
<li>Redundancy can be helpful; sometimes conveying the same message in multiple ways reinforces it for the audience.</li>
</ul>
<p><strong>Minimize noise</strong></p>
<ul>
<li>Use colors sparingly. Too many different colors can be distracting, create false patterns, and detract from the message.</li>
<li>Be wary of overplotting. Overplotting is when marks that represent the data
overlap, and is problematic as it prevents you from seeing how many data
points are represented in areas of the visualization where this occurs. If your
plot has too many dots or lines and starts to look like a mess, you need to do
something different.</li>
<li>Only make the plot area (where the dots, lines, bars are) as big as needed. Simple plots can be made small.</li>
<li>Don’t adjust the axes to zoom in on small differences. If the difference is small, show that it’s small!</li>
</ul>
</div>
</div>
<div id="creating-visualizations-with-ggplot2" class="section level2" number="4.5">
<h2><span class="header-section-number">4.5</span> Creating visualizations with <code>ggplot2</code></h2>
<div id="build-the-visualization-iteratively" class="section level4 unnumbered">
<h4><em>Build the visualization iteratively</em></h4>
<p>This section will cover examples of how to choose and refine a visualization given a data set and a question that you want to answer,
and then how to create the visualization in R  using <code>ggplot2</code>. To use the <code>ggplot2</code> package, we need to load the <code>tidyverse</code> metapackage.</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="viz.html#cb214-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
</div>
<div id="scatter-plots-and-line-plots-the-mauna-loa-co_text2-data-set" class="section level3" number="4.5.1">
<h3><span class="header-section-number">4.5.1</span> Scatter plots and line plots: the Mauna Loa CO<span class="math inline">\(_{\text{2}}\)</span> data set</h3>
<p>The <a href="https://www.esrl.noaa.gov/gmd/ccgg/trends/data.html">Mauna Loa CO<span class="math inline">\(_{\text{2}}\)</span> data set</a>,
curated by Dr. Pieter Tans, NOAA/GML
and Dr. Ralph Keeling, Scripps Institution of Oceanography,
records the atmospheric concentration of carbon dioxide
(CO<span class="math inline">\(_{\text{2}}\)</span>, in parts per million)
at the Mauna Loa research station in  Hawaii
from 1959 onward <span class="citation">(<a href="#ref-maunadata" role="doc-biblioref">Tans and Keeling 2020</a>)</span>.
For this book, we are going to focus on the last 40 years of the data set,
1980-2020.</p>
<p><strong>Question:</strong> 
Does the concentration of atmospheric CO<span class="math inline">\(_{\text{2}}\)</span> change over time,
and are there any interesting patterns to note?</p>
<p>To get started, we will read and inspect the data:</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="viz.html#cb215-1" aria-hidden="true" tabindex="-1"></a><span class="co"># mauna loa carbon dioxide data</span></span>
<span id="cb215-2"><a href="viz.html#cb215-2" aria-hidden="true" tabindex="-1"></a>co2_df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/mauna_loa_data.csv&quot;</span>)</span>
<span id="cb215-3"><a href="viz.html#cb215-3" aria-hidden="true" tabindex="-1"></a>co2_df</span></code></pre></div>
<pre><code>## # A tibble: 484 × 2
##    date_measured   ppm
##    &lt;date&gt;        &lt;dbl&gt;
##  1 1980-02-01     338.
##  2 1980-03-01     340.
##  3 1980-04-01     341.
##  4 1980-05-01     341.
##  5 1980-06-01     341.
##  6 1980-07-01     339.
##  7 1980-08-01     338.
##  8 1980-09-01     336.
##  9 1980-10-01     336.
## 10 1980-11-01     337.
## # … with 474 more rows</code></pre>
<p>We see that there are two columns in the <code>co2_df</code> data frame; <code>date_measured</code> and <code>ppm</code>.
The <code>date_measured</code> column holds the date the measurement was taken,
and is of type <code>date</code>.
The <code>ppm</code> column holds the value of CO<span class="math inline">\(_{\text{2}}\)</span> in parts per million
that was measured on each date, and is type <code>double</code>.</p>
<blockquote>
<p><strong>Note:</strong> <code>read_csv</code> was able to parse the <code>date_measured</code> column into the
<code>date</code> vector type because it was entered
in the international standard date format,
called ISO 8601, which lists dates as <code>year-month-day</code>.
<code>date</code> vectors are <code>double</code> vectors with special properties that allow
them to handle dates correctly.
For example, <code>date</code> type vectors allow functions like <code>ggplot</code>
to treat them as numeric dates and not as character vectors,
even though they contain non-numeric characters
(e.g., in the <code>date_measured</code> column in the <code>co2_df</code> data frame).
This means R will not accidentally plot the dates in the wrong order
(i.e., not alphanumerically as would happen if it was a character vector).
An in-depth study of dates and times is beyond the scope of the book,
but interested readers
may consult the Dates and Times chapter of <em>R for Data Science</em> <span class="citation">(<a href="#ref-wickham2016r" role="doc-biblioref">Wickham and Grolemund 2016</a>)</span>;
see the additional resources at the end of this chapter.</p>
</blockquote>
<p>Since we are investigating a relationship between two variables
(CO<span class="math inline">\(_{\text{2}}\)</span> concentration and date),
a scatter plot is a good place to start.
Scatter plots show the data as individual points with <code>x</code> (horizontal axis)
and <code>y</code> (vertical axis) coordinates.
Here, we will use the measurement date as the <code>x</code> coordinate
and the CO<span class="math inline">\(_{\text{2}}\)</span> concentration as the <code>y</code> coordinate.
When using the <code>ggplot2</code> package,
we create a plot object with the <code>ggplot</code> function.
There are a few basic aspects of a plot that we need to specify:

</p>
<ul>
<li>The name of the data frame object to visualize.
<ul>
<li>Here, we specify the <code>co2_df</code> data frame.</li>
</ul></li>
<li>The <strong>aesthetic mapping</strong>, which tells  <code>ggplot</code> how the columns in the data frame map to properties of the visualization.
<ul>
<li>To create an aesthetic mapping, we use the <code>aes</code> function.</li>
<li>Here, we set the plot <code>x</code> axis to the <code>date_measured</code> variable, and the plot <code>y</code> axis to the <code>ppm</code> variable.</li>
</ul></li>
<li>The <code>+</code> operator, which tells <code>ggplot</code> that we would like to add another layer to the plot.</li>
<li>The <strong>geometric object</strong>, which specifies  how the mapped data should be displayed.
<ul>
<li>To create a geometric object, we use a <code>geom_*</code> function (see the <a href="https://ggplot2.tidyverse.org/reference/">ggplot reference</a> for a list of geometric objects).</li>
<li>Here, we use the <code>geom_point</code> function to visualize our data as a scatter plot.</li>
</ul></li>
</ul>
<p>Figure <a href="viz.html#fig:03-ggplot-function-scatter">4.2</a>
shows how each of these aspects map to code
for creating a basic scatter plot of the <code>co2_df</code> data.
Note that we could pass many other possible arguments to the aesthetic mapping
and geometric object to change how the plot looks. For the purposes of quickly
testing things out to see what they look like, though, we can just start with the
default settings.

</p>

<div class="figure" style="text-align: center"><span style="display:block;" id="fig:03-ggplot-function-scatter"></span>
<img src="_main_files/figure-html/03-ggplot-function-scatter-1.png" alt="Creating a scatter plot with the ggplot function." width="100%" />
<p class="caption">
Figure 4.2: Creating a scatter plot with the <code>ggplot</code> function.
</p>
</div>
<div style="page-break-after: always;"></div>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="viz.html#cb217-1" aria-hidden="true" tabindex="-1"></a>co2_scatter <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(co2_df, <span class="fu">aes</span>(<span class="at">x =</span> date_measured, <span class="at">y =</span> ppm)) <span class="sc">+</span></span>
<span id="cb217-2"><a href="viz.html#cb217-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span>
<span id="cb217-3"><a href="viz.html#cb217-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb217-4"><a href="viz.html#cb217-4" aria-hidden="true" tabindex="-1"></a>co2_scatter</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:03-data-co2-scatter"></span>
<img src="_main_files/figure-html/03-data-co2-scatter-1.png" alt="Scatter plot of atmospheric concentration of CO$_{2}$ over time." width="432" />
<p class="caption">
Figure 4.3: Scatter plot of atmospheric concentration of CO<span class="math inline">\(_{2}\)</span> over time.
</p>
</div>
<p>Certainly, the visualization in Figure <a href="viz.html#fig:03-data-co2-scatter">4.3</a>
shows a clear upward trend
in the atmospheric concentration of CO<span class="math inline">\(_{\text{2}}\)</span> over time.
This plot answers the first part of our question in the affirmative,
but that appears to be the only conclusion one can make
from the scatter visualization.</p>
<p>One important thing to note about this data is that one of the variables
we are exploring is time.
Time is a special kind of quantitative variable
because it forces additional structure on the data—the
data points have a natural order.
Specifically, each observation in the data set has a predecessor
and a successor, and the order of the observations matters; changing their order
alters their meaning.
In situations like this, we typically use a line plot to visualize
the data. Line plots connect the sequence of <code>x</code> and <code>y</code> coordinates
of the observations with line segments, thereby emphasizing their order.</p>
<p>We can create a line plot in <code>ggplot</code> using the <code>geom_line</code> function.
Let’s now try to visualize the <code>co2_df</code> as a line plot
with just the default arguments:
</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="viz.html#cb218-1" aria-hidden="true" tabindex="-1"></a>co2_line <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(co2_df, <span class="fu">aes</span>(<span class="at">x =</span> date_measured, <span class="at">y =</span> ppm)) <span class="sc">+</span></span>
<span id="cb218-2"><a href="viz.html#cb218-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()</span>
<span id="cb218-3"><a href="viz.html#cb218-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb218-4"><a href="viz.html#cb218-4" aria-hidden="true" tabindex="-1"></a>co2_line</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:03-data-co2-line"></span>
<img src="_main_files/figure-html/03-data-co2-line-1.png" alt="Line plot of atmospheric concentration of CO$_{2}$ over time." width="432" />
<p class="caption">
Figure 4.4: Line plot of atmospheric concentration of CO<span class="math inline">\(_{2}\)</span> over time.
</p>
</div>
<p>Aha! Figure <a href="viz.html#fig:03-data-co2-line">4.4</a> shows us there <em>is</em> another interesting
phenomenon in the data: in addition to increasing over time, the concentration
seems to oscillate as well. Given the visualization as it is now, it is still
hard to tell how fast the oscillation is, but nevertheless, the line seems to
be a better choice for answering the question than the scatter plot was. The
comparison between these two visualizations also illustrates a common issue with
scatter plots: often, the points are shown too close together or even on top of
one another, muddling information that would otherwise be clear
(<em>overplotting</em>). </p>
<p>Now that we have settled on the rough details of the visualization, it is time
to refine things. This plot is fairly straightforward, and there is not much
visual noise to remove. But there are a few things we must do to improve
clarity, such as adding informative axis labels and making the font a more
readable size. To add axis labels, we use the <code>xlab</code> and <code>ylab</code> functions. To
change the font size, we use the <code>theme</code> function with the <code>text</code> argument:

</p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="viz.html#cb219-1" aria-hidden="true" tabindex="-1"></a>co2_line <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(co2_df, <span class="fu">aes</span>(<span class="at">x =</span> date_measured, <span class="at">y =</span> ppm)) <span class="sc">+</span></span>
<span id="cb219-2"><a href="viz.html#cb219-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb219-3"><a href="viz.html#cb219-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Year&quot;</span>) <span class="sc">+</span></span>
<span id="cb219-4"><a href="viz.html#cb219-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Atmospheric CO2 (ppm)&quot;</span>) <span class="sc">+</span></span>
<span id="cb219-5"><a href="viz.html#cb219-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>))</span>
<span id="cb219-6"><a href="viz.html#cb219-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb219-7"><a href="viz.html#cb219-7" aria-hidden="true" tabindex="-1"></a>co2_line</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:03-data-co2-line-2"></span>
<img src="_main_files/figure-html/03-data-co2-line-2-1.png" alt="Line plot of atmospheric concentration of CO$_{2}$ over time with clearer axes and labels." width="432" />
<p class="caption">
Figure 4.5: Line plot of atmospheric concentration of CO<span class="math inline">\(_{2}\)</span> over time with clearer axes and labels.
</p>
</div>
<blockquote>
<p><strong>Note:</strong> The <code>theme</code> function is quite complex and has many arguments
that can be specified to control many non-data aspects of a visualization.
An in-depth discussion of the <code>theme</code> function is beyond the scope of this book.
Interested readers may consult the <code>theme</code> function documentation;
see the additional resources section at the end of this chapter.</p>
</blockquote>
<p>Finally, let’s see if we can better understand the oscillation by changing the
visualization slightly. Note that it is totally fine to use a small number of
visualizations to answer different aspects of the question you are trying to
answer. We will accomplish this by using <em>scales</em>, 
another important feature of <code>ggplot2</code> that easily transforms the different
variables and set limits. We scale the horizontal axis using the <code>xlim</code> function,
and the vertical axis with the <code>ylim</code> function.
In particular, here, we will use the <code>xlim</code> function to zoom in
on just five years of data (say, 1990-1994).
<code>xlim</code> takes a vector of length two
to specify the upper and lower bounds to limit the axis.
We can create that using the <code>c</code> function.
Note that it is important that the vector given to <code>xlim</code> must be of the same
type as the data that is mapped to that axis.
Here, we have mapped a date to the x-axis,
and so we need to use the <code>date</code> function
(from the <code>tidyverse</code> <a href="https://lubridate.tidyverse.org/"><code>lubridate</code> R package</a> <span class="citation">(<a href="#ref-lubridate" role="doc-biblioref">Spinu, Grolemund, and Wickham 2021</a>; <a href="#ref-lubridatepaper" role="doc-biblioref">Grolemund and Wickham 2011</a>)</span>)
to convert the character strings we provide to <code>c</code> to <code>date</code> vectors.</p>
<blockquote>
<p><strong>Note:</strong> <code>lubridate</code> is a package that is installed by the <code>tidyverse</code> metapackage,
but is not loaded by it.
Hence we need to load it separately in the code below.</p>
</blockquote>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="viz.html#cb220-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb220-2"><a href="viz.html#cb220-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb220-3"><a href="viz.html#cb220-3" aria-hidden="true" tabindex="-1"></a>co2_line <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(co2_df, <span class="fu">aes</span>(<span class="at">x =</span> date_measured, <span class="at">y =</span> ppm)) <span class="sc">+</span></span>
<span id="cb220-4"><a href="viz.html#cb220-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb220-5"><a href="viz.html#cb220-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Year&quot;</span>) <span class="sc">+</span></span>
<span id="cb220-6"><a href="viz.html#cb220-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Atmospheric CO2 (ppm)&quot;</span>) <span class="sc">+</span></span>
<span id="cb220-7"><a href="viz.html#cb220-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="fu">c</span>(<span class="fu">date</span>(<span class="st">&quot;1990-01-01&quot;</span>), <span class="fu">date</span>(<span class="st">&quot;1993-12-01&quot;</span>))) <span class="sc">+</span></span>
<span id="cb220-8"><a href="viz.html#cb220-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>))</span>
<span id="cb220-9"><a href="viz.html#cb220-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb220-10"><a href="viz.html#cb220-10" aria-hidden="true" tabindex="-1"></a>co2_line</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:03-data-co2-line-3"></span>
<img src="_main_files/figure-html/03-data-co2-line-3-1.png" alt="Line plot of atmospheric concentration of CO$_{2}$ from 1990 to 1994." width="432"  />
<p class="caption">
Figure 4.6: Line plot of atmospheric concentration of CO<span class="math inline">\(_{2}\)</span> from 1990 to 1994.
</p>
</div>
<p>Interesting! It seems that each year, the atmospheric CO<span class="math inline">\(_{\text{2}}\)</span> increases until it reaches its peak somewhere around April, decreases until around late September,
and finally increases again until the end of the year. In Hawaii, there are two seasons: summer from May through October, and winter from November through April.
Therefore, the oscillating pattern in CO<span class="math inline">\(_{\text{2}}\)</span> matches up fairly closely with the two seasons.</p>
<p>As you might have noticed from the code used to create the final visualization
of the <code>co2_df</code> data frame,
we construct the visualizations in <code>ggplot</code> with layers.
New layers are added with the <code>+</code> operator,
and we can really add as many as we would like!
A useful analogy to constructing a data visualization is painting a picture.
We start with a blank canvas,
and the first thing we do is prepare the surface
for our painting by adding primer.
In our data visualization this is akin to calling <code>ggplot</code>
and specifying the data set we will be using.
Next, we sketch out the background of the painting.
In our data visualization,
this would be when we map data to the axes in the <code>aes</code> function.
Then we add our key visual subjects to the painting.
In our data visualization,
this would be the geometric objects (e.g., <code>geom_point</code>, <code>geom_line</code>, etc.).
And finally, we work on adding details and refinements to the painting.
In our data visualization this would be when we fine tune axis labels,
change the font, adjust the point size, and do other related things.</p>
</div>
<div id="scatter-plots-the-old-faithful-eruption-time-data-set" class="section level3" number="4.5.2">
<h3><span class="header-section-number">4.5.2</span> Scatter plots: the Old Faithful eruption time data set</h3>
<p>The <code>faithful</code> data set  contains measurements
of the waiting time between eruptions
and the subsequent eruption duration (in minutes) of the Old Faithful
geyser in Yellowstone National Park, Wyoming, United States.
The <code>faithful</code> data set is available in base R as a data frame,
so it does not need to be loaded.
We convert it to a tibble to take advantage of the nicer print output
these specialized data frames provide.</p>
<p><strong>Question:</strong> 
Is there a relationship between the waiting time before an eruption
and the duration of the eruption?</p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="viz.html#cb221-1" aria-hidden="true" tabindex="-1"></a><span class="co"># old faithful eruption time / wait time data</span></span>
<span id="cb221-2"><a href="viz.html#cb221-2" aria-hidden="true" tabindex="-1"></a>faithful <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(faithful)</span>
<span id="cb221-3"><a href="viz.html#cb221-3" aria-hidden="true" tabindex="-1"></a>faithful</span></code></pre></div>
<pre><code>## # A tibble: 272 × 2
##    eruptions waiting
##        &lt;dbl&gt;   &lt;dbl&gt;
##  1      3.6       79
##  2      1.8       54
##  3      3.33      74
##  4      2.28      62
##  5      4.53      85
##  6      2.88      55
##  7      4.7       88
##  8      3.6       85
##  9      1.95      51
## 10      4.35      85
## # … with 262 more rows</code></pre>
<p>Here again, we investigate the relationship between two quantitative variables
(waiting time and eruption time).
But if you look at the output of the data frame,
you’ll notice that unlike time in the Mauna Loa CO<span class="math inline">\(_{\text{2}}\)</span> data set,
neither of the variables here have a natural order to them.
So a scatter plot is likely to be the most appropriate
visualization. Let’s create a scatter plot using the <code>ggplot</code>
function with the <code>waiting</code> variable on the horizontal axis, the <code>eruptions</code>
variable on the vertical axis, and the <code>geom_point</code> geometric object.
The result is shown in Figure <a href="viz.html#fig:03-data-faithful-scatter">4.7</a>.</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="viz.html#cb223-1" aria-hidden="true" tabindex="-1"></a>faithful_scatter <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(faithful, <span class="fu">aes</span>(<span class="at">x =</span> waiting, <span class="at">y =</span> eruptions)) <span class="sc">+</span></span>
<span id="cb223-2"><a href="viz.html#cb223-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span>
<span id="cb223-3"><a href="viz.html#cb223-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb223-4"><a href="viz.html#cb223-4" aria-hidden="true" tabindex="-1"></a>faithful_scatter</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:03-data-faithful-scatter"></span>
<img src="_main_files/figure-html/03-data-faithful-scatter-1.png" alt="Scatter plot of waiting time and eruption time." width="360"  />
<p class="caption">
Figure 4.7: Scatter plot of waiting time and eruption time.
</p>
</div>
<p>We can see in Figure <a href="viz.html#fig:03-data-faithful-scatter">4.7</a> that the data tend to fall
into two groups: one with short waiting and eruption times, and one with long
waiting and eruption times. Note that in this case, there is no overplotting:
the points are generally nicely visually separated, and the pattern they form
is clear. In order to refine the visualization, we need only to add axis
labels and make the font more readable:</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="viz.html#cb224-1" aria-hidden="true" tabindex="-1"></a>faithful_scatter <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(faithful, <span class="fu">aes</span>(<span class="at">x =</span> waiting, <span class="at">y =</span> eruptions)) <span class="sc">+</span></span>
<span id="cb224-2"><a href="viz.html#cb224-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb224-3"><a href="viz.html#cb224-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Waiting Time (mins)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Eruption Duration (mins)&quot;</span>) <span class="sc">+</span></span>
<span id="cb224-4"><a href="viz.html#cb224-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>))</span>
<span id="cb224-5"><a href="viz.html#cb224-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb224-6"><a href="viz.html#cb224-6" aria-hidden="true" tabindex="-1"></a>faithful_scatter</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:03-data-faithful-scatter-2"></span>
<img src="_main_files/figure-html/03-data-faithful-scatter-2-1.png" alt="Scatter plot of waiting time and eruption time with clearer axes and labels." width="360"  />
<p class="caption">
Figure 4.8: Scatter plot of waiting time and eruption time with clearer axes and labels.
</p>
</div>
<div style="page-break-after: always;"></div>
</div>
<div id="axis-transformation-and-colored-scatter-plots-the-canadian-languages-data-set" class="section level3" number="4.5.3">
<h3><span class="header-section-number">4.5.3</span> Axis transformation and colored scatter plots: the Canadian languages data set</h3>
<p>Recall the <code>can_lang</code> data set <span class="citation">(<a href="#ref-timbers2020canlang" role="doc-biblioref">Timbers 2020</a>)</span> from Chapters <a href="intro.html#intro">1</a>, <a href="reading.html#reading">2</a>, and <a href="wrangling.html#wrangling">3</a>,
 which contains counts of languages from the 2016
Canadian census.</p>
<p><strong>Question:</strong>  Is there a relationship between
the percentage of people who speak a language as their mother tongue and
the percentage for whom that is the primary language spoken at home?
And is there a pattern in the strength of this relationship in the
higher-level language categories (Official languages, Aboriginal languages, or
non-official and non-Aboriginal languages)?</p>
<p>To get started, we will read and inspect the data:</p>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="viz.html#cb225-1" aria-hidden="true" tabindex="-1"></a>can_lang <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/can_lang.csv&quot;</span>)</span>
<span id="cb225-2"><a href="viz.html#cb225-2" aria-hidden="true" tabindex="-1"></a>can_lang</span></code></pre></div>
<pre><code>## # A tibble: 214 × 6
##    category       language    mother_tongue most_at_home most_at_work lang_known
##    &lt;chr&gt;          &lt;chr&gt;               &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt;
##  1 Aboriginal la… Aboriginal…           590          235           30        665
##  2 Non-Official … Afrikaans           10260         4785           85      23415
##  3 Non-Official … Afro-Asiat…          1150          445           10       2775
##  4 Non-Official … Akan (Twi)          13460         5985           25      22150
##  5 Non-Official … Albanian            26895        13135          345      31930
##  6 Aboriginal la… Algonquian…            45           10            0        120
##  7 Aboriginal la… Algonquin            1260          370           40       2480
##  8 Non-Official … American S…          2685         3020         1145      21930
##  9 Non-Official … Amharic             22465        12785          200      33670
## 10 Non-Official … Arabic             419890       223535         5585     629055
## # … with 204 more rows</code></pre>
<p>We will begin with a scatter plot of the <code>mother_tongue</code> and <code>most_at_home</code> columns from our data frame.
The resulting plot is shown in Figure <a href="viz.html#fig:03-mother-tongue-vs-most-at-home">4.9</a>.
</p>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="viz.html#cb227-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(can_lang, <span class="fu">aes</span>(<span class="at">x =</span> most_at_home, <span class="at">y =</span> mother_tongue)) <span class="sc">+</span></span>
<span id="cb227-2"><a href="viz.html#cb227-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:03-mother-tongue-vs-most-at-home"></span>
<img src="_main_files/figure-html/03-mother-tongue-vs-most-at-home-1.png" alt="Scatter plot of number of Canadians reporting a language as their mother tongue vs the primary language at home." width="360"  />
<p class="caption">
Figure 4.9: Scatter plot of number of Canadians reporting a language as their mother tongue vs the primary language at home.
</p>
</div>
<p>To make an initial improvement in the interpretability
of Figure <a href="viz.html#fig:03-mother-tongue-vs-most-at-home">4.9</a>, we should
replace the default axis
names with more informative labels. We can use <code>\n</code> to create a line break in
the axis names so that the words after <code>\n</code> are printed on a new line. This will
make the axes labels on the plots more readable.
 We should also increase the font size to further
improve readability.</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="viz.html#cb228-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(can_lang, <span class="fu">aes</span>(<span class="at">x =</span> most_at_home, <span class="at">y =</span> mother_tongue)) <span class="sc">+</span></span>
<span id="cb228-2"><a href="viz.html#cb228-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb228-3"><a href="viz.html#cb228-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Language spoken most at home </span><span class="sc">\n</span><span class="st"> (number of Canadian residents)&quot;</span>,</span>
<span id="cb228-4"><a href="viz.html#cb228-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Mother tongue </span><span class="sc">\n</span><span class="st"> (number of Canadian residents)&quot;</span>) <span class="sc">+</span></span>
<span id="cb228-5"><a href="viz.html#cb228-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:03-mother-tongue-vs-most-at-home-labs"></span>
<img src="_main_files/figure-html/03-mother-tongue-vs-most-at-home-labs-1.png" alt="Scatter plot of number of Canadians reporting a language as their mother tongue vs the primary language at home with x and y labels." width="360"  />
<p class="caption">
Figure 4.10: Scatter plot of number of Canadians reporting a language as their mother tongue vs the primary language at home with x and y labels.
</p>
</div>
<p>Okay! The axes and labels in Figure <a href="viz.html#fig:03-mother-tongue-vs-most-at-home-labs">4.10</a> are
much more readable and interpretable now. However, the scatter points themselves could use
some work; most of the 214 data points are bunched
up in the lower left-hand side of the visualization. The data is clumped because
many more people in Canada speak English or French (the two points in
the upper right corner) than other languages.
In particular, the most common mother tongue language
has 19,460,850 speakers,
while the least common has only 10.
That’s a 6-decimal-place difference
in the magnitude of these two numbers!
We can confirm that the two points in the upper right-hand corner correspond
to Canada’s two official languages by filtering the data:
</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="viz.html#cb229-1" aria-hidden="true" tabindex="-1"></a>can_lang <span class="sc">|&gt;</span></span>
<span id="cb229-2"><a href="viz.html#cb229-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(language <span class="sc">==</span> <span class="st">&quot;English&quot;</span> <span class="sc">|</span> language <span class="sc">==</span> <span class="st">&quot;French&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 6
##   category           language mother_tongue most_at_home most_at_work lang_known
##   &lt;chr&gt;              &lt;chr&gt;            &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt;
## 1 Official languages English       19460850     22162865     15265335   29748265
## 2 Official languages French         7166700      6943800      3825215   10242945</code></pre>
<p>Recall that our question about this data pertains to <em>all</em> languages;
so to properly answer our question,
we will need to adjust the scale of the axes so that we can clearly
see all of the scatter points.
In particular, we will improve the plot by adjusting the horizontal
and vertical axes so that they are on a <strong>logarithmic</strong> (or <strong>log</strong>) scale. 
Log scaling is useful when your data take both <em>very large</em> and <em>very small</em> values,
because it helps space out small values and squishes larger values together.
For example, <span class="math inline">\(\log_{10}(1) = 0\)</span>, <span class="math inline">\(\log_{10}(10) = 1\)</span>, <span class="math inline">\(\log_{10}(100) = 2\)</span>, and <span class="math inline">\(\log_{10}(1000) = 3\)</span>;
on the logarithmic scale, 
the values 1, 10, 100, and 1000 are all the same distance apart!
So we see that applying this function is moving big values closer together
and moving small values farther apart.
Note that if your data can take the value 0, logarithmic scaling may not
be appropriate (since <code>log10(0) = -Inf</code> in R). There are other ways to transform
the data in such a case, but these are beyond the scope of the book.</p>
<p>We can accomplish logarithmic scaling in a <code>ggplot</code> visualization
using the <code>scale_x_log10</code> and <code>scale_y_log10</code> functions.
Given that the x and y axes have large numbers, we should also format the axis labels
to put commas in these numbers to increase their readability.
We can do this in R by passing the <code>label_comma</code> function (from the <code>scales</code> package)
to the <code>labels</code> argument of the <code>scale_x_log10</code> and <code>scale_x_log10</code> functions.</p>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="viz.html#cb231-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb231-2"><a href="viz.html#cb231-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb231-3"><a href="viz.html#cb231-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(can_lang, <span class="fu">aes</span>(<span class="at">x =</span> most_at_home, <span class="at">y =</span> mother_tongue)) <span class="sc">+</span></span>
<span id="cb231-4"><a href="viz.html#cb231-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb231-5"><a href="viz.html#cb231-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Language spoken most at home </span><span class="sc">\n</span><span class="st"> (number of Canadian residents)&quot;</span>,</span>
<span id="cb231-6"><a href="viz.html#cb231-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Mother tongue </span><span class="sc">\n</span><span class="st"> (number of Canadian residents)&quot;</span>) <span class="sc">+</span></span>
<span id="cb231-7"><a href="viz.html#cb231-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>)) <span class="sc">+</span></span>
<span id="cb231-8"><a href="viz.html#cb231-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>(<span class="at">labels =</span> <span class="fu">label_comma</span>()) <span class="sc">+</span></span>
<span id="cb231-9"><a href="viz.html#cb231-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>(<span class="at">labels =</span> <span class="fu">label_comma</span>())</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:03-mother-tongue-vs-most-at-home-scale"></span>
<img src="_main_files/figure-html/03-mother-tongue-vs-most-at-home-scale-1.png" alt="Scatter plot of number of Canadians reporting a language as their mother tongue vs the primary language at home with log adjusted x and y axes." width="360"  />
<p class="caption">
Figure 4.11: Scatter plot of number of Canadians reporting a language as their mother tongue vs the primary language at home with log adjusted x and y axes.
</p>
</div>
<p>Similar to some of the examples in Chapter <a href="wrangling.html#wrangling">3</a>,
we can convert the counts to percentages to give them context
and make them easier to understand.
We can do this by dividing the number of people reporting a given language
as their mother tongue or primary language at home
by the number of people who live in Canada and multiplying by 100%.
For example,
the percentage of people who reported that their mother tongue was English
in the 2016 Canadian census
was 19,460,850
/ 35,151,728 <span class="math inline">\(\times\)</span>
100 % =
55.36%.</p>
<p>Below we use <code>mutate</code> to calculate the percentage of people reporting a given
language as their mother tongue and primary language at home for all the
languages in the <code>can_lang</code> data set. Since the new columns are appended to the
end of the data table, we selected the new columns after the transformation so
you can clearly see the mutated output from the table.
</p>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb232-1"><a href="viz.html#cb232-1" aria-hidden="true" tabindex="-1"></a>can_lang <span class="ot">&lt;-</span> can_lang <span class="sc">|&gt;</span></span>
<span id="cb232-2"><a href="viz.html#cb232-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb232-3"><a href="viz.html#cb232-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">mother_tongue_percent =</span> (mother_tongue <span class="sc">/</span> <span class="dv">35151728</span>) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb232-4"><a href="viz.html#cb232-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">most_at_home_percent =</span> (most_at_home <span class="sc">/</span> <span class="dv">35151728</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb232-5"><a href="viz.html#cb232-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb232-6"><a href="viz.html#cb232-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb232-7"><a href="viz.html#cb232-7" aria-hidden="true" tabindex="-1"></a>can_lang <span class="sc">|&gt;</span> </span>
<span id="cb232-8"><a href="viz.html#cb232-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(mother_tongue_percent, most_at_home_percent)</span></code></pre></div>
<pre><code>## # A tibble: 214 × 2
##    mother_tongue_percent most_at_home_percent
##                    &lt;dbl&gt;                &lt;dbl&gt;
##  1              0.00168             0.000669 
##  2              0.0292              0.0136   
##  3              0.00327             0.00127  
##  4              0.0383              0.0170   
##  5              0.0765              0.0374   
##  6              0.000128            0.0000284
##  7              0.00358             0.00105  
##  8              0.00764             0.00859  
##  9              0.0639              0.0364   
## 10              1.19                0.636    
## # … with 204 more rows</code></pre>
<p>Finally, we will edit the visualization to use the percentages we just computed
(and change our axis labels to reflect this change in
units). Figure <a href="viz.html#fig:03-mother-tongue-vs-most-at-home-scale-props">4.12</a> displays
the final result.</p>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb234-1"><a href="viz.html#cb234-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(can_lang, <span class="fu">aes</span>(<span class="at">x =</span> most_at_home_percent, <span class="at">y =</span> mother_tongue_percent)) <span class="sc">+</span></span>
<span id="cb234-2"><a href="viz.html#cb234-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb234-3"><a href="viz.html#cb234-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Language spoken most at home </span><span class="sc">\n</span><span class="st"> (percentage of Canadian residents)&quot;</span>,</span>
<span id="cb234-4"><a href="viz.html#cb234-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Mother tongue </span><span class="sc">\n</span><span class="st"> (percentage of Canadian residents)&quot;</span>) <span class="sc">+</span></span>
<span id="cb234-5"><a href="viz.html#cb234-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>)) <span class="sc">+</span></span>
<span id="cb234-6"><a href="viz.html#cb234-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb234-7"><a href="viz.html#cb234-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>(<span class="at">labels =</span> comma)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:03-mother-tongue-vs-most-at-home-scale-props"></span>
<img src="_main_files/figure-html/03-mother-tongue-vs-most-at-home-scale-props-1.png" alt="Scatter plot of percentage of Canadians reporting a language as their mother tongue vs the primary language at home." width="360"  />
<p class="caption">
Figure 4.12: Scatter plot of percentage of Canadians reporting a language as their mother tongue vs the primary language at home.
</p>
</div>
<p>Figure <a href="viz.html#fig:03-mother-tongue-vs-most-at-home-scale-props">4.12</a> is the appropriate
visualization to use to answer the first question in this section, i.e.,
whether there is a relationship between the percentage of people who speak
a language as their mother tongue and the percentage for whom that
is the primary language spoken at home.
To fully answer the question, we need to use
Figure <a href="viz.html#fig:03-mother-tongue-vs-most-at-home-scale-props">4.12</a>
to assess a few key characteristics of the data:</p>
<ul>
<li><strong>Direction:</strong> if the y variable tends to increase when the x variable increases, then y has a <strong>positive</strong> relationship with x. If
y tends to decrease when x increases, then y has a <strong>negative</strong> relationship with x. If y does not meaningfully increase or decrease
as x increases, then y has <strong>little or no</strong> relationship with x. </li>
<li><strong>Strength:</strong> if the y variable <em>reliably</em> increases, decreases, or stays flat as x increases,
then the relationship is <strong>strong</strong>. Otherwise, the relationship is <strong>weak</strong>. Intuitively, 
the relationship is strong when the scatter points are close together and look more like a “line” or “curve” than a “cloud.”</li>
<li><strong>Shape:</strong> if you can draw a straight line roughly through the data points, the relationship is <strong>linear</strong>. Otherwise, it is <strong>nonlinear</strong>. </li>
</ul>
<p>In Figure <a href="viz.html#fig:03-mother-tongue-vs-most-at-home-scale-props">4.12</a>, we see that
as the percentage of people who have a language as their mother tongue increases,
so does the percentage of people who speak that language at home.
Therefore, there is a <strong>positive</strong> relationship between these two variables.
Furthermore, because the points in Figure <a href="viz.html#fig:03-mother-tongue-vs-most-at-home-scale-props">4.12</a>
are fairly close together, and the points look more like a “line” than a “cloud,”
we can say that this is a <strong>strong</strong> relationship.
And finally, because drawing a straight line through these points in
Figure <a href="viz.html#fig:03-mother-tongue-vs-most-at-home-scale-props">4.12</a>
would fit the pattern we observe quite well, we say that the relationship is <strong>linear</strong>.</p>
<p>Onto the second part of our exploratory data analysis question!
Recall that we are interested in knowing whether the strength
of the relationship we uncovered
in Figure <a href="viz.html#fig:03-mother-tongue-vs-most-at-home-scale-props">4.12</a> depends
on the higher-level language category (Official languages, Aboriginal languages,
and non-official, non-Aboriginal languages).
One common way to explore this
is to color the data points on the scatter plot we have already created by
group. For example, given that we have the higher-level language category for
each language recorded in the 2016 Canadian census, we can color the points in
our previous
scatter plot to represent each language’s higher-level language category.</p>
<p>Here we want to distinguish the values according to the <code>category</code> group with
which they belong. We can add an argument to the <code>aes</code> function, specifying
that the <code>category</code> column should color the points. Adding this argument will
color the points according to their group and add a legend at the side of the
plot.</p>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="viz.html#cb235-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(can_lang, <span class="fu">aes</span>(<span class="at">x =</span> most_at_home_percent, </span>
<span id="cb235-2"><a href="viz.html#cb235-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">y =</span> mother_tongue_percent, </span>
<span id="cb235-3"><a href="viz.html#cb235-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">color =</span> category)) <span class="sc">+</span></span>
<span id="cb235-4"><a href="viz.html#cb235-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb235-5"><a href="viz.html#cb235-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Language spoken most at home </span><span class="sc">\n</span><span class="st"> (percentage of Canadian residents)&quot;</span>,</span>
<span id="cb235-6"><a href="viz.html#cb235-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Mother tongue </span><span class="sc">\n</span><span class="st"> (percentage of Canadian residents)&quot;</span>) <span class="sc">+</span></span>
<span id="cb235-7"><a href="viz.html#cb235-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>)) <span class="sc">+</span></span>
<span id="cb235-8"><a href="viz.html#cb235-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb235-9"><a href="viz.html#cb235-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>(<span class="at">labels =</span> comma)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:03-scatter-color-by-category"></span>
<img src="_main_files/figure-html/03-scatter-color-by-category-1.png" alt="Scatter plot of percentage of Canadians reporting a language as their mother tongue vs the primary language at home colored by language category." width="480"  />
<p class="caption">
Figure 4.13: Scatter plot of percentage of Canadians reporting a language as their mother tongue vs the primary language at home colored by language category.
</p>
</div>
<p>The legend in Figure <a href="viz.html#fig:03-scatter-color-by-category">4.13</a>
takes up valuable plot area.
We can improve this by moving the legend title using the <code>legend.position</code>
and <code>legend.direction</code>
arguments of the <code>theme</code> function.
Here we set <code>legend.position</code> to <code>"top"</code> to put the legend above the plot
and <code>legend.direction</code> to <code>"vertical"</code> so that the legend items remain
vertically stacked on top of each other.
When the <code>legend.position</code> is set to either <code>"top"</code> or <code>"bottom"</code>
the default direction is to stack the legend items horizontally.
However, that will not work well for this particular visualization
because the legend labels are quite long
and would run off the page if displayed this way.</p>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb236-1"><a href="viz.html#cb236-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(can_lang, <span class="fu">aes</span>(<span class="at">x =</span> most_at_home_percent, </span>
<span id="cb236-2"><a href="viz.html#cb236-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">y =</span> mother_tongue_percent, </span>
<span id="cb236-3"><a href="viz.html#cb236-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">color =</span> category)) <span class="sc">+</span></span>
<span id="cb236-4"><a href="viz.html#cb236-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb236-5"><a href="viz.html#cb236-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Language spoken most at home </span><span class="sc">\n</span><span class="st"> (percentage of Canadian residents)&quot;</span>,</span>
<span id="cb236-6"><a href="viz.html#cb236-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Mother tongue </span><span class="sc">\n</span><span class="st"> (percentage of Canadian residents)&quot;</span>) <span class="sc">+</span></span>
<span id="cb236-7"><a href="viz.html#cb236-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb236-8"><a href="viz.html#cb236-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position =</span> <span class="st">&quot;top&quot;</span>,</span>
<span id="cb236-9"><a href="viz.html#cb236-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.direction =</span> <span class="st">&quot;vertical&quot;</span>) <span class="sc">+</span></span>
<span id="cb236-10"><a href="viz.html#cb236-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb236-11"><a href="viz.html#cb236-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>(<span class="at">labels =</span> comma)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:03-scatter-color-by-category-legend-edit"></span>
<img src="_main_files/figure-html/03-scatter-color-by-category-legend-edit-1.png" alt="Scatter plot of percentage of Canadians reporting a language as their mother tongue vs the primary language at home colored by language category with the legend edited." width="360"  />
<p class="caption">
Figure 4.14: Scatter plot of percentage of Canadians reporting a language as their mother tongue vs the primary language at home colored by language category with the legend edited.
</p>
</div>
<p>In Figure <a href="viz.html#fig:03-scatter-color-by-category-legend-edit">4.14</a>, the points are colored with
the default <code>ggplot2</code> color palette. But what if you want to use different
colors? In R, two packages that provide alternative color
palettes  are <code>RColorBrewer</code> <span class="citation">(<a href="#ref-RColorBrewer" role="doc-biblioref">Neuwirth 2014</a>)</span>
and <code>ggthemes</code> <span class="citation">(<a href="#ref-ggthemes" role="doc-biblioref">Arnold 2019</a>)</span>; in this book we will cover how to use <code>RColorBrewer</code>.
You can visualize the list of color
palettes that <code>RColorBrewer</code> has to offer with the <code>display.brewer.all</code>
function. You can also print a list of color-blind friendly palettes by adding
<code>colorblindFriendly = TRUE</code> to the function.</p>

<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb237-1"><a href="viz.html#cb237-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RColorBrewer)</span>
<span id="cb237-2"><a href="viz.html#cb237-2" aria-hidden="true" tabindex="-1"></a><span class="fu">display.brewer.all</span>(<span class="at">colorblindFriendly =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:rcolorbrewer"></span>
<img src="_main_files/figure-html/rcolorbrewer-1.png" alt="Color palettes available from the RColorBrewer R package." width="672" />
<p class="caption">
Figure 4.15: Color palettes available from the <code>RColorBrewer</code> R package.
</p>
</div>
<p>From Figure <a href="viz.html#fig:rcolorbrewer">4.15</a>,
we can choose the color palette we want to use in our plot.
To change the color palette,
we add the <code>scale_color_brewer</code> layer indicating the palette we want to use.
You can use
this <a href="https://www.color-blindness.com/coblis-color-blindness-simulator/">color blindness simulator</a> to check
if your visualizations 
are color-blind friendly.
Below we pick the <code>"Set2"</code> palette, with the result shown
in Figure <a href="viz.html#fig:scatter-color-by-category-palette">4.16</a>.
We also set the <code>shape</code> aesthetic mapping to the <code>category</code> variable as well;
this makes the scatter point shapes different for each category. This kind of
visual redundancy—i.e., conveying the same information with both scatter point color and shape—can
further improve the clarity and accessibility of your visualization.</p>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb238-1"><a href="viz.html#cb238-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(can_lang, <span class="fu">aes</span>(<span class="at">x =</span> most_at_home_percent, </span>
<span id="cb238-2"><a href="viz.html#cb238-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">y =</span> mother_tongue_percent, </span>
<span id="cb238-3"><a href="viz.html#cb238-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">color =</span> category, </span>
<span id="cb238-4"><a href="viz.html#cb238-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">shape =</span> category)) <span class="sc">+</span></span>
<span id="cb238-5"><a href="viz.html#cb238-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb238-6"><a href="viz.html#cb238-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Language spoken most at home </span><span class="sc">\n</span><span class="st"> (percentage of Canadian residents)&quot;</span>,</span>
<span id="cb238-7"><a href="viz.html#cb238-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Mother tongue </span><span class="sc">\n</span><span class="st"> (percentage of Canadian residents)&quot;</span>) <span class="sc">+</span></span>
<span id="cb238-8"><a href="viz.html#cb238-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb238-9"><a href="viz.html#cb238-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position =</span> <span class="st">&quot;top&quot;</span>,</span>
<span id="cb238-10"><a href="viz.html#cb238-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.direction =</span> <span class="st">&quot;vertical&quot;</span>) <span class="sc">+</span></span>
<span id="cb238-11"><a href="viz.html#cb238-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb238-12"><a href="viz.html#cb238-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb238-13"><a href="viz.html#cb238-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_brewer</span>(<span class="at">palette =</span> <span class="st">&quot;Set2&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:scatter-color-by-category-palette"></span>
<img src="_main_files/figure-html/scatter-color-by-category-palette-1.png" alt="Scatter plot of percentage of Canadians reporting a language as their mother tongue vs the primary language at home colored by language category with color-blind friendly colors." width="360"  />
<p class="caption">
Figure 4.16: Scatter plot of percentage of Canadians reporting a language as their mother tongue vs the primary language at home colored by language category with color-blind friendly colors.
</p>
</div>
<p>From the visualization in Figure <a href="viz.html#fig:scatter-color-by-category-palette">4.16</a>,
we can now clearly see that the vast majority of Canadians reported one of the official languages
as their mother tongue and as the language they speak most often at home.
What do we see when considering the second part of our exploratory question?
Do we see a difference in the relationship
between languages spoken as a mother tongue and as a primary language
at home across the higher-level language categories?
Based on Figure <a href="viz.html#fig:scatter-color-by-category-palette">4.16</a>, there does not
appear to be much of a difference.
For each higher-level language category,
there appears to be a strong, positive, and linear relationship between
the percentage of people who speak a language as their mother tongue
and the percentage who speak it as their primary language at home.
The relationship looks similar regardless of the category.</p>
<p>Does this mean that this relationship is positive for all languages in the
world? And further, can we use this data visualization on its own to predict how many people
have a given language as their mother tongue if we know how many people speak
it as their primary language at home? The answer to both these questions is
“no!” However, with exploratory data analysis, we can create new hypotheses,
ideas, and questions (like the ones at the beginning of this paragraph).
Answering those questions often involves doing more complex analyses, and sometimes
even gathering additional data. We will see more of such complex analyses later on in
this book.</p>
<!--
Finally, we can go one step further and distinguish English and French languages
with different colors in our visualization. To separate these languages, we
will filter the rows where the language is either English or French and mutate
the `category` column to equal the corresponding language. 
\index{filter}\index{mutate}


```r
english_and_french <- can_lang |>
  filter(language == "English" | language == "French") |>
  mutate(category = language)
english_and_french
```

```
## # A tibble: 2 × 8
##   category language mother_tongue most_at_home most_at_work lang_known
##   <chr>    <chr>            <dbl>        <dbl>        <dbl>      <dbl>
## 1 English  English       19460850     22162865     15265335   29748265
## 2 French   French         7166700      6943800      3825215   10242945
## # … with 2 more variables: mother_tongue_percent <dbl>,
## #   most_at_home_percent <dbl>
```

Next we will bind \index{bind\_rows} the mutated data set `english_and_french` that we just created with the remaining rows in the `can_lang` data set:

```r
can_lang <- bind_rows(
  english_and_french,
  can_lang |>
    filter(language != "English" & language != "French")
)
```


We have added a few more layers to make the data visualization in Figure \@ref(fig:03-nachos-to-cheesecake) even more effective. Specifically, we used have improved the visualizations accessibility by choosing colors that are easier to distinguish, mapped category to shape, and handled the problem of overlapping data points by making them slightly transparent. \index{ggplot!transparency}\index{alpha|see{ggplot}}


```r
ggplot(can_lang, aes(
  x = most_at_home_percent,
  y = mother_tongue_percent,
  color = category,
  shape = category # map categories to different shapes
)) + 
  geom_point(alpha = 0.6) + # set the transparency of the points
  labs(x = "Language spoken most at home \n (percentage of Canadian residents)",
       y = "Mother tongue \n (percentage of Canadian residents)") +
  theme(text = element_text(size = 12)) +
  scale_x_log10(labels = comma) +
  scale_y_log10(labels = comma) + 
  scale_color_brewer(palette = "RdYlBu")
```

<div class="figure" style="text-align: center">
<img src="_main_files/figure-html/03-nachos-to-cheesecake-1.png" alt="Scatter plot of percentage of Canadians reporting a language as their mother tongue vs the primary language at home colored by language category." width="744" />
<p class="caption">(\#fig:03-nachos-to-cheesecake)Scatter plot of percentage of Canadians reporting a language as their mother tongue vs the primary language at home colored by language category.</p>
</div>
-->
</div>
<div id="bar-plots-the-island-landmass-data-set" class="section level3" number="4.5.4">
<h3><span class="header-section-number">4.5.4</span> Bar plots: the island landmass data set</h3>
<p>The <code>islands.csv</code> data set  contains a list of Earth’s landmasses as well as their area (in thousands of square miles) <span class="citation">(<a href="#ref-islandsdata" role="doc-biblioref">McNeil 1977</a>)</span>.</p>
<p><strong>Question:</strong>  Are the continents (North / South America, Africa, Europe, Asia, Australia, Antarctica) Earth’s seven largest landmasses? If so, what are the next few largest landmasses after those?</p>
<p>To get started, we will read and inspect the data:</p>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="viz.html#cb239-1" aria-hidden="true" tabindex="-1"></a><span class="co"># islands data</span></span>
<span id="cb239-2"><a href="viz.html#cb239-2" aria-hidden="true" tabindex="-1"></a>islands_df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/islands.csv&quot;</span>)</span>
<span id="cb239-3"><a href="viz.html#cb239-3" aria-hidden="true" tabindex="-1"></a>islands_df</span></code></pre></div>
<pre><code>## # A tibble: 48 × 3
##    landmass      size landmass_type
##    &lt;chr&gt;        &lt;dbl&gt; &lt;chr&gt;        
##  1 Africa       11506 Continent    
##  2 Antarctica    5500 Continent    
##  3 Asia         16988 Continent    
##  4 Australia     2968 Continent    
##  5 Axel Heiberg    16 Other        
##  6 Baffin         184 Other        
##  7 Banks           23 Other        
##  8 Borneo         280 Other        
##  9 Britain         84 Other        
## 10 Celebes         73 Other        
## # … with 38 more rows</code></pre>
<p>Here, we have a data frame of Earth’s landmasses,
and are trying to compare their sizes.
The right type of visualization to answer this question is a bar plot.
In a bar plot, the height of the bar represents the value of a summary statistic
(usually a size, count, proportion or percentage).
They are particularly useful for comparing summary statistics between different
groups of a categorical variable.</p>
<p>We specify that we would like to use a bar plot
via the <code>geom_bar</code> function in <code>ggplot2</code>.
However, by default, <code>geom_bar</code> sets the heights
of bars to the number of times a value appears in a data frame (its <em>count</em>); here, we want to plot exactly the values in the data frame, i.e.,
the landmass sizes. So we have to pass the <code>stat = "identity"</code> argument to <code>geom_bar</code>. The result is
shown in Figure <a href="viz.html#fig:03-data-islands-bar">4.17</a>.
</p>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb241-1"><a href="viz.html#cb241-1" aria-hidden="true" tabindex="-1"></a>islands_bar <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(islands_df, <span class="fu">aes</span>(<span class="at">x =</span> landmass, <span class="at">y =</span> size)) <span class="sc">+</span></span>
<span id="cb241-2"><a href="viz.html#cb241-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>)</span>
<span id="cb241-3"><a href="viz.html#cb241-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb241-4"><a href="viz.html#cb241-4" aria-hidden="true" tabindex="-1"></a>islands_bar</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:03-data-islands-bar"></span>
<img src="_main_files/figure-html/03-data-islands-bar-1.png" alt="Bar plot of all Earth's landmasses' size with squished labels." width="480"  />
<p class="caption">
Figure 4.17: Bar plot of all Earth’s landmasses’ size with squished labels.
</p>
</div>
<p>Alright, not bad! The plot in Figure <a href="viz.html#fig:03-data-islands-bar">4.17</a> is
definitely the right kind of visualization, as we can clearly see and compare
sizes of landmasses. The major issues are that the smaller landmasses’ sizes
are hard to distinguish, and the names of the landmasses are obscuring each
other as they have been squished into too little space. But remember that the
question we asked was only about the largest landmasses; let’s make the plot a
little bit clearer by keeping only the largest 12 landmasses. We do this using
the <code>slice_max</code> function. Then to help us make sure the labels have enough
space, we’ll use horizontal bars instead of vertical ones. We do this by
swapping the <code>x</code> and <code>y</code> variables:
</p>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb242-1"><a href="viz.html#cb242-1" aria-hidden="true" tabindex="-1"></a>islands_top12 <span class="ot">&lt;-</span> <span class="fu">slice_max</span>(islands_df, <span class="at">order_by =</span> size, <span class="at">n =</span> <span class="dv">12</span>)</span>
<span id="cb242-2"><a href="viz.html#cb242-2" aria-hidden="true" tabindex="-1"></a>islands_bar <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(islands_top12, <span class="fu">aes</span>(<span class="at">x =</span> size, <span class="at">y =</span> landmass)) <span class="sc">+</span></span>
<span id="cb242-3"><a href="viz.html#cb242-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>) </span>
<span id="cb242-4"><a href="viz.html#cb242-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb242-5"><a href="viz.html#cb242-5" aria-hidden="true" tabindex="-1"></a>islands_bar</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:03-data-islands-bar-2"></span>
<img src="_main_files/figure-html/03-data-islands-bar-2-1.png" alt="Bar plot of size for Earth's largest 12 landmasses." width="480"  />
<p class="caption">
Figure 4.18: Bar plot of size for Earth’s largest 12 landmasses.
</p>
</div>
<p>The plot in Figure <a href="viz.html#fig:03-data-islands-bar-2">4.18</a> is definitely clearer now,
and allows us to answer our question
(“are the top 7 largest landmasses continents?”) in the affirmative.
But the question could be made clearer from the plot
by organizing the bars not by alphabetical order
but by size, and to color them based on whether they are a continent.
The data for this is stored in the <code>landmass_type</code> column.
To use this to color the bars,
we add the <code>fill</code> argument to the aesthetic mapping
and set it to <code>landmass_type</code>.</p>
<p>To organize the landmasses by their <code>size</code> variable,
we will use the <code>tidyverse</code> <code>fct_reorder</code> function
in the aesthetic mapping to organize the landmasses by their <code>size</code> variable.
The first argument passed to <code>fct_reorder</code> is the name of the factor column
whose levels we would like to reorder (here, <code>landmass</code>).
The second argument is the column name
that holds the values we would like to use to do the ordering (here, <code>size</code>).
The <code>fct_reorder</code> function uses ascending order by default,
but this can be changed to descending order
by setting <code>.desc = TRUE</code>.
We do this here so that the largest bar will be closest to the axis line,
which is more visually appealing.</p>
<p>To label the x and y axes, we will use the <code>labs</code> function
instead of the <code>xlab</code> and <code>ylab</code> functions from earlier in this chapter.
The <code>labs</code> function is more general; we are using it in this case because
we would also like to change the legend label.
The default label is the name of the column being mapped to <code>fill</code>. Here that
would be <code>landmass_type</code>;
however <code>landmass_type</code> is not proper English (and so is less readable).
Thus we use the <code>fill</code> argument inside <code>labs</code> to change that to “Type.”
Finally, we again  use the <code>theme</code> function
to change the font size.</p>
<div class="sourceCode" id="cb243"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb243-1"><a href="viz.html#cb243-1" aria-hidden="true" tabindex="-1"></a>islands_bar <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(islands_top12, </span>
<span id="cb243-2"><a href="viz.html#cb243-2" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">aes</span>(<span class="at">x =</span> size,</span>
<span id="cb243-3"><a href="viz.html#cb243-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">y =</span> <span class="fu">fct_reorder</span>(landmass, size, <span class="at">.desc =</span> <span class="cn">TRUE</span>), </span>
<span id="cb243-4"><a href="viz.html#cb243-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">fill =</span> landmass_type)) <span class="sc">+</span></span>
<span id="cb243-5"><a href="viz.html#cb243-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>) <span class="sc">+</span></span>
<span id="cb243-6"><a href="viz.html#cb243-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Size (1000 square mi)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Landmass&quot;</span>,  <span class="at">fill =</span> <span class="st">&quot;Type&quot;</span>) <span class="sc">+</span></span>
<span id="cb243-7"><a href="viz.html#cb243-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>))</span>
<span id="cb243-8"><a href="viz.html#cb243-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb243-9"><a href="viz.html#cb243-9" aria-hidden="true" tabindex="-1"></a>islands_bar</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:03-data-islands-bar-4"></span>
<img src="_main_files/figure-html/03-data-islands-bar-4-1.png" alt="Bar plot of size for Earth's largest 12 landmasses colored by whether its a continent with clearer axes and labels." width="480"  />
<p class="caption">
Figure 4.19: Bar plot of size for Earth’s largest 12 landmasses colored by whether its a continent with clearer axes and labels.
</p>
</div>
<p>The plot in Figure <a href="viz.html#fig:03-data-islands-bar-4">4.19</a> is now a very effective
visualization for answering our original questions. Landmasses are organized by
their size, and continents are colored differently than other landmasses,
making it quite clear that continents are the largest seven landmasses.</p>
</div>
<div id="histograms-the-michelson-speed-of-light-data-set" class="section level3" number="4.5.5">
<h3><span class="header-section-number">4.5.5</span> Histograms: the Michelson speed of light data set</h3>
<p>The <code>morley</code> data set 
contains measurements of the speed of light
collected in experiments performed in 1879.
Five experiments were performed,
and in each experiment, 20 runs were performed—meaning that
20 measurements of the speed of light were collected
in each experiment <span class="citation">(<a href="#ref-lightdata" role="doc-biblioref">Michelson 1882</a>)</span>.
The <code>morley</code> data set is available in base R as a data frame,
so it does not need to be loaded.
Because the speed of light is a very large number
(the true value is 299,792.458 km/sec), the data is coded
to be the measured speed of light minus 299,000.
This coding allows us to focus on the variations in the measurements, which are generally
much smaller than 299,000.
If we used the full large speed measurements, the variations in the measurements
would not be noticeable, making it difficult to study the differences between the experiments.
Note that we convert the <code>morley</code> data to a tibble to take advantage of the nicer print output
these specialized data frames provide.</p>
<p><strong>Question:</strong>  Given what we know now about the speed of
light (299,792.458 kilometres per second), how accurate were each of the experiments?</p>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb244-1"><a href="viz.html#cb244-1" aria-hidden="true" tabindex="-1"></a><span class="co"># michelson morley experimental data</span></span>
<span id="cb244-2"><a href="viz.html#cb244-2" aria-hidden="true" tabindex="-1"></a>morley <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(morley)</span>
<span id="cb244-3"><a href="viz.html#cb244-3" aria-hidden="true" tabindex="-1"></a>morley</span></code></pre></div>
<pre><code>## # A tibble: 100 × 3
##     Expt   Run Speed
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;
##  1     1     1   850
##  2     1     2   740
##  3     1     3   900
##  4     1     4  1070
##  5     1     5   930
##  6     1     6   850
##  7     1     7   950
##  8     1     8   980
##  9     1     9   980
## 10     1    10   880
## # … with 90 more rows</code></pre>
<p>In this experimental data,
Michelson was trying to measure just a single quantitative number
(the speed of light).
The data set contains many measurements of this single quantity.

To tell how accurate the experiments were,
we need to visualize the distribution of the measurements
(i.e., all their possible values and how often each occurs).
We can do this using a <em>histogram</em>.
A histogram 
helps us visualize how a particular variable is distributed in a data set
by separating the data into bins,
and then using vertical bars to show how many data points fell in each bin.</p>
<p>To create a histogram in <code>ggplot2</code> we will use the <code>geom_histogram</code> geometric
object, setting the <code>x</code> axis to the <code>Speed</code> measurement variable. As usual,
let’s use the default arguments just to see how things look.</p>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb246-1"><a href="viz.html#cb246-1" aria-hidden="true" tabindex="-1"></a>morley_hist <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(morley, <span class="fu">aes</span>(<span class="at">x =</span> Speed)) <span class="sc">+</span></span>
<span id="cb246-2"><a href="viz.html#cb246-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()</span>
<span id="cb246-3"><a href="viz.html#cb246-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb246-4"><a href="viz.html#cb246-4" aria-hidden="true" tabindex="-1"></a>morley_hist</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:03-data-morley-hist"></span>
<img src="_main_files/figure-html/03-data-morley-hist-1.png" alt="Histogram of Michelson's speed of light data." width="432"  />
<p class="caption">
Figure 4.20: Histogram of Michelson’s speed of light data.
</p>
</div>
<p>Figure <a href="viz.html#fig:03-data-morley-hist">4.20</a> is a great start.
However,
we cannot tell how accurate the measurements are using this visualization
unless we can see the true value.
In order to visualize the true speed of light,
we will add a vertical line with the <code>geom_vline</code> function.
To draw a vertical line with <code>geom_vline</code>, 
we need to specify where on the x-axis the line should be drawn.
We can do this by setting the <code>xintercept</code> argument.
Here we set it to 792.458, which is the true value of light speed
minus 299,000; this ensures it is coded the same way as the
measurements in the <code>morley</code> data frame.
We would also like to fine tune this vertical line,
styling it so that it is dashed and 1 point in thickness.
A point is a measurement unit commonly used with fonts,
and 1 point is about 0.353 mm.
We do this by setting <code>linetype = "dashed"</code> and <code>size = 1</code>, respectively.
There is a similar function, <code>geom_hline</code>,
that is used for plotting horizontal lines.
Note that
<em>vertical lines</em> are used to denote quantities on the <em>horizontal axis</em>,
while <em>horizontal lines</em> are used to denote quantities on the <em>vertical axis</em>.</p>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb247-1"><a href="viz.html#cb247-1" aria-hidden="true" tabindex="-1"></a>morley_hist <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(morley, <span class="fu">aes</span>(<span class="at">x =</span> Speed)) <span class="sc">+</span></span>
<span id="cb247-2"><a href="viz.html#cb247-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb247-3"><a href="viz.html#cb247-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fl">792.458</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>)</span>
<span id="cb247-4"><a href="viz.html#cb247-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb247-5"><a href="viz.html#cb247-5" aria-hidden="true" tabindex="-1"></a>morley_hist</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:03-data-morley-hist-2"></span>
<img src="_main_files/figure-html/03-data-morley-hist-2-1.png" alt="Histogram of Michelson's speed of light data with vertical line indicating true speed of light." width="432"  />
<p class="caption">
Figure 4.21: Histogram of Michelson’s speed of light data with vertical line indicating true speed of light.
</p>
</div>
<p>In Figure <a href="viz.html#fig:03-data-morley-hist-2">4.21</a>,
we still cannot tell which experiments (denoted in the <code>Expt</code> column)
led to which measurements;
perhaps some experiments were more accurate than others.
To fully answer our question,
we need to separate the measurements from each other visually.
We can try to do this using a <em>colored</em> histogram,
where counts from different experiments are stacked on top of each other
in different colors.
We can create a histogram colored by the <code>Expt</code> variable
by adding it to the <code>fill</code> aesthetic mapping.
We make sure the different colors can be seen
(despite them all sitting on top of each other)
by setting the <code>alpha</code> argument in <code>geom_histogram</code> to <code>0.5</code>
to make the bars slightly translucent.
We also specify <code>position = "identity"</code> in <code>geom_histogram</code> to ensure
the histograms for each experiment will be overlaid side-by-side,
instead of stacked bars
(which is the default for bar plots or histograms
when they are colored by another categorical variable).</p>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb248-1"><a href="viz.html#cb248-1" aria-hidden="true" tabindex="-1"></a>morley_hist <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(morley, <span class="fu">aes</span>(<span class="at">x =</span> Speed, <span class="at">fill =</span> Expt)) <span class="sc">+</span></span>
<span id="cb248-2"><a href="viz.html#cb248-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">position =</span> <span class="st">&quot;identity&quot;</span>) <span class="sc">+</span></span>
<span id="cb248-3"><a href="viz.html#cb248-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fl">792.458</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">size =</span> <span class="fl">1.0</span>)</span>
<span id="cb248-4"><a href="viz.html#cb248-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb248-5"><a href="viz.html#cb248-5" aria-hidden="true" tabindex="-1"></a>morley_hist</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:03-data-morley-hist-3"></span>
<img src="_main_files/figure-html/03-data-morley-hist-3-1.png" alt="Histogram of Michelson's speed of light data colored by experiment." width="432"  />
<p class="caption">
Figure 4.22: Histogram of Michelson’s speed of light data colored by experiment.
</p>
</div>
<p>Alright great, Figure <a href="viz.html#fig:03-data-morley-hist-3">4.22</a> looks…wait a second! The
histogram is still all the same color! What is going on here? Well, if you
recall from Chapter <a href="wrangling.html#wrangling">3</a>, the <em>data type</em> you use for each variable
can influence how R and <code>tidyverse</code> treats it. Here, we indeed have an issue
with the data types in the <code>morley</code> data frame. In particular, the <code>Expt</code> column
is currently an <em>integer</em> (you can see the label <code>&lt;int&gt;</code> underneath the <code>Expt</code> column in  the printed
data frame at the start of this section). But we want to treat it as a
<em>category</em>, i.e., there should be one category per type of experiment.</p>
<p>To fix this issue we can convert the <code>Expt</code> variable into a <em>factor</em> by 
passing it to <code>as_factor</code> in the <code>fill</code> aesthetic mapping.
Recall that factor is a data type in R that is often used to represent
categories. By writing
<code>as_factor(Expt)</code> we are ensuring that R will treat this variable as a factor,
and the color will be mapped discretely.
</p>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb249-1"><a href="viz.html#cb249-1" aria-hidden="true" tabindex="-1"></a>morley_hist <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(morley, <span class="fu">aes</span>(<span class="at">x =</span> Speed, <span class="at">fill =</span> <span class="fu">as_factor</span>(Expt))) <span class="sc">+</span></span>
<span id="cb249-2"><a href="viz.html#cb249-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">position =</span> <span class="st">&quot;identity&quot;</span>) <span class="sc">+</span></span>
<span id="cb249-3"><a href="viz.html#cb249-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fl">792.458</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">size =</span> <span class="fl">1.0</span>)</span>
<span id="cb249-4"><a href="viz.html#cb249-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb249-5"><a href="viz.html#cb249-5" aria-hidden="true" tabindex="-1"></a>morley_hist</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:03-data-morley-hist-with-factor"></span>
<img src="_main_files/figure-html/03-data-morley-hist-with-factor-1.png" alt="Histogram of Michelson's speed of light data colored by experiment as factor." width="480"  />
<p class="caption">
Figure 4.23: Histogram of Michelson’s speed of light data colored by experiment as factor.
</p>
</div>
<blockquote>
<p><strong>Note:</strong> Factors impact plots in two ways:
(1) ensuring a color is mapped as discretely where appropriate (as in this
example) and (2) the ordering of levels in a plot. <code>ggplot</code> takes into account
the order of the factor levels as opposed to the order of data in
your data frame. Learning how to reorder your factor levels will help you with
reordering the labels of a factor on a plot.</p>
</blockquote>
<p>Unfortunately, the attempt to separate out the experiment number visually has
created a bit of a mess. All of the colors in Figure
<a href="viz.html#fig:03-data-morley-hist-with-factor">4.23</a> are blending together, and although it is
possible to derive <em>some</em> insight from this (e.g., experiments 1 and 3 had some
of the most incorrect measurements), it isn’t the clearest way to convey our
message and answer the question. Let’s try a different strategy of creating
grid of separate histogram plots.</p>
<p>We use the <code>facet_grid</code> function to create a plot
that has multiple subplots arranged in a grid.
The argument to <code>facet_grid</code> specifies the variable(s) used to split the plot
into subplots, and how to split them (i.e., into rows or columns).
If the plot is to be split horizontally, into rows,
then the <code>rows</code> argument is used.
If the plot is to be split vertically, into columns,
then the <code>columns</code> argument is used.
Both the <code>rows</code> and <code>columns</code> arguments take the column names on which to split the data when creating the subplots.
Note that the column names must be surrounded by the <code>vars</code> function.
This function allows the column names to be correctly evaluated
in the context of the data frame.
</p>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="viz.html#cb250-1" aria-hidden="true" tabindex="-1"></a>morley_hist <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(morley, <span class="fu">aes</span>(<span class="at">x =</span> Speed, <span class="at">fill =</span> <span class="fu">as_factor</span>(Expt))) <span class="sc">+</span></span>
<span id="cb250-2"><a href="viz.html#cb250-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb250-3"><a href="viz.html#cb250-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="at">rows =</span> <span class="fu">vars</span>(Expt)) <span class="sc">+</span></span>
<span id="cb250-4"><a href="viz.html#cb250-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fl">792.458</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">size =</span> <span class="fl">1.0</span>)</span>
<span id="cb250-5"><a href="viz.html#cb250-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb250-6"><a href="viz.html#cb250-6" aria-hidden="true" tabindex="-1"></a>morley_hist</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:03-data-morley-hist-4"></span>
<img src="_main_files/figure-html/03-data-morley-hist-4-1.png" alt="Histogram of Michelson's speed of light data split vertically by experiment." width="408"  />
<p class="caption">
Figure 4.24: Histogram of Michelson’s speed of light data split vertically by experiment.
</p>
</div>
<p>The visualization in Figure <a href="viz.html#fig:03-data-morley-hist-4">4.24</a>
now makes it quite clear how accurate the different experiments were
with respect to one another.
The most variable measurements came from Experiment 1.
There the measurements ranged from about 650–1050 km/sec.
The least variable measurements came from Experiment 2.
There, the measurements ranged from about 750–950 km/sec.
The most different experiments still obtained quite similar results!</p>
<p>There are two finishing touches to make this visualization even clearer. First and foremost, we need to add informative axis labels
using the <code>labs</code> function, and increase the font size to make it readable using the <code>theme</code> function. Second, and perhaps more subtly, even though it
is easy to compare the experiments on this plot to one another, it is hard to get a sense
of just how accurate all the experiments were overall. For example, how accurate is the value 800 on the plot, relative to the true speed of light?
To answer this question, we’ll use the <code>mutate</code> function to transform our data into a relative measure of accuracy rather than absolute measurements:
</p>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb251-1"><a href="viz.html#cb251-1" aria-hidden="true" tabindex="-1"></a>morley_rel <span class="ot">&lt;-</span> <span class="fu">mutate</span>(morley, </span>
<span id="cb251-2"><a href="viz.html#cb251-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">relative_accuracy =</span> <span class="dv">100</span> <span class="sc">*</span> </span>
<span id="cb251-3"><a href="viz.html#cb251-3" aria-hidden="true" tabindex="-1"></a>                       ((<span class="dv">299000</span> <span class="sc">+</span> Speed) <span class="sc">-</span> <span class="fl">299792.458</span>) <span class="sc">/</span> (<span class="fl">299792.458</span>))</span>
<span id="cb251-4"><a href="viz.html#cb251-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb251-5"><a href="viz.html#cb251-5" aria-hidden="true" tabindex="-1"></a>morley_hist <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(morley_rel, </span>
<span id="cb251-6"><a href="viz.html#cb251-6" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">aes</span>(<span class="at">x =</span> relative_accuracy, </span>
<span id="cb251-7"><a href="viz.html#cb251-7" aria-hidden="true" tabindex="-1"></a>                          <span class="at">fill =</span> <span class="fu">as_factor</span>(Expt))) <span class="sc">+</span></span>
<span id="cb251-8"><a href="viz.html#cb251-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb251-9"><a href="viz.html#cb251-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="at">rows =</span> <span class="fu">vars</span>(Expt)) <span class="sc">+</span></span>
<span id="cb251-10"><a href="viz.html#cb251-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">size =</span> <span class="fl">1.0</span>) <span class="sc">+</span></span>
<span id="cb251-11"><a href="viz.html#cb251-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Relative Accuracy (%)&quot;</span>, </span>
<span id="cb251-12"><a href="viz.html#cb251-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;# Measurements&quot;</span>, </span>
<span id="cb251-13"><a href="viz.html#cb251-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">&quot;Experiment ID&quot;</span>) <span class="sc">+</span></span>
<span id="cb251-14"><a href="viz.html#cb251-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>))</span>
<span id="cb251-15"><a href="viz.html#cb251-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb251-16"><a href="viz.html#cb251-16" aria-hidden="true" tabindex="-1"></a>morley_hist</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:03-data-morley-hist-5"></span>
<img src="_main_files/figure-html/03-data-morley-hist-5-1.png" alt="Histogram of relative accuracy split vertically by experiment with clearer axes and labels." width="432"  />
<p class="caption">
Figure 4.25: Histogram of relative accuracy split vertically by experiment with clearer axes and labels.
</p>
</div>
<p>Wow, impressive! These measurements of the speed of light from 1879 had errors around <em>0.05%</em> of the true speed. Figure <a href="viz.html#fig:03-data-morley-hist-5">4.25</a> shows you that even though experiments 2 and 5 were perhaps the most accurate, all of the experiments did quite an
admirable job given the technology available at the time.</p>
<div style="page-break-after: always;"></div>
<div id="choosing-a-binwidth-for-histograms" class="section level4 unnumbered">
<h4>Choosing a binwidth for histograms</h4>
<p>When you create a histogram in R, the default number of bins used is 30.
Naturally, this is not always the right number to use.
You can set the number of bins yourself by using
the <code>bins</code> argument in the <code>geom_histogram</code> geometric object.
You can also set the <em>width</em> of the bins using the
<code>binwidth</code> argument in the <code>geom_histogram</code> geometric object.
But what number of bins, or bin width, is the right one to use?</p>
<p>Unfortunately there is no hard rule for what the right bin number
or width is. It depends entirely on your problem; the <em>right</em> number of bins
or bin width is
the one that <em>helps you answer the question</em> you asked.
Choosing the correct setting for your problem
is something that commonly takes iteration.
We recommend setting the <em>bin width</em> (not the <em>number of bins</em>) because
it often more directly corresponds to values in your problem of interest. For example,
if you are looking at a histogram of human heights,
a bin width of 1 inch would likely be reasonable, while the number of bins to use is
not immediately clear.
It’s usually a good idea to try out several bin widths to see which one
most clearly captures your data in the context of the question
you want to answer.</p>
<p>To get a sense for how different bin widths affect visualizations,
let’s experiment with the histogram that we have been working on in this section.
In Figure <a href="viz.html#fig:03-data-morley-hist-binwidth">4.26</a>,
we compare the default setting with three other histograms where we set the
<code>binwidth</code> to 0.001, 0.01 and 0.1.
In this case, we can see that both the default number of bins
and the binwidth of 0.01 are effective for helping answer our question.
On the other hand, the bin widths of 0.001 and 0.1 are too small and too big, respectively.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:03-data-morley-hist-binwidth"></span>
<img src="_main_files/figure-html/03-data-morley-hist-binwidth-1.png" alt="Effect of varying bin width on histograms." width="672"  />
<p class="caption">
Figure 4.26: Effect of varying bin width on histograms.
</p>
</div>
</div>
<div id="adding-layers-to-a-ggplot-plot-object" class="section level4 unnumbered">
<h4>Adding layers to a <code>ggplot</code> plot object</h4>
<p>One of the powerful features of <code>ggplot</code> is that you
can continue to iterate on a single plot object, adding and refining
one layer  at a time. If you stored your plot as a named object
using the assignment symbol (<code>&lt;-</code>), you can
add to it using the <code>+</code> operator.
For example, if we wanted to add a title to the last plot we created (<code>morley_hist</code>),
we can use the <code>+</code> operator to add a title layer with the <code>ggtitle</code> function.
The result is shown in Figure <a href="viz.html#fig:03-data-morley-hist-addlayer">4.27</a>.</p>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="viz.html#cb252-1" aria-hidden="true" tabindex="-1"></a>morley_hist_title <span class="ot">&lt;-</span> morley_hist <span class="sc">+</span></span>
<span id="cb252-2"><a href="viz.html#cb252-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Speed of light experiments </span><span class="sc">\n</span><span class="st"> were accurate to about 0.05%&quot;</span>)</span>
<span id="cb252-3"><a href="viz.html#cb252-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb252-4"><a href="viz.html#cb252-4" aria-hidden="true" tabindex="-1"></a>morley_hist_title</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:03-data-morley-hist-addlayer"></span>
<img src="_main_files/figure-html/03-data-morley-hist-addlayer-1.png" alt="Histogram of relative accuracy split vertically by experiment with a descriptive title highlighting the take home message of the visualization." width="432"  />
<p class="caption">
Figure 4.27: Histogram of relative accuracy split vertically by experiment with a descriptive title highlighting the take home message of the visualization.
</p>
</div>
<blockquote>
<p><strong>Note:</strong> Good visualization titles clearly communicate
the take home message to the audience. Typically,
that is the answer to the question you posed before making the visualization.</p>
</blockquote>
</div>
</div>
</div>
<div id="explaining-the-visualization" class="section level2" number="4.6">
<h2><span class="header-section-number">4.6</span> Explaining the visualization</h2>
<div id="tell-a-story" class="section level4 unnumbered">
<h4><em>Tell a story</em></h4>
<p>Typically, your visualization will not be shown entirely on its own, but rather
it will be part of a larger presentation. Further, visualizations can provide
supporting information for any aspect of a presentation, from opening to
conclusion. For example, you could use an exploratory visualization in the
opening of the presentation to motivate your choice of a more detailed data
analysis / model, a visualization of the results of your analysis to show what
your analysis has uncovered, or even one at the end of a presentation to help
suggest directions for future work.</p>
<p>Regardless of where it appears, a good way to discuss your visualization  is as
a story:</p>
<ol style="list-style-type: decimal">
<li>Establish the setting and scope, and describe why you did what you did.</li>
<li>Pose the question that your visualization answers. Justify why the question is important to answer.</li>
<li>Answer the question using your visualization. Make sure you describe <em>all</em> aspects of the visualization (including describing the axes). But you
can emphasize different aspects based on what is important to answer your question:
<ul>
<li><strong>trends (lines):</strong> Does a line describe the trend well? If so, the trend is <em>linear</em>, and if not, the trend is <em>nonlinear</em>. Is the trend increasing, decreasing, or neither?
Is there a periodic oscillation (wiggle) in the trend? Is the trend noisy (does the line “jump around” a lot) or smooth?</li>
<li><strong>distributions (scatters, histograms):</strong> How spread out are the data? Where are they centered, roughly? Are there any obvious “clusters” or “subgroups,” which would be visible as multiple bumps in the histogram?</li>
<li><strong>distributions of two variables (scatters):</strong> Is there a clear / strong relationship between the variables (points fall in a distinct pattern), a weak one (points fall in a pattern but there is some noise), or no discernible
relationship (the data are too noisy to make any conclusion)?</li>
<li><strong>amounts (bars):</strong> How large are the bars relative to one another? Are there patterns in different groups of bars?</li>
</ul></li>
<li>Summarize your findings, and use them to motivate whatever you will discuss next.</li>
</ol>
<p>Below are two examples of how one might take these four steps in describing the example visualizations that appeared earlier in this chapter.
Each of the steps is denoted by its numeral in parentheses, e.g. (3).</p>
<p><strong>Mauna Loa Atmospheric CO<span class="math inline">\(_{\text{2}}\)</span> Measurements:</strong> (1)  Many
current forms of energy generation and conversion—from automotive
engines to natural gas power plants—rely on burning fossil fuels and produce
greenhouse gases, typically primarily carbon dioxide (CO<span class="math inline">\(_{\text{2}}\)</span>), as a
byproduct. Too much of these gases in the Earth’s atmosphere will cause it to
trap more heat from the sun, leading to global warming. (2) In order to assess
how quickly the atmospheric concentration of CO<span class="math inline">\(_{\text{2}}\)</span> is increasing over
time, we (3) used a data set from the Mauna Loa observatory in Hawaii,
consisting of CO<span class="math inline">\(_{\text{2}}\)</span> measurements from 1980 to 2020. We plotted the
measured concentration of CO<span class="math inline">\(_{\text{2}}\)</span> (on the vertical axis) over time (on
the horizontal axis). From this plot, you can see a clear, increasing, and
generally linear trend over time. There is also a periodic oscillation that
occurs once per year and aligns with Hawaii’s seasons, with an amplitude that
is small relative to the growth in the overall trend. This shows that
atmospheric CO<span class="math inline">\(_{\text{2}}\)</span> is clearly increasing over time, and (4) it is
perhaps worth investigating more into the causes.</p>
<p><strong>Michelson Light Speed Experiments:</strong> (1)  Our
modern understanding of the physics of light has advanced significantly from
the late 1800s when Michelson and Morley’s experiments first demonstrated that
it had a finite speed. We now know, based on modern experiments, that it moves at
roughly 299,792.458 kilometers per second. (2) But how accurately were we first
able to measure this fundamental physical constant, and did certain experiments
produce more accurate results than others? (3) To better understand this, we
plotted data from 5 experiments by Michelson in 1879, each with 20 trials, as
histograms stacked on top of one another. The horizontal axis shows the
accuracy of the measurements relative to the true speed of light as we know it
today, expressed as a percentage. From this visualization, you can see that
most results had relative errors of at most 0.05%. You can also see that
experiments 1 and 3 had measurements that were the farthest from the true
value, and experiment 5 tended to provide the most consistently accurate
result. (4) It would be worth further investigating the differences between
these experiments to see why they produced different results.</p>
</div>
</div>
<div id="saving-the-visualization" class="section level2" number="4.7">
<h2><span class="header-section-number">4.7</span> Saving the visualization</h2>
<div id="choose-the-right-output-format-for-your-needs" class="section level4 unnumbered">
<h4><em>Choose the right output format for your needs</em></h4>
<p>Just as there are many ways to store data sets, there are many ways to store
visualizations and images. Which one you choose can depend on several factors,
such as file size/type limitations (e.g., if you are submitting your
visualization as part of a conference paper or to a poster printing shop) and
where it will be displayed (e.g., online, in a paper, on a poster, on a
billboard, in talk slides). Generally speaking, images come in two flavors:
<em>raster</em>  formats
and <em>vector</em>  formats.</p>
<p><strong>Raster</strong> images are represented as a 2-D grid of square pixels, each
with its own color. Raster images are often <em>compressed</em> before storing so they
take up less space. A compressed format is <em>lossy</em> if the image cannot be
perfectly re-created when loading and displaying, with the hope that the change
is not noticeable. <em>Lossless</em> formats, on the other hand, allow a perfect
display of the original image.
</p>
<ul>
<li><em>Common file types:</em>
<ul>
<li><a href="https://en.wikipedia.org/wiki/JPEG">JPEG</a> (<code>.jpg</code>, <code>.jpeg</code>): lossy, usually used for photographs</li>
<li><a href="https://en.wikipedia.org/wiki/Portable_Network_Graphics">PNG</a> (<code>.png</code>): lossless, usually used for plots / line drawings</li>
<li><a href="https://en.wikipedia.org/wiki/BMP_file_format">BMP</a> (<code>.bmp</code>): lossless, raw image data, no compression (rarely used)</li>
<li><a href="https://en.wikipedia.org/wiki/TIFF">TIFF</a> (<code>.tif</code>, <code>.tiff</code>): typically lossless, no compression, used mostly in graphic arts, publishing</li>
</ul></li>
<li><em>Open-source software:</em> <a href="https://www.gimp.org/">GIMP</a></li>
</ul>
<p><strong>Vector</strong> images are represented as a collection of mathematical
objects (lines, surfaces, shapes, curves). When the computer displays the image, it
redraws all of the elements using their mathematical formulas.
</p>
<ul>
<li><em>Common file types:</em>
<ul>
<li><a href="https://en.wikipedia.org/wiki/Scalable_Vector_Graphics">SVG</a> (<code>.svg</code>): general-purpose use</li>
<li><a href="https://en.wikipedia.org/wiki/Encapsulated_PostScript">EPS</a> (<code>.eps</code>), general-purpose use (rarely used)</li>
</ul></li>
<li><em>Open-source software:</em> <a href="https://inkscape.org/">Inkscape</a></li>
</ul>
<p>Raster and vector images have opposing advantages and disadvantages. A raster
image of a fixed width / height takes the same amount of space and time to load
regardless of what the image shows (the one caveat is that the compression algorithms may
shrink the image more or run faster for certain images). A vector image takes
space and time to load corresponding to how complex the image is, since the
computer has to draw all the elements each time it is displayed. For example,
if you have a scatter plot with 1 million points stored as an SVG file, it may
take your computer some time to open the image. On the other hand, you can zoom
into / scale up vector graphics as much as you like without the image looking
bad, while raster images eventually start to look “pixelated.”</p>
<blockquote>
<p><strong>Note:</strong> The portable document format <a href="https://en.wikipedia.org/wiki/PDF">PDF</a> (<code>.pdf</code>) is commonly used to
store <em>both</em> raster and vector formats. If you try to open a PDF and it’s taking a long time
to load, it may be because there is a complicated vector graphics image that your computer is rendering.

</p>
</blockquote>
<p>Let’s learn how to save plot images to these different file formats using a
scatter plot of
the <a href="https://www.stat.cmu.edu/~larry/all-of-statistics/=data/faithful.dat">Old Faithful data set</a> <span class="citation">(<a href="#ref-faithfuldata" role="doc-biblioref">Hardle 1991</a>)</span>,
shown in Figure <a href="viz.html#fig:03-plot-line">4.28</a>.</p>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="viz.html#cb253-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(svglite) <span class="co"># we need this to save SVG files</span></span>
<span id="cb253-2"><a href="viz.html#cb253-2" aria-hidden="true" tabindex="-1"></a>faithful_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> faithful, <span class="fu">aes</span>(<span class="at">x =</span> waiting, <span class="at">y =</span> eruptions)) <span class="sc">+</span></span>
<span id="cb253-3"><a href="viz.html#cb253-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb253-4"><a href="viz.html#cb253-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Waiting time to next eruption </span><span class="sc">\n</span><span class="st"> (minutes)&quot;</span>,</span>
<span id="cb253-5"><a href="viz.html#cb253-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Eruption time </span><span class="sc">\n</span><span class="st"> (minutes)&quot;</span>) <span class="sc">+</span> </span>
<span id="cb253-6"><a href="viz.html#cb253-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>))</span>
<span id="cb253-7"><a href="viz.html#cb253-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb253-8"><a href="viz.html#cb253-8" aria-hidden="true" tabindex="-1"></a>faithful_plot</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:03-plot-line"></span>
<img src="_main_files/figure-html/03-plot-line-1.png" alt="Scatter plot of waiting time and eruption time." width="360"  />
<p class="caption">
Figure 4.28: Scatter plot of waiting time and eruption time.
</p>
</div>
<p>Now that we have a named <code>ggplot</code> plot object, we can use the <code>ggsave</code> function
to save a file containing this image.
<code>ggsave</code> works by taking a file name to create for the image
as its first argument.
This can include the path to the directory where you would like to save the file
(e.g., <code>img/filename.png</code> to save a file named <code>filename</code> to the <code>img</code> directory),
and the name of the plot object to save as its second argument.
The kind of image to save is specified by the file extension.
For example,
to create a PNG image file, we specify that the file extension is <code>.png</code>.
Below we demonstrate how to save PNG, JPG, BMP, TIFF and SVG file types
for the <code>faithful_plot</code>:</p>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb254-1"><a href="viz.html#cb254-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">&quot;img/faithful_plot.png&quot;</span>, faithful_plot)</span>
<span id="cb254-2"><a href="viz.html#cb254-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">&quot;img/faithful_plot.jpg&quot;</span>, faithful_plot)</span>
<span id="cb254-3"><a href="viz.html#cb254-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">&quot;img/faithful_plot.bmp&quot;</span>, faithful_plot)</span>
<span id="cb254-4"><a href="viz.html#cb254-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">&quot;img/faithful_plot.tiff&quot;</span>, faithful_plot)</span>
<span id="cb254-5"><a href="viz.html#cb254-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">&quot;img/faithful_plot.svg&quot;</span>, faithful_plot)</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:filesizes">Table 4.1: </span>File sizes of the scatter plot of the Old Faithful data set when saved as different file formats.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Image type
</th>
<th style="text-align:left;">
File type
</th>
<th style="text-align:left;">
Image size
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Raster
</td>
<td style="text-align:left;">
PNG
</td>
<td style="text-align:left;">
0.15 MB
</td>
</tr>
<tr>
<td style="text-align:left;">
Raster
</td>
<td style="text-align:left;">
JPG
</td>
<td style="text-align:left;">
0.42 MB
</td>
</tr>
<tr>
<td style="text-align:left;">
Raster
</td>
<td style="text-align:left;">
BMP
</td>
<td style="text-align:left;">
3.15 MB
</td>
</tr>
<tr>
<td style="text-align:left;">
Raster
</td>
<td style="text-align:left;">
TIFF
</td>
<td style="text-align:left;">
9.44 MB
</td>
</tr>
<tr>
<td style="text-align:left;">
Vector
</td>
<td style="text-align:left;">
SVG
</td>
<td style="text-align:left;">
0.03 MB
</td>
</tr>
</tbody>
</table>
<p>Take a look at the file sizes in Table <a href="viz.html#tab:filesizes">4.1</a>.
Wow, that’s quite a difference! Notice that for such a simple plot with few
graphical elements (points), the vector graphics format (SVG) is over 100 times
smaller than the uncompressed raster images (BMP, TIFF). Also, note that the
JPG format is twice as large as the PNG format since the JPG compression
algorithm is designed for natural images (not plots).</p>
<p>In Figure <a href="viz.html#fig:03-raster-image">4.29</a>, we also show what
the images look like when we zoom in to a rectangle with only 3 data points.
You can see why vector graphics formats are so useful: because they’re just
based on mathematical formulas, vector graphics can be scaled up to arbitrary
sizes. This makes them great for presentation media of all sizes, from papers
to posters to billboards.</p>

<div class="figure" style="text-align: center"><span style="display:block;" id="fig:03-raster-image"></span>
<img src="img/png-vs-svg.png" alt="Zoomed in faithful, raster (PNG, left) and vector (SVG, right) formats." width="100%" />
<p class="caption">
Figure 4.29: Zoomed in <code>faithful</code>, raster (PNG, left) and vector (SVG, right) formats.
</p>
</div>
</div>
</div>
<div id="exercises-3" class="section level2" number="4.8">
<h2><span class="header-section-number">4.8</span> Exercises</h2>
<p>Practice exercises for the material covered in this chapter
can be found in the accompanying <a href="https://github.com/UBC-DSCI/data-science-a-first-intro-worksheets/blob/main/worksheet_viz/worksheet_viz.ipynb">worksheet</a>.
The worksheet tries to provide automated feedback
and help guide you through the problems.
To make sure this functionality works as intended,
please follow the instructions for computer setup needed to run the worksheets
found in Chapter <a href="move-to-your-own-machine.html#move-to-your-own-machine">13</a>.</p>
</div>
<div id="additional-resources-2" class="section level2" number="4.9">
<h2><span class="header-section-number">4.9</span> Additional resources</h2>
<ul>
<li>The <a href="https://ggplot2.tidyverse.org"><code>ggplot2</code> R package page</a> <span class="citation">(<a href="#ref-ggplot" role="doc-biblioref">Wickham, Chang, et al. 2021</a>)</span> is
where you should look if you want to learn more about the functions in this
chapter, the full set of arguments you can use, and other related functions.
The site also provides a very nice cheat sheet that summarizes many of the data
wrangling functions from this chapter.</li>
<li>The <em>Fundamentals of Data Visualization</em> <span class="citation">(<a href="#ref-wilkeviz" role="doc-biblioref">Wilke 2019</a>)</span> has
a wealth of information on designing effective visualizations. It is not
specific to any particular programming language or library. If you want to
improve your visualization skills, this is the next place to look.</li>
<li><em>R for Data Science</em> <span class="citation">(<a href="#ref-wickham2016r" role="doc-biblioref">Wickham and Grolemund 2016</a>)</span> has a <a href="https://r4ds.had.co.nz/data-visualisation.html">chapter on creating visualizations using
<code>ggplot2</code></a>. This reference is
specific to R and <code>ggplot2</code>, but provides a much more detailed introduction to
the full set of tools that <code>ggplot2</code> provides. This chapter is where you should
look if you want to learn how to make more intricate visualizations in
<code>ggplot2</code> than what is included in this chapter.</li>
<li>The <a href="https://ggplot2.tidyverse.org/reference/theme.html"><code>theme</code> function documentation</a>
is an excellent reference to see how you can fine tune the non-data aspects
of your visualization.</li>
<li><em>R for Data Science</em> <span class="citation">(<a href="#ref-wickham2016r" role="doc-biblioref">Wickham and Grolemund 2016</a>)</span> has a chapter on <a href="https://r4ds.had.co.nz/dates-and-times.html">dates and
times</a>. This chapter is where
you should look if you want to learn about <code>date</code> vectors, including how to
create them, and how to use them to effectively handle durations, periods and
intervals using the <code>lubridate</code> package.</li>
</ul>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-ggthemes" class="csl-entry">
Arnold, Jeffrey. 2019. <em><span class="nocase">ggthemes</span></em>. <a href="https://jrnold.github.io/ggthemes/">https://jrnold.github.io/ggthemes/</a>.
</div>
<div id="ref-deebblind" class="csl-entry">
Deeb, Sameer. 2005. <span>“The Molecular Basis of Variation in Human Color Vision.”</span> <em>Clinical Genetics</em> 67: 369–77.
</div>
<div id="ref-lubridatepaper" class="csl-entry">
Grolemund, Garrett, and Hadley Wickham. 2011. <span>“Dates and Times Made Easy with <span class="nocase">lubridate</span>.”</span> <em>Journal of Statistical Software</em> 40 (3): 1–25.
</div>
<div id="ref-faithfuldata" class="csl-entry">
Hardle, Wolfgang. 1991. <em>Smoothing Techniques with Implementation in <span>S</span></em>. New York: Springer.
</div>
<div id="ref-islandsdata" class="csl-entry">
McNeil, Donald R. 1977. <em>Interactive Data Analysis: A Practical Primer</em>. Wiley.
</div>
<div id="ref-lightdata" class="csl-entry">
Michelson, Albert. 1882. <span>“Experimental Determination of the Velocity of Light Made at the <span>U</span>nited <span>S</span>tates <span>N</span>aval <span>A</span>cademy, <span>A</span>nnapolis.”</span> <em>Astronomic Papers</em> 1: 135–38.
</div>
<div id="ref-RColorBrewer" class="csl-entry">
Neuwirth, Erich. 2014. <em><span>RColorBrewer</span>: ColorBrewer Palettes</em>. <a href="https://cran.r-project.org/web/packages/RColorBrewer/index.html">https://cran.r-project.org/web/packages/RColorBrewer/index.html</a>.
</div>
<div id="ref-lubridate" class="csl-entry">
Spinu, Vitalie, Garrett Grolemund, and Hadley Wickham. 2021. <em><span class="nocase">lubridate R package</span></em>. <a href="https://lubridate.tidyverse.org/">https://lubridate.tidyverse.org/</a>.
</div>
<div id="ref-maunadata" class="csl-entry">
Tans, Pieter, and Ralph Keeling. 2020. <span>“Trends in Atmospheric Carbon Dioxide.”</span> <a href="https://gml.noaa.gov/ccgg/trends/data.html">https://gml.noaa.gov/ccgg/trends/data.html</a>.
</div>
<div id="ref-timbers2020canlang" class="csl-entry">
Timbers, Tiffany. 2020. <em><span class="nocase">canlang</span>: Canadian Census Language Data</em>. <a href="https://ttimbers.github.io/canlang/">https://ttimbers.github.io/canlang/</a>.
</div>
<div id="ref-ggplot" class="csl-entry">
Wickham, Hadley, Winston Chang, Lionel Henry, Thomas Lin Pederson, Kohske Takahashi, Claus Wilke, Kara Woo, Hiroaki Yutani, and Dewey Dunnington. 2021. <em><span class="nocase">ggplot2 R package</span></em>. <a href="https://ggplot2.tidyverse.org/">https://ggplot2.tidyverse.org/</a>.
</div>
<div id="ref-wickham2016r" class="csl-entry">
Wickham, Hadley, and Garrett Grolemund. 2016. <em>R for Data Science: Import, Tidy, Transform, Visualize, and Model Data</em>. O’Reilly. <a href="https://r4ds.had.co.nz/">https://r4ds.had.co.nz/</a>.
</div>
<div id="ref-wilkeviz" class="csl-entry">
Wilke, Claus. 2019. <em>Fundamentals of Data Visualization</em>. O’Reilly Media. <a href="https://clauswilke.com/dataviz/">https://clauswilke.com/dataviz/</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="wrangling.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="classification.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
