<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Cleaning and wrangling data | Data Science: A First Introduction</title>
  <meta name="description" content="This is a textbook for teaching a first introduction to data science." />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Cleaning and wrangling data | Data Science: A First Introduction" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a textbook for teaching a first introduction to data science." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Cleaning and wrangling data | Data Science: A First Introduction" />
  
  <meta name="twitter:description" content="This is a textbook for teaching a first introduction to data science." />
  

<meta name="author" content="Tiffany-Anne Timbers" />
<meta name="author" content="Trevor Campbell" />
<meta name="author" content="Melissa Lee" />


<meta name="date" content="2021-09-23" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="reading.html"/>
<link rel="next" href="viz.html"/>
<script src="libs/header-attrs-2.9/header-attrs.js"></script>
<script src="libs/jquery-3.5.1/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.3/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.9.4.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.57.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.57.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Data Science: A First Introduction</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> R and the tidyverse</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#overview"><i class="fa fa-check"></i><b>1.1</b> Overview</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#chapter-learning-objectives"><i class="fa fa-check"></i><b>1.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#canadian-languages-data-set"><i class="fa fa-check"></i><b>1.3</b> Canadian languages data set</a></li>
<li class="chapter" data-level="1.4" data-path="intro.html"><a href="intro.html#asking-a-question"><i class="fa fa-check"></i><b>1.4</b> Asking a question</a></li>
<li class="chapter" data-level="1.5" data-path="intro.html"><a href="intro.html#loading-a-tabular-data-set"><i class="fa fa-check"></i><b>1.5</b> Loading a tabular data set</a></li>
<li class="chapter" data-level="1.6" data-path="intro.html"><a href="intro.html#naming-things-in-r"><i class="fa fa-check"></i><b>1.6</b> Naming things in R</a></li>
<li class="chapter" data-level="1.7" data-path="intro.html"><a href="intro.html#creating-subsets-of-data-frames-with-filter-select"><i class="fa fa-check"></i><b>1.7</b> Creating subsets of data frames with <code>filter</code> &amp; <code>select</code></a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="intro.html"><a href="intro.html#using-filter-to-extract-rows"><i class="fa fa-check"></i><b>1.7.1</b> Using <code>filter</code> to extract rows</a></li>
<li class="chapter" data-level="1.7.2" data-path="intro.html"><a href="intro.html#using-select-to-extract-columns"><i class="fa fa-check"></i><b>1.7.2</b> Using <code>select</code> to extract columns</a></li>
<li class="chapter" data-level="1.7.3" data-path="intro.html"><a href="intro.html#using-arrange-to-order-and-slice-to-select-rows-by-index-number"><i class="fa fa-check"></i><b>1.7.3</b> Using <code>arrange</code> to order and <code>slice</code> to select rows by index number</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="intro.html"><a href="intro.html#exploring-data-with-visualizations"><i class="fa fa-check"></i><b>1.8</b> Exploring data with visualizations</a>
<ul>
<li class="chapter" data-level="1.8.1" data-path="intro.html"><a href="intro.html#using-ggplot-to-create-a-bar-plot"><i class="fa fa-check"></i><b>1.8.1</b> Using <code>ggplot</code> to create a bar plot</a></li>
<li class="chapter" data-level="1.8.2" data-path="intro.html"><a href="intro.html#formatting-ggplot-objects"><i class="fa fa-check"></i><b>1.8.2</b> Formatting ggplot objects</a></li>
<li class="chapter" data-level="1.8.3" data-path="intro.html"><a href="intro.html#putting-it-all-together"><i class="fa fa-check"></i><b>1.8.3</b> Putting it all together</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="intro.html"><a href="intro.html#accessing-documentation"><i class="fa fa-check"></i><b>1.9</b> Accessing documentation</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="reading.html"><a href="reading.html"><i class="fa fa-check"></i><b>2</b> Reading in data locally and from the web</a>
<ul>
<li class="chapter" data-level="2.1" data-path="reading.html"><a href="reading.html#overview-1"><i class="fa fa-check"></i><b>2.1</b> Overview</a></li>
<li class="chapter" data-level="2.2" data-path="reading.html"><a href="reading.html#chapter-learning-objectives-1"><i class="fa fa-check"></i><b>2.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="2.3" data-path="reading.html"><a href="reading.html#absolute-and-relative-file-paths"><i class="fa fa-check"></i><b>2.3</b> Absolute and relative file paths</a></li>
<li class="chapter" data-level="2.4" data-path="reading.html"><a href="reading.html#reading-tabular-data-from-a-plain-text-file-into-r"><i class="fa fa-check"></i><b>2.4</b> Reading tabular data from a plain text file into R</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="reading.html"><a href="reading.html#readcsv"><i class="fa fa-check"></i><b>2.4.1</b> <code>read_csv</code> to read in comma-separated files</a></li>
<li class="chapter" data-level="2.4.2" data-path="reading.html"><a href="reading.html#skipping-rows-when-reading-in-data"><i class="fa fa-check"></i><b>2.4.2</b> Skipping rows when reading in data</a></li>
<li class="chapter" data-level="2.4.3" data-path="reading.html"><a href="reading.html#read_tsv-to-read-in-tab-separated-files"><i class="fa fa-check"></i><b>2.4.3</b> <code>read_tsv</code> to read in tab-separated files</a></li>
<li class="chapter" data-level="2.4.4" data-path="reading.html"><a href="reading.html#read_delim-as-a-more-flexible-method-to-get-tabular-data-into-r"><i class="fa fa-check"></i><b>2.4.4</b> <code>read_delim</code> as a more flexible method to get tabular data into R</a></li>
<li class="chapter" data-level="2.4.5" data-path="reading.html"><a href="reading.html#reading-tabular-data-directly-from-a-url"><i class="fa fa-check"></i><b>2.4.5</b> Reading tabular data directly from a URL</a></li>
<li class="chapter" data-level="2.4.6" data-path="reading.html"><a href="reading.html#previewing-a-data-file-before-reading-it-into-r"><i class="fa fa-check"></i><b>2.4.6</b> Previewing a data file before reading it into R</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="reading.html"><a href="reading.html#reading-tabular-data-from-a-microsoft-excel-file"><i class="fa fa-check"></i><b>2.5</b> Reading tabular data from a Microsoft Excel file</a></li>
<li class="chapter" data-level="2.6" data-path="reading.html"><a href="reading.html#reading-data-from-a-database"><i class="fa fa-check"></i><b>2.6</b> Reading data from a database</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="reading.html"><a href="reading.html#connecting-to-a-database"><i class="fa fa-check"></i><b>2.6.1</b> Connecting to a database</a></li>
<li class="chapter" data-level="2.6.2" data-path="reading.html"><a href="reading.html#interacting-with-a-database"><i class="fa fa-check"></i><b>2.6.2</b> Interacting with a database</a></li>
<li class="chapter" data-level="2.6.3" data-path="reading.html"><a href="reading.html#why-should-we-bother-with-databases-at-all"><i class="fa fa-check"></i><b>2.6.3</b> Why should we bother with databases at all?</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="reading.html"><a href="reading.html#writing-data-from-r-to-a-.csv-file"><i class="fa fa-check"></i><b>2.7</b> Writing data from R to a <code>.csv</code> file</a></li>
<li class="chapter" data-level="2.8" data-path="reading.html"><a href="reading.html#obtaining-data-from-the-web"><i class="fa fa-check"></i><b>2.8</b> Obtaining data from the web</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="reading.html"><a href="reading.html#web-scraping"><i class="fa fa-check"></i><b>2.8.1</b> Web scraping</a></li>
<li class="chapter" data-level="2.8.2" data-path="reading.html"><a href="reading.html#using-an-api"><i class="fa fa-check"></i><b>2.8.2</b> Using an API</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="reading.html"><a href="reading.html#additional-resources"><i class="fa fa-check"></i><b>2.9</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="wrangling.html"><a href="wrangling.html"><i class="fa fa-check"></i><b>3</b> Cleaning and wrangling data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="wrangling.html"><a href="wrangling.html#overview-2"><i class="fa fa-check"></i><b>3.1</b> Overview</a></li>
<li class="chapter" data-level="3.2" data-path="wrangling.html"><a href="wrangling.html#chapter-learning-objectives-2"><i class="fa fa-check"></i><b>3.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="3.3" data-path="wrangling.html"><a href="wrangling.html#data-frames-and-vectors"><i class="fa fa-check"></i><b>3.3</b> Data frames and Vectors</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="wrangling.html"><a href="wrangling.html#what-is-a-data-frame"><i class="fa fa-check"></i><b>3.3.1</b> What is a data frame?</a></li>
<li class="chapter" data-level="3.3.2" data-path="wrangling.html"><a href="wrangling.html#what-is-a-vector"><i class="fa fa-check"></i><b>3.3.2</b> What is a vector?</a></li>
<li class="chapter" data-level="3.3.3" data-path="wrangling.html"><a href="wrangling.html#how-are-vectors-different-from-a-list"><i class="fa fa-check"></i><b>3.3.3</b> How are vectors different from a list?</a></li>
<li class="chapter" data-level="3.3.4" data-path="wrangling.html"><a href="wrangling.html#what-does-this-have-to-do-with-data-frames"><i class="fa fa-check"></i><b>3.3.4</b> What does this have to do with data frames?</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="wrangling.html"><a href="wrangling.html#tidy-data"><i class="fa fa-check"></i><b>3.4</b> Tidy Data</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="wrangling.html"><a href="wrangling.html#what-is-tidy-data"><i class="fa fa-check"></i><b>3.4.1</b> What is tidy data?</a></li>
<li class="chapter" data-level="3.4.2" data-path="wrangling.html"><a href="wrangling.html#why-is-tidy-data-important-in-r"><i class="fa fa-check"></i><b>3.4.2</b> Why is tidy data important in R?</a></li>
<li class="chapter" data-level="3.4.3" data-path="wrangling.html"><a href="wrangling.html#going-from-wide-to-long-or-tidy-using-pivot_longer"><i class="fa fa-check"></i><b>3.4.3</b> Going from wide to long (or tidy!) using <code>pivot_longer</code></a></li>
<li class="chapter" data-level="3.4.4" data-path="wrangling.html"><a href="wrangling.html#pivot-wider"><i class="fa fa-check"></i><b>3.4.4</b> Going from long to wide using <code>pivot_wider</code></a></li>
<li class="chapter" data-level="3.4.5" data-path="wrangling.html"><a href="wrangling.html#using-separate-to-deal-with-multiple-delimiters"><i class="fa fa-check"></i><b>3.4.5</b> Using <code>separate</code> to deal with multiple delimiters</a></li>
<li class="chapter" data-level="3.4.6" data-path="wrangling.html"><a href="wrangling.html#notes-on-defining-tidy-data"><i class="fa fa-check"></i><b>3.4.6</b> Notes on defining tidy data</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="wrangling.html"><a href="wrangling.html#using-select-to-extract-a-range-of-columns"><i class="fa fa-check"></i><b>3.5</b> Using <code>select</code> to extract a range of columns</a></li>
<li class="chapter" data-level="3.6" data-path="wrangling.html"><a href="wrangling.html#using-filter-to-extract-rows-1"><i class="fa fa-check"></i><b>3.6</b> Using <code>filter</code> to extract rows</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="wrangling.html"><a href="wrangling.html#using-filter-to-extract-rows-with"><i class="fa fa-check"></i><b>3.6.1</b> Using <code>filter</code> to extract rows with <code>==</code></a></li>
<li class="chapter" data-level="3.6.2" data-path="wrangling.html"><a href="wrangling.html#using-filter-to-extract-rows-with-1"><i class="fa fa-check"></i><b>3.6.2</b> Using <code>filter</code> to extract rows with <code>!=</code></a></li>
<li class="chapter" data-level="3.6.3" data-path="wrangling.html"><a href="wrangling.html#using-filter-to-extract-rows-with-2"><i class="fa fa-check"></i><b>3.6.3</b> Using <code>filter</code> to extract rows with <code>,</code> &amp;`</a></li>
<li class="chapter" data-level="3.6.4" data-path="wrangling.html"><a href="wrangling.html#using-filter-to-extract-rows-with-3"><i class="fa fa-check"></i><b>3.6.4</b> Using <code>filter</code> to extract rows with <code>|</code></a></li>
<li class="chapter" data-level="3.6.5" data-path="wrangling.html"><a href="wrangling.html#using-filter-to-extract-rows-with-in"><i class="fa fa-check"></i><b>3.6.5</b> Using <code>filter</code> to extract rows with <code>%in%</code></a></li>
<li class="chapter" data-level="3.6.6" data-path="wrangling.html"><a href="wrangling.html#using-filter-to-extract-rows-with-values-above-or-below-a-threshold"><i class="fa fa-check"></i><b>3.6.6</b> Using <code>filter</code> to extract rows with values above or below a threshold</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="wrangling.html"><a href="wrangling.html#using-mutate-to-modify-or-add-columns"><i class="fa fa-check"></i><b>3.7</b> Using <code>mutate</code> to modify or add columns</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="wrangling.html"><a href="wrangling.html#using-mutate-to-modify-columns"><i class="fa fa-check"></i><b>3.7.1</b> Using <code>mutate</code> to modify columns</a></li>
<li class="chapter" data-level="3.7.2" data-path="wrangling.html"><a href="wrangling.html#using-mutate-to-create-new-columns"><i class="fa fa-check"></i><b>3.7.2</b> Using <code>mutate</code> to create new columns</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="wrangling.html"><a href="wrangling.html#creating-a-visualization-with-tidy-data"><i class="fa fa-check"></i><b>3.8</b> Creating a visualization with tidy data</a></li>
<li class="chapter" data-level="3.9" data-path="wrangling.html"><a href="wrangling.html#combining-functions-using-the-pipe-operator"><i class="fa fa-check"></i><b>3.9</b> Combining functions using the pipe operator, <code>|&gt;</code></a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="wrangling.html"><a href="wrangling.html#using-to-combine-filter-and-select"><i class="fa fa-check"></i><b>3.9.1</b> Using <code>|&gt;</code> to combine <code>filter</code> and <code>select</code></a></li>
<li class="chapter" data-level="3.9.2" data-path="wrangling.html"><a href="wrangling.html#using-with-more-than-two-functions"><i class="fa fa-check"></i><b>3.9.2</b> Using <code>|&gt;</code> with more than two functions</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="wrangling.html"><a href="wrangling.html#iterating-over-data-with-group_by-summarize"><i class="fa fa-check"></i><b>3.10</b> Iterating over data with <code>group_by</code> + <code>summarize</code></a>
<ul>
<li class="chapter" data-level="3.10.1" data-path="wrangling.html"><a href="wrangling.html#calculating-summary-statistics"><i class="fa fa-check"></i><b>3.10.1</b> Calculating summary statistics:</a></li>
<li class="chapter" data-level="3.10.2" data-path="wrangling.html"><a href="wrangling.html#calculating-group-summary-statistics"><i class="fa fa-check"></i><b>3.10.2</b> Calculating group summary statistics:</a></li>
<li class="chapter" data-level="3.10.3" data-path="wrangling.html"><a href="wrangling.html#additional-reading-on-the-dplyr-functions"><i class="fa fa-check"></i><b>3.10.3</b> Additional reading on the <code>dplyr</code> functions</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="wrangling.html"><a href="wrangling.html#using-purrrs-map-functions-to-iterate"><i class="fa fa-check"></i><b>3.11</b> Using <code>purrr</code>’s <code>map*</code> functions to iterate</a></li>
<li class="chapter" data-level="3.12" data-path="wrangling.html"><a href="wrangling.html#additional-resources-1"><i class="fa fa-check"></i><b>3.12</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="viz.html"><a href="viz.html"><i class="fa fa-check"></i><b>4</b> Effective data visualization</a>
<ul>
<li class="chapter" data-level="4.1" data-path="viz.html"><a href="viz.html#overview-3"><i class="fa fa-check"></i><b>4.1</b> Overview</a></li>
<li class="chapter" data-level="4.2" data-path="viz.html"><a href="viz.html#chapter-learning-objectives-3"><i class="fa fa-check"></i><b>4.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="4.3" data-path="viz.html"><a href="viz.html#choosing-the-visualization"><i class="fa fa-check"></i><b>4.3</b> Choosing the visualization</a></li>
<li class="chapter" data-level="4.4" data-path="viz.html"><a href="viz.html#refining-the-visualization"><i class="fa fa-check"></i><b>4.4</b> Refining the visualization</a></li>
<li class="chapter" data-level="4.5" data-path="viz.html"><a href="viz.html#creating-visualizations-with-ggplot2"><i class="fa fa-check"></i><b>4.5</b> Creating visualizations with <code>ggplot2</code></a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="viz.html"><a href="viz.html#the-mauna-loa-co2-data-set"><i class="fa fa-check"></i><b>4.5.1</b> The Mauna Loa CO2 data set</a></li>
<li class="chapter" data-level="4.5.2" data-path="viz.html"><a href="viz.html#the-island-landmass-data-set"><i class="fa fa-check"></i><b>4.5.2</b> The island landmass data set</a></li>
<li class="chapter" data-level="4.5.3" data-path="viz.html"><a href="viz.html#the-old-faithful-eruptionwaiting-time-data-set"><i class="fa fa-check"></i><b>4.5.3</b> The Old Faithful eruption/waiting time data set</a></li>
<li class="chapter" data-level="4.5.4" data-path="viz.html"><a href="viz.html#the-canadian-languages-data-set"><i class="fa fa-check"></i><b>4.5.4</b> The Canadian languages data set</a></li>
<li class="chapter" data-level="4.5.5" data-path="viz.html"><a href="viz.html#the-michelson-speed-of-light-data-set"><i class="fa fa-check"></i><b>4.5.5</b> The Michelson speed of light data set</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="viz.html"><a href="viz.html#explaining-the-visualization"><i class="fa fa-check"></i><b>4.6</b> Explaining the visualization</a></li>
<li class="chapter" data-level="4.7" data-path="viz.html"><a href="viz.html#saving-the-visualization"><i class="fa fa-check"></i><b>4.7</b> Saving the visualization</a></li>
<li class="chapter" data-level="4.8" data-path="viz.html"><a href="viz.html#additional-resources-2"><i class="fa fa-check"></i><b>4.8</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="classification.html"><a href="classification.html"><i class="fa fa-check"></i><b>5</b> Classification I: training &amp; predicting</a>
<ul>
<li class="chapter" data-level="5.1" data-path="classification.html"><a href="classification.html#overview-4"><i class="fa fa-check"></i><b>5.1</b> Overview</a></li>
<li class="chapter" data-level="5.2" data-path="classification.html"><a href="classification.html#chapter-learning-objectives-4"><i class="fa fa-check"></i><b>5.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="5.3" data-path="classification.html"><a href="classification.html#the-classification-problem"><i class="fa fa-check"></i><b>5.3</b> The classification problem</a></li>
<li class="chapter" data-level="5.4" data-path="classification.html"><a href="classification.html#exploring-a-data-set"><i class="fa fa-check"></i><b>5.4</b> Exploring a data set</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="classification.html"><a href="classification.html#loading-the-cancer-data"><i class="fa fa-check"></i><b>5.4.1</b> Loading the cancer data</a></li>
<li class="chapter" data-level="5.4.2" data-path="classification.html"><a href="classification.html#describing-the-variables-in-the-cancer-data-set"><i class="fa fa-check"></i><b>5.4.2</b> Describing the variables in the cancer data set</a></li>
<li class="chapter" data-level="5.4.3" data-path="classification.html"><a href="classification.html#exploring-the-cancer-data"><i class="fa fa-check"></i><b>5.4.3</b> Exploring the cancer data</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="classification.html"><a href="classification.html#classification-with-k-nearest-neighbors"><i class="fa fa-check"></i><b>5.5</b> Classification with <span class="math inline">\(K\)</span>-nearest neighbors</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="classification.html"><a href="classification.html#distance-between-points"><i class="fa fa-check"></i><b>5.5.1</b> Distance between points</a></li>
<li class="chapter" data-level="5.5.2" data-path="classification.html"><a href="classification.html#more-than-two-explanatory-variables"><i class="fa fa-check"></i><b>5.5.2</b> More than two explanatory variables</a></li>
<li class="chapter" data-level="5.5.3" data-path="classification.html"><a href="classification.html#summary-of-k-nearest-neighbors-algorithm"><i class="fa fa-check"></i><b>5.5.3</b> Summary of <span class="math inline">\(K\)</span>-nearest neighbors algorithm</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="classification.html"><a href="classification.html#k-nearest-neighbors-with-tidymodels"><i class="fa fa-check"></i><b>5.6</b> <span class="math inline">\(K\)</span>-nearest neighbors with <code>tidymodels</code></a></li>
<li class="chapter" data-level="5.7" data-path="classification.html"><a href="classification.html#data-preprocessing-with-tidymodels"><i class="fa fa-check"></i><b>5.7</b> Data preprocessing with <code>tidymodels</code></a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="classification.html"><a href="classification.html#centering-and-scaling"><i class="fa fa-check"></i><b>5.7.1</b> Centering and scaling</a></li>
<li class="chapter" data-level="5.7.2" data-path="classification.html"><a href="classification.html#balancing"><i class="fa fa-check"></i><b>5.7.2</b> Balancing</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="classification.html"><a href="classification.html#puttingittogetherworkflow"><i class="fa fa-check"></i><b>5.8</b> Putting it together in a <code>workflow</code></a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="classification2.html"><a href="classification2.html"><i class="fa fa-check"></i><b>6</b> Classification II: evaluation &amp; tuning</a>
<ul>
<li class="chapter" data-level="6.1" data-path="classification2.html"><a href="classification2.html#overview-5"><i class="fa fa-check"></i><b>6.1</b> Overview</a></li>
<li class="chapter" data-level="6.2" data-path="classification2.html"><a href="classification2.html#chapter-learning-objectives-5"><i class="fa fa-check"></i><b>6.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="6.3" data-path="classification2.html"><a href="classification2.html#evaluating-accuracy"><i class="fa fa-check"></i><b>6.3</b> Evaluating accuracy</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="classification2.html"><a href="classification2.html#create-the-train-test-split"><i class="fa fa-check"></i><b>6.3.1</b> Create the train / test split</a></li>
<li class="chapter" data-level="6.3.2" data-path="classification2.html"><a href="classification2.html#preprocess-the-data"><i class="fa fa-check"></i><b>6.3.2</b> Preprocess the data</a></li>
<li class="chapter" data-level="6.3.3" data-path="classification2.html"><a href="classification2.html#train-the-classifier"><i class="fa fa-check"></i><b>6.3.3</b> Train the classifier</a></li>
<li class="chapter" data-level="6.3.4" data-path="classification2.html"><a href="classification2.html#predict-the-labels-in-the-test-set"><i class="fa fa-check"></i><b>6.3.4</b> Predict the labels in the test set</a></li>
<li class="chapter" data-level="6.3.5" data-path="classification2.html"><a href="classification2.html#compute-the-accuracy"><i class="fa fa-check"></i><b>6.3.5</b> Compute the accuracy</a></li>
<li class="chapter" data-level="6.3.6" data-path="classification2.html"><a href="classification2.html#critically-analyze-performance"><i class="fa fa-check"></i><b>6.3.6</b> Critically analyze performance</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="classification2.html"><a href="classification2.html#tuning-the-classifier"><i class="fa fa-check"></i><b>6.4</b> Tuning the classifier</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="classification2.html"><a href="classification2.html#cross-validation"><i class="fa fa-check"></i><b>6.4.1</b> Cross-validation</a></li>
<li class="chapter" data-level="6.4.2" data-path="classification2.html"><a href="classification2.html#parameter-value-selection"><i class="fa fa-check"></i><b>6.4.2</b> Parameter value selection</a></li>
<li class="chapter" data-level="6.4.3" data-path="classification2.html"><a href="classification2.html#underoverfitting"><i class="fa fa-check"></i><b>6.4.3</b> Under/Overfitting</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="classification2.html"><a href="classification2.html#summary"><i class="fa fa-check"></i><b>6.5</b> Summary</a></li>
<li class="chapter" data-level="6.6" data-path="classification2.html"><a href="classification2.html#predictor-variable-selection"><i class="fa fa-check"></i><b>6.6</b> Predictor variable selection</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="classification2.html"><a href="classification2.html#the-effect-of-irrelevant-predictors"><i class="fa fa-check"></i><b>6.6.1</b> The effect of irrelevant predictors</a></li>
<li class="chapter" data-level="6.6.2" data-path="classification2.html"><a href="classification2.html#finding-a-good-subset-of-predictors"><i class="fa fa-check"></i><b>6.6.2</b> Finding a good subset of predictors</a></li>
<li class="chapter" data-level="6.6.3" data-path="classification2.html"><a href="classification2.html#forward-selection-in-r"><i class="fa fa-check"></i><b>6.6.3</b> Forward selection in R</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="classification2.html"><a href="classification2.html#additional-resources-3"><i class="fa fa-check"></i><b>6.7</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="regression1.html"><a href="regression1.html"><i class="fa fa-check"></i><b>7</b> Regression I: K-nearest neighbours</a>
<ul>
<li class="chapter" data-level="7.1" data-path="regression1.html"><a href="regression1.html#overview-6"><i class="fa fa-check"></i><b>7.1</b> Overview</a></li>
<li class="chapter" data-level="7.2" data-path="regression1.html"><a href="regression1.html#chapter-learning-objectives-6"><i class="fa fa-check"></i><b>7.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="7.3" data-path="regression1.html"><a href="regression1.html#the-regression-problem"><i class="fa fa-check"></i><b>7.3</b> The regression problem</a></li>
<li class="chapter" data-level="7.4" data-path="regression1.html"><a href="regression1.html#exploring-a-data-set-1"><i class="fa fa-check"></i><b>7.4</b> Exploring a data set</a></li>
<li class="chapter" data-level="7.5" data-path="regression1.html"><a href="regression1.html#k-nearest-neighbours-regression"><i class="fa fa-check"></i><b>7.5</b> K-nearest neighbours regression</a></li>
<li class="chapter" data-level="7.6" data-path="regression1.html"><a href="regression1.html#training-evaluating-and-tuning-the-model"><i class="fa fa-check"></i><b>7.6</b> Training, evaluating, and tuning the model</a></li>
<li class="chapter" data-level="7.7" data-path="regression1.html"><a href="regression1.html#underfitting-and-overfitting"><i class="fa fa-check"></i><b>7.7</b> Underfitting and overfitting</a></li>
<li class="chapter" data-level="7.8" data-path="regression1.html"><a href="regression1.html#evaluating-on-the-test-set"><i class="fa fa-check"></i><b>7.8</b> Evaluating on the test set</a></li>
<li class="chapter" data-level="7.9" data-path="regression1.html"><a href="regression1.html#strengths-and-limitations-of-knn-regression"><i class="fa fa-check"></i><b>7.9</b> Strengths and limitations of KNN regression</a></li>
<li class="chapter" data-level="7.10" data-path="regression1.html"><a href="regression1.html#multivariate-knn-regression"><i class="fa fa-check"></i><b>7.10</b> Multivariate KNN regression</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="regression2.html"><a href="regression2.html"><i class="fa fa-check"></i><b>8</b> Regression II: linear regression</a>
<ul>
<li class="chapter" data-level="8.1" data-path="regression2.html"><a href="regression2.html#overview-7"><i class="fa fa-check"></i><b>8.1</b> Overview</a></li>
<li class="chapter" data-level="8.2" data-path="regression2.html"><a href="regression2.html#chapter-learning-objectives-7"><i class="fa fa-check"></i><b>8.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="8.3" data-path="regression2.html"><a href="regression2.html#simple-linear-regression"><i class="fa fa-check"></i><b>8.3</b> Simple linear regression</a></li>
<li class="chapter" data-level="8.4" data-path="regression2.html"><a href="regression2.html#linear-regression-in-r"><i class="fa fa-check"></i><b>8.4</b> Linear regression in R</a></li>
<li class="chapter" data-level="8.5" data-path="regression2.html"><a href="regression2.html#comparing-simple-linear-and-knn-regression"><i class="fa fa-check"></i><b>8.5</b> Comparing simple linear and KNN regression</a></li>
<li class="chapter" data-level="8.6" data-path="regression2.html"><a href="regression2.html#multivariate-linear-regression"><i class="fa fa-check"></i><b>8.6</b> Multivariate linear regression</a></li>
<li class="chapter" data-level="8.7" data-path="regression2.html"><a href="regression2.html#multicollinearity-and-outliers"><i class="fa fa-check"></i><b>8.7</b> Multicollinearity and outliers</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="regression2.html"><a href="regression2.html#outliers"><i class="fa fa-check"></i><b>8.7.1</b> Outliers</a></li>
<li class="chapter" data-level="8.7.2" data-path="regression2.html"><a href="regression2.html#multicollinearity"><i class="fa fa-check"></i><b>8.7.2</b> Multicollinearity</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="regression2.html"><a href="regression2.html#designing-new-predictors"><i class="fa fa-check"></i><b>8.8</b> Designing new predictors</a></li>
<li class="chapter" data-level="8.9" data-path="regression2.html"><a href="regression2.html#the-other-sides-of-regression"><i class="fa fa-check"></i><b>8.9</b> The other sides of regression</a></li>
<li class="chapter" data-level="8.10" data-path="regression2.html"><a href="regression2.html#additional-resources-4"><i class="fa fa-check"></i><b>8.10</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="clustering.html"><a href="clustering.html"><i class="fa fa-check"></i><b>9</b> Clustering</a>
<ul>
<li class="chapter" data-level="9.1" data-path="clustering.html"><a href="clustering.html#overview-8"><i class="fa fa-check"></i><b>9.1</b> Overview</a></li>
<li class="chapter" data-level="9.2" data-path="clustering.html"><a href="clustering.html#chapter-learning-objectives-8"><i class="fa fa-check"></i><b>9.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="9.3" data-path="clustering.html"><a href="clustering.html#clustering-1"><i class="fa fa-check"></i><b>9.3</b> Clustering</a></li>
<li class="chapter" data-level="9.4" data-path="clustering.html"><a href="clustering.html#k-means"><i class="fa fa-check"></i><b>9.4</b> K-means</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="clustering.html"><a href="clustering.html#measuring-cluster-quality"><i class="fa fa-check"></i><b>9.4.1</b> Measuring cluster quality</a></li>
<li class="chapter" data-level="9.4.2" data-path="clustering.html"><a href="clustering.html#the-clustering-algorithm"><i class="fa fa-check"></i><b>9.4.2</b> The clustering algorithm</a></li>
<li class="chapter" data-level="9.4.3" data-path="clustering.html"><a href="clustering.html#random-restarts"><i class="fa fa-check"></i><b>9.4.3</b> Random restarts</a></li>
<li class="chapter" data-level="9.4.4" data-path="clustering.html"><a href="clustering.html#choosing-k"><i class="fa fa-check"></i><b>9.4.4</b> Choosing K</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="clustering.html"><a href="clustering.html#data-pre-processing-for-k-means"><i class="fa fa-check"></i><b>9.5</b> Data pre-processing for K-means</a></li>
<li class="chapter" data-level="9.6" data-path="clustering.html"><a href="clustering.html#k-means-in-r"><i class="fa fa-check"></i><b>9.6</b> K-means in R</a></li>
<li class="chapter" data-level="9.7" data-path="clustering.html"><a href="clustering.html#additional-resources-5"><i class="fa fa-check"></i><b>9.7</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="inference.html"><a href="inference.html"><i class="fa fa-check"></i><b>10</b> Introduction to statistical inference</a>
<ul>
<li class="chapter" data-level="10.1" data-path="inference.html"><a href="inference.html#overview-9"><i class="fa fa-check"></i><b>10.1</b> Overview</a></li>
<li class="chapter" data-level="10.2" data-path="inference.html"><a href="inference.html#chapter-learning-objectives-9"><i class="fa fa-check"></i><b>10.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="10.3" data-path="inference.html"><a href="inference.html#why-do-we-need-sampling"><i class="fa fa-check"></i><b>10.3</b> Why do we need sampling?</a></li>
<li class="chapter" data-level="10.4" data-path="inference.html"><a href="inference.html#sampling-distributions"><i class="fa fa-check"></i><b>10.4</b> Sampling distributions</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="inference.html"><a href="inference.html#sampling-distributions-for-proportions"><i class="fa fa-check"></i><b>10.4.1</b> Sampling distributions for proportions</a></li>
<li class="chapter" data-level="10.4.2" data-path="inference.html"><a href="inference.html#sampling-distributions-for-means"><i class="fa fa-check"></i><b>10.4.2</b> Sampling distributions for means</a></li>
<li class="chapter" data-level="10.4.3" data-path="inference.html"><a href="inference.html#summary-1"><i class="fa fa-check"></i><b>10.4.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="inference.html"><a href="inference.html#bootstrapping"><i class="fa fa-check"></i><b>10.5</b> Bootstrapping</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="inference.html"><a href="inference.html#overview-10"><i class="fa fa-check"></i><b>10.5.1</b> Overview</a></li>
<li class="chapter" data-level="10.5.2" data-path="inference.html"><a href="inference.html#bootstrapping-in-r"><i class="fa fa-check"></i><b>10.5.2</b> Bootstrapping in R</a></li>
<li class="chapter" data-level="10.5.3" data-path="inference.html"><a href="inference.html#using-the-bootstrap-to-calculate-a-plausible-range"><i class="fa fa-check"></i><b>10.5.3</b> Using the bootstrap to calculate a plausible range</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="inference.html"><a href="inference.html#additional-resources-6"><i class="fa fa-check"></i><b>10.6</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html"><i class="fa fa-check"></i><b>11</b> Combining code and text with Jupyter</a>
<ul>
<li class="chapter" data-level="11.1" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#overview-11"><i class="fa fa-check"></i><b>11.1</b> Overview</a></li>
<li class="chapter" data-level="11.2" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#chapter-learning-objectives-10"><i class="fa fa-check"></i><b>11.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="11.3" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#jupyter"><i class="fa fa-check"></i><b>11.3</b> Jupyter</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#accessing-jupyter"><i class="fa fa-check"></i><b>11.3.1</b> Accessing Jupyter</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#code-cells"><i class="fa fa-check"></i><b>11.4</b> Code cells</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#executing-code-cells"><i class="fa fa-check"></i><b>11.4.1</b> Executing code cells</a></li>
<li class="chapter" data-level="11.4.2" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#the-kernel"><i class="fa fa-check"></i><b>11.4.2</b> The Kernel</a></li>
<li class="chapter" data-level="11.4.3" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#creating-new-code-cells"><i class="fa fa-check"></i><b>11.4.3</b> Creating new code cells</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#markdown-cells"><i class="fa fa-check"></i><b>11.5</b> Markdown cells</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#editing-markdown-cells"><i class="fa fa-check"></i><b>11.5.1</b> Editing Markdown cells</a></li>
<li class="chapter" data-level="11.5.2" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#creating-new-markdown-cells"><i class="fa fa-check"></i><b>11.5.2</b> Creating new Markdown cells</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#saving-your-work"><i class="fa fa-check"></i><b>11.6</b> Saving your work</a></li>
<li class="chapter" data-level="11.7" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#best-practices-for-running-a-notebook"><i class="fa fa-check"></i><b>11.7</b> Best practices for running a notebook</a>
<ul>
<li class="chapter" data-level="11.7.1" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#best-practices-for-executing-code-cells"><i class="fa fa-check"></i><b>11.7.1</b> Best practices for executing code cells</a></li>
<li class="chapter" data-level="11.7.2" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#best-practices-for-including-r-packages-in-notebooks"><i class="fa fa-check"></i><b>11.7.2</b> Best practices for including R packages in notebooks</a></li>
<li class="chapter" data-level="11.7.3" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#summary-of-best-practices-for-running-a-notebook"><i class="fa fa-check"></i><b>11.7.3</b> Summary of best practices for running a notebook</a></li>
</ul></li>
<li class="chapter" data-level="11.8" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#exploring-data-files"><i class="fa fa-check"></i><b>11.8</b> Exploring data files</a></li>
<li class="chapter" data-level="11.9" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#exporting-to-a-different-file-format"><i class="fa fa-check"></i><b>11.9</b> Exporting to a different file format</a>
<ul>
<li class="chapter" data-level="11.9.1" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#exporting-to-html"><i class="fa fa-check"></i><b>11.9.1</b> Exporting to HTML</a></li>
<li class="chapter" data-level="11.9.2" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#exporting-to-pdf"><i class="fa fa-check"></i><b>11.9.2</b> Exporting to PDF</a></li>
</ul></li>
<li class="chapter" data-level="11.10" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#creating-a-new-jupyter-notebook"><i class="fa fa-check"></i><b>11.10</b> Creating a new Jupyter notebook</a></li>
<li class="chapter" data-level="11.11" data-path="getting-started-with-jupyter.html"><a href="getting-started-with-jupyter.html#additional-resources-7"><i class="fa fa-check"></i><b>11.11</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html"><i class="fa fa-check"></i><b>12</b> Collaboration with version control</a>
<ul>
<li class="chapter" data-level="12.1" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#overview-12"><i class="fa fa-check"></i><b>12.1</b> Overview</a></li>
<li class="chapter" data-level="12.2" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#chapter-learning-objectives-11"><i class="fa fa-check"></i><b>12.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="12.3" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#what-is-version-control-and-why-should-i-use-it"><i class="fa fa-check"></i><b>12.3</b> What is version control, and why should I use it?</a></li>
<li class="chapter" data-level="12.4" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#version-control-repositories"><i class="fa fa-check"></i><b>12.4</b> Version control repositories</a></li>
<li class="chapter" data-level="12.5" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#version-control-workflows"><i class="fa fa-check"></i><b>12.5</b> Version control workflows</a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#commit-changes"><i class="fa fa-check"></i><b>12.5.1</b> Committing changes to a local repository</a></li>
<li class="chapter" data-level="12.5.2" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#pushing-changes-to-a-remote-repository"><i class="fa fa-check"></i><b>12.5.2</b> Pushing changes to a remote repository</a></li>
<li class="chapter" data-level="12.5.3" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#pulling-changes-from-a-remote-repository"><i class="fa fa-check"></i><b>12.5.3</b> Pulling changes from a remote repository</a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#working-with-remote-repositories-using-github"><i class="fa fa-check"></i><b>12.6</b> Working with remote repositories using GitHub</a>
<ul>
<li class="chapter" data-level="12.6.1" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#creating-a-remote-repository-on-github"><i class="fa fa-check"></i><b>12.6.1</b> Creating a remote repository on GitHub</a></li>
<li class="chapter" data-level="12.6.2" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#editing-files-on-github-with-the-pen-tool"><i class="fa fa-check"></i><b>12.6.2</b> Editing files on GitHub with the pen tool</a></li>
<li class="chapter" data-level="12.6.3" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#creating-files-on-github-with-the-add-file-menu"><i class="fa fa-check"></i><b>12.6.3</b> Creating files on GitHub with the “Add file” menu</a></li>
</ul></li>
<li class="chapter" data-level="12.7" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#local-repo-jupyter"><i class="fa fa-check"></i><b>12.7</b> Working with local repositories using Jupyter</a>
<ul>
<li class="chapter" data-level="12.7.1" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#cloning-a-repository-using-jupyter"><i class="fa fa-check"></i><b>12.7.1</b> Cloning a repository using Jupyter</a></li>
<li class="chapter" data-level="12.7.2" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#specifying-files-to-commit"><i class="fa fa-check"></i><b>12.7.2</b> Specifying files to commit</a></li>
<li class="chapter" data-level="12.7.3" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#making-the-commit"><i class="fa fa-check"></i><b>12.7.3</b> Making the commit</a></li>
<li class="chapter" data-level="12.7.4" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#pushing-the-commits-to-github"><i class="fa fa-check"></i><b>12.7.4</b> Pushing the commits to GitHub</a></li>
</ul></li>
<li class="chapter" data-level="12.8" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#collaboration"><i class="fa fa-check"></i><b>12.8</b> Collaboration</a>
<ul>
<li class="chapter" data-level="12.8.1" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#giving-collaborators-access-to-your-project"><i class="fa fa-check"></i><b>12.8.1</b> Giving collaborators access to your project</a></li>
<li class="chapter" data-level="12.8.2" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#pulling-changes-from-github-using-jupyter"><i class="fa fa-check"></i><b>12.8.2</b> Pulling changes from GitHub using Jupyter</a></li>
<li class="chapter" data-level="12.8.3" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#handling-merge-conflicts"><i class="fa fa-check"></i><b>12.8.3</b> Handling merge conflicts</a></li>
<li class="chapter" data-level="12.8.4" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#communicating-using-github-issues"><i class="fa fa-check"></i><b>12.8.4</b> Communicating using GitHub issues</a></li>
</ul></li>
<li class="chapter" data-level="12.9" data-path="Getting-started-with-version-control.html"><a href="Getting-started-with-version-control.html#vc-add-res"><i class="fa fa-check"></i><b>12.9</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html"><i class="fa fa-check"></i><b>13</b> Setting up your computer</a>
<ul>
<li class="chapter" data-level="13.1" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#overview-13"><i class="fa fa-check"></i><b>13.1</b> Overview</a></li>
<li class="chapter" data-level="13.2" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#chapter-learning-objectives-12"><i class="fa fa-check"></i><b>13.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="13.3" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#installing-software-on-your-own-computer"><i class="fa fa-check"></i><b>13.3</b> Installing software on your own computer</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#git"><i class="fa fa-check"></i><b>13.3.1</b> Git</a></li>
<li class="chapter" data-level="13.3.2" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#miniconda"><i class="fa fa-check"></i><b>13.3.2</b> Miniconda</a></li>
<li class="chapter" data-level="13.3.3" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#jupyterlab"><i class="fa fa-check"></i><b>13.3.3</b> JupyterLab</a></li>
<li class="chapter" data-level="13.3.4" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#r-and-the-irkernel"><i class="fa fa-check"></i><b>13.3.4</b> R and the IRkernel</a></li>
<li class="chapter" data-level="13.3.5" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#r-packages"><i class="fa fa-check"></i><b>13.3.5</b> R packages</a></li>
<li class="chapter" data-level="13.3.6" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#latex"><i class="fa fa-check"></i><b>13.3.6</b> LaTeX</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="move-to-your-own-machine.html"><a href="move-to-your-own-machine.html#finishing-up-installation"><i class="fa fa-check"></i><b>13.4</b> Finishing up installation</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="appendixA.html"><a href="appendixA.html"><i class="fa fa-check"></i><b>A</b> Download files from a JupyterHub for later local use</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Science: A First Introduction</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="wrangling" class="section level1" number="3">
<h1><span class="header-section-number">Chapter 3</span> Cleaning and wrangling data</h1>
<div id="overview-2" class="section level2" number="3.1">
<h2><span class="header-section-number">3.1</span> Overview</h2>
<p>This chapter is centred around defining tidy data,
a data format that is suitable for analysis,
and the tools needed to transform raw data into this format.
This will be presented in the context of a real-world data science application,
providing more practice working through a whole case study.</p>
</div>
<div id="chapter-learning-objectives-2" class="section level2" number="3.2">
<h2><span class="header-section-number">3.2</span> Chapter learning objectives</h2>
<p>By the end of the chapter, readers will be able to:</p>
<ul>
<li>define the term “tidy data”</li>
<li>discuss the advantages and disadvantages of storing data in a tidy data format</li>
<li>define what vector and data frames are in R, and describe how they relate to each other</li>
<li>describe the types of data that can be stored in integer, double, character, logical, and factor vectors in R</li>
<li>recall and use the following tidyverse functions and operators for their intended data wrangling tasks:
<ul>
<li><code>select</code></li>
<li><code>filter</code></li>
<li><code>mutate</code></li>
<li><code>|&gt;</code></li>
<li><code>c()</code></li>
<li><code>%in%</code></li>
<li><code>pivot_longer</code></li>
<li><code>pivot_wider</code></li>
<li><code>separate</code></li>
<li><code>summarize</code></li>
<li><code>group_by</code></li>
<li><code>map</code></li>
</ul></li>
</ul>
</div>
<div id="data-frames-and-vectors" class="section level2" number="3.3">
<h2><span class="header-section-number">3.3</span> Data frames and Vectors</h2>
<p>We now know how to load data into R from various file formats.
Given that most of the tools we have used to do this represent the data as a
data frame in R, we will spend some time learning more about data frames
to deepen our understanding of them. This will be useful prerequisite knowledge
to use and manipulate these objects in our data analysis.</p>
<div id="what-is-a-data-frame" class="section level3" number="3.3.1">
<h3><span class="header-section-number">3.3.1</span> What is a data frame?</h3>
<p>To define a <strong>data frame</strong>, first, let’s introduce a few commonly used terms in statistics:</p>
<ul>
<li><strong>observation</strong> - all of the quantities or a qualities we collect from a given entity/object (<em>e.g.,</em> adult)</li>
<li><strong>variable</strong> - any characteristic, number, or quantity that can be measured or collected (<em>e.g.,</em> adult height)</li>
<li><strong>value</strong> - a single collected quantity or a quality from a given entity/object (<em>e.g.,</em> the adult height of a particular person)</li>
</ul>
<p>From a data perspective, a data frame is a rectangle where the rows are the observations:</p>
<div class="figure"><span id="fig:02-obs"></span>
<img src="img/obs.jpeg" alt="Rows are observations in a data frame" width="650" />
<p class="caption">
Figure 3.1: Rows are observations in a data frame
</p>
</div>
<p>and the columns are the variables:</p>
<div class="figure"><span id="fig:02-vars"></span>
<img src="img/vars.jpeg" alt="Columns are variables in a data frame" width="700" />
<p class="caption">
Figure 3.2: Columns are variables in a data frame
</p>
</div>
<p>From a computer programming perspective, in R, a data frame is a special subtype of a list object whose elements (columns) are <em>vectors</em>. For example, the data frame in Figure <a href="wrangling.html#fig:02-vectors">3.3</a> has three vectors whose names are <code>region</code>, <code>year</code> and <code>population</code>.</p>
<div class="figure"><span id="fig:02-vectors"></span>
<img src="img/vectors.jpeg" alt="Data frame with 3 vectors" width="700" />
<p class="caption">
Figure 3.3: Data frame with 3 vectors
</p>
</div>
</div>
<div id="what-is-a-vector" class="section level3" number="3.3.2">
<h3><span class="header-section-number">3.3.2</span> What is a vector?</h3>
<p>In R, <strong>vectors</strong> are objects that can contain one or more elements. The vector elements are ordered, and they must all be of the same <em>data type</em>. R has several different basic data types, as shown in table <a href="wrangling.html#tab:datatype-table">3.1</a>.</p>
<p>Lists, which are sometimes called recursive vectors because lists can contain other lists.
In the vector shown in Figure <a href="wrangling.html#fig:02-vector">3.4</a>, the elements are of integer type:</p>
<div class="figure"><span id="fig:02-vector"></span>
<img src="img/vector.jpeg" alt="Example of a numeric type vector" width="700" />
<p class="caption">
Figure 3.4: Example of a numeric type vector
</p>
</div>
<p>You can create vectors in R using the concatenate <code>c()</code> function.
To create the vector <code>year</code> in Figure <a href="wrangling.html#fig:02-vector">3.4</a> we write:</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="wrangling.html#cb103-1" aria-hidden="true" tabindex="-1"></a>year <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2015</span>, <span class="dv">2013</span>, <span class="dv">2011</span>, <span class="dv">2016</span>, <span class="dv">2018</span>)</span>
<span id="cb103-2"><a href="wrangling.html#cb103-2" aria-hidden="true" tabindex="-1"></a>year</span></code></pre></div>
<pre><code>## [1] 2015 2013 2011 2016 2018</code></pre>
<table>
<caption><span id="tab:datatype-table">Table 3.1: </span> Basic data types in R</caption>
<colgroup>
<col width="19%" />
<col width="50%" />
<col width="30%" />
</colgroup>
<thead>
<tr class="header">
<th>Data type</th>
<th>Description</th>
<th>Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>character</td>
<td>Letters or numbers surrounded by quotes</td>
<td>“1” , “Hello world!”</td>
</tr>
<tr class="even">
<td>double</td>
<td>Numbers with decimals values</td>
<td>1.2333</td>
</tr>
<tr class="odd">
<td>integer</td>
<td>Numbers that do not contain decimals</td>
<td>1L, 20L (where “L” tells R to store as an integer)</td>
</tr>
<tr class="even">
<td>logical</td>
<td>A value of true and false</td>
<td><code>TRUE</code>, <code>FALSE</code></td>
</tr>
<tr class="odd">
<td>factor</td>
<td>Used to represent data with a limited number of values</td>
<td>a <code>size</code> variable with levels “large,” “medium” and “small”</td>
</tr>
</tbody>
</table>
<blockquote>
<p>“Numeric” is an umbrella term that includes integer and double data types.
Most of the time when working with numbers in R they will be double types. For instance, a double data type is the default when you create a vector of numbers using <code>c()</code>, and when you read in whole numbers via <code>read_csv</code>.
There are other basic data types in R, such as <em>raw</em> and <em>complex</em>, which we won’t cover in this textbook.
We will go into more details about factors in chapter <a href="viz.html#viz">4</a>.</p>
</blockquote>
</div>
<div id="how-are-vectors-different-from-a-list" class="section level3" number="3.3.3">
<h3><span class="header-section-number">3.3.3</span> How are vectors different from a list?</h3>
<p>Lists are also objects in R that have multiple elements, you can think of them as super-vectors. Vectors and lists differ by the requirement of element type consistency. All elements
within a single vector must be of the same type (e.g., all elements are numbers), whereas elements within a single list can be of different
types (e.g., characters, numbers, logicals and even other lists can be elements in the same list).</p>
<div class="figure"><span id="fig:02-vec-vs-list"></span>
<img src="img/vec_vs_list.jpeg" alt="A vector versus a list" width="650" />
<p class="caption">
Figure 3.5: A vector versus a list
</p>
</div>
<blockquote>
<p>Note that there are actually two types of vectors in R: <em>atomic vectors</em> and <em>lists</em>.
Though when people say “vector,” they are <em>usually</em> referring to atomic vectors. Confusing, we know! You can think of <strong>atom</strong>ic vectors as the “atoms” of R since they are built from R’s most fundamental data types.</p>
</blockquote>
</div>
<div id="what-does-this-have-to-do-with-data-frames" class="section level3" number="3.3.4">
<h3><span class="header-section-number">3.3.4</span> What does this have to do with data frames?</h3>
<p>As mentioned earlier, a data frame is really a special type of list
where the elements can only be vectors.
Representing data with such an object enables us to easily work with our data
in a tabular manner. It also allows us to have columns,
containing qualities or values, for different statistical variables linked
in a row for one observation - these columns cannot be independently sorted.
This is similar to a table in a database.</p>
<div class="figure"><span id="fig:02-dataframe"></span>
<img src="img/dataframe.jpeg" alt="Data frame and vector types" width="650" />
<p class="caption">
Figure 3.6: Data frame and vector types
</p>
</div>
<p>The functions from the <code>tidyverse</code> package that we are using often give us a special class of data frame called a <em>tibble</em>. Tibbles have some additional features and benefits over the built-in data frame object. These include the ability to add grouping (and other useful) attributes and more predictable type preservation when subsetting. Because a tibble is just a data frame with some added features, we will collectively refer to both built-in R data frames and tibbles as data frames in this book.</p>
<blockquote>
<p>You can use the function <code>class</code> on a data object to assess whether a data frame is a built-in R data frame or a tibble. If the data object is a data frame <code>class</code> will return <code>"data.frame"</code>, whereas if the data object is a tibble it will return <code>"tbl_df" "tbl" "data.frame"</code>. You can easily convert built-in R data frames to tibbles using the <code>tidyverse</code> <code>as_tibble</code> function.</p>
</blockquote>
<p>Vectors, data frames and lists are basic types of <em>data structures</em> in R which are core to most data analyses. We summarize them in table <a href="wrangling.html#tab:datastructure-table">3.2</a>.</p>
<table>
<caption><span id="tab:datastructure-table">Table 3.2: </span> Basic data structures in R</caption>
<colgroup>
<col width="25%" />
<col width="75%" />
</colgroup>
<thead>
<tr class="header">
<th>Data Structure</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>vector</td>
<td>An ordered collection of one, or more, values of the <em>same data type</em> (e.g. all values are numeric). <em>Note: in R, a vector of length one is used to represent a single value.</em></td>
</tr>
<tr class="even">
<td>data frame</td>
<td>A list of <em>vectors</em> of the <em>same length</em>, which has column and row names. We typically use a data frame to represent a data set.</td>
</tr>
<tr class="odd">
<td>list</td>
<td>An ordered collection of one, or more, values. The elements in the list can be of different data types.</td>
</tr>
</tbody>
</table>
<blockquote>
<p>There are several other data structures in the R programming language (<em>e.g.,</em> matrices), however, they are beyond the scope of this book.</p>
</blockquote>
</div>
</div>
<div id="tidy-data" class="section level2" number="3.4">
<h2><span class="header-section-number">3.4</span> Tidy Data</h2>
<p>There are many ways a tabular data set can be organized.
This chapter will focus on introducing the <em>tidy data</em> format of organization
and how to make your raw (and likely messy) data tidy.</p>
<div id="what-is-tidy-data" class="section level3" number="3.4.1">
<h3><span class="header-section-number">3.4.1</span> What is tidy data?</h3>
<p>Tidy data satisfy the following three criteria <span class="citation">(<a href="#ref-wickham2014tidy" role="doc-biblioref">Wickham and others 2014</a>)</span>:</p>
<ul>
<li>each row is a single observation,</li>
<li>each column is a single variable, and</li>
<li>each value is a single cell (i.e., its row and column position in the data frame is not shared with another value)</li>
</ul>
<div class="figure"><span id="fig:02-tidy-image"></span>
<img src="img/tidy_data.jpeg" alt="Tidy data" width="1150" />
<p class="caption">
Figure 3.7: Tidy data
</p>
</div>
</div>
<div id="why-is-tidy-data-important-in-r" class="section level3" number="3.4.2">
<h3><span class="header-section-number">3.4.2</span> Why is tidy data important in R?</h3>
<p>First, tidy data is a straightforward way to work with data and thus, one of R’s most popular plotting toolsets, the <code>ggplot2</code> package
(which is one of the packages that the <code>tidyverse</code> package loads), expects the
data to be in a tidy format. Second, most statistical analysis functions also
expect data in a tidy format. Given that both of these tasks are central in
almost all data analysis projects, it is well worth spending the time to get your
data into a tidy format upfront. Luckily there are many well-designed <code>tidyverse</code>
data cleaning/wrangling tools to help you easily tidy your data. Let’s explore
them below!</p>
</div>
<div id="going-from-wide-to-long-or-tidy-using-pivot_longer" class="section level3" number="3.4.3">
<h3><span class="header-section-number">3.4.3</span> Going from wide to long (or tidy!) using <code>pivot_longer</code></h3>
<p>One common step to get data into a tidy format is to combine columns stored in
separate columns but are really part of the same variable. Data is often stored
in a wider, not tidy, format because this format is usually more intuitive for
human readability and understanding, and humans create data sets.</p>
<p>For example, in Figure <a href="wrangling.html#fig:02-wide-to-long">3.8</a>, the table on the left is an
untidy format because the year values (2011, 2016) are listed as the column headers.
One problem with using data in this format is that we don’t know what the values
under each year represent in the table. Also, we can’t easily access the year
values, so if we wanted to find the maximum year, for example, it’s hard to do
when the values are not in their own column. We can reshape this data set to a long format by creating a column called “year” and a column called “population,” which is the table on the right.</p>
<div class="figure"><span id="fig:02-wide-to-long"></span>
<img src="img/wide_to_long.jpeg" alt="Going from wide to long data" width="1150" />
<p class="caption">
Figure 3.8: Going from wide to long data
</p>
</div>
<p>We can use the function <code>pivot_longer</code>, which combines columns, making the data frame longer and narrower. To learn how to use <code>pivot_longer</code>, we will work with the <code>region_lang_top5_cities_wide.csv</code> data set. This data set contains contains the counts of how many Canadians cited each language as their mother tongue for five major Canadian cities (Toronto, Montréal, Vancouver, Calgary and Edmonton) from the 2016 Canadian census. We will load the <code>tidyverse</code> packing so we can use our wrangling functions and the <code>canlang</code> package
since it contains the <code>region_lang</code> and <code>region_data</code> data sets that we will use later in the chapter.</p>
<p>Our data set is stored in an untidy format, as shown below:</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="wrangling.html#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb105-2"><a href="wrangling.html#cb105-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(canlang)</span>
<span id="cb105-3"><a href="wrangling.html#cb105-3" aria-hidden="true" tabindex="-1"></a>lang_wide <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/region_lang_top5_cities_wide.csv&quot;</span>)</span>
<span id="cb105-4"><a href="wrangling.html#cb105-4" aria-hidden="true" tabindex="-1"></a>lang_wide</span></code></pre></div>
<pre><code>## # A tibble: 214 x 7
##    category           language       Toronto Montréal Vancouver Calgary Edmonton
##    &lt;chr&gt;              &lt;chr&gt;            &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;
##  1 Aboriginal langua… Aboriginal la…      80       30        70      20       25
##  2 Non-Official &amp; No… Afrikaans          985       90      1435     960      575
##  3 Non-Official &amp; No… Afro-Asiatic …     360      240        45      45       65
##  4 Non-Official &amp; No… Akan (Twi)        8485     1015       400     705      885
##  5 Non-Official &amp; No… Albanian         13260     2450      1090    1365      770
##  6 Aboriginal langua… Algonquian la…       5        5         0       0        0
##  7 Aboriginal langua… Algonquin            5       30         5       5        0
##  8 Non-Official &amp; No… American Sign…     470       50       265     100      180
##  9 Non-Official &amp; No… Amharic           7460      665      1140    4075     2515
## 10 Non-Official &amp; No… Arabic           85175   151955     14320   18965    17525
## # … with 204 more rows</code></pre>
<p>What is wrong with our untidy format above? From a data analysis perspective, this format is not ideal because the values of the variable <em>region</em> (Toronto, Montréal, Vancouver, Calgary and Edmonton) are stored as column names. Thus they are not easily accessible to the data analysis functions we will want to apply to our data set. Additionally, the values of the <em>mother tongue</em> variable are spread across multiple columns, which will prevent us from doing any desired visualization or statistical tasks until we combine them into one column. For instance, suppose we want to know the languages with the highest number of Canadians reporting it as their mother tongue among all five regions. This question would be tough to answer with the data in its current format. It would be much easier to answer if we tidy our data first.</p>
To accomplish this data transformation, we will use the <code>tidyverse</code> function
<code>pivot_longer</code>. Figure <a href="wrangling.html#fig:img-pivot-longer-with-table">3.9</a> summarizes how we want to
reshape our data from wide to long with using the <code>pivot_longer</code> function.
<div class="figure"><span id="fig:img-pivot-longer-with-table"></span>
<img src="img/pivot_longer_with_table.jpeg" alt="Going from wide to long with the pivot_longer function" width="1100" />
<p class="caption">
Figure 3.9: Going from wide to long with the pivot_longer function
</p>
</div>
<p>Figure <a href="wrangling.html#fig:img-pivot-longer">3.10</a> details what we need to specify to use <code>pivot_longer</code>.</p>
<div class="figure"><span id="fig:img-pivot-longer"></span>
<img src="img/pivot_longer.jpeg" alt="Syntax for the pivot_longer function" width="1100" />
<p class="caption">
Figure 3.10: Syntax for the pivot_longer function
</p>
</div>
<p>For the above example, we use <code>pivot_longer</code> to combine the Toronto, Montréal, Vancouver, Calgary and Edmonton columns into a single column called <code>region</code>, and create a column called <code>mother_tongue</code> that contains the count of how many Canadians report each language as their mother tongue for each metropolitan area. We use a colon <code>,</code> between Toronto, and Edmonton tells R to select all the columns in between Toronto and Edmonton:</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="wrangling.html#cb107-1" aria-hidden="true" tabindex="-1"></a>lang_mother_tidy <span class="ot">&lt;-</span> <span class="fu">pivot_longer</span>(lang_wide,</span>
<span id="cb107-2"><a href="wrangling.html#cb107-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">cols =</span> Toronto<span class="sc">:</span>Edmonton,</span>
<span id="cb107-3"><a href="wrangling.html#cb107-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">names_to =</span> <span class="st">&quot;region&quot;</span>,</span>
<span id="cb107-4"><a href="wrangling.html#cb107-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">values_to =</span> <span class="st">&quot;mother_tongue&quot;</span></span>
<span id="cb107-5"><a href="wrangling.html#cb107-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb107-6"><a href="wrangling.html#cb107-6" aria-hidden="true" tabindex="-1"></a>lang_mother_tidy</span></code></pre></div>
<pre><code>## # A tibble: 1,070 x 4
##    category                        language               region   mother_tongue
##    &lt;chr&gt;                           &lt;chr&gt;                  &lt;chr&gt;            &lt;dbl&gt;
##  1 Aboriginal languages            Aboriginal languages,… Toronto             80
##  2 Aboriginal languages            Aboriginal languages,… Montréal            30
##  3 Aboriginal languages            Aboriginal languages,… Vancouv…            70
##  4 Aboriginal languages            Aboriginal languages,… Calgary             20
##  5 Aboriginal languages            Aboriginal languages,… Edmonton            25
##  6 Non-Official &amp; Non-Aboriginal … Afrikaans              Toronto            985
##  7 Non-Official &amp; Non-Aboriginal … Afrikaans              Montréal            90
##  8 Non-Official &amp; Non-Aboriginal … Afrikaans              Vancouv…          1435
##  9 Non-Official &amp; Non-Aboriginal … Afrikaans              Calgary            960
## 10 Non-Official &amp; Non-Aboriginal … Afrikaans              Edmonton           575
## # … with 1,060 more rows</code></pre>
<blockquote>
<p><strong>Splitting code across lines</strong>: <em>In the code above, the call to the <code>pivot_longer</code> function is split across several lines.</em>
<em>This is allowed and encouraged when programming in R when your code line gets too long</em>
<em>to read clearly. About 80 characters per line is recommended and when doing this, it is important to end the line with a comma <code>,</code> so that R</em>
<em>knows the function should continue to the next line.</em></p>
</blockquote>
<p>The data above is now tidy because all three criteria for tidy data have now been met:</p>
<ol style="list-style-type: decimal">
<li>All the variables (<code>category</code>, <code>language</code>, <code>region</code> and <code>mother_tongue</code>) are now their own columns in the data frame.</li>
<li>Each observation, i.e., each <code>category</code>, <code>language</code>, <code>region</code>, and count of Canadians where that language is the mother tongue, are in a single row.</li>
<li>Each value is a single cell, i.e., its row, column position in the data frame is not shared with another value.</li>
</ol>
</div>
<div id="pivot-wider" class="section level3" number="3.4.4">
<h3><span class="header-section-number">3.4.4</span> Going from long to wide using <code>pivot_wider</code></h3>
<p>Suppose we have observations spread across multiple rows rather than in a single row. For example, in Figure <a href="wrangling.html#fig:long-to-wide">3.11</a>, the table on the left is an
untidy format because the <code>count</code> column contains two variables (population and commuter count) and each observation is split across two rows.
Using data in this format means it’s harder to apply functions when the values are not in their own column. For example, finding the maximum number of commuters is possible to do with the untidy table but requires a few more steps and is cumbersome. We can reshape this data set to a wider format by creating a column called “population” and a column called “commuters,” which is the table on the right.</p>
<div class="figure"><span id="fig:long-to-wide"></span>
<img src="img/long_to_wide.jpeg" alt="Going from long to wide data" width="1150" />
<p class="caption">
Figure 3.11: Going from long to wide data
</p>
</div>
<p>To tidy this type of data in R, we can use the function <code>pivot_wider</code>, which generally increases the number of columns (widens) and decreases the number of rows in a data set. The data set <code>region_lang_top5_cities_long.csv</code> contains the number of Canadians reporting the primary language at home and work for five major cities (Toronto, Montréal, Vancouver, Calgary and Edmonton).</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="wrangling.html#cb109-1" aria-hidden="true" tabindex="-1"></a>lang_long <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/region_lang_top5_cities_long.csv&quot;</span>)</span>
<span id="cb109-2"><a href="wrangling.html#cb109-2" aria-hidden="true" tabindex="-1"></a>lang_long</span></code></pre></div>
<pre><code>## # A tibble: 2,140 x 5
##    region    category             language                     type        count
##    &lt;chr&gt;     &lt;chr&gt;                &lt;chr&gt;                        &lt;chr&gt;       &lt;dbl&gt;
##  1 Montréal  Aboriginal languages Aboriginal languages, n.o.s. most_at_ho…    15
##  2 Montréal  Aboriginal languages Aboriginal languages, n.o.s. most_at_wo…     0
##  3 Toronto   Aboriginal languages Aboriginal languages, n.o.s. most_at_ho…    50
##  4 Toronto   Aboriginal languages Aboriginal languages, n.o.s. most_at_wo…     0
##  5 Calgary   Aboriginal languages Aboriginal languages, n.o.s. most_at_ho…     5
##  6 Calgary   Aboriginal languages Aboriginal languages, n.o.s. most_at_wo…     0
##  7 Edmonton  Aboriginal languages Aboriginal languages, n.o.s. most_at_ho…    10
##  8 Edmonton  Aboriginal languages Aboriginal languages, n.o.s. most_at_wo…     0
##  9 Vancouver Aboriginal languages Aboriginal languages, n.o.s. most_at_ho…    15
## 10 Vancouver Aboriginal languages Aboriginal languages, n.o.s. most_at_wo…     0
## # … with 2,130 more rows</code></pre>
<p>What is wrong with this format above? In this example, each observation should be a language in a region. However, in the messy data set above, each observation is split across multiple rows. One where the count for <code>most_at_home</code> is recorded and the other where the count for <code>most_at_work</code> is recorded. Suppose we wanted to visualize the relationship between the number of Canadians reporting their primary language at home and work. It would be difficult to do that with the data in its current format.</p>
We can see how we would like to transform the data from long to wide with <code>pivot_wider</code> in Figure <a href="wrangling.html#fig:img-pivot-wider-table">3.12</a>.<br />

<div class="figure"><span id="fig:img-pivot-wider-table"></span>
<img src="img/pivot_wider_with_table.jpeg" alt="Going from long to wide with pivot_wider" width="1100" />
<p class="caption">
Figure 3.12: Going from long to wide with pivot_wider
</p>
</div>
<p>To tidy this data, we will use <code>pivot_wider</code>, and Figure <a href="wrangling.html#fig:img-pivot-wider">3.13</a> details what we need to specify to use this function.</p>
<div class="figure"><span id="fig:img-pivot-wider"></span>
<img src="img/pivot_longer.jpeg" alt="Syntax for the pivot_wider function" width="1100" />
<p class="caption">
Figure 3.13: Syntax for the pivot_wider function
</p>
</div>
<p>We will apply the function as detailed in Figure <a href="wrangling.html#fig:img-pivot-wider">3.13</a>.</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="wrangling.html#cb111-1" aria-hidden="true" tabindex="-1"></a>lang_home_tidy <span class="ot">&lt;-</span> <span class="fu">pivot_wider</span>(lang_long,</span>
<span id="cb111-2"><a href="wrangling.html#cb111-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">names_from =</span> type,</span>
<span id="cb111-3"><a href="wrangling.html#cb111-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">values_from =</span> count</span>
<span id="cb111-4"><a href="wrangling.html#cb111-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb111-5"><a href="wrangling.html#cb111-5" aria-hidden="true" tabindex="-1"></a>lang_home_tidy</span></code></pre></div>
<pre><code>## # A tibble: 1,070 x 5
##    region   category                language           most_at_home most_at_work
##    &lt;chr&gt;    &lt;chr&gt;                   &lt;chr&gt;                     &lt;dbl&gt;        &lt;dbl&gt;
##  1 Montréal Aboriginal languages    Aboriginal langua…           15            0
##  2 Toronto  Aboriginal languages    Aboriginal langua…           50            0
##  3 Calgary  Aboriginal languages    Aboriginal langua…            5            0
##  4 Edmonton Aboriginal languages    Aboriginal langua…           10            0
##  5 Vancouv… Aboriginal languages    Aboriginal langua…           15            0
##  6 Montréal Non-Official &amp; Non-Abo… Afrikaans                    10            0
##  7 Toronto  Non-Official &amp; Non-Abo… Afrikaans                   265            0
##  8 Calgary  Non-Official &amp; Non-Abo… Afrikaans                   505           15
##  9 Edmonton Non-Official &amp; Non-Abo… Afrikaans                   300            0
## 10 Vancouv… Non-Official &amp; Non-Abo… Afrikaans                   520           10
## # … with 1,060 more rows</code></pre>
<p>The data above is now tidy! We can go through the three criteria again to check that this data is a tidy data set.</p>
<ol style="list-style-type: decimal">
<li>All the variables are their own columns in the data frame, i.e., <code>most_at_home</code>, and <code>most_at_work</code> have been separated into their own columns in the data frame.</li>
<li>Each observation, i.e., each <code>category</code>, <code>language</code>, <code>region</code>, <code>most_at_home</code> and <code>most_at_work</code>, are in a single row.</li>
<li>Each value is a single cell, i.e., its row, column position in the data frame is not shared with another value.</li>
</ol>
<p>You might notice that we have the same number of columns in our tidy data set as we did in our messy one. Therefore <code>pivot_wider</code> didn’t really “widen” our data as the name suggests. However, if we had more than two categories in the original <code>type</code> column, then we would see the data set “widen.”</p>
</div>
<div id="using-separate-to-deal-with-multiple-delimiters" class="section level3" number="3.4.5">
<h3><span class="header-section-number">3.4.5</span> Using <code>separate</code> to deal with multiple delimiters</h3>
<p>Data are also not considered tidy when multiple values are stored in the same cell. The data set we show below is even messier than the ones we dealt with above: the <code>Toronto</code>, <code>Montréal</code>, <code>Vancouver</code>, <code>Calgary</code> and <code>Edmonton</code> columns contain the number of Canadians reporting their primary language at home and work in one column separated by the delimiter “/.” The column names are the values of a variable, AND each value does not have its own cell! To turn this messy data into tidy data, we’ll have to fix these issues.</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="wrangling.html#cb113-1" aria-hidden="true" tabindex="-1"></a>lang_messy <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/region_lang_top5_cities_messy.csv&quot;</span>)</span>
<span id="cb113-2"><a href="wrangling.html#cb113-2" aria-hidden="true" tabindex="-1"></a>lang_messy</span></code></pre></div>
<pre><code>## # A tibble: 214 x 7
##    category          language       Toronto  Montréal Vancouver Calgary Edmonton
##    &lt;chr&gt;             &lt;chr&gt;          &lt;chr&gt;    &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;   &lt;chr&gt;   
##  1 Aboriginal langu… Aboriginal la… 50/0     15/0     15/0      5/0     10/0    
##  2 Non-Official &amp; N… Afrikaans      265/0    10/0     520/10    505/15  300/0   
##  3 Non-Official &amp; N… Afro-Asiatic … 185/10   65/0     10/0      15/0    20/0    
##  4 Non-Official &amp; N… Akan (Twi)     4045/20  440/0    125/10    330/0   445/0   
##  5 Non-Official &amp; N… Albanian       6380/215 1445/20  530/10    620/25  370/10  
##  6 Aboriginal langu… Algonquian la… 5/0      0/0      0/0       0/0     0/0     
##  7 Aboriginal langu… Algonquin      0/0      10/0     0/0       0/0     0/0     
##  8 Non-Official &amp; N… American Sign… 720/245  70/0     300/140   85/25   190/85  
##  9 Non-Official &amp; N… Amharic        3820/55  315/0    540/10    2730/50 1695/35 
## 10 Non-Official &amp; N… Arabic         45025/1… 72980/1… 8680/275  11010/… 10590/3…
## # … with 204 more rows</code></pre>
<p>First we’ll use <code>pivot_longer</code> to create two columns, <code>region</code> and <code>value</code>, similar to what we did previously:</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="wrangling.html#cb115-1" aria-hidden="true" tabindex="-1"></a>lang_messy_longer <span class="ot">&lt;-</span> <span class="fu">pivot_longer</span>(lang_messy,</span>
<span id="cb115-2"><a href="wrangling.html#cb115-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">cols =</span> Toronto<span class="sc">:</span>Edmonton,</span>
<span id="cb115-3"><a href="wrangling.html#cb115-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">names_to =</span> <span class="st">&quot;region&quot;</span>,</span>
<span id="cb115-4"><a href="wrangling.html#cb115-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">values_to =</span> <span class="st">&quot;value&quot;</span></span>
<span id="cb115-5"><a href="wrangling.html#cb115-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb115-6"><a href="wrangling.html#cb115-6" aria-hidden="true" tabindex="-1"></a>lang_messy_longer</span></code></pre></div>
<pre><code>## # A tibble: 1,070 x 4
##    category                            language                   region   value
##    &lt;chr&gt;                               &lt;chr&gt;                      &lt;chr&gt;    &lt;chr&gt;
##  1 Aboriginal languages                Aboriginal languages, n.o… Toronto  50/0 
##  2 Aboriginal languages                Aboriginal languages, n.o… Montréal 15/0 
##  3 Aboriginal languages                Aboriginal languages, n.o… Vancouv… 15/0 
##  4 Aboriginal languages                Aboriginal languages, n.o… Calgary  5/0  
##  5 Aboriginal languages                Aboriginal languages, n.o… Edmonton 10/0 
##  6 Non-Official &amp; Non-Aboriginal lang… Afrikaans                  Toronto  265/0
##  7 Non-Official &amp; Non-Aboriginal lang… Afrikaans                  Montréal 10/0 
##  8 Non-Official &amp; Non-Aboriginal lang… Afrikaans                  Vancouv… 520/…
##  9 Non-Official &amp; Non-Aboriginal lang… Afrikaans                  Calgary  505/…
## 10 Non-Official &amp; Non-Aboriginal lang… Afrikaans                  Edmonton 300/0
## # … with 1,060 more rows</code></pre>
<p>Then we’ll use <code>separate</code> to split the <code>value</code> column into two columns, one that contains only the counts of Canadians that speak each language most at home, and one that contains the counts for most at work for each region. To use <code>separate</code> we need to specify the:</p>
<ol style="list-style-type: decimal">
<li><p><code>data</code>: the data set</p></li>
<li><p><code>col</code>: the name of a the column we need to split</p></li>
<li><p><code>into</code>: a character vector of the new column names we would like to put the split data into</p></li>
<li><p><code>sep</code>: the separator on which to split</p></li>
</ol>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="wrangling.html#cb117-1" aria-hidden="true" tabindex="-1"></a>lang_no_delimiter <span class="ot">&lt;-</span> <span class="fu">separate</span>(lang_messy_longer,</span>
<span id="cb117-2"><a href="wrangling.html#cb117-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> value,</span>
<span id="cb117-3"><a href="wrangling.html#cb117-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">into =</span> <span class="fu">c</span>(<span class="st">&quot;most_at_home&quot;</span>, <span class="st">&quot;most_at_work&quot;</span>),</span>
<span id="cb117-4"><a href="wrangling.html#cb117-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">sep =</span> <span class="st">&quot;/&quot;</span></span>
<span id="cb117-5"><a href="wrangling.html#cb117-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb117-6"><a href="wrangling.html#cb117-6" aria-hidden="true" tabindex="-1"></a>lang_no_delimiter</span></code></pre></div>
<pre><code>## # A tibble: 1,070 x 5
##    category                 language           region  most_at_home most_at_work
##    &lt;chr&gt;                    &lt;chr&gt;              &lt;chr&gt;   &lt;chr&gt;        &lt;chr&gt;       
##  1 Aboriginal languages     Aboriginal langua… Toronto 50           0           
##  2 Aboriginal languages     Aboriginal langua… Montré… 15           0           
##  3 Aboriginal languages     Aboriginal langua… Vancou… 15           0           
##  4 Aboriginal languages     Aboriginal langua… Calgary 5            0           
##  5 Aboriginal languages     Aboriginal langua… Edmont… 10           0           
##  6 Non-Official &amp; Non-Abor… Afrikaans          Toronto 265          0           
##  7 Non-Official &amp; Non-Abor… Afrikaans          Montré… 10           0           
##  8 Non-Official &amp; Non-Abor… Afrikaans          Vancou… 520          10          
##  9 Non-Official &amp; Non-Abor… Afrikaans          Calgary 505          15          
## 10 Non-Official &amp; Non-Abor… Afrikaans          Edmont… 300          0           
## # … with 1,060 more rows</code></pre>
<p>Is this data set now tidy? If we recall the three criteria for tidy data:</p>
<ul>
<li>each row is a single observation,</li>
<li>each column is a single variable, and</li>
<li>each value is a single cell.</li>
</ul>
<p>We can see that this data now satisfies all three criteria, making it easier to analyze. However, we aren’t done yet! We have a few more tasks we need to do to get this data in a more usable format, which we will see in the sections below.</p>
</div>
<div id="notes-on-defining-tidy-data" class="section level3" number="3.4.6">
<h3><span class="header-section-number">3.4.6</span> Notes on defining tidy data</h3>
<p>Is there only one shape for tidy data for a given data set? Not necessarily! It depends on the statistical question you are asking and what the variables are for that question. For tidy data, each variable should be its own column. So, just as it’s essential to match your statistical question with the appropriate data analysis tool (classification, clustering, hypothesis testing, etc.). It’s important to match your statistical question with the appropriate variables and ensure they are represented as individual columns to make the data tidy.</p>
</div>
</div>
<div id="using-select-to-extract-a-range-of-columns" class="section level2" number="3.5">
<h2><span class="header-section-number">3.5</span> Using <code>select</code> to extract a range of columns</h2>
<p>Chapter 1 discussed two <code>tidyverse</code> functions: <code>select</code> and <code>filter</code> to select columns and filter rows from a data frame. We will now learn more ways we can use these functions. Recall, the <code>select</code> function creates a subset of the <em>columns</em> of a data frame, while the <code>filter</code> subsets <em>rows</em> with specific values.</p>
<p>We can use <code>select</code> to obtain a subset of the data frame constructed from a range of columns rather than typing each column name out. To do this, we use the colon (<code>:</code>) operator to denote the range. For example, to get all the columns in the <code>lang_no_delimiter</code> data frame from <code>language</code> to <code>most_at_work</code> we pass <code>language:most_at_work</code> as the second argument to the <code>select</code> function.</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="wrangling.html#cb119-1" aria-hidden="true" tabindex="-1"></a>column_range <span class="ot">&lt;-</span> <span class="fu">select</span>(lang_no_delimiter, language<span class="sc">:</span>most_at_work)</span>
<span id="cb119-2"><a href="wrangling.html#cb119-2" aria-hidden="true" tabindex="-1"></a>column_range</span></code></pre></div>
<pre><code>## # A tibble: 1,070 x 4
##    language                     region    most_at_home most_at_work
##    &lt;chr&gt;                        &lt;chr&gt;     &lt;chr&gt;        &lt;chr&gt;       
##  1 Aboriginal languages, n.o.s. Toronto   50           0           
##  2 Aboriginal languages, n.o.s. Montréal  15           0           
##  3 Aboriginal languages, n.o.s. Vancouver 15           0           
##  4 Aboriginal languages, n.o.s. Calgary   5            0           
##  5 Aboriginal languages, n.o.s. Edmonton  10           0           
##  6 Afrikaans                    Toronto   265          0           
##  7 Afrikaans                    Montréal  10           0           
##  8 Afrikaans                    Vancouver 520          10          
##  9 Afrikaans                    Calgary   505          15          
## 10 Afrikaans                    Edmonton  300          0           
## # … with 1,060 more rows</code></pre>
</div>
<div id="using-filter-to-extract-rows-1" class="section level2" number="3.6">
<h2><span class="header-section-number">3.6</span> Using <code>filter</code> to extract rows</h2>
<div id="using-filter-to-extract-rows-with" class="section level3" number="3.6.1">
<h3><span class="header-section-number">3.6.1</span> Using <code>filter</code> to extract rows with <code>==</code></h3>
<p>Recall we can use the <code>filter</code> function to obtain the subset of rows with desired values from a data frame. Again, our first argument is the name of the data frame object, <code>lang_no_delimiter</code>. The second argument is a logical statement to use when filtering the rows. Here, for example, we’ll say that we are interested in rows where the category is “Official languages.” We use the <em>equivalency operator</em> (<code>==</code>) to compare the values of the <code>category</code> column with the value <code>"Official languages"</code>. With these arguments, <code>filter</code> returns a data frame with all the columns of the input data frame but only the rows we asked for in our logical filter statement.</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="wrangling.html#cb121-1" aria-hidden="true" tabindex="-1"></a>official_langs <span class="ot">&lt;-</span> <span class="fu">filter</span>(lang_no_delimiter, category <span class="sc">==</span> <span class="st">&quot;Official languages&quot;</span>)</span>
<span id="cb121-2"><a href="wrangling.html#cb121-2" aria-hidden="true" tabindex="-1"></a>official_langs</span></code></pre></div>
<pre><code>## # A tibble: 10 x 5
##    category           language region    most_at_home most_at_work
##    &lt;chr&gt;              &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;        &lt;chr&gt;       
##  1 Official languages English  Toronto   3836770      3218725     
##  2 Official languages English  Montréal  620510       412120      
##  3 Official languages English  Vancouver 1622735      1330555     
##  4 Official languages English  Calgary   1065070      844740      
##  5 Official languages English  Edmonton  1050410      792700      
##  6 Official languages French   Toronto   29800        11940       
##  7 Official languages French   Montréal  2669195      1607550     
##  8 Official languages French   Vancouver 8630         3245        
##  9 Official languages French   Calgary   8630         2140        
## 10 Official languages French   Edmonton  10950        2520</code></pre>
</div>
<div id="using-filter-to-extract-rows-with-1" class="section level3" number="3.6.2">
<h3><span class="header-section-number">3.6.2</span> Using <code>filter</code> to extract rows with <code>!=</code></h3>
<p>What if we want all the other language categories in the data set <em>except</em> for those in the “Official languages” category? We can accomplish this with the <code>!=</code> logical operator, which means “NOT EQUAL TO.” So if we want to find all the rows where the <code>category</code> does NOT equal “Official languages” we write the code below.</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="wrangling.html#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(lang_no_delimiter, category <span class="sc">!=</span> <span class="st">&quot;Official languages&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1,060 x 5
##    category                 language           region  most_at_home most_at_work
##    &lt;chr&gt;                    &lt;chr&gt;              &lt;chr&gt;   &lt;chr&gt;        &lt;chr&gt;       
##  1 Aboriginal languages     Aboriginal langua… Toronto 50           0           
##  2 Aboriginal languages     Aboriginal langua… Montré… 15           0           
##  3 Aboriginal languages     Aboriginal langua… Vancou… 15           0           
##  4 Aboriginal languages     Aboriginal langua… Calgary 5            0           
##  5 Aboriginal languages     Aboriginal langua… Edmont… 10           0           
##  6 Non-Official &amp; Non-Abor… Afrikaans          Toronto 265          0           
##  7 Non-Official &amp; Non-Abor… Afrikaans          Montré… 10           0           
##  8 Non-Official &amp; Non-Abor… Afrikaans          Vancou… 520          10          
##  9 Non-Official &amp; Non-Abor… Afrikaans          Calgary 505          15          
## 10 Non-Official &amp; Non-Abor… Afrikaans          Edmont… 300          0           
## # … with 1,050 more rows</code></pre>
</div>
<div id="using-filter-to-extract-rows-with-2" class="section level3" number="3.6.3">
<h3><span class="header-section-number">3.6.3</span> Using <code>filter</code> to extract rows with <code>,</code> &amp;`</h3>
<p>Let’s suppose we want to look at only the rows for English in Vancouver. Here we want to filter the data set to find rows that satisfy multiple conditions simultaneously. We can do this with <code>&amp;</code>, which is a logical operator meaning “AND.” We are filtering the <code>official_langs</code> data frame where the <code>region</code> equals “Vancouver” AND the <code>language</code> equals “English.”</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="wrangling.html#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(official_langs, region <span class="sc">==</span> <span class="st">&quot;Vancouver&quot;</span> <span class="sc">&amp;</span> language <span class="sc">==</span> <span class="st">&quot;English&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 5
##   category           language region    most_at_home most_at_work
##   &lt;chr&gt;              &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;        &lt;chr&gt;       
## 1 Official languages English  Vancouver 1622735      1330555</code></pre>
<p>Notice that we can accomplish the same thing using a comma <code>,</code> instead of the ampersand sign <code>&amp;</code>.
The <code>filter</code> function treats the comma <code>,</code> between the logical statements as an “AND.”</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="wrangling.html#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(official_langs, region <span class="sc">==</span> <span class="st">&quot;Vancouver&quot;</span> , language <span class="sc">==</span> <span class="st">&quot;English&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 5
##   category           language region    most_at_home most_at_work
##   &lt;chr&gt;              &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;        &lt;chr&gt;       
## 1 Official languages English  Vancouver 1622735      1330555</code></pre>
</div>
<div id="using-filter-to-extract-rows-with-3" class="section level3" number="3.6.4">
<h3><span class="header-section-number">3.6.4</span> Using <code>filter</code> to extract rows with <code>|</code></h3>
<p>Suppose we were interested in the rows for only the Albertan cities in our data set (Edmonton and Calgary). We can’t use <code>&amp;</code> as we did above because <code>region</code> cannot be both Edmonton and Calgary simultaneously. Instead, we can use the <code>|</code> logical operator, which gives us the cases where one condition OR another condition is satisfied OR both. In the code below, we ask R to return the rows where the <code>region</code> columns are equal to “Calgary” OR “Edmonton.”</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="wrangling.html#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(official_langs, region <span class="sc">==</span> <span class="st">&quot;Calgary&quot;</span> <span class="sc">|</span> region <span class="sc">==</span> <span class="st">&quot;Edmonton&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 4 x 5
##   category           language region   most_at_home most_at_work
##   &lt;chr&gt;              &lt;chr&gt;    &lt;chr&gt;    &lt;chr&gt;        &lt;chr&gt;       
## 1 Official languages English  Calgary  1065070      844740      
## 2 Official languages English  Edmonton 1050410      792700      
## 3 Official languages French   Calgary  8630         2140        
## 4 Official languages French   Edmonton 10950        2520</code></pre>
</div>
<div id="using-filter-to-extract-rows-with-in" class="section level3" number="3.6.5">
<h3><span class="header-section-number">3.6.5</span> Using <code>filter</code> to extract rows with <code>%in%</code></h3>
<p>Suppose we want to see the populations of our five cities. The <code>region_data</code> data set from the <code>canlang</code> package contains statistics for number of households, land area, population and number of dwellings for different regions according to the 2016 Canadian census.</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="wrangling.html#cb131-1" aria-hidden="true" tabindex="-1"></a>region_data</span></code></pre></div>
<pre><code>## # A tibble: 35 x 5
##    region         households  area population dwellings
##    &lt;chr&gt;               &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;
##  1 Belleville          43002 1355.     103472     45050
##  2 Lethbridge          45696 3047.     117394     48317
##  3 Thunder Bay         52545 2618.     121621     57146
##  4 Peterborough        50533 1637.     121721     55662
##  5 Saint John          52872 3793.     126202     58398
##  6 Brantford           52530 1086.     134203     54419
##  7 Moncton             61769 2625.     144810     66699
##  8 Guelph              59280  604.     151984     63324
##  9 Trois-Rivières      72502 1053.     156042     77734
## 10 Saguenay            72479 3079.     160980     77968
## # … with 25 more rows</code></pre>
<p>To get the population of our five cities we can filter the data set
using the <code>%in%</code> operator. The <code>%in%</code> operator is used to see if an element
belongs to a vector. Here we are filtering if any of the five cities
(“Toronto,” “Montréal,” “Vancouver,” “Calgary,” “Edmonton”) match the rows in the <code>region</code>
column.</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="wrangling.html#cb133-1" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(region_data, region <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;Toronto&quot;</span>, <span class="st">&quot;Montréal&quot;</span>, <span class="st">&quot;Vancouver&quot;</span>, <span class="st">&quot;Calgary&quot;</span>, <span class="st">&quot;Edmonton&quot;</span>))</span></code></pre></div>
<pre><code>## # A tibble: 5 x 5
##   region    households  area population dwellings
##   &lt;chr&gt;          &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;
## 1 Edmonton      502143 9858.    1321426    537634
## 2 Calgary       519693 5242.    1392609    544870
## 3 Vancouver     960894 3040.    2463431   1027613
## 4 Montréal     1727310 4638.    4098927   1823281
## 5 Toronto      2135909 6270.    5928040   2235145</code></pre>
<blockquote>
<p><strong>What’s the difference between <code>==</code> and <code>%in%</code>?</strong>
Let’s suppose we have two vectors, <code>vector1</code> and <code>vector2</code>. If you type
<code>vector1 == vector2</code> into R it
will compare the vectors element by element. R checks if the first element of
<code>vector1</code> equals the first element of <code>vector2</code>, the second element of <code>vector1</code>
equals the second element of <code>vector2</code> etc.
On the other hand, <code>vector1 %in% vector2</code>
compares the first element of <code>vector1</code> to all the elements in <code>vector2</code>.
Then the second element of <code>vector1</code> is then compared to all the elements in <code>vector2</code> etc. Notice the difference between <code>==</code> and <code>%in%</code> in the example below.</p>
</blockquote>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="wrangling.html#cb135-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="st">&quot;Vancouver&quot;</span>, <span class="st">&quot;Toronto&quot;</span>) <span class="sc">==</span> <span class="fu">c</span>(<span class="st">&quot;Toronto&quot;</span>, <span class="st">&quot;Vancouver&quot;</span>)</span></code></pre></div>
<pre><code>## [1] FALSE FALSE</code></pre>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="wrangling.html#cb137-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="st">&quot;Vancouver&quot;</span>, <span class="st">&quot;Toronto&quot;</span>) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;Toronto&quot;</span>, <span class="st">&quot;Vancouver&quot;</span>)</span></code></pre></div>
<pre><code>## [1] TRUE TRUE</code></pre>
</div>
<div id="using-filter-to-extract-rows-with-values-above-or-below-a-threshold" class="section level3" number="3.6.6">
<h3><span class="header-section-number">3.6.6</span> Using <code>filter</code> to extract rows with values above or below a threshold</h3>
<p>We see that 2,669,195 people reported speaking French in Montréal as their primary language at home. If we are interested in finding the languages in regions with higher numbers of people who speak it as their primary language at home than French in Montréal then we can create a filter to obtain rows where the value of <code>most_at_home</code> is greater than 2,669,195.</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="wrangling.html#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(official_langs, most_at_home <span class="sc">&gt;</span> <span class="dv">2669195</span>)</span></code></pre></div>
<pre><code>## # A tibble: 5 x 5
##   category           language region    most_at_home most_at_work
##   &lt;chr&gt;              &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;        &lt;chr&gt;       
## 1 Official languages English  Toronto   3836770      3218725     
## 2 Official languages English  Montréal  620510       412120      
## 3 Official languages French   Toronto   29800        11940       
## 4 Official languages French   Vancouver 8630         3245        
## 5 Official languages French   Calgary   8630         2140</code></pre>
<p>When we look at the table we got from <code>filter</code> above, it isn’t quite doing what we’d expect. We see numbers in the table in the <code>most_at_home</code> column that are less than 2,669,195. What’s going on here?</p>
</div>
</div>
<div id="using-mutate-to-modify-or-add-columns" class="section level2" number="3.7">
<h2><span class="header-section-number">3.7</span> Using <code>mutate</code> to modify or add columns</h2>
<div id="using-mutate-to-modify-columns" class="section level3" number="3.7.1">
<h3><span class="header-section-number">3.7.1</span> Using <code>mutate</code> to modify columns</h3>
<p>Notice in the table above the word <code>&lt;chr&gt;</code> appears beneath each of the column names. The word under the column name indicates the data type of each column. Here all of our variables are “character” data types. Recall, a character data type is a letter or a number surrounded by quotes. In the previous example in section
<a href="wrangling.html#pivot-wider">3.4.4</a>, the <code>most_at_home</code> and <code>most_at_work</code> variables were <code>&lt;dbl&gt;</code> (double) (you can verify this by looking at the tables in the previous sections), which is a numeric data type. This change is due to the delimiter “/” when we read in this messy data set. R read the columns in as character types, and it stayed that way after we separated the columns.</p>
<p>Here it makes sense for <code>region</code>, <code>category</code>, and <code>language</code> to be stored as a character type. However, if we want to apply any functions that treat the <code>most_at_home</code> and <code>most_at_work</code> columns as a number (e.g. finding rows that are above a numeric threshold of a column), it won’t be possible to do if the variable is stored as a <code>character</code>. R has a variety of data types, but here we will use the function <code>mutate</code> to convert these two columns to a “numeric” data type. <code>mutate</code> is a function that will allow us to create a new variable or transform existing ones in our data set. We specify the data set in the first argument, and in the proceeding arguments, we specify the function we want to apply (<code>as.numeric</code>) to which columns (<code>most_at_home</code>, <code>most_at_work</code>). Then we give the mutated variable a new name. Here we are naming the columns the same names (“most_at_home,” “most_at_work”), but you can call these mutated variables anything you’d like.</p>
<p><code>mutate</code>’s general syntax is detailed in Figure <a href="wrangling.html#fig:img-mutate">3.14</a>.</p>
<div class="figure"><span id="fig:img-mutate"></span>
<img src="img/mutate_function.jpeg" alt="Syntax for the mutate function" width="1100" />
<p class="caption">
Figure 3.14: Syntax for the mutate function
</p>
</div>
<p>Below we use <code>mutate</code> to convert the columns <code>most_at_home</code> and <code>most_at_home</code>
to numeric data types in the <code>official_langs</code> data set as described in figure
<a href="wrangling.html#fig:img-mutate">3.14</a>:</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="wrangling.html#cb141-1" aria-hidden="true" tabindex="-1"></a>official_langs <span class="ot">&lt;-</span> <span class="fu">mutate</span>(official_langs,</span>
<span id="cb141-2"><a href="wrangling.html#cb141-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">most_at_home =</span> <span class="fu">as.numeric</span>(most_at_home),</span>
<span id="cb141-3"><a href="wrangling.html#cb141-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">most_at_work =</span> <span class="fu">as.numeric</span>(most_at_work)</span>
<span id="cb141-4"><a href="wrangling.html#cb141-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb141-5"><a href="wrangling.html#cb141-5" aria-hidden="true" tabindex="-1"></a>official_langs</span></code></pre></div>
<pre><code>## # A tibble: 10 x 5
##    category           language region    most_at_home most_at_work
##    &lt;chr&gt;              &lt;chr&gt;    &lt;chr&gt;            &lt;dbl&gt;        &lt;dbl&gt;
##  1 Official languages English  Toronto        3836770      3218725
##  2 Official languages English  Montréal        620510       412120
##  3 Official languages English  Vancouver      1622735      1330555
##  4 Official languages English  Calgary        1065070       844740
##  5 Official languages English  Edmonton       1050410       792700
##  6 Official languages French   Toronto          29800        11940
##  7 Official languages French   Montréal       2669195      1607550
##  8 Official languages French   Vancouver         8630         3245
##  9 Official languages French   Calgary           8630         2140
## 10 Official languages French   Edmonton         10950         2520</code></pre>
<p>Now we see <code>&lt;dbl&gt;</code> appears under our columns, <code>most_at_home</code> and <code>most_at_work</code>, indicating they are double data types (which is one of the sub-types of numeric)!</p>
<p>Now when we filter we get what we expect:</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="wrangling.html#cb143-1" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(official_langs, most_at_home <span class="sc">&gt;</span> <span class="dv">2669195</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 5
##   category           language region  most_at_home most_at_work
##   &lt;chr&gt;              &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;        &lt;dbl&gt;
## 1 Official languages English  Toronto      3836770      3218725</code></pre>
<p>In this case, we see that <code>filter</code> returns a data frame with only one row; this indicates that only English in Toronto is reported by more people as their primary language at home than French in Montréal.</p>
</div>
<div id="using-mutate-to-create-new-columns" class="section level3" number="3.7.2">
<h3><span class="header-section-number">3.7.2</span> Using <code>mutate</code> to create new columns</h3>
<p>We can see in the table that 3,836,770 people reported speaking English in Toronto as their primary language at home according to the 2016 Canadian census. What does this number mean to us? To understand this number, we need context. In particular, how many people were in Toronto when this data was collected? From the 2016 Canadian census profile, the population of Toronto was reported to be 5,928,040 people. The number of people who report that English as their primary language at home is much more meaningful when we report it in this context. We can even go a step further and transform this count to a relative frequency or proportion. We can do this by dividing the number of people reporting a given language as their primary language at home by the number of people who live in Toronto. For example, the proportion of people who reported that their primary language at home was English in the 2016 Canadian census was 0.65 in Toronto.</p>
<p>We can create a vector of the city populations.
Then we use <code>mutate</code> to calculate
the proportion of people reporting a given language as their primary language at home for all the languages in the <code>official_langs</code> data set by dividing the column by our vector of city populations. We give the mutated column a new name <code>most_at_home_proportion</code>, which will create a new column in our data set.</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="wrangling.html#cb145-1" aria-hidden="true" tabindex="-1"></a>city_populations <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5928040</span>, <span class="dv">4098927</span>, <span class="dv">2463431</span>, <span class="dv">1392609</span>, <span class="dv">1321426</span>)</span>
<span id="cb145-2"><a href="wrangling.html#cb145-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb145-3"><a href="wrangling.html#cb145-3" aria-hidden="true" tabindex="-1"></a>official_langs <span class="ot">&lt;-</span> <span class="fu">mutate</span>(official_langs,</span>
<span id="cb145-4"><a href="wrangling.html#cb145-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">most_at_home_proportion =</span> most_at_home <span class="sc">/</span> city_populations</span>
<span id="cb145-5"><a href="wrangling.html#cb145-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb145-6"><a href="wrangling.html#cb145-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb145-7"><a href="wrangling.html#cb145-7" aria-hidden="true" tabindex="-1"></a>official_langs</span></code></pre></div>
<pre><code>## # A tibble: 10 x 6
##    category      language region   most_at_home most_at_work most_at_home_propo…
##    &lt;chr&gt;         &lt;chr&gt;    &lt;chr&gt;           &lt;dbl&gt;        &lt;dbl&gt;               &lt;dbl&gt;
##  1 Official lan… English  Toronto       3836770      3218725             0.647  
##  2 Official lan… English  Montréal       620510       412120             0.151  
##  3 Official lan… English  Vancouv…      1622735      1330555             0.659  
##  4 Official lan… English  Calgary       1065070       844740             0.765  
##  5 Official lan… English  Edmonton      1050410       792700             0.795  
##  6 Official lan… French   Toronto         29800        11940             0.00503
##  7 Official lan… French   Montréal      2669195      1607550             0.651  
##  8 Official lan… French   Vancouv…         8630         3245             0.00350
##  9 Official lan… French   Calgary          8630         2140             0.00620
## 10 Official lan… French   Edmonton        10950         2520             0.00829</code></pre>
<p>Notice that we divided a vector with 10 elements (<code>most_at_home</code>) by a vector with
only 5 elements (<code>city_populations</code>). What gives? Arithmetic operations of vectors are performed <em>memberwise</em> meaning the first element of <code>most_at_home</code> will be divided by the first element
of <code>city_populations</code>, the second element of <code>most_at_home</code> will be divided by the second element of <code>city_populations</code> and so on. When two vectors have different lengths, the
shorter one will be recycled to match the longer one. Here the elements of
<code>city_populations</code> will be repeated once to match the length of <code>most_at_home</code>.</p>
<p>You <em>can</em> do this in R, however we can very easily introduce errors using this method without realizing. For example, suppose we only listed four city populations, but still had ten elements of five cities in the <code>most_at_home column</code>. Then the first two city populations listed in the <code>city_populations</code> vector (Toronto and Montréal) would be repeated at the end and our calculated proportions would be wrong in our final data table.</p>
<p>Instead, let’s use the <code>case_when</code> function. When used inside the <code>mutate</code> function, <code>case_when</code> will allow us to mutate a variable <em>when</em> a particular condition is met.
We write the condition on the left side of the tilde (<code>~</code>) symbol and the mutation on the right side. Let’s consider just Toronto to start. We want to take the <code>most_at_home</code> value for English in Toronto (3,836,770) and divide it by Toronto’s population (5,928,040). We also want to divide the <code>most_at_home</code> value for French in Toronto (29,800) and divide it by Toronto’s population. So when <code>region == Toronto</code> (the <em>condition</em>), we want to apply <code>most_at_home/5928040</code> (the <em>mutation</em>). We do the same for the other cities, which is what you see in the code below.</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="wrangling.html#cb147-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(official_langs,</span>
<span id="cb147-2"><a href="wrangling.html#cb147-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">most_at_home_proportion =</span> <span class="fu">case_when</span>(</span>
<span id="cb147-3"><a href="wrangling.html#cb147-3" aria-hidden="true" tabindex="-1"></a>    region <span class="sc">==</span> <span class="st">&quot;Toronto&quot;</span> <span class="sc">~</span> most_at_home <span class="sc">/</span> <span class="dv">5928040</span>,</span>
<span id="cb147-4"><a href="wrangling.html#cb147-4" aria-hidden="true" tabindex="-1"></a>    region <span class="sc">==</span> <span class="st">&quot;Montréal&quot;</span> <span class="sc">~</span> most_at_home <span class="sc">/</span> <span class="dv">4098927</span>,</span>
<span id="cb147-5"><a href="wrangling.html#cb147-5" aria-hidden="true" tabindex="-1"></a>    region <span class="sc">==</span> <span class="st">&quot;Vancouver&quot;</span> <span class="sc">~</span> most_at_home <span class="sc">/</span> <span class="dv">2463431</span>,</span>
<span id="cb147-6"><a href="wrangling.html#cb147-6" aria-hidden="true" tabindex="-1"></a>    region <span class="sc">==</span> <span class="st">&quot;Calgary&quot;</span> <span class="sc">~</span> most_at_home <span class="sc">/</span> <span class="dv">1392609</span>,</span>
<span id="cb147-7"><a href="wrangling.html#cb147-7" aria-hidden="true" tabindex="-1"></a>    region <span class="sc">==</span> <span class="st">&quot;Edmonton&quot;</span> <span class="sc">~</span> most_at_home <span class="sc">/</span> <span class="dv">1321426</span></span>
<span id="cb147-8"><a href="wrangling.html#cb147-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb147-9"><a href="wrangling.html#cb147-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## # A tibble: 10 x 6
##    category      language region   most_at_home most_at_work most_at_home_propo…
##    &lt;chr&gt;         &lt;chr&gt;    &lt;chr&gt;           &lt;dbl&gt;        &lt;dbl&gt;               &lt;dbl&gt;
##  1 Official lan… English  Toronto       3836770      3218725             0.647  
##  2 Official lan… English  Montréal       620510       412120             0.151  
##  3 Official lan… English  Vancouv…      1622735      1330555             0.659  
##  4 Official lan… English  Calgary       1065070       844740             0.765  
##  5 Official lan… English  Edmonton      1050410       792700             0.795  
##  6 Official lan… French   Toronto         29800        11940             0.00503
##  7 Official lan… French   Montréal      2669195      1607550             0.651  
##  8 Official lan… French   Vancouv…         8630         3245             0.00350
##  9 Official lan… French   Calgary          8630         2140             0.00620
## 10 Official lan… French   Edmonton        10950         2520             0.00829</code></pre>
<p>If you compare the proportions in these two tables, we get the same values with both methods.
That is the beauty (and sometimes downfall) of R – there are usually multiple ways to accomplish the same thing!</p>
</div>
</div>
<div id="creating-a-visualization-with-tidy-data" class="section level2" number="3.8">
<h2><span class="header-section-number">3.8</span> Creating a visualization with tidy data</h2>
<p>Now that we have cleaned and wrangled our data, we can visualize how many people speak each of Canada’s two
official languages (English and French) as their primary language at home in
these 5 regions. We can use
<code>ggplot</code> to create our data visualization. Here we create a bar chart to
represent the proportions for each region, and colour the proportions by language.</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="wrangling.html#cb149-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(</span>
<span id="cb149-2"><a href="wrangling.html#cb149-2" aria-hidden="true" tabindex="-1"></a>  official_langs,</span>
<span id="cb149-3"><a href="wrangling.html#cb149-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(</span>
<span id="cb149-4"><a href="wrangling.html#cb149-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> most_at_home_proportion,</span>
<span id="cb149-5"><a href="wrangling.html#cb149-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> region,</span>
<span id="cb149-6"><a href="wrangling.html#cb149-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> language</span>
<span id="cb149-7"><a href="wrangling.html#cb149-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb149-8"><a href="wrangling.html#cb149-8" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb149-9"><a href="wrangling.html#cb149-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>) <span class="sc">+</span></span>
<span id="cb149-10"><a href="wrangling.html#cb149-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Proportion of residents reporting their primary language at home&quot;</span>) <span class="sc">+</span></span>
<span id="cb149-11"><a href="wrangling.html#cb149-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Region&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/02-plot-1.png" width="672" /></p>
<blockquote>
<p>Don’t worry too much about the code to make this plot, we will talk more in detail about visualizations in chapter <a href="viz.html#viz">4</a>.</p>
</blockquote>
<p>From this visualization, we can see that in Calgary, Edmonton, Toronto and Vancouver, English was reported as the most common primary language used at home compared to French. However, in Montréal, French was reported as the most common primary language used at home over English.</p>
</div>
<div id="combining-functions-using-the-pipe-operator" class="section level2" number="3.9">
<h2><span class="header-section-number">3.9</span> Combining functions using the pipe operator, <code>|&gt;</code></h2>
<p>In R, we often have to call multiple functions in a sequence to process a data frame. The basic ways of doing this can become quickly unreadable if there are many steps. For example, suppose we need to perform three operations on
a data frame <code>data</code>:</p>
<ol style="list-style-type: decimal">
<li>add a new column <code>new_col</code> that is double another <code>old_col</code></li>
<li>filter for rows where another column, <code>other_col</code>, is more than 5, and</li>
<li>select only the new column <code>new_col</code> for those rows.</li>
</ol>
<p>One way of doing is to just write multiple lines of code, storing temporary objects as you go:</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="wrangling.html#cb150-1" aria-hidden="true" tabindex="-1"></a>output_1 <span class="ot">&lt;-</span> <span class="fu">mutate</span>(data, <span class="at">new_col =</span> old_col <span class="sc">*</span> <span class="dv">2</span>)</span>
<span id="cb150-2"><a href="wrangling.html#cb150-2" aria-hidden="true" tabindex="-1"></a>output_2 <span class="ot">&lt;-</span> <span class="fu">filter</span>(output_1, other_col <span class="sc">&gt;</span> <span class="dv">5</span>)</span>
<span id="cb150-3"><a href="wrangling.html#cb150-3" aria-hidden="true" tabindex="-1"></a>output <span class="ot">&lt;-</span> <span class="fu">select</span>(output_2, new_col)</span></code></pre></div>
<p>This is difficult to understand for multiple reasons. The reader may be tricked into thinking the named <code>output_1</code> and <code>output_2</code>
objects are important for some reason, while they are just temporary intermediate computations. Further, the reader has to look
through and find where <code>output_1</code> and <code>output_2</code> are used in each subsequent line.</p>
<p>Another option for doing this would be to <em>compose</em> the functions:</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="wrangling.html#cb151-1" aria-hidden="true" tabindex="-1"></a>output <span class="ot">&lt;-</span> <span class="fu">select</span>(<span class="fu">filter</span>(<span class="fu">mutate</span>(data, <span class="at">new_col =</span> old_col <span class="sc">*</span> <span class="dv">2</span>), other_col <span class="sc">&gt;</span> <span class="dv">5</span>), new_col)</span></code></pre></div>
<p>Code like this can also be difficult to understand. Functions compose (reading from left to right) in the <em>opposite order</em> in which
they are computed by R (above, <code>mutate</code> happens first, then <code>filter</code>, then <code>select</code>). It is also just a really long line of code
to read in one go.</p>
<p>The <em>pipe operator</em> <code>|&gt;</code> solves this problem, resulting in cleaner and easier-to-follow code. <code>|&gt;</code> in built into R so you don’t need to load any packages to use it. The code below accomplishes the same thing as the previous two code blocks:</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="wrangling.html#cb152-1" aria-hidden="true" tabindex="-1"></a>output <span class="ot">&lt;-</span> data <span class="sc">|</span><span class="er">&gt;</span></span>
<span id="cb152-2"><a href="wrangling.html#cb152-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(<span class="at">new_col =</span> old_col <span class="sc">*</span> <span class="dv">2</span>) <span class="sc">|</span><span class="er">&gt;</span></span>
<span id="cb152-3"><a href="wrangling.html#cb152-3" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(other_col <span class="sc">&gt;</span> <span class="dv">5</span>) <span class="sc">|</span><span class="er">&gt;</span></span>
<span id="cb152-4"><a href="wrangling.html#cb152-4" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(new_col)</span></code></pre></div>
<blockquote>
<p>Note: The <code>|&gt;</code> pipe operator was inspired by a previous version of the pipe operator, <code>%&gt;%</code>. The <code>%&gt;%</code> pipe operator is not built into R and needs to be loaded via an external R package. There are some other drawbacks to using <code>%&gt;%</code>, which are beyond the scope of this textbook. However, be aware that <code>%&gt;%</code> exists since you may see it used in some books or other sources. In this textbook, we will be using the base R pipe operator syntax, <code>|&gt;</code>.</p>
</blockquote>
<p>You can think of the pipe as a physical pipe. It takes the output from the function on the left-hand side of the pipe, and
passes it as the first argument to the function on the right-hand side of the pipe. Note here that we have again split the
code across multiple lines for readability; R is fine with this, since it knows that a line ending in a pipe <code>|&gt;</code> is continued
on the next line. Similarly, you see that after the first pipe, the remaining
lines are indented until the end of the pipeline. This is not required for the
R code to work, but again is used to aid in improving code readability.</p>
<p>Next, let’s learn about the details of using the pipe, and look at some examples of how to use it in data analysis.</p>
<div id="using-to-combine-filter-and-select" class="section level3" number="3.9.1">
<h3><span class="header-section-number">3.9.1</span> Using <code>|&gt;</code> to combine <code>filter</code> and <code>select</code></h3>
<p>Let’s work with our tidy <code>lang_home_tidy</code> data set from above, which contains the number of Canadians reporting their primary language at home and work for five major cities (Toronto, Montréal, Vancouver, Calgary and Edmonton):</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="wrangling.html#cb153-1" aria-hidden="true" tabindex="-1"></a>lang_home_tidy</span></code></pre></div>
<pre><code>## # A tibble: 1,070 x 5
##    region   category                language           most_at_home most_at_work
##    &lt;chr&gt;    &lt;chr&gt;                   &lt;chr&gt;                     &lt;dbl&gt;        &lt;dbl&gt;
##  1 Montréal Aboriginal languages    Aboriginal langua…           15            0
##  2 Toronto  Aboriginal languages    Aboriginal langua…           50            0
##  3 Calgary  Aboriginal languages    Aboriginal langua…            5            0
##  4 Edmonton Aboriginal languages    Aboriginal langua…           10            0
##  5 Vancouv… Aboriginal languages    Aboriginal langua…           15            0
##  6 Montréal Non-Official &amp; Non-Abo… Afrikaans                    10            0
##  7 Toronto  Non-Official &amp; Non-Abo… Afrikaans                   265            0
##  8 Calgary  Non-Official &amp; Non-Abo… Afrikaans                   505           15
##  9 Edmonton Non-Official &amp; Non-Abo… Afrikaans                   300            0
## 10 Vancouv… Non-Official &amp; Non-Abo… Afrikaans                   520           10
## # … with 1,060 more rows</code></pre>
<p>Suppose we want to create a subset of the data with only the languages and counts of each language spoken most at home for the city of Vancouver. To do this, we can use the functions <code>filter</code> and <code>select</code>. First, we use <code>filter</code> to create a data frame called <code>van_data</code> that contains only values for Vancouver. We then use <code>select</code> on this data frame to keep only the variables we want:</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="wrangling.html#cb155-1" aria-hidden="true" tabindex="-1"></a>van_data <span class="ot">&lt;-</span> <span class="fu">filter</span>(lang_home_tidy, region <span class="sc">==</span> <span class="st">&quot;Vancouver&quot;</span>)</span>
<span id="cb155-2"><a href="wrangling.html#cb155-2" aria-hidden="true" tabindex="-1"></a>van_data</span></code></pre></div>
<pre><code>## # A tibble: 214 x 5
##    region   category                language           most_at_home most_at_work
##    &lt;chr&gt;    &lt;chr&gt;                   &lt;chr&gt;                     &lt;dbl&gt;        &lt;dbl&gt;
##  1 Vancouv… Aboriginal languages    Aboriginal langua…           15            0
##  2 Vancouv… Non-Official &amp; Non-Abo… Afrikaans                   520           10
##  3 Vancouv… Non-Official &amp; Non-Abo… Afro-Asiatic lang…           10            0
##  4 Vancouv… Non-Official &amp; Non-Abo… Akan (Twi)                  125           10
##  5 Vancouv… Non-Official &amp; Non-Abo… Albanian                    530           10
##  6 Vancouv… Aboriginal languages    Algonquian langua…            0            0
##  7 Vancouv… Aboriginal languages    Algonquin                     0            0
##  8 Vancouv… Non-Official &amp; Non-Abo… American Sign Lan…          300          140
##  9 Vancouv… Non-Official &amp; Non-Abo… Amharic                     540           10
## 10 Vancouv… Non-Official &amp; Non-Abo… Arabic                     8680          275
## # … with 204 more rows</code></pre>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="wrangling.html#cb157-1" aria-hidden="true" tabindex="-1"></a>van_data_selected <span class="ot">&lt;-</span> <span class="fu">select</span>(van_data, language, most_at_home)</span>
<span id="cb157-2"><a href="wrangling.html#cb157-2" aria-hidden="true" tabindex="-1"></a>van_data_selected</span></code></pre></div>
<pre><code>## # A tibble: 214 x 2
##    language                       most_at_home
##    &lt;chr&gt;                                 &lt;dbl&gt;
##  1 Aboriginal languages, n.o.s.             15
##  2 Afrikaans                               520
##  3 Afro-Asiatic languages, n.i.e.           10
##  4 Akan (Twi)                              125
##  5 Albanian                                530
##  6 Algonquian languages, n.i.e.              0
##  7 Algonquin                                 0
##  8 American Sign Language                  300
##  9 Amharic                                 540
## 10 Arabic                                 8680
## # … with 204 more rows</code></pre>
<p>Although this is valid code, there is a more readable approach we could take by using the pipe, <code>|&gt;</code>. With the pipe, we do not need to create an intermediate object to store the output from <code>filter</code>. Instead we can directly send the
output of <code>filter</code> to the input of <code>select</code>:</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="wrangling.html#cb159-1" aria-hidden="true" tabindex="-1"></a>van_data_selected <span class="ot">&lt;-</span> <span class="fu">filter</span>(lang_home_tidy, region <span class="sc">==</span> <span class="st">&quot;Vancouver&quot;</span>) <span class="sc">|</span><span class="er">&gt;</span></span>
<span id="cb159-2"><a href="wrangling.html#cb159-2" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(language, most_at_home)</span>
<span id="cb159-3"><a href="wrangling.html#cb159-3" aria-hidden="true" tabindex="-1"></a>van_data_selected</span></code></pre></div>
<pre><code>## # A tibble: 214 x 2
##    language                       most_at_home
##    &lt;chr&gt;                                 &lt;dbl&gt;
##  1 Aboriginal languages, n.o.s.             15
##  2 Afrikaans                               520
##  3 Afro-Asiatic languages, n.i.e.           10
##  4 Akan (Twi)                              125
##  5 Albanian                                530
##  6 Algonquian languages, n.i.e.              0
##  7 Algonquin                                 0
##  8 American Sign Language                  300
##  9 Amharic                                 540
## 10 Arabic                                 8680
## # … with 204 more rows</code></pre>
<p>But wait - why does our <code>select</code> function call look different in these two examples? When you use the pipe,
the output of the function on the left is automatically provided as the first argument for the function on the right, and thus you do not specify that argument in that function call. In the code above, the first
argument of <code>select</code> is the data frame we are <code>select</code>-ing from, which is provided by the output of <code>filter</code>.</p>
<p>As you can see, both of these approaches give us the same output, but the second approach is more clear and readable.</p>
</div>
<div id="using-with-more-than-two-functions" class="section level3" number="3.9.2">
<h3><span class="header-section-number">3.9.2</span> Using <code>|&gt;</code> with more than two functions</h3>
<p>The <code>|&gt;</code> can be used with any function in R. Additionally, we can pipe together more than two functions. For example, we can pipe together three functions to order the rows by counts of the language most spoken at home for only the counts that are more than 10,000 and only include the region, language and count of Canadians reporting their primary language at home in our table.</p>
<p>To order by counts of the language most spoken at home we will use the
<code>tidyverse</code> function, <code>arrange</code>. Recall this function takes column names as input and
orders the rows in the data frame in ascending order based on the values in the
columns. Here we use only one column for sorting (<code>most_at_home</code>), but more than
one can also be used. To do this, list additional columns separated by commas.
The order they are listed in indicates the order in which they will be used for
sorting. This is much like how an English dictionary sorts words: first by the
first letter, then by the second letter, and so on. <em>Remember: If you want to sort
in reverse order, you can pair a function called <code>desc</code> with <code>arrange</code> (e.g.,
<code>arrange(desc(column_name))</code>).</em></p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="wrangling.html#cb161-1" aria-hidden="true" tabindex="-1"></a>large_region_lang <span class="ot">&lt;-</span> <span class="fu">filter</span>(lang_home_tidy, most_at_home <span class="sc">&gt;</span> <span class="dv">10000</span>) <span class="sc">|</span><span class="er">&gt;</span></span>
<span id="cb161-2"><a href="wrangling.html#cb161-2" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(region, language, most_at_home) <span class="sc">|</span><span class="er">&gt;</span></span>
<span id="cb161-3"><a href="wrangling.html#cb161-3" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(most_at_home)</span>
<span id="cb161-4"><a href="wrangling.html#cb161-4" aria-hidden="true" tabindex="-1"></a>large_region_lang</span></code></pre></div>
<pre><code>## # A tibble: 67 x 3
##    region    language most_at_home
##    &lt;chr&gt;     &lt;chr&gt;           &lt;dbl&gt;
##  1 Edmonton  Arabic          10590
##  2 Montréal  Tamil           10670
##  3 Vancouver Russian         10795
##  4 Edmonton  Spanish         10880
##  5 Edmonton  French          10950
##  6 Calgary   Arabic          11010
##  7 Calgary   Urdu            11060
##  8 Vancouver Hindi           11235
##  9 Montréal  Armenian        11835
## 10 Toronto   Romanian        12200
## # … with 57 more rows</code></pre>
<blockquote>
<p><strong>Note:</strong> You might also have noticed that we split the function calls across lines after the pipe, similar as to
when we did this earlier in the chapter for long function calls. Again this is allowed and recommeded, especially when the
piped function calls would create a long line of code. Doing this makes your code more readable. When you do this it is important
to end each line with the pipe operator <code>|&gt;</code> to tell R that your code is continuing onto the next line.</p>
</blockquote>
</div>
</div>
<div id="iterating-over-data-with-group_by-summarize" class="section level2" number="3.10">
<h2><span class="header-section-number">3.10</span> Iterating over data with <code>group_by</code> + <code>summarize</code></h2>
<div id="calculating-summary-statistics" class="section level3" number="3.10.1">
<h3><span class="header-section-number">3.10.1</span> Calculating summary statistics:</h3>
<p>As a part of many data analyses, we need to calculate a summary value for the data (a summary statistic). A useful <code>dplyr</code> function for doing this is
<code>summarize</code>. Examples of summary statistics we might want to calculate are the number of observations, the average/mean value
for a column, the minimum value for a column, etc. Below we show how to use the <code>summarize</code> function to calculate the minimum and maximum
number of Canadians reporting a particular language as their primary language at home:</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="wrangling.html#cb163-1" aria-hidden="true" tabindex="-1"></a>lang_summary <span class="ot">&lt;-</span> <span class="fu">summarize</span>(lang_home_tidy,</span>
<span id="cb163-2"><a href="wrangling.html#cb163-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">min_most_at_home =</span> <span class="fu">min</span>(most_at_home),</span>
<span id="cb163-3"><a href="wrangling.html#cb163-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">most_most_at_home =</span> <span class="fu">max</span>(most_at_home)</span>
<span id="cb163-4"><a href="wrangling.html#cb163-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb163-5"><a href="wrangling.html#cb163-5" aria-hidden="true" tabindex="-1"></a>lang_summary</span></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##   min_most_at_home most_most_at_home
##              &lt;dbl&gt;             &lt;dbl&gt;
## 1                0           3836770</code></pre>
<p>From this we see that there are some languages in the data set the no one speaks
as their primary language at home, as well as that the most commonly spoken
primary language at home is spoken by 3,836,770
people.</p>
</div>
<div id="calculating-group-summary-statistics" class="section level3" number="3.10.2">
<h3><span class="header-section-number">3.10.2</span> Calculating group summary statistics:</h3>
<p>A common pairing with <code>summarize</code> is <code>group_by</code>. Pairing these functions together can let you summarize values for subgroups within a data set. For example, here, we can use <code>group_by</code> to group the regions and then calculate the minimum and maximum number of Canadians reporting the language as the primary language at home for each of the groups.</p>
<p>The <code>group_by</code> function takes at least two arguments. The first is the data frame that will be grouped, and the second and onwards are columns to use in the grouping. Here we use only one column for grouping (<code>region</code>), but more than one can also be used. To do this, list additional columns separated by commas.</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="wrangling.html#cb165-1" aria-hidden="true" tabindex="-1"></a>lang_summary_by_region <span class="ot">&lt;-</span> <span class="fu">group_by</span>(lang_home_tidy, region) <span class="sc">|</span><span class="er">&gt;</span></span>
<span id="cb165-2"><a href="wrangling.html#cb165-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize</span>(</span>
<span id="cb165-3"><a href="wrangling.html#cb165-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">min_most_at_home =</span> <span class="fu">min</span>(most_at_home),</span>
<span id="cb165-4"><a href="wrangling.html#cb165-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">max_most_at_home =</span> <span class="fu">max</span>(most_at_home)</span>
<span id="cb165-5"><a href="wrangling.html#cb165-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb165-6"><a href="wrangling.html#cb165-6" aria-hidden="true" tabindex="-1"></a>lang_summary_by_region</span></code></pre></div>
<pre><code>## # A tibble: 5 x 3
##   region    min_most_at_home max_most_at_home
##   &lt;chr&gt;                &lt;dbl&gt;            &lt;dbl&gt;
## 1 Calgary                  0          1065070
## 2 Edmonton                 0          1050410
## 3 Montréal                 0          2669195
## 4 Toronto                  0          3836770
## 5 Vancouver                0          1622735</code></pre>
</div>
<div id="additional-reading-on-the-dplyr-functions" class="section level3" number="3.10.3">
<h3><span class="header-section-number">3.10.3</span> Additional reading on the <code>dplyr</code> functions</h3>
<p>As we briefly mentioned earlier in a note, the <code>tidyverse</code> is actually a <em>meta R package</em>: it installs and loads a collection of R packages that all follow
the tidy data philosophy we discussed above. One of the <code>tidyverse</code> packages is <code>dplyr</code> - a data wrangling workhorse. You have already met six of
the dplyr function (<code>select</code>, <code>filter</code>, <code>mutate</code>, <code>arrange</code>, <code>summarize</code>, and <code>group_by</code>). To learn more about those six and meet a few more
useful functions, we recommend you checkout <a href="http://stat545.com/block010_dplyr-end-single-table.html#where-were-we">this chapter</a> of the Stat 545 book.</p>
</div>
</div>
<div id="using-purrrs-map-functions-to-iterate" class="section level2" number="3.11">
<h2><span class="header-section-number">3.11</span> Using <code>purrr</code>’s <code>map*</code> functions to iterate</h2>
<p>Where should you turn when you discover the next step in your data wrangling/cleaning process requires you to apply a function to
each column in a data frame? For example, if you wanted to know the maximum value of each column in a data frame? Well, you could use <code>summarize</code>
as discussed above. However, this becomes inconvenient when you have many columns, as <code>summarize</code> requires you to type out a column name and a data
transformation for each summary statistic you want to calculate.</p>
<p>In cases like this, where you want to apply the same data transformation to all columns, it is more efficient to use <code>purrr</code>’s <code>map</code> function to
apply it to each column. For example, let’s find the maximum value of each column of the <code>region_lang</code> data frame by using <code>map</code> with the <code>max</code> function. First, let’s peak at the data to familiarize ourselves with it:</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="wrangling.html#cb167-1" aria-hidden="true" tabindex="-1"></a>region_lang <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/region_lang.csv&quot;</span>)</span>
<span id="cb167-2"><a href="wrangling.html#cb167-2" aria-hidden="true" tabindex="-1"></a>region_lang</span></code></pre></div>
<pre><code>## # A tibble: 7,490 x 7
##    region  category language  mother_tongue most_at_home most_at_work lang_known
##    &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;             &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt;
##  1 St. Jo… Aborigi… Aborigin…             5            0            0          0
##  2 Halifax Aborigi… Aborigin…             5            0            0          0
##  3 Moncton Aborigi… Aborigin…             0            0            0          0
##  4 Saint … Aborigi… Aborigin…             0            0            0          0
##  5 Saguen… Aborigi… Aborigin…             5            5            0          0
##  6 Québec  Aborigi… Aborigin…             0            5            0         20
##  7 Sherbr… Aborigi… Aborigin…             0            0            0          0
##  8 Trois-… Aborigi… Aborigin…             0            0            0          0
##  9 Montré… Aborigi… Aborigin…            30           15            0         10
## 10 Kingst… Aborigi… Aborigin…             0            0            0          0
## # … with 7,480 more rows</code></pre>
<p>Next, we will select only the numeric columns of the data frame:</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="wrangling.html#cb169-1" aria-hidden="true" tabindex="-1"></a>region_lang_numeric <span class="ot">&lt;-</span> region_lang <span class="sc">|</span><span class="er">&gt;</span></span>
<span id="cb169-2"><a href="wrangling.html#cb169-2" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(mother_tongue<span class="sc">:</span>lang_known)</span>
<span id="cb169-3"><a href="wrangling.html#cb169-3" aria-hidden="true" tabindex="-1"></a>region_lang_numeric</span></code></pre></div>
<pre><code>## # A tibble: 7,490 x 4
##    mother_tongue most_at_home most_at_work lang_known
##            &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt;
##  1             5            0            0          0
##  2             5            0            0          0
##  3             0            0            0          0
##  4             0            0            0          0
##  5             5            5            0          0
##  6             0            5            0         20
##  7             0            0            0          0
##  8             0            0            0          0
##  9            30           15            0         10
## 10             0            0            0          0
## # … with 7,480 more rows</code></pre>
<p>Next, we use <code>map</code> to apply the <code>max</code> function to each column. <code>map</code> takes two arguments, an object (a vector, data frame or list) that you want
to apply the function to, and the function that you would like to apply. Here our arguments will be <code>region_lang_numeric</code> and <code>max</code>:</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="wrangling.html#cb171-1" aria-hidden="true" tabindex="-1"></a>max_of_columns <span class="ot">&lt;-</span> <span class="fu">map</span>(region_lang_numeric, max)</span>
<span id="cb171-2"><a href="wrangling.html#cb171-2" aria-hidden="true" tabindex="-1"></a>max_of_columns</span></code></pre></div>
<pre><code>## $mother_tongue
## [1] 3061820
## 
## $most_at_home
## [1] 3836770
## 
## $most_at_work
## [1] 3218725
## 
## $lang_known
## [1] 5600480</code></pre>
<blockquote>
<p><strong>Note:</strong> <code>purrr</code> is part of the tidyverse, and so like the <code>dplyr</code> and <code>ggplot</code> functions, once we call <code>library(tidyverse)</code> we
do not need to load the <code>purrr</code> package separately.</p>
</blockquote>
<p>Our output looks a bit weird… we passed in a data frame, but our output doesn’t look like a data frame. As it so happens, it is <em>not</em> a
data frame, but rather a plain vanilla list:</p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="wrangling.html#cb173-1" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(max_of_columns)</span></code></pre></div>
<pre><code>## [1] &quot;list&quot;</code></pre>
<p>So what do we do? Should we convert this to a data frame? We could, but a simpler alternative is to just use a different <code>map_*</code> function from
the <code>purrr</code> package. There are quite a few to choose from, they all work similarly, and their name reflects the type of output you want from
the mapping operation:</p>
<table>
<thead>
<tr class="header">
<th><code>map</code> function</th>
<th>Output</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>map()</code></td>
<td>list</td>
</tr>
<tr class="even">
<td><code>map_lgl()</code></td>
<td>logical vector</td>
</tr>
<tr class="odd">
<td><code>map_int()</code></td>
<td>integer vector</td>
</tr>
<tr class="even">
<td><code>map_dbl()</code></td>
<td>double vector</td>
</tr>
<tr class="odd">
<td><code>map_chr()</code></td>
<td>character vector</td>
</tr>
<tr class="even">
<td><code>map_df()</code></td>
<td>data frame</td>
</tr>
</tbody>
</table>
<p>Let’s get the columns’ maximums again, but this time use the <code>map_df</code> function to return the output as a data frame:</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="wrangling.html#cb175-1" aria-hidden="true" tabindex="-1"></a>max_of_columns <span class="ot">&lt;-</span> <span class="fu">map_df</span>(region_lang_numeric, max)</span>
<span id="cb175-2"><a href="wrangling.html#cb175-2" aria-hidden="true" tabindex="-1"></a>max_of_columns</span></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   mother_tongue most_at_home most_at_work lang_known
##           &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt;
## 1       3061820      3836770      3218725    5600480</code></pre>
<p>Which <code>map_*</code> function you choose depends on what you want to do with the output; you don’t always have to pick <code>map_df</code>!</p>
<p>What if you need to add other arguments to the functions you want to map? For example, what if there were NA values in our columns that we wanted to know the maximum of?</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="wrangling.html#cb177-1" aria-hidden="true" tabindex="-1"></a>region_with_nas <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/region_lang_with_nas.csv&quot;</span>)</span>
<span id="cb177-2"><a href="wrangling.html#cb177-2" aria-hidden="true" tabindex="-1"></a>region_with_nas</span></code></pre></div>
<pre><code>## # A tibble: 7,491 x 4
##    mother_tongue most_at_home most_at_work lang_known
##            &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt;
##  1             5            5           NA         NA
##  2             5            0            0          0
##  3             5            0            0          0
##  4             0            0            0          0
##  5             0            0            0          0
##  6             5            5            0          0
##  7             0            0            0          0
##  8             0            0            0          0
##  9             0            0            0          0
## 10             0            0            0          0
## # … with 7,481 more rows</code></pre>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb179-1"><a href="wrangling.html#cb179-1" aria-hidden="true" tabindex="-1"></a><span class="fu">map_df</span>(region_with_nas, max)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   mother_tongue most_at_home most_at_work lang_known
##           &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt;
## 1       3061820      3836770           NA         NA</code></pre>
<p>Notice <code>map_df()</code> returns <code>NA</code> for the <code>most_at_work</code> and <code>lang_known</code> variables since those columns contained NAs in the data frame. Thus, we also need to add the argument <code>na.rm  = TRUE</code> to the <code>max</code> function so that we get a more useful value than <code>NA</code> returned (remember that is what happens with many of the built-in R statistical functions when NA’s are present…). What we need to do in that case is add these additional arguments to the end of our call to to <code>map</code> and they will be passed to the function that we are mapping. An example of this is shown below:</p>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="wrangling.html#cb181-1" aria-hidden="true" tabindex="-1"></a><span class="fu">map_df</span>(region_with_nas, max, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   mother_tongue most_at_home most_at_work lang_known
##           &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt;
## 1       3061820      3836770      3218725    5600480</code></pre>
<p>Now <code>map_df()</code> returns the maximum count for each column ignoring the NAs in the data set!</p>
<p>The <code>map_*</code> functions are generally quite useful for solving problems involving iteration/repetition. Additionally, their use is not limited to columns
of a data frame; <code>map_*</code> functions can be used to apply functions to elements of a vector or list, and even to lists of data frames, or nested data frames.</p>
</div>
<div id="additional-resources-1" class="section level2" number="3.12">
<h2><span class="header-section-number">3.12</span> Additional resources</h2>
<ul>
<li>The <a href="https://dplyr.tidyverse.org/"><code>dplyr</code> page on the tidyverse website</a> is where you should look if you want to learn more about the functions in this chapter, the full set of arguments you can use, and other related functions. The site also provides a very nice cheat sheet that summarizes many of the data wrangling functions from this chapter.</li>
<li><a href="https://r4ds.had.co.nz/">R for Data Science</a> has a few chapters related to data wrangling that go into more depth than this book. For example, the <a href="https://r4ds.had.co.nz/tidy-data.html">tidy data</a> chapter covers tidy data, <code>pivot_longer</code>/<code>pivot_wider</code> and <code>separate</code>, but also covers missing values and additional wrangling functions (like <code>unite</code>). The <a href="https://r4ds.had.co.nz/transform.html">data transformation</a> chapter covers <code>select</code>, <code>filter</code>, <code>arrange</code>, <code>mutate</code>, and <code>summarize</code>. And the <a href="https://r4ds.had.co.nz/iteration.html#the-map-functions"><code>map_*</code> functions</a> chapter provides more about the <code>map_*</code> functions.</li>
<li>You will occasionally encounter a case where you need to iterate over items in a data frame, but none of the above functions are flexible enough to do what you want. In that case, you may consider using <a href="https://r4ds.had.co.nz/iteration.html#iteration">a for loop</a>.</li>
</ul>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-wickham2014tidy" class="csl-entry">
Wickham, Hadley, and others. 2014. <span>“Tidy Data.”</span> <em>Journal of Statistical Software</em> 59 (10): 1–23.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="reading.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="viz.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/wrangling.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
