name: Rebuild and deploy book to gh-pages branch
on:
  push:
    branches:
      - production
    paths:
      - 'index.Rmd'
      - '_bookdown.yml'
      - '_output.yml'
      - 'source/*.Rmd'
      - 'source/*.bib'
      - 'source/*.css'
      - 'data/**'
      - 'img/**'
      - 'build_html.sh'
      
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Get Actions user id
        id: get_uid
        run: |
          actions_user_id=`id -u $USER`
          echo $actions_user_id
          echo "uid=$actions_user_id" >> $GITHUB_OUTPUT
          
      - name: checkout production
        uses: actions/checkout@v2
        with:
          ref: 'production'
          
      - name: Build the book
        run: |
          ./build_html.sh

      - name: Reset ownership of workspace after build
        uses: peter-murray/reset-workspace-ownership-action@v1
        with:
          user_id: ${{ steps.get_uid.outputs.uid }}

       # Push the book's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/
          force_orphan: true # this will clean up all previous PR previews / main branch preview
          cname: datasciencebook.ca

      # rebuild the dev version after the previous copy was cleaned out
      - name: checkout main
        uses: actions/checkout@v2
        with:
          ref: 'main'
          
      - name: Build the book
        run: |
          ./build_html.sh
          
      - name: Reset ownership of workspace after build
        uses: peter-murray/reset-workspace-ownership-action@v1
        with:
          user_id: ${{ steps.get_uid.outputs.uid }}

       # Push the book's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/
          keep_files: true 
          destination_dir: dev

