name: Rebuild and publish new ubcdsci/intro-to-ds image on DockerHub
on:
  push:
    branches:
      - master
    paths:
      - Dockerfile
jobs:
  rebuild-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout master
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
        ref: 'master'
    - name: Rebuild and publish image
      id: rebuild
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: ubcdsci/intro-to-ds
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
        snapshot: true
    - name: Update build_html.sh script
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull origin master
        sed 's/ubcdsci\/intro-to-ds:[[:alnum:]]\+/ubcdsci\/intro-to-ds:${{ steps.rebuild.outputs.snapshot-tag }}/g' build_html.sh > build_html.tmp && mv build_html.tmp build_html.sh
        chmod u+x build_html.sh
        git add build_html.sh
        git commit -m "update build_html.sh script with new docker image"
    - name: Update build_pdf.sh script
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull origin master
        sed 's/ubcdsci\/intro-to-ds:[[:alnum:]]\+/ubcdsci\/intro-to-ds:${{ steps.rebuild.outputs.snapshot-tag }}/g' build_pdf.sh > build_pdf.tmp && mv build_pdf.tmp build_pdf.sh
        chmod u+x build_pdf.sh
        git add build_pdf.sh
        git commit -m "update build_pdf.sh script with new docker image"
    - name: Push changes to build scripts
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'master'
